### ISSUE TITLE
Buttercup 2.1.0 not unlocking Google Drive vault

### ISSUE THREAD

**Issue by juninholiveira** [buttercup/buttercup-desktop#1001]
When trying to unlock a vault in Google Drive, this message appears in red:

Vault unlock failed: Error invoking remote method 'unlock-source': Error: Cannot invoke 'Layerr' like a function: It must be called with 'new'

Log:
`[INF] 16:38:42: (front-end) Starting with language: pt-BR
[INF] 16:38:42: (front-end) Window opened and initialised
[INF] 16:38:42: (front-end) Setting body theme: dark
[INF] 16:38:42: (front-end) Rendering application
[INF] 16:38:47: (front-end) Unlocking source: 71518fb5-a1e7-4c42-bbac-c931cb6901c1
[ERR] 16:38:48: Failed unlocking vault source Layerr: Failed unlocking source: Failed fetching Google Drive vault: Failed executing auth handlers: No handlers registered for datasource type: googledrive
at                            …pp.asar/node_modules/buttercup/dist/core/VaultSource.js:487  throw new layerr_1.Layerr(err, "Failed unlocking source");
at processTicksAndRejections  internal/process/task_queues.js:93`

**Comment by perry-mitchell** [comment]
This is the underlying issue here: 

> Failed executing auth handlers: No handlers registered for datasource type: googledrive

Definitely a bug, sorry. Will look at this asap.

**Comment by perry-mitchell** [comment]
I've re-implemented the re-auth components to address this issue.. I haven't had time to fully test that they work with all expired tokens, but the fix will at least remove the bug causing that error message. If the issue persists I can make a quick adjustment.
