### ISSUE TITLE
Windows code-signing expired

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#1003]
The codesigning cert has expired on Windows. It needs to be renewed.

**Comment by perry-mitchell** [comment]
Should be fixed in 2.2.0

**Comment by javilaurin** [comment]
@perry-mitchell also happening again with v2.2.1 😬

**Comment by perry-mitchell** [comment]
You're right.. still not solved for some reason

**Comment by perry-mitchell** [comment]
Ok, think I found the issue. Pushing another release.

**Comment by perry-mitchell** [comment]
I can confirm that code signing is now working on 2.2.3. The install prompt showed the cert info properly.
