### ISSUE TITLE
Appimage renames self after update

### ISSUE THREAD

**Issue by BlackGopher2030** [buttercup/buttercup-desktop#1004]
I am using linux and i use alacarte to make an icon on the side menu for easy access to buttercup. When updating the app image,  for example it is now `Buttercup-linux-x64-2.0.0.AppImage*` and its updated to `Buttercup-linux-x64-2.1.1.AppImage*`

The name of the AppImage changes (the version part)

Now i have to go to alacarte again and make a new icon entering the icon image again and the executable path with the new AppImage name. I wish the version in the name of the AppImage do not change.

**Comment by perry-mitchell** [comment]
We're probably not going to change the name in the releases list.. All files there should remain versioned. I _do_ however agree that the file should not be renamed after an auto-update.. This appears to be an Electron builder issue. **We** do not rename the file.

I'd happy accept a PR for this, but it's not something I know how to fix. By the looks of it there are similar (yet not quite the same) issues on the electron builder repo:
 * https://github.com/electron-userland/electron-builder/issues/5239
 * https://github.com/electron-userland/electron-builder/issues/5477

**Comment by perry-mitchell** [comment]
Issue on the electron builder repo for this: electron-userland/electron-builder#5810

**Comment by perry-mitchell** [comment]
I'm going to remove the version from the AppImage filename - this seems to be the accepted solution for electron artifacts using electron-updater.
