### ISSUE TITLE
Buttercup 2.x.x AppImage not starting

### ISSUE THREAD

**Issue by David-Lor** [buttercup/buttercup-desktop#1007]
Executing the appimage for the latest Buttercup release (2.2.0) throws this error:

```bash
~$ ./Buttercup-linux-x64-2.2.0.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.hNZn90: fallo al asignar un segmento del objeto compartido
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_Butter8aFyA1/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

(the message shown after "Error: [...]Chromium[...]" translates to "failed to map segment from shared object").

The process is kept running, but nothing happens. In (h)top the process is running, but does nothing:

![htop](https://user-images.githubusercontent.com/17401854/115116665-18d08c80-9f9b-11eb-8a7f-5c3313705f26.png)

System information:

- Ubuntu 18.04, x86_64
- An older version of Buttercup was installed on the system. Tried uninstalling it, removing `~/.config/Buttercup` data dir and killing all buttercup processes, but the same error happens after running the appimage again
- After trying appimage of version 2.2.0, tried appimages of 2.0.0 and 2.0.1 as well, with the same error
- AppImage of version 1.20.5 (latest before 2.0.0) and deb package: both work fine

**Comment by perry-mitchell** [comment]
Why such an old image? Please try one of the newer ones, like 2.2.0. The config files from v1 are not used at all in V2, so there should be no conflict.

**Comment by David-Lor** [comment]
@perry-mitchell Yeah, I actually tried the latest version (2.2.0) appimage (which led to the error I pasted at the beggining). Then I tried 2.0.0 and 2.0.1 as well to verify if the same error did happen. My bad, I did not specify after "System information" that I tried 2.2.0 first.

Updated the issue to be more clear about it.

**Comment by perry-mitchell** [comment]
Seems to be a similar issue to here: https://github.com/tutao/tutanota/issues/1618#issuecomment-552796132

Can you try those instructions to see if they help?

**Comment by David-Lor** [comment]
Yes, that seems to be the problem. Running something like:

```bash
mkdir tmpdir
TMPDIR=$(pwd)/tmpdir ./Buttercup-linux-x64-2.2.0.AppImage
```

makes it work! The problem seems to be that I'm mounting /tmp in RAM using tmpfs, and it does not have execution permission in that directory.
