### ISSUE TITLE
UI: multiple blue update notifications 

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#1008]
I have run Buttercup version 2.1.1 for one day without closing it. When I looked at the Buttercup window again, there were a lot of blue update notifications. There were so many notifactions they hit the top border of the window.

Would it be possible to make the update notifcation unique?

![Bildschirmfoto 2021-04-18 um 13 47 31](https://user-images.githubusercontent.com/25926588/115144500-4fff7600-a04d-11eb-9f5a-8df97d120294.png)

System Information:
MacOS 11.2.3
Buttercup 2.1.1

**Comment by perry-mitchell** [comment]
Yep, we use Blueprint's toast component, so it could be made unique for updates. Good find - can't believe I haven't seen this yet myself.
