### ISSUE TITLE
Search bar does not appear when using the ctrl + f

### ISSUE THREAD

**Issue by FuridamuFaita** [buttercup/buttercup-desktop#1011]
Hi, i an using buttercup `2.2.0` and when i press `ctrl + f` the search bar does not appear. I tried version `1.20.5` and it works fine.

I am using linux debian with KDE.

Another thing is the copy buttons in an entry, in the previous v1 release they were all vertically on the same column. that made them easy to click. In the current version they are after the entry's width. (This was solved)

**Comment by perry-mitchell** [comment]
> Another thing is the copy buttons in an entry, in the previous v1 release they were all vertically on the same column. that made them easy to click. In the current version they are after the entry's width.

This is covered in another issue: https://github.com/buttercup/ui/issues/52

**Comment by perry-mitchell** [comment]
This needs reproduction, but I don't have time personally to try it. I don't use Debian desktop nor KDE.

**Comment by BlackGopher2030** [comment]
I think you just need to see what is the difference between v1 and v2, in version 1 which i am still using, the search bar appears when i press ctrl+f, but in v2 it does not appear. How do i know the shortcuts ? maybe if i changed the shortcut to something else it works and the search bar appears. Right now in v2 all i can do is using the filter and its little bit annoying to have to click 2 clicks before i can start searching.

Thank you for modifying the vertical copy to clipboard buttons in entries.

**Comment by perry-mitchell** [comment]
There’s a lot of differences, unfortunately. But so far no one else has reported this issue, and the method we’re using to detect Ctrl+F is one recommended by Electron. 

If you’d be interested in trying to debug it you could set up the development environment and add some logs to where the hot key is listened for.. see if it fires at all?

**Comment by perry-mitchell** [comment]
Can you confirm that you’re on the vault UI page when pressing ctrl+F, with nothing else selected?

**Comment by BlackGopher2030** [comment]
I tried and disabled the KDE `ctrl+f` shortcut cuz i thought it may be conflicting with buttercup's shortcut but nothing happened. and yes i am on the buttercup's UI interface.

Meanwhile i caught this thing (i dont know if its an error or no) by chance in my terminal  when running v2 (the latest version):

String surrounding the error:
```
[INF] 13:56:33: (front-end) Starting with language: en-US
[INF] 13:56:33: (front-end) Window opened and initialised
[INF] 13:56:33: (front-end) Setting body theme: dark
[INF] 13:56:33: (front-end) Rendering application
(node:9032) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 updated listeners added to [NativeTheme]. Use emitter.setMaxListeners() to increase limit
(Use `buttercup --trace-warnings ...` to show where the warning was created)
[INF] 13:56:33: (front-end) Toggling auto-update for vault editing (editing=false, auto-update=true)
[INF] 13:56:33: Enabled auto-update
[INF] 13:56:39: (front-end) Starting with language: en-US
[INF] 13:56:39: (front-end) Window opened and initialised
[INF] 13:56:39: (front-end) Setting body theme: dark
[INF] 13:56:39: (front-end) Rendering application

```

The error:
`(node:9032) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 updated listeners added to [NativeTheme]. Use emitter.setMaxListeners() to increase limit`

**Comment by maciek134** [comment]
@perry-mitchell I had this for a long time, just figured out the cause. Running on Artix with i3 WM, the error speaks for itself:

> Failed updating app menu after source change Error: The name org.freedesktop.secrets was not provided by any .service files

I created #1057 with a fix, would be nice if @FuridamuFaita confirmed if it works - if I remember correctly KDE doesn't ship with gnome-keyring alternative by default.

**Comment by FuridamuFaita** [comment]
> @perry-mitchell I had this happen to me for a long time, just figured out the cause. Running on Artix with i3 WM, the error speaks for itself:
> 
> > Failed updating app menu after source change Error: The name org.freedesktop.secrets was not provided by any .service files
> 
> I created #1057 with a fix, would be nice if @FuridamuFaita confirmed if it works - if I remember correctly KDE doesn't ship with a gnome-keyring alternative by default.

Yes it worked, i was still using buttercup v1 cuz of that issue. Thank you man.

**Comment by perry-mitchell** [comment]
Great stuff finding this, thank you! Releasing a fix now.
