### ISSUE TITLE
Render a nice and stylish component when an user locks their vaults.

### ISSUE THREAD

**Issue by slorenzo** [buttercup/buttercup-desktop#1012]
Hello there.

I notice that when my vaults are locked it doesn't show a nice component. From what I can understand looking at the code, [here](https://github.com/buttercup/buttercup-desktop/blob/974bf6b5505afc464fd465cc8302411819e83cdd/source/renderer/components/VaultEditor.tsx#L63) where it is displayed. It's a simple span tag without the proper styles.

<img width="426" alt="Screen Shot 2021-04-22 at 15 35 04" src="https://user-images.githubusercontent.com/15804684/115768170-5446ce80-a380-11eb-813b-ef996d2a31df.png">

I think it could be a component or even it could redirect to the vaults page-the first page when someone open the app- if there is no others opened vaults.

Thanks for building this app! it's amazing.

**Comment by perry-mitchell** [comment]
Thanks! But this looks almost like a bug. Yes, there _should_ be a nicer rendering on this page - but I'm pretty sure it should redirect to a lock page when getting into this state.

Would you mind adding some reproduction steps?

**Comment by slorenzo** [comment]
Hello @perry-mitchell.

I'm not sure if there is another flow to render this page.
I got this page following these steps:

- Open your vault
- Click on the "Lock All" button on the Vaults tab.

Hope it helps!

**Comment by slorenzo** [comment]
Hey @perry-mitchell. I just found out that it's already fixed!

Thanks to the Buttercup team for the effort to make this app so awesome.
