### ISSUE TITLE
Can't empty trash in app version 2.x

### ISSUE THREAD

**Issue by David-Lor** [buttercup/buttercup-desktop#1021]
Using Buttercup Desktop for Linux (AppImage), versions 2.2.0 & 2.3.0. Seems like the feature for emptying trash entries is not implemented (it was in older 1.x versions, such as 1.20.5). Right click on "Trash" or on any of the entries within Trash does nothing; neither pressing the Delete key with one entry selected.

**Comment by gcallari** [comment]
I have the same issue on the Mac version.

**Comment by perry-mitchell** [comment]
Added in 2.4.0

**Comment by graphixillusion** [comment]
@perry-mitchell I'm using the last version under Windows 10 and the empty trash doesn't work.

Desktop @ v2.19.1
Core @ v7.1.1

**Comment by perry-mitchell** [comment]
I'd be happy if someone could consider providing a fix here as I'm juggling a lot right now in the browser extension 😅.

**Comment by graphixillusion** [comment]
@perry-mitchell local filesystem
