### ISSUE TITLE
[UX] Open empty search bar when shortcut triggered

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#1025]
When I open the search bar using CMD + F on MacOS, it opens a search bar filled with the text used from the previous search. The problem is that the caret is positioned at the end of the text. If I want to search after another keyword, I have to delete the old text at first and fill in the new keyword at second.

It would be nice if a) the search bar is empty every time I hit CMD + F or b) all text in the search bar is selected so I can ovewrite it easily.

System:
MacOS: 11.3.1
Buttercup: 2.3.0

**Comment by fmommeja** [comment]
Hi,
this is one of the most, if not the most used Buttercup's functionalities and I really think it shouldn't be considered as _Medium_ priority with _Low_ effort.
I personally consider it like a **bug** more than an _Enhancement_.

**Comment by fmommeja** [comment]
@perry-mitchell **clearing** would definitely be much better ^^

**Comment by perry-mitchell** [comment]
Actually, I managed to make it work.. I can make it select all text when re-appearing, so you can simply start typing to get new results.

This is best imo as it:
 * Allows for easily starting new searches
 * Allows for seeing the previous results

**Comment by fmommeja** [comment]
Great news Perry! ^^
Thank you for that. :)

**Comment by julianpoemp** [comment]
@perry-mitchell Thank you!!
![image](https://user-images.githubusercontent.com/25926588/118548319-730b6b80-b75a-11eb-97d3-fe1ad43697a5.png)
