### ISSUE TITLE
[AppImage] Chrome sandbox error

### ISSUE THREAD

**Issue by kolole** [buttercup/buttercup-desktop#1037]
Running the .appimage directly, I get

[6227:0519/033857.156162:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_ButterHMK4Co/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

The only way to run it, is by creating a script to run it with the "--no-sandbox" option.

Bunsenlabs Lithium (Debian 10 based distro)

**Comment by perry-mitchell** [comment]
The new AppImageLauncher support in #1043 addresses this by creating correct `.desktop` files, eg:
```
Exec=/home/perry/Applications/Buttercup-linux-x64_6b48947ece518f7619eb57acb56c884c.AppImage --no-sandbox %U
```

**Comment by perry-mitchell** [comment]
Buttercup AppImage installs require AppImageLauncher to work correctly with protocols (such as that required for Google authentication). The `AppImage` authors also recommend installing this tool. Please refer to our [new instructions](https://github.com/buttercup/buttercup-desktop#linux).
