### ISSUE TITLE
Failed deriving key salt must be provided

### ISSUE THREAD

**Issue by cabdev** [buttercup/buttercup-desktop#1039]
Hi, I want to thank you for creating this wonderful and simple password manager. I have keyed in my password and it resulted to Failed mapping credentials to a source: Failed deriving key: Salt must be provided.

I hope you can address this problem since there are important accounts that are stored in that .bcup file. An answer will be greatly appreciated.

**Comment by perry-mitchell** [comment]
Please provide more information:

- Your OS
- Bcup desktop version
- Exact steps you took in creating/connecting your vault
- Exact steps after that to reproduce the issue

**Comment by cabdev** [comment]
I have tried two versions
I am in Ubuntu Linux

v2.5.1
v1.20.4

I have already copied it and opened but I have keyed in wrong master password. And the error Salt must be provided comes after I have keyed in the correct master password. I have a new keyboard so I am getting used to it that's why I got the password incorrectly.I just need to know the context why salt must be provided. Thank you for your response.

**Comment by perry-mitchell** [comment]
Ok, sorry if I misunderstand you - but you entered your password incorrectly when _creating_ the vault? If so there's nothing I can do to help you retrieve your password.. Buttercup is a secure vault wrapped around native encryption technologies and we provide no major modification of the processes they use to encrypt and decrypt text. Only the password can unlock vaults, nothing else. 

The salt provided error sounds like decryption failed, but the wrong error is being provided in the message - or at least, I'd expect a decryption failed message to appear, not something related to the salt. The salt is a random string attached to the password when encryption is being performed - it's an added layer of security. It's nothing the user needs to be concerned about, and not something you ever need to see or remember. During normal operation the salt is not seen by anyone and is simply stored alongside the encrypted payload.

**Comment by perry-mitchell** [comment]
I'll close this issue as it sounds more like a question rather than a bug with Buttercup.
