### ISSUE TITLE
Can't add vault from Google Drive

### ISSUE THREAD

**Issue by jescobarv-git** [buttercup/buttercup-desktop#1040]
When using the desktop app in Fedora 34 when adding a new vault from drive it takes you to the browser for permissions, once permissions are allowed it stays on the authentication screen.

![image](https://user-images.githubusercontent.com/61430982/119032310-a83dd680-b971-11eb-94dc-a5687d99475e.png)

![image](https://user-images.githubusercontent.com/61430982/119032189-85132700-b971-11eb-9ddc-e291dfaf4b86.png)

**Comment by perry-mitchell** [comment]
Yes, seems to be an issue with auth - not sure if related to #987. I don't use Google drive actively so any help would be appreciated.

**Comment by perry-mitchell** [comment]
Buttercup AppImage installs require AppImageLauncher to work correctly with protocols (such as that required for Google authentication). The `AppImage` authors also recommend installing this tool. Please refer to our [new instructions](https://github.com/buttercup/buttercup-desktop#linux).
