### ISSUE TITLE
copy username/password shortcut

### ISSUE THREAD

**Issue by odbaeu** [buttercup/buttercup-desktop#1041]
I miss the functionality to copy the username (cmd + b) and password (cmd + c). This was implemented in earlier versions.

Will this feature be implemented again?

Currently I use the following version:
Desktop @ v2.5.1
Core @ v5.13.1
MacOS

**Comment by perry-mitchell** [comment]
Copy password is already implemented but buggy, it seems. Copy username should be brought back, I agree.

**Comment by antoine-amara** [comment]
Hello, I'm working on this issue, I've got a potential solution but, I don't know if it is the best way to resolve it.

My idea is to update the `Entry` component from `@buttercup/ui` package to add a `Hotkeys` component to define ctrl+b and ctrl+c shortcuts for entry username and password.

Moreover, I don't know how to test my update on `@buttercup/ui` in `buttercup-desktop`.

What do you think about my idea @perry-mitchell ? If it is the right way, I can implement it and open a pull request on `buttercup-ui` repository.
