### ISSUE TITLE
[Enhancement] Automated local vault backup when using cloud vault

### ISSUE THREAD

**Issue by fmommeja** [buttercup/buttercup-desktop#1048]
Hi @perry-mitchell 

it would be great if we could check an option in the parameters allowing us to locally define a file path that would indicate where to save a copy of a cloud vault in use, every time this last one is modified.

This way, if there was any kind of issue with the cloud service we use, we still could open our vault(s) on our machine local drive and use our precious passwords.
This would then provide us with a real-time backup, which would not be irrelevant.

**Comment by julianpoemp** [comment]
This would have an interesting side-effect: We could use Buttercup offline e.g. when we go by train and want to use buttercup on our notebook, but there's no internet connection. To make it easier to implement, Buttercup could open the last backup in read-only mode so there is no need to synchronize new entries after switching to online mode.

**Comment by perry-mitchell** [comment]
Buttercup already has offline vault support with read-only access when there's no connection available, but this hasn't been added in desktop yet (#307).

Otherwise I completely agree that we need scheduled/automatic local+remote backup capabilities. I'll keep this open to track that.

**Comment by yxw820603** [comment]
Hi,any news about this feature?
I like this application.if this feature done,then this application is **Perfect** ,because some people(me) use this application manage some offline program password or sometime i can not use internet connection.

**Comment by perry-mitchell** [comment]
Seeing as we're about to rollout format B for our vaults, this would make sense to have first. I'll try to get to it this weekend.

**Comment by fmommeja** [comment]
Great news @perry-mitchell !!!
Thank you :)
