### ISSUE TITLE
Cannot make multiple selection with a filter

### ISSUE THREAD

**Issue by pedro000p** [buttercup/buttercup-desktop#1051]
I want to select all the logins that have a filter pattern, but i cant, which is a pain to make it 1 by 1.
I exported a .csv from google account and i want to make a group for each different e-mail that i have to simplify.
I think that this common features should be present like:

- Ctrl (control) key and the click on each item (using the mouse/trackpad) to select multiple items simultaneously
- range of items, use the Shift key, with the hold of the shift key and the click on the last item in the range

By the way the foundations of Buttercup are nice and solid in the UI. I hope it can grow from this.

Kind regards for all that develop this OpenSource app,

**Comment by perry-mitchell** [comment]
@pedro000p What do you want to do with the items once selected?
