### ISSUE TITLE
[Bug] Unable to create new Entry in v2.8.0

### ISSUE THREAD

**Issue by devang-metron** [buttercup/buttercup-desktop#1053]
After updating to 2.8.0, New Entry button is not working. It does not display any error message on screen or in log files.

**Comment by julianpoemp** [comment]
same here on MacOS 11.4

**Comment by stanschus** [comment]
same here: Ubuntu 20.04 / AppImage 
Creating a new Vault or group works.
Modifying an existing entry or adding a new one doesn't

editing throws error message, will post it in #1055

**Comment by perry-mitchell** [comment]
Closing in favour of #1055
