### ISSUE TITLE
Can't connect to webdav

### ISSUE THREAD

**Issue by LucasStinchcombe** [buttercup/buttercup-desktop#1054]
I have a password protected webdav instance running via Apache2.
It uses ssl certificates signed by Comodo SSL, and on connection, I get the following:

> Vault unlock failed: Error invoking remote method 'unlock-source': Layerr: Failed unlocking vault source: Failed unlocking source: unable to verify the first certificate

I'm able to access it via browser.

**Comment by perry-mitchell** [comment]
This is most likely a [server configuration issue](https://stackoverflow.com/a/7644229/966338).. and not something that buttercup can control. SSL certificates must be valid as to what a browser would expect in a strict environment.

**Comment by LucasStinchcombe** [comment]
Stackoverflow seems down for me atm. Thanks, I'll look into it as it's odd that I can access from browser but buttercup cannot.

**Comment by LucasStinchcombe** [comment]
Big thanks, I hadn't installed the certificate chain and didn't have write permissions on the directory on the wedav server.
