### ISSUE TITLE
Buttercup going online while it is configured to store the passwords locally

### ISSUE THREAD

**Issue by JF0001** [buttercup/buttercup-desktop#1058]
I have installed the Desktop version of Buttercup on my Ubuntu 20.04 system, configured to store the passwords only locally (not in the cloud). I have noticed in nethogs (utility which monitors network traffic), that buttercup goes online when open (nethogs displaying the following entry: /.mount_Butter*****/buttercup --utility-sub-type=network.mojom.NetworkServices)

Why is Buttercup going online while it is configured to store the passwords locally?

Thank you. J

**Comment by julianpoemp** [comment]
I think that it goes online because it checks for new updates (I'm just a user, not a developer). Perhaps you can use Devtools  (Debug > Devtool > Network)  or Wireshark to check it?

**Comment by JF0001** [comment]
Thank you @julianpoemp Yes, possibly, but what is strange is that the process doesn't seem to close once it has been started, although indeed, it doesn't appear to be sending or receiving much/if any data. I was hoping to receive an answer without having to troubleshoot. Thanks again. J

**Comment by perry-mitchell** [comment]
> the process doesn't seem to close once it has been started

This is by design. The app stays running in the background for faster launching and easier vault access. You can literally see it in the task bar.

> Why is Buttercup going online while it is configured to store the passwords locally?

Buttercup checks for updates while online, that's it. It doesn't make any other request unless you unlock a vault that is of a remote nature, like Dropbox.

**Comment by JF0001** [comment]
Thank you for your answer @perry-mitchell !
