### ISSUE TITLE
How can I provide translations in other languages?

### ISSUE THREAD

**Issue by zeenpower** [buttercup/buttercup-desktop#1060]
I want to translate the software into Chinese, how can I help you?

**Comment by perry-mitchell** [comment]
Hi @zeenpower! We'd love a Chinese translation - please follow [these instructions](https://github.com/buttercup/buttercup-desktop#translations) if you'd like to contribute. There's 2 projects, our [UI library](https://github.com/buttercup/ui) and this one, that need translations added.

**Comment by perry-mitchell** [comment]
I'll close this issue for now, thank you.
