### ISSUE TITLE
[BUG] Cannot read property 'createEntry' of null when no group selected

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#1062]
If I try to add a new entry without selecting any group it fails with an error message: `Cannot read property 'createEntry' of null`. Full error message:

````
index.js:530 Uncaught (in promise) Error: Failed saving vault: Cannot read property 'createEntry' of null
    at EventEmitter.<anonymous> (index.js:530)
    at Object.onceWrapper (events.js:422)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)
````

To reproduce this bug you need to unlock a vault and right after that click on "New Entry".

Tested on Windows and MacOS with the latest version of Buttercup: 2.9.0

### Suggestion

If users should not add any entries outside of groups, the "New Entry" button should'nt appear.

**Comment by julianpoemp** [comment]
Sorry, I didn't see issue #1053

**Comment by perry-mitchell** [comment]
Thanks @julianpoemp - Yes seems to have returned unfortunately.
