### ISSUE TITLE
Make copy button larger

### ISSUE THREAD

**Issue by jgorfenger** [buttercup/buttercup-desktop#1064]
The copy button is very small. Please consider making it much larger wherever it's used. That way, users don't have to struggle to be precise with their mouse when clicking the copy button.

I suggest making the copy button at least 5 times wider and roughly 2 times taller. This change might actually help reduce wrist strain.

![buttercup_tinypaste](https://user-images.githubusercontent.com/82081204/123371244-e2058c80-d570-11eb-8db3-cfda8134842d.png)

**Comment by perry-mitchell** [comment]
Closing in favour of #1049, for now.. as the copy button might go away (to improve UX).
