### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by vkuznet** [buttercup/buttercup-desktop#1079]
HI, before making migration from 1Password to Buttercup I would like to know what is a status of ARM support. I saw on a main page that it is not supported yet but I would like to know if it is in pipeline and what is timeline for such support. I view ARM support important as more hardware vendors will move to it (I would assume all major platform, Linux, Mac, and WIndows) will required it soon.

**Comment by Claywd** [comment]
I'm interested in this as well. Willing to give it a go if there is a way to directly collaborate like discord or matrix. I'm running a librem 5 so an arm64 app image would be ideal

**Comment by perry-mitchell** [comment]
Hi! I'm actually not at all sure as to the current ARM support, as the only real restriction is what Electron supports in terms of platforms. We don't use any platform specific code so as long as Electron supports ARM, I don't see why Buttercup wouldn't. I'd be very surprised if it didn't support it this late in the game.

I'll leave this open as I don't have time to check this myself right now. Hopefully someone else can check the status of ARM support with Electron.

**Comment by perry-mitchell** [comment]
This should be solved by #1090, which is pending release.

**Comment by lukechilds** [comment]
@perry-mitchell as far as i can tell that PR only adds arm support for Linux, any plans to support arm based Macs?

**Comment by glenvan** [comment]
@perry-mitchell, it isn't actually all that hard. I could start a PR for this, but as your DMG file name would have to change (impacting your deployment, especially the [Homebrew Recipe](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/buttercup.rb), it's probably better to supply a patch for the core team to consider.

[mac-universal.patch](https://github.com/buttercup/buttercup-desktop/files/10559608/mac-universal.patch)

"Works for me..." and makes a big difference for the launch time.

**Comment by chrw** [comment]
What's keeping us from releasing a macOS Apple Silicon version? This is the single one reason I can't use Buttercup just yet. Installing Rosetta is not an option. It's a hack.

**Comment by julianpoemp** [comment]
On another project I was able to build an Electron app using electron-builder with platform = mac and arch = arm64 . Should work for this project, too. It would be nice to have an ARM version of buttercup because it improves the performance on MX Macbooks very much.
