### ISSUE TITLE
WEBDAV error for write

### ISSUE THREAD

**Issue by acexiis** [buttercup/buttercup-desktop#1084]
I can add a vault from webdav server thats work fine on the MacOS client, Linux Client or chrome plugin
but I can't write new password on each client.

Error on MACOS
`request failed with status code 403`

On plugin web
`Failed updating archive
Unable to update archive (3d8070bb-2720-4e73-9aa3-e5b5ed279c66): Failed applying vault facade: Request failed with status code 403`

Suggestion ?

**Comment by perry-mitchell** [comment]
This sounds to me like a limitation or restriction regarding your WebDAV server. I use webdav daily on different services and write works fine.

403 is a permissions failure, or likely some other kind of configuration issue on your WebDAV host. What webdav service are you using? A personal/private one, or a commercial host?

**Comment by acexiis** [comment]
@perry-mitchell thanks for your answer.

I know the message seems to be en problem of permission but for webDav server I use webdav on my own synology server and I use it with the admin account and full access in webdav. I dont't have an other webdav server to test it but I don't think the rights are the problem. Do you have any idea ? 

Thanks

**Comment by perry-mitchell** [comment]
Unfortunately I can't help unless I see the results of what your WebDAV server is returning. A recommendation from my side is to double check that you don't require **digest** authentication on your webdav server - only basic will work.

Besides that, a 403 is simply an authentication error that is out of the scope of Buttercup unless you can find an example of where the error is arising from (incorrect data being sent by Buttercup, etc.). Buttercup uses [this client](https://github.com/perry-mitchell/webdav-client) for WebDAV access, so any webdav-related bugs should be opened there as well.

I'll close this in the meantime as there's no action here right now.
