### ISSUE TITLE
Webdav vault - Certificate error

### ISSUE THREAD

**Issue by emendo-web** [buttercup/buttercup-desktop#1091]
Hi,

We use ButterCup desktop to connect to webdav server.
Your vaults are on this webdav share.
Since yesterday, we have this error :

Le déverrouillage du coffre-fort a échoué: Error invoking remote method 'unlock-source': Layerr: Failed unlocking vault source: Failed unlocking source: certificate has expired.

We could correctly connect to the webdav server using Chrome.

Best,
Sebastien.

**Comment by julianpoemp** [comment]
same for me. Desktop Client 2.10.0 certification error on MacOS BigSur 11.6.

**Comment by julianpoemp** [comment]
@perry-mitchell could you fix this, please?

**Comment by emendo-web** [comment]
Same Desktop and OS version than julianpoemp.

**Comment by toxis** [comment]
Hello,

Same here, we use Let's Encrypt certificate and their DST Root CA X3 is expired: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Maybe Buttercup does not integrate the new ISRG Root X1 to validate correctly Let's Encrypt certificate?

**Comment by perry-mitchell** [comment]
As far as I know, this isn't up to Buttercup. I don't manage any certificate authority validation. Buttercup has no embedded certificate information.

Perhaps this is an issue with Electron? I'll try an update shortly.

**Comment by julianpoemp** [comment]
@perry-mitchell it's working now with the new update! Thank you very much! 😄

**Comment by emendo-web** [comment]
It's working too with the new update. Thanks ! 👍

**Comment by toxis** [comment]
Yep working with the update, thanks! ☺️

**Comment by perry-mitchell** [comment]
Glad to hear! Must have been an electron thing 😅
