### ISSUE TITLE
Ordering custom fields in an entry

### ISSUE THREAD

**Issue by Keikai1880** [buttercup/buttercup-desktop#1104]
Requesting new feature:

**Problem:**
When i have lots of custom fields in an entry i cannot reorder them, reordering is very handy when i have lots of fields and wanna put related fields under each other. For example when i add fields, the field names look like this (i wrote here the field names only not their values):

```
Cpanel username
Cpanel password
Account username
Account password  
```
Then afterward i added a new `Cpanel url` field:
```
Cpanel username
Cpanel password
Account username
Account password
Cpanel url  
```
I want to reorder them to look like this:
```
Cpanel url
Cpanel username
Cpanel password
Account username
Account password  
```
I want to be able to order the `CUSTOM FIELDS` in an entry, currently they are being added in order. I want to be able to drag them up and down or reorder them in any other way. This will help a lot in putting related fields together when i have many fields.

Thank you for help and support.

**Comment by perry-mitchell** [comment]
buttercup/buttercup-core#165
