### ISSUE TITLE
Webdav - cannot read properties of null

### ISSUE THREAD

**Issue by taumeister** [buttercup/buttercup-desktop#1105]
Unfortunately I can't access any database via webdav, neither from my cell phones ( iphone/android) nor from any operating system ( Linux / Windows ).

The error message from Linux (Firefox/Edge) for example reads:
'Failed connecting to 'webdav' resource.
A connection attempt to https://... has failed.
Cannot read properties of null ( reading 'getDirectoryContents').

The webdav storage is located on its own Nextcloud storage.
Access via browser addons like KeepassXC with access to the same webdav storage works without problems.
![ksnip_20211201-150101](https://user-images.githubusercontent.com/86101207/144247848-84a9dbb1-0f04-44a4-b1de-71c4f15b9b97.png)

**Comment by perry-mitchell** [comment]
Hi @taumeister - Unfortunately I can't reproduce this. I use Nextcloud also, on all platforms, and it works just fine.

If you find some way that I might be personally able to reproduce this, I can try to help. If you want me to check your Nextcloud service via Buttercup I'm happy to do this privately, but it's up to you of course. You can find me on [Keybase](https://keybase.io/perrymitchell), for instance.
