### ISSUE TITLE
macOS Desktop v2.13.0 fails to open Google Drive archive

### ISSUE THREAD

**Issue by xakraz** [buttercup/buttercup-desktop#1118]
I have just updated the desktop app as suggested by the self-update system.
I am now with v2.13.0 on MacOS Mojave 10.14.6 

<img width="467" alt="Screenshot 2022-01-15 at 18 55 18" src="https://user-images.githubusercontent.com/1590399/149633069-5676ff7e-d18e-43a2-b273-850d28f461cf.png">

And I can not unlock my previously configured archive stored on Google Drive

<img width="564" alt="Screenshot 2022-01-15 at 18 55 06" src="https://user-images.githubusercontent.com/1590399/149633091-5266a23e-4034-4049-883e-35f0b909549c.png">

📝 :
* The Google Chrome extension still can open the archive
* The Android version still can too (`v2.1.0`)
<img width="379" alt="Screenshot 2022-01-15 at 19 15 55" src="https://user-images.githubusercontent.com/1590399/149633314-eefc2598-11f3-4982-a44c-d7ddcf757698.png">

**Comment by perry-mitchell** [comment]
Seems I'm able to reproduce, I'll take a look.

**Comment by perry-mitchell** [comment]
Seeing this in the logs:
```
[INF] 18:47:43: Google Drive datasource needs re-authentication
[INF] 18:47:43: Datasource contains refresh token: Refreshing authorisation
[INF] 18:47:43: Refreshing Google Drive token
[ERR] 18:47:44: Failed unlocking vault source Layerr: Failed unlocking source: Failed fetching Google Drive vault: Request failed: 400 Bad Request
at                            buttercup/dist/core/VaultSource.js:487  throw new layerr_1.Layerr(err, "Failed unlocking source");
at processTicksAndRejections  node:internal/process/task_queues:96
```

Seems refreshing OAuth tokens is failing. Not sure why.

**Comment by perry-mitchell** [comment]
This might simply be a case that the token needs to be fully re-loaded, after a fresh login cycle. This requires additional auth flow implementation. I'll try to get it done ASAP.
