### ISSUE TITLE
[BUG][Critical] v2.14.2 unable to sync on dropbox

### ISSUE THREAD

**Issue by Alexintosh** [buttercup/buttercup-desktop#1122]
Hello devs,
Taking the change to express my appreciation on this product which has gone a long way :)
The latest version presents a critical issue that does not allow to save the state after adding a new entry or editing one.

After a change, the toast will appear but nothing happens, it stays there forever.
The console presents no errors and no XHR requests are registered. As a result, passwords are lost when the app is closed.

The vault is stored on dropbox.
<img width="319" alt="Screenshot 2022-01-30 at 11 02 02" src="https://user-images.githubusercontent.com/776519/151697006-737b3799-acb2-4ce8-bc58-e557b771aa55.png">

```
Desktop @ v2.14.2
Core @ v6.7.0
Flags: installed
```

**Comment by perry-mitchell** [comment]
Hi, thanks for the message!

Is this reproducible every time? If so, could you try again with the dev tools open to see if there are any pending or failed requests? Perhaps we need a timeout.

**Comment by perry-mitchell** [comment]
Closing as I haven't heard back. Will reopen if it's reproduced.
