### ISSUE TITLE
Permissions on Google far too invasive

### ISSUE THREAD

**Issue by dlannan** [buttercup/buttercup-desktop#1125]
Im very concerned about the security requirements Buttercup is recently doing.
Because of this I will not ne using Buttercup anymore (its just too dangerous to be sharing this sort of information).
I want to raise this with the developers and let others know. 

The base requirement for Buttercup should _not_ require peoples information for tracking or details. You only need secure login information and thats it. If you want to use 2FA then do that, but do NOT request 4 levels of google information from users.

Its clear to me that someone involved in this project is selling that information. The network traffic is also unacceptable.

**Comment by perry-mitchell** [comment]
This is why we have the following option, which is **off** by default:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/3869469/163100198-06d0483b-e35b-4962-af6b-00a9b1991322.png">

> Its clear to me that someone involved in this project is selling that information.

Any evidence to back up your claims? It's an open source project.. you can literally go read all of the code we've put into this project. 

> The network traffic is also unacceptable.

You state no evidence as to what you mean by this. We don't load external assets, and we only request updates and the user vaults from remote sources.

**Comment by perry-mitchell** [comment]
As it seems like you've had an agenda, I bid you farewell. We encourage users to come forward with concerns but would at least expect some dialog before coming to any conclusions.
