### ISSUE TITLE
Multiple URLs for single account

### ISSUE THREAD

**Issue by ZTiKnl** [buttercup/buttercup-desktop#1128]
Again, I just started migrating from MYKI to Buttercup, so apologies if I missed something obvious ;)

Is Buttercup capable of linking multiple websites to a single account?

For example, a https://gmail.com and a https://google.com account are the same username/password/OTP.
Do I have to create a separate account for each, or does Buttercup have a way to detect/scan outside URL field for connected URLs?

If not yet possible, can I perhaps suggest having Buttercup to scan for URL# fields?
(just a thought...)

Using a new Website entry:
```Title: Test
Username: Test
Password: *********
URL: https://example.org

Custom fields:
URL1: https://example.com
URL2: https://example.edu
```

**Comment by perry-mitchell** [comment]
Hi, 

This should work out of the box in the browser extension. Not 100% sure on the mobile app (due to how password autofill is handled by the OS). But the intention is that you can use as many URLs as you want.

If there are glitches etc. regarding this functionality I'd mark those as bugs.
