### ISSUE TITLE
Recover vault from phone

### ISSUE THREAD

**Issue by dirk527** [buttercup/buttercup-desktop#1130]
I have my .bcup file on a WebDAV drive, where it seems to have been corrupted.

However: I can still open Buttercup on the iPhone in offline mode and access all data.

Is there any way to recover the .bcup file? Or export all the data, or copy it to a new vault, or something?

**Comment by perry-mitchell** [comment]
Unfortunately not at the moment I'm afraid. That would pose a bit of a security risk, allowing someone to dump the contents of a vault on a mobile device.

Any chance you had a backup? If you use a service like Dropbox/Box/Nextcloud/ownCloud they have _revisions_ of files so you can restore to an earlier point.

**Comment by perry-mitchell** [comment]
I'll close this as there's unfortunately no other action to take here.
