### ISSUE TITLE
Impossible to add custom field

### ISSUE THREAD

**Issue by vlanse** [buttercup/buttercup-desktop#1131]
When adding custom field (either for new document of when editing existing one), "Save" button gets disabled and stays disabled until all custom fields are removed

So, adding custom field of any type is impossible in fact, issue is critical (to me) because OTP key could not be added

About info:

Desktop @ v2.14.2
Core @ v6.7.0
Flags: installed

**Comment by perry-mitchell** [comment]
@vlanse Can you record a screen capture or something? Or steps to reproduce?

**Comment by q3aql** [comment]
@vlanse That's because you haven't set a name for the 'custom field'.

![buttercup](https://user-images.githubusercontent.com/11588247/163812249-79c83f44-f1ff-49de-b87b-6996d661b0e4.png)

After that, the 'save' button will be enabled.
