### ISSUE TITLE
Can I use buttercup as a library?

### ISSUE THREAD

**Issue by qleguennec** [buttercup/buttercup-desktop#1133]
Hello, I am building an electron app which needs to store sensitive passwords on the user file system. A master password is needed to access those password, so it seems like buttercup would be a good fit. 

Could I easily use buttercup as a library?

**Comment by perry-mitchell** [comment]
Hello - sounds cool! And exactly what the Buttercup core library was made for. You can certainly use it in your project - it's MIT licensed and regularly updated.

**Comment by qleguennec** [comment]
Thank you, I should've looked into that first!
