### ISSUE TITLE
Import CSV: what are names of fields in Notes Entry?

### ISSUE THREAD

**Issue by salsysd** [buttercup/buttercup-desktop#1134]
Hi, I'm coming back over to buttercup as my primary password manager got acquired and shut down their products...

But Im trying to migrate all my shit over via csv imports. via desktop app.

what are the field names for Notes? or really any entry for that matter? I'd like to be able to just change the table header titles (if you will) of my csv files then import them so they map correctly into buttercup...

**Comment by laurensmiers** [comment]
Never tried importing CSV with buttercup, but if I export my vault to csv, I get this as column names:

!type,!group_id,!group_name,!group_parent,title,username,password,URL,Notes,id,url,email,Unlock code,Org ID,PUK

**Comment by salsysd** [comment]
@laurensmiers oh good idea! derp.. shoulda thought of that.. I ended up just manually fixing my data - notes group. So Ima close this.
