### ISSUE TITLE
Chrome version 94 ?!?

### ISSUE THREAD

**Issue by streamnsight** [buttercup/buttercup-desktop#1136]
When I use the DevTool to look at debug stuff, the frist thing that pops up is 'What's new with Chrome 94'

We're at Chrome 101.0.4951.41 now and 100 was already a hot fix for some serious security issues.

Is this thing still safe to use if it runs on Chrome 94 under the hood?

**Comment by perry-mitchell** [comment]
It's still completely safe, yes. Buttercup isn't exposed to the same conditions as a normal browser is, even though it embeds a version of Chrome. We do occasionally update the embedded Chrome version via Electron, but that's a lot of work and we don't have the time to do it continuously.

Still want to iterate: It's safe.. Buttercup doesn't import 3rd party scripts so there's no foreign code running (beyond our own deployed dependencies).
