### ISSUE TITLE
[Feature Request] Change Entry type after creation, keeping similar field values

### ISSUE THREAD

**Issue by juninholiveira** [buttercup/buttercup-desktop#1138]
I would like the possibility to change the Type of my entries. I have multiple entries of the "Default" type, that I would like to change to "Website" while keeping the values of the fields with the same name.

**Comment by ldexterldesign** [comment]
👋

I suggest following up / subscribing [here] - if y'all agree then please close this issue to help the repo' maintainer

Hope this helps!

Regards

[here]: https://github.com/buttercup/buttercup-desktop/issues/1219

**Comment by juninholiveira** [comment]
@ldexterldesign 

Close as completed, or close as not planned? What would be more useful to the maintainer?

**Comment by ldexterldesign** [comment]
The maintainer has both commented and labelled the other issue so this seems like a superfluous duplicate now

If you don't agree then do nothing

Regards

**Comment by juninholiveira** [comment]
I do agree! Just don't know what option to choose when closing. But it's a minor detail, anyway. Will close it now. Thank you!
