### ISSUE TITLE
AppImage in windows WSL

### ISSUE THREAD

**Issue by Claywd** [buttercup/buttercup-desktop#1139]
Couldn't get buttercup to run in windows 11 anymore so I resorted to running the appimage for linux in my debian wsl distro. Ran into this issue when it tries to update though. 

[3594:0512/072029.594816:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

I started dbus manually but no luck... not sure what the best way to address this and wondering if its an upstream error with electron. 

any direction appreciated.

**Comment by perry-mitchell** [comment]
Unfortunately this is out of scope for Buttercup Desktop, in my opinion.. Buttercup was designed for Windows with its own build, which is what we support. We don't support running Buttercup under WSL on Windows..

It would be best to address the issues you're having running the Windows version. Sorry for the inconvenience.
