### ISSUE TITLE
Buttercup Desktop won't authenticate on Google Drive

### ISSUE THREAD

**Issue by srrhub** [buttercup/buttercup-desktop#1142]
Ubuntu 20.04. Buttercup (Buttercup-linux-x86_64.AppImage). Open it, click on add a vault, select google drive, click Authenticate, new web page opens (in Chrome), I input my credential, continue, a new web page opens at Buttercup.pw saying "Authenticated. You can close this window now." I close it. 
The problem is that the desktop version still displays the same page about adding a vault and to click "Authenticate or Cancel". The info about the authentication done with the browser was not received by to the desktop version.

**Comment by perry-mitchell** [comment]
Unfortunately I can't reproduce this issue. I'm using appimage on ubuntu and it works every time I try, regardless of the permissions setting.

It sounds like an issue with the registration of the buttercup protocol (that the auth uses to contact the app), but I can't be sure.
