### ISSUE TITLE
Trying to download attachment

### ISSUE THREAD

**Issue by ghost** [buttercup/buttercup-desktop#1150]
I am trying to download an attachment, but it keeps failing.
The error messages I get is:

1. Failed downloading attachment: Error invoking remote method 'attachment-download': Error: Authentication failed while decrypting content
2. Failed deleting attachment: Error invoking remote method 'attachment-get-data': Error: Authentication failed while decrypting content

I have tried logging out and logging in again but it does not help.

It's the same problem with the addon on Google Chrome.

**Comment by perry-mitchell** [comment]
Unfortunately this is probably a corruption - a different attachment key was saved at some point, perhaps when updating the attachment from another device.. Then the vault has probably been rolled back or changed state at some point and the key no longer matches the attachment.

While a bug, there's nothing I can do to restore the key, sorry.
