### ISSUE TITLE
When I search for twitch in the document filter section app crashes with a error message.

### ISSUE THREAD

**Issue by Ramen5914** [buttercup/buttercup-desktop#1152]
It only happens when I type the last letter it twitch, the "h". I can type h any other time, but I can't type ich either or the same error is displayed.

Here is the error message:
![image](https://user-images.githubusercontent.com/49323171/180623975-bbb4d276-dc93-425c-afec-98a44946666b.png)

**Comment by perry-mitchell** [comment]
Can't reproduce. If it continues to happen, creating a reproduction vault for testing would be very helpful.
