### ISSUE TITLE
Vault Name in tab

### ISSUE THREAD

**Issue by saderi** [buttercup/buttercup-desktop#1155]
I just upgrade from `v2.14` to `v2.16` and this drag-able tabs are good but before this feature If someone looked at my monitor, they only saw the first two letters of the vault name, but now they can see the full name of vaults.

Sounds like a privacy issue :)

It might be nice to have the option to switch to the previous tab version or the option to use color and short name like the previous tab view.

BTW, Buttercup is awesome.
Thank you.

**Comment by perry-mitchell** [comment]
You could expand the old sidebar to show the full name of the vault, so in that way there's no difference. Imo the name should not be sensitive - if users have access to the session/drive where you store Buttercup, then of course they'll be able to read unencrypted settings. If you're concerned about Buttercup's unencrypted features such as filenames I'd recommend not sharing your account, or renaming the file to something nondescript.

For now I think the tabs will stay, as they're much more usable compared to the sidebar (original items weren't draggable). The new tabs will need some love going forward as they're still a bit stiff, but I think they're the way to go. I would accept someone adding the work to support say vertical tabs with some alternate designs, but that'd have to be done [here](https://github.com/buttercup/ui).
