### ISSUE TITLE
Error invoking remote method 'unlock-source' - Impossible to unlock vault

### ISSUE THREAD

**Issue by ln56b** [buttercup/buttercup-desktop#1156]
I am on version Desktop @ v2.16.0 with Core @ v6.14.0.
When trying to unlock the vault, I get the following error `"Error invoking remote method 'unlock-source'. Layer: Failed unlocking vault source. EPERM: operation not permitted"`

I could successfully unlock my vault with same password using buttercup chrome extension though.

Not sure when the problem arose, I tried to downgrade to v2.14.0 but encountered the same issue.

**Comment by perry-mitchell** [comment]
Could you please check your logs and see what the underlying error actually is? Sounds like the file you're using isn't accessible by your current user.

What datasource are you using? File/Dropbox etc?

**Comment by ln56b** [comment]
I am using File as datasource and could not get any additional logs from the one I submitted.
Pb solved though 😃 
I deleted the vault and added it again (using File) and it now works. It looks like the app could not link to my vault anymore.

Thanks !

**Comment by Osmauro** [comment]
Hola, tuve el mismo inconveniente en el Sistema Operativo Windows con esta versión: 
Desktop @ v2.18.2
Core @ v6.17.2
Lo que me funcionó a mi fue lo siguiente: Desinstalar por completo el programa (yo utilicé "Revo Uninstaller"), luego volver a descargar el instalador, y una vez abra, quitar el Cofre, y luego volver a añadirlo en el programa.

Espero que sea de utilidad para alguien más con la misma situación.

--------------------------------------------------------------------------------
Hi, I had the same problem on Windows OS with this version: 
Desktop @ v2.18.2
Core @ v6.17.2
The solution what worked for me was the following:
Completely uninstall the program (I used "Revo Uninstaller"), then re-download the installer, and once open, remove the Chest, then add it back into the program.

I hope this is helpful to someone else with the same situation.
