### ISSUE TITLE
Cannot connect to PCloud Webdav

### ISSUE THREAD

**Issue by dtantono** [buttercup/buttercup-desktop#1157]
Hi
I tried to connect Pcloud account webdav protocol that have 2fa. But, it does not work on Windows 10.
<img width="579" alt="image" src="https://user-images.githubusercontent.com/29157187/184628399-da8b2c48-d670-4226-bf34-fefd31c2f414.png">

**Comment by perry-mitchell** [comment]
Unfortunately not enough info to go on here, as I don't use PCloud. Logs might help but I don't think this is always the case with these network issues..
