### ISSUE TITLE
MacOS icon enhancement

### ISSUE THREAD

**Issue by zenpeaky** [buttercup/buttercup-desktop#1170]
Hi community, I think the icon on macos is not respecting the OS design concept, especially on the rounded corner and the size.
I can help to edit the icon, something like I do for Antares sql app, but I need your editable icon thanks.

template and example :
[template.zip](https://github.com/buttercup/buttercup-desktop/files/9570974/template.zip)

**Comment by perry-mitchell** [comment]
What specifically is wrong with the icon, in your opinion? I've checked your assets and look at the icon daily on Mac OS, and don't think it stands out from any other app I use. I use a lot of free and open source software.

**Comment by zenpeaky** [comment]
Hi @perry-mitchell , 
actually nothing is wrong with the icon. But if you read this apple guidelines and this post, you will see that the icon and its rounded-corner is bigger,

Reff:
https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/#best-practices
https://bootcamp.uxdesign.cc/creating-app-icons-for-macos-11-and-up-1132ccd479bc

comparison:
<img width="495" alt="Screen Shot 2022-09-16 at 8 40 35 AM" src="https://user-images.githubusercontent.com/47457477/190534039-e2726e86-3452-4b5a-9017-d136ffbb83bb.png">
<img width="335" alt="Screen Shot 2022-09-16 at 8 41 41 AM" src="https://user-images.githubusercontent.com/47457477/190534050-054301df-6683-43cc-bb12-34901fc1bd84.png">
