### ISSUE TITLE
unable to add otp 

### ISSUE THREAD

**Issue by anwaruddin2k** [buttercup/buttercup-desktop#1173]
I have been using keepass for long time but adding totp not working in buttercup .
![image](https://user-images.githubusercontent.com/53415502/191180063-e3c4310b-ecd9-4286-846b-23de4b8a4390.png)

**Comment by anwaruddin2k** [comment]
![image](https://user-images.githubusercontent.com/53415502/191180386-c84d01a9-d4ed-4140-a691-8599b01c00d7.png)

**Comment by anwaruddin2k** [comment]
![otp](https://user-images.githubusercontent.com/53415502/191180817-0acdf930-a974-4b08-b48f-5a011a887e9b.png)

**Comment by wrrnlim** [comment]
OTP needs to be added as a URI:
```
otpauth://totp/generator?period=30&digits=6&secret={YOUR_SECRET}
```

**Comment by anwaruddin2k** [comment]
thanks

**Comment by nursoda** [comment]
This should be added to documentation, or a user friendly dialog should be provided once OTP is selected as type.
