### ISSUE TITLE
Cannot unlock Vault: 'Salt must be provided' or 'maxContentLength size exceeded'

### ISSUE THREAD

**Issue by laurensmiers** [buttercup/buttercup-desktop#1177]
Hi,

I'm unable to unlock my Vault anymore, nothing special happened to my knowledge. It just stopped working.
I tried several ways, through the buttercup-desktop app, through android app and through firefox extension. All exhibit the same behaviour described below.

I'm getting the following error:
`
Vault unlock failed: Error invoking remote method 'unlock-source': Layerr: Failed unlocking vault source: Failed unlocking source: Failed deriving key: Salt must be provided
`
I am entering the correct password because if I enter a wrong password, I get the following error:
`
Vault unlock failed: Error invoking remote method 'unlock-source': Layerr: Failed unlocking vault source: Failed unlocking source: Authentication failed while decrypting content
`
I don't know why, but sometimes, I get a different error in buttercup-desktop about max-content-length:
`
Vault unlock failed: Error invoking remote method 'unlock-source': Layerr: Failed unlocking vault source: Failed unlocking source: maxContentLength size of 209715200 exceeded
`
Not sure how to proceed, I tried downloading the password-file and just opening that, but then I get the 'Salt'-error.

Anyone have any ideas?
Thanks,

Laurens.

Environment:

OS: EndeavourOs/Arch Linux
Buttercup desktop: 
Desktop @ v2.17.0
Core @ v6.16.2

**Comment by perry-mitchell** [comment]
Apologies for not getting back sooner.. Anything special with your vault? Is it particularly full?

Can you check if you're able to unlock the vault in any of our other applications, such as the browser extension or mobile app? Or even the desktop app on another OS like Ubuntu/Mac/Windows?

**Comment by laurensmiers** [comment]
Hey, no problem, thanks for the response.

What do you mean with 'full'? If you mean size/entries, size of the vault is 94 kB and I have around 170 entries and 8 groups.
Vault is stored on a Nextcloud and the buttercup app connects via webdav .

Tested on android with appversion v2.5.2 , a different error appears (can't read it completely, is there a log I can take from somewhere?):
`Failed unlocking source: Attempt to invoke virtual method 'bytes[] java.lang.String.getByte...`
But also, same behaviour in that entering a wrong password gives an authentication failure, so the password seems correct.

Tested on Linux Mint (closed thing I have to Ubuntu), Desktop app version:
Desktop @ v2.17.0
Core @ v6.16.2
It gave the maxContentLength error when trying to add the Vault:
`Failed adding vault: Failed unlocking source: maxContentLength size of 209715200 exceeded`

Browser extension in Firefox gives the Salt error:
`Unable to unlock archive (723e3290-1939-479c-b69f-a395b836b814): Unlocking archive source (723e3290-1939-479c-b69f-a395b836b814) failed: Failed unlocking source: Failed deriving key: Salt must be provided`

Just for completeness, Buttercup-desktop app gives the maxContentLength error or the salt error:
`Unable to unlock archive (723e3290-1939-479c-b69f-a395b836b814): Unlocking archive source (723e3290-1939-479c-b69f-a395b836b814) failed: Failed unlocking source: Failed deriving key: Salt must be provided`

**Comment by perry-mitchell** [comment]
94kb? But the max content size error states it's >200mb: `209715200`... Maybe the remote size is bloated out for some reason? Can you check on the NC server?

Something might have broken and caused a huge file to be written. I'd recommend downloading the vault file and using [this tool](https://github.com/buttercup/diag-cli) to check the vault.

I'm sorry I've taken so long to respond. I understand if you've simply moved on. Currently my family and my day job keep me from fulfilling what I'd hope is my day-to-day availability for OSS, but I hope that's just a matter of juggling things a bit better. I'm working on it.

**Comment by laurensmiers** [comment]
@perry-mitchell no problem, thank you for the continued work! I haven't responded in the fastest manner either and we all got lives besides OSS ( hopefully ;).... ).

I ran the script and it's giving the same kind of error about "Salt must be provided":

> $> bcup-diag inspect ~/Downloads/passwords.bcup 
Password: ******************
Error: Failed deriving key: Salt must be provided
    at /usr/lib/node_modules/@buttercup/diag/node_modules/iocane/dist/node/derivation.js:66:31
    at step (/usr/lib/node_modules/@buttercup/diag/node_modules/iocane/dist/node/derivation.js:33:23)
    at Object.next (/usr/lib/node_modules/@buttercup/diag/node_modules/iocane/dist/node/derivation.js:14:53)
    at /usr/lib/node_modules/@buttercup/diag/node_modules/iocane/dist/node/derivation.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/@buttercup/diag/node_modules/iocane/dist/node/derivation.js:4:12)
    at deriveFromPassword (/usr/lib/node_modules/@buttercup/diag/node_modules/iocane/dist/node/derivation.js:57:12)
    at deriveKeyCall (/usr/lib/node_modules/@buttercup/diag/node_modules/iocane/dist/base/Session.js:141:36)
    at Session._deriveKey (/usr/lib/node_modules/@buttercup/diag/node_modules/iocane/dist/base/Session.js:142:16)
    at Session.<anonymous> (/usr/lib/node_modules/@buttercup/diag/node_modules/iocane/dist/base/Session.js:83:51)

By downloading the file (and looking at it a bit more closely, should have done that sooner...) I did notice that although the nextcloud shows 94 kB, when downloaded, it's only 80 kB on my system. So it seems it got corrupted somehow I guess?....
Luckily I have some backups lying around (thanks Nextcloud) so I was able to restore it in the meantime.
If I run the tool on a backup version (about a month ago), it runs without errors:

> $> bcup-diag inspect ~/Downloads/passwords_backup.bcup                          
Password: ******************
╔════════════════════════════╤════════╗
║ Aspect                     │ Value  ║
╟────────────────────────────┼────────╢
║ Groups                     │ 8      ║
╟────────────────────────────┼────────╢
║ Entries                    │ 164    ║
╟────────────────────────────┼────────╢
║ Vault Size (memory, bytes) │ 299178 ║
╚════════════════════════════╧════════╝

Sorry for the hassle, I'm opening the vault on several devices/apps so could be that it triggered this somehow, somewhere. Not sure if it's worth keeping this issue open?
I'm happy to close it or if you want more info/debugging, that's fine as well.

**Comment by perry-mitchell** [comment]
Hmm, that's a bit concerning. Perhaps something went wrong during saving, but I wouldn't expect Nextcloud to write a partial file (should be whole files).

It might be worthwhile for Buttercup to eventually write to a temporary file first, so if the write fails we don't corrupt the main vault. After successfully writing the temp file we can move it to overwrite the original. 

I'll close this for now - sorry for the inconvenience. Please let me know if it occurs again and we can re-prioritise such a fix.
