### ISSUE TITLE
Ubuntu Desktop: Cannot change preferences for Privacy and Debug

### ISSUE THREAD

**Issue by skillz-xx** [buttercup/buttercup-desktop#1180]
the fields are deactivated and I cannot change anything for Privacy and Debug in the settings of the Desktop version.

Ubuntu 22.04 - everything up to date.
I have installed the appimage launcher too..

is this on purpose or what is the problem?

**Comment by perry-mitchell** [comment]
Those options simply aren't implemented yet. They were to do with handling custom icon proxy URLs and the like.

Honestly Buttercup is already privacy focused so there hasn't been much else I'd have added to the privacy section. It hasn't been so important and I could've just removed them for now.
