### ISSUE TITLE
CSV import won't work if quote symbol used in a password

### ISSUE THREAD

**Issue by gslager** [buttercup/buttercup-desktop#1181]
Tried importing a CSV password file. Some of the passwords use special characters. The import failed if the quote symbol (") was used in a password.

**Comment by perry-mitchell** [comment]
CSV files must use correct escaping - it's up to whatever program is exporting the CSV to encode it correctly. Not an issue with Buttercup.

Please consider including a stripped (no sensitive information) CSV file in this issue if the issue persists.
