### ISSUE TITLE
Can't delete entries after reformatting vault to format B

### ISSUE THREAD

**Issue by willisplummer** [buttercup/buttercup-desktop#1184]
Desktop @ v2.18.0
Core @ v6.16.5

I reformatted my fault to the new format, and now I'm unable to delete entries — when I click the trash can icon, the item is removed from the folder it is in and the saving vault progress bar displays, but when the progress bar disappears, the item reappears in the folder where it was previously. No errors appear in the dev console.

I can successfully make other edits to my entries.

I'm on an M1 Mac running Ventura and my backup is saved in Dropbox.

**Comment by dimforensics** [comment]
I have same issue, and when trying to "Move to" it comes back.

**Comment by perry-mitchell** [comment]
Confirmed. Sorry this has taken so long to get to. Will look into it now.

**Comment by perry-mitchell** [comment]
Works in core, and works in the UI lib. Might be a desktop-only issue.

**Comment by perry-mitchell** [comment]
Core issue: buttercup/buttercup-core#321

**Comment by perry-mitchell** [comment]
Released v2.18.1

**Comment by willisplummer** [comment]
confirmed that this is fixed. thanks!

**Comment by gnarlsnishi** [comment]
Hi, I am also having the same issue of being unable to empty the trash. The items disappear briefly, I get the confirmation that the Vault has updated, and then the trashed items immediately reappear in the trash. This occurs both on Desktop version 2.18.2 and Android version 2.5.3 for me.
