### ISSUE TITLE
Chromium extension on desktop Windows, Add Vault on Local file, prompts only to files on C: drive

### ISSUE THREAD

**Issue by Bratieres** [buttercup/buttercup-desktop#1186]
Installed Chrome extension on Vivaldi, W11.
Created a local vault on D:
Adding a vault to extension prompts with folders on C:, did not find how to use another drive.
![addVault](https://user-images.githubusercontent.com/123510018/214408256-62b40b7d-0ed4-48c7-8250-7e9d17d9525d.jpg)

**Comment by perry-mitchell** [comment]
Duplicate: buttercup/buttercup-browser-extension#206
