### ISSUE TITLE
Android App oauth authorization only works with chrome browser

### ISSUE THREAD

**Issue by Bratieres** [buttercup/buttercup-desktop#1187]
Android App oauth authorization only works with chrome browser, my default browser is Android Vivaldi and authentication never ends.
Changing default browser to Chrome works.

**Comment by perry-mitchell** [comment]
This is an issue with Vivaldi then, as for authentication we use typical HTTPS and protocol links that should reopen Buttercup after authorising. The fact that it works in Chrome shows that Vivaldi is not correctly executing the protocol links for auth to return you to Buttercup (I presume that this is the issue).

Also, please open such issues in the mobile repository - this is for desktop issues.
