### ISSUE TITLE
Google Drive failing to connect to Buttercup

### ISSUE THREAD

**Issue by rezphotos** [buttercup/buttercup-desktop#1188]
I get this error when I attempt to open a vault:
failed unlocking archive
Unable to unlock archive (37bee656-bf3a-43ed-98cb-0918aca0d4e2): Unlocking archive source (37bee656-bf3a-43ed-98cb-0918aca0d4e2) failed: Failed unlocking source: Failed fetching Google Drive vault: Request failed: Request failed: 401

I can access my Drive, only Buttercup fails.

**Comment by xakraz** [comment]
Hi @rezphotos 👋🏻 

I was able to "fix" this by doing the following step:

1. Go to https://myaccount.google.com/u/0/security (change the 0 to the id of your Google account if you are logged in with multiple ones int he same browser)
2. Go to "Third-party apps with account access" (https://myaccount.google.com/u/0/permissions)
3. I removed ButterCup access
4. Opened ButterCup desktop 
5. Delete the current vault
6. Re-add the Vault

This resets the Google permissions and everything is working as before.

I hope it will help you too.

**Comment by rezphotos** [comment]
Thanks, That worked for me.  Is this due to a Buttercup change or something Google did?

**Comment by juninholiveira** [comment]
Above solution worked for me too. Hope it does not happen again :/

**Comment by perry-mitchell** [comment]
No changes in Buttercup that might have caused this - [this is the library responsible](https://github.com/buttercup/google-oauth2-client) for Google connections in Buttercup. If you find an issue I'd really appreciate someone creating an issue or debugging it there.

I'll close this now as there doesn't seem to be a way to easily reproduce this. If you find a way to reproduce it I'd gladly reopen this issue.

**Comment by perry-mitchell** [comment]
I was completely and confidently incorrect there - seems this is indeed a widespread issue. Seems something has changed on the google side.

If anyone can reproduce this, especially in our browser extension, please try to find the response headers from Google as they're vital to fixing this.

**Comment by perry-mitchell** [comment]
Found the issue: Google added quotes round part of their error string on the `www-authenticate` response header:

```
www-authenticate | Bearer realm="https://accounts.google.com/", error="invalid_token"
```

Meanwhile we expect no quotes: https://github.com/buttercup/googledrive-client/blob/master/source/request.ts#L29

**Comment by perry-mitchell** [comment]
Released: https://github.com/buttercup/buttercup-desktop/releases/tag/v2.18.2
