### ISSUE TITLE
Failed unlocking source: Failed fetching Google Drive vault: Request failed: 401

### ISSUE THREAD

**Issue by abashtovyigeniusee** [buttercup/buttercup-desktop#1191]
I'm unable to open my vault because I'm getting this error.

![image](https://user-images.githubusercontent.com/99344875/222465818-208885bf-9190-4e79-8183-6551b7c35470.png)
I've tried to resync my archive following these steps:
1. Delete the current archive that is synced with Google Drive
2. Connect to Google Drive
3. Select my bcup file that is stored on Google Drive
4. Add it to the desktop app again

First time it works, I mean it is working when I finish the steps above. Once I close Buttercup and reopen it, it shows me the error and I cannot log in to my archive anymore.

**OS**:
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
Kenel: 5.4.0-40-generic

On My Iphone 14 it is working fine, although I experienced the same issue couple of times

**Comment by perry-mitchell** [comment]
Hi,

It looks like you're using a _super_ old version of Buttercup 😅 - While I love the look of the old interface still, it's evident that you're a few versions behind. The newer unlock prompt looks more like this:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/3869469/222972066-e6c34e4e-0efd-4536-b656-a4fc4fc129a6.png">

Perhaps head over to our downloads section and grab a newer version? The most recent releases have added several fixes for Google Drive.

I'll close this issue.
