### ISSUE TITLE
Biometric unlock option is grayed out in Windows

### ISSUE THREAD

**Issue by pdwonline** [buttercup/buttercup-desktop#1192]
Biometric unclock works flawless on my phone, but not on Windows. It is essential in order to enable make a strong and difficult vault password manageble.

**Comment by perry-mitchell** [comment]
Dupe of #1089 - this is a huge undertaking, which failed the last time someone was generous enough to devote their time to implementing it. Hello is a beast and hard to integrate properly. I don't recall what the exact issue was last time but it was un-mergeable.
