### ISSUE TITLE
5 key appears to be mapped to backspace

### ISSUE THREAD

**Issue by Nubicola** [buttercup/buttercup-desktop#1195]
Hi,

I'm using a british keyboard layout on Ubuntu Linux and using the latest release of the AppImage. When I'm in a terminal, I press the number '5' and I see, as expected, '5.' When I'm adding a new entry to a vault, I press the number '5' in the username or password field and it executes ^H! It's very confusing. % behaves the same. While I can enter '5' using the numeric keypad, I have no way to enter %.

**Comment by Nubicola** [comment]
I tried quitting the app and restarting it, but that didn't change anything. I checked that other apps don't exhibit the behavior, but everything else produces a '5' when I hit the '5' key.

**Comment by Nubicola** [comment]
I did some further checking. The above report was made when I was running over TightVNC. I had no idea that would make a difference. But it did! Running natively, everything works as expected.

I'm not sure if this should be closed...probably should be since the culprit lies somewhere between AppImage and TightVNC.

**Comment by perry-mitchell** [comment]
Thanks for the research into this! It does sound strange. I'll be sure to refer back to this issue if another arises with similar problems.
