### ISSUE TITLE
When will be available from flatpak or rpm?

### ISSUE THREAD

**Issue by callmehanu** [buttercup/buttercup-desktop#1196]
Just that simple questions! 😀

**Comment by perry-mitchell** [comment]
It won't be I'm afraid, as updating those automatically isn't possible so far as I know. Last I checked only Appimage is supported for auto updating via Electron (our base).

**Comment by kra-mo** [comment]
> updating those automatically isn't possible so far as I know

Updating Flatpak automatically is possible and is the reason most developers choose Flatpak. The most popular repository is [Flathub](https://flathub.org).

**Comment by perry-mitchell** [comment]
I mean via our current build tool, baked into our release pipeline. Once everything is updated **and** if our electron pipeline supports it then yes.. 

I've nothing against the tech but we need to stick to items that are easily configured and right now Flatpak isn't.
