### ISSUE TITLE
[mac] Vault unlock failed

### ISSUE THREAD

**Issue by TimeZediter** [buttercup/buttercup-desktop#1197]
Vault unlock failed: Error invoking remote method 'unlock-source:
X. Layerr: Failed unlocking vault source: Failed unlocking source: Failed
fetching Google Drive vault: Request failed: Request failed: O

always be loading.
![image](https://user-images.githubusercontent.com/48017006/229096598-4650da1f-4c50-4541-b983-61479aa7ec09.png)

then give me a alert.
![image](https://user-images.githubusercontent.com/48017006/229096872-4fe9307d-e4ef-48c3-873b-70f9d518059c.png)

**Comment by perry-mitchell** [comment]
0 is a network failure. Most likely something wrong with your connection to Google, or the filename etc. causing a network request failure.
