### ISSUE TITLE
wired import .bcup vault on buttercup in Android ?

### ISSUE THREAD

**Issue by ihubgit** [buttercup/buttercup-desktop#1198]
Hi, i did a usb transfer from my Mac desktop .bcup vault on my Pixel 6 but was un able to select it as a vault in the android buttercup app.
Is there a way to do this ?

**Comment by perry-mitchell** [comment]
Unfortunately not for now - only document storage for the **app** is accessible, not external storages. You need to ensure it's in the app's document directory. You could perhaps create a local vault in app and then search for that to find where it's located.

I'm not a daily driver of android so I apologise for not being able to help further.
