### ISSUE TITLE
[Linux] No panel/systray icon since v2.18.0

### ISSUE THREAD

**Issue by casasfernando** [buttercup/buttercup-desktop#1199]
Title says it all. Since Buttercup v2.18.0 the panel/systray icon is missing. Last version that displays it is v2.17.0.
This is the icon I'm talking about:

![image](https://user-images.githubusercontent.com/15861819/231589772-a6d7dc55-da8c-42b5-a758-a692ee0ef7f3.png)

I discovered this problem after upgrading from v2.17.0 to v2.18.2.
I'm running Buttercup on Ubuntu 22.04 using the x86_64 AppImage downloaded from the project releases page on GitHub.
I suspect the problem was introduced when updating the project's node versions and dependencies prior to v2.18.0 release.
Let me know if you need any additional information and thanks a lot for writing this great piece of software. I'm using it on ***all*** my devices (Linux, Windows, iOS and Android).

Thanks

**Comment by perry-mitchell** [comment]
Hi! 

Do you mean that it doesn't auto start with your OS, or that the icon never appears, even after launching the app image?

I still have it working on my Ubuntu 22.04, stable version.

**Comment by casasfernando** [comment]
The icon never appears, even after launching the app image.
Having said that, let me clarify that I'm using elementary OS 7 (based on Ubuntu 22.04) which uses Pantheon desktop.
Ayatana compatible indicators are working (e.g.: Nextcloud), and Buttercup was also working before.

After the project updates for v2.18.0 something changed. Maybe ayatana is not used anymore by node or one of the deps?

**Comment by perry-mitchell** [comment]
We updated core Electron dependencies in 2.18, so it's possible that it's because of that.

Another electron update might help but I can't be certain.

**Comment by perry-mitchell** [comment]
I'm going to close this as it seems to potentially be a specific incompatibility with your desktop environment. From what I can tell, Buttercup's tray icon works as expected in most scenarios, including in Ubuntu Gnome and Fedora KDE, for example:

![image](https://github.com/buttercup/buttercup-desktop/assets/3869469/3b71f5aa-a81f-4ded-a0b3-a47ceff9aab4)

![image](https://github.com/buttercup/buttercup-desktop/assets/3869469/71f8da25-ee9e-4d0f-b17b-9c8dde0ab0eb)

**Comment by casasfernando** [comment]
Most likely, yes.
Thanks for looking into this anyway.

**Comment by casasfernando** [comment]
> We updated core Electron dependencies in 2.18, so it's possible that it's because of that.
> 
> Another electron update might help but I can't be certain.

@perry-mitchell after looking further into this, it seems that this issue is actually an electron bug indeed, that is fixed in newer versions: https://github.com/electron/electron/pull/36815

I see that you are currently using electron 22.0.0 in the project. Would it be possible to bump electron version to at least 22.3.24 that should include a fix for this bug?

Looking forward your reply.

Thanks!

**Comment by perry-mitchell** [comment]
I unfortunately don't think we can go back a major version. I'm soon considering updating it to the latest major, but this includes changes that will break buttercup on windows 7 and earlier, due to a chrome/v8 upgrade.

I suspect that if this bug is fixed on Electron that it won't be backported this far, so it'd be easier to be on a newer version when that happens.

**Comment by casasfernando** [comment]
Thanks for taking the time to reply @perry-mitchell .
All clear. At least there is a workaround.
