### ISSUE TITLE
ask for passphrase every once in a while when biometric unlock is active

### ISSUE THREAD

**Issue by macno** [buttercup/buttercup-desktop#1201]
I'd love to be forced to input the passphrase every X days to unlock the vault even if I enabled the biometric unlock.

**Comment by perry-mitchell** [comment]
I like this idea.

**Comment by macno** [comment]
Hi @perry-mitchell since I have some free time in the next weeks I'd like to start implementing it. Could you provide me any pointers to where to look at?

**Comment by macno** [comment]
This is the plan:
* add two new settings (global? per vault?):
    * forcePromptPasswordAfterBioUnlockCount
    * forcePromptPasswordAfterDeltaTime

  whichever comes first, user will have to unlock the vault typing the password.  
  A value of `0` will disable the check
* store 2 values after each bio unlock (per vault)
  * bioUnlockCount
  * bioUlockTimestamp

WDYT?
