### ISSUE TITLE
Buttercup Desktop failing to Start on Windows

### ISSUE THREAD

**Issue by JKhan01** [buttercup/buttercup-desktop#1203]
Hi, Whenever I am trying to run Buttercup Desktop for windows, it will just not start and fail silently, 
Therefore, I tried running it from Terminal to see if I can get some logs. PFB the Screenshot of the exception being thrown. Please let me know if there is a temporary fix for this.

![image](https://user-images.githubusercontent.com/40734042/232280506-5ab31afa-bb95-4d93-b32b-748bd6b26a28.png)

The error logs are as follows:

```
[ERR] 07:20:03: SyntaxError: Unexpected token '', ""... is not valid JSON
at undefined

at parse

at <anonymous>  resources/app.asar/build/main/library/FileStorage.js:85  return JSON.parse(data);

at next

at fulfilled    resources/app.asar/build/main/library/FileStorage.js:5   function fulfilled(value) { try { step(generator.next(value)); } catch (e) { re…
```

**Comment by perry-mitchell** [comment]
It looks like your vaults configuration is corrupted. Can you inspect the contents and see if it looks ok? I suspect that it's got junk in it and is mostly empty. Deleting it and running again should fix it, and you'll just have to add your vaults again.

This has been reported before but I'm unsure as to what causes the corruption.

**Comment by JKhan01** [comment]
The workaround fix was to delete the desktop-config.json. 
That is the file which got corrupted from some unknown reason I presume to be some String encoding issue with OS and JSON. Vaults config JSON didn't needed to be touched.

In a powershell windows terminal

`cd "C:\Users\<username>\AppData\Roaming\Buttercup-nodejs\Config"`
`rm desktop-config.json`

**Comment by JKhan01** [comment]
Closing Issue with the temporary fix mentioned in the previous comment
