### ISSUE TITLE
Syncing a vault on Google Drive does not work with 2.19.0 and 2.19.1

### ISSUE THREAD

**Issue by tigrouind** [buttercup/buttercup-desktop#1208]
The changes made in version 2.19.1 fix the problem that prevents adding a vault located on Google Drive.

However, synchronization still does not work. After making changes to a vault (e.g. creating or updating a password), the vault is not updated. An "Untitled" file is created in the same folder as the vault in Google Drive. That file contains '[object Object]'. In Buttercup, everything seems fine : the progress bar is shown and no errors are reported (in other words, it fails silently).

Removing the vault and attaching it again does not help. The syncing works perfectly in 2.18.2

**Comment by perry-mitchell** [comment]
I haven't been able to reproduce this. Can you share more information about the process?

Is it only with new vaults you create or existing? What if you take a successful vault saved locally and overwrite the contents of one stored in Google Drive, does loading and saving work then?

**Comment by boissierflorian** [comment]
Hello, I've got the same issue for an existing vault.

Here is the video where I tried to delete an entry from the trash https://easyupload.io/iuh3ij

**Comment by tigrouind** [comment]
> I haven't been able to reproduce this. Can you share more information about the process?

Steps :
1. Open a vault located on Google Drive.
2. Make some changes (eg : create a new entry)
3. Save changes. A progress bar is shown then disappear (as usual)
4. Close buttercup and open vault again.

Expected : changes from in step 2 are still there.

Actual : changes are lost. Additionally files named "Untitled" appear on Google drive. A new file is created for each change made to the vault. The vault file is not modified. 

![image](https://user-images.githubusercontent.com/2211721/235475826-624a1591-74ee-4fae-b614-950e2d388649.png)
![image](https://user-images.githubusercontent.com/2211721/235475898-e714008e-86d1-40db-80dc-13c1c931d752.png)

If I open DevTools : no errors are reported in "Console" tab.

> Is it only with new vaults you create or existing? 

Both. I have created a new vault locally, uploaded it to Google Drive and attached it to buttercup.
If I make changes, it fails as well.

> What if you take a successful vault saved locally and overwrite the contents of one stored in Google Drive, does loading and saving work then?

If I modify a fault locally, then overwrite file on Google Drive : once I open remote vault, changes are propagated. So loading works as it should. Saving will fail silently anyway.

**Comment by tfrum** [comment]
Also having this problem. There ought to be a beta branch to preempt issues like this, as it can seriously interrupt user workflows.

**Comment by tigrouind** [comment]
> Also having this problem. There ought to be a beta branch to preempt issues like this, as it can seriously interrupt user workflows.

I suggest you to revert to 2.18.2 until all issues are fixed. That one works fine.

**Comment by tfrum** [comment]
> > Also having this problem. There ought to be a beta branch to preempt issues like this, as it can seriously interrupt user workflows.
> 
> I suggest you to revert to 2.18.2 until all issues are fixed. That one works fine.

Of course. Though this isn't really a response to what I said.

**Comment by boissierflorian** [comment]
> suggest you to revert to 2.18.2 until all issues are fixed. That one works fine.

You still can't delete entries from trash on this version

**Comment by tigrouind** [comment]
> > suggest you to revert to 2.18.2 until all issues are fixed. That one works fine.
> 
> You still can't delete entries from trash on this version

I tried on my side and it fails as well. I never notified this. I don't think it's related to issues in 2.19.0.
Which version do you recommend or do you use ?

**Comment by sukhdeepsekhon** [comment]
I am also facing the same syncing issue for version 2.19.1 but it started working fine once I revert it back to **2.18.2**

**Comment by perry-mitchell** [comment]
I've found the issue, patching now. I'm terribly sorry this has gone unnoticed for so long.
