### ISSUE TITLE
Missing preferences for global hotkeys

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#1209]
I was wondering if Buttercup v2.x does support any global hotkeys? There seems to be a setting window in Buttercup >= v1.19 (see [PR 882](https://github.com/buttercup/buttercup-desktop/pull/882) and more specific [issue 702](https://github.com/buttercup/buttercup-desktop/issues/702)) but I can't find it in Buttercup v2.x.

**Comment by perry-mitchell** [comment]
Yes, this was certainly a regression. I'd be happy to see a PR for this as I don't currently have time to add it myself. I'll close this as a dupe of #1009 for now.
