### ISSUE TITLE
Sync from Windows not working

### ISSUE THREAD

**Issue by ShieldM4tr1x** [buttercup/buttercup-desktop#1211]
Whenever I tried to make changes to my vault from Windows, its not syncing on mobile app. New entry can be seen only in Windows until app remains open. Once I close it and reopen it again, then I also lost that entry even from Windows. Syncing is working completely fine if I made changes from Mobile. Therefore, moved back to 2.18.2 version where everything is working fine for me.

**Comment by Blastertoad** [comment]
Just setup buttercup today. Can confirm any changes past creating vault results in message cannot merge. 

Windows installer 2.19.1, core 7.1.1

**Comment by sukhdeepsekhon** [comment]
It's not working even with latest version Desktop @ v2.19.1
Core @ v7.1.1. Still having the same issue. I do not make any changes in past. Last option left for me is moving back to 2.18.2 version when everything is working properly.

**Comment by perry-mitchell** [comment]
Could you kindly try again on 2.20.1?

**Comment by ShieldM4tr1x** [comment]
It's working perfect now. Thank you so much.
