### ISSUE TITLE
How to add OTP 2Auth in BetterCup?

### ISSUE THREAD

**Issue by uuc110** [buttercup/buttercup-desktop#1212]
I installed and tried but in custom field i only see the Change type: OTP and i understood nothing🤷‍♂️

**Comment by perry-mitchell** [comment]
To add OTPs to Buttercup, you need to get the **OTP URI** and paste it into a new field with type "OTP", as you mentioned. You can see examples [here](https://github.com/google/google-authenticator/wiki/Key-Uri-Format).

Usually this can be derived from a QR code on a website when you're **enabling 2FA**. You can, for now, install an extension that decodes QR codes to give you the value which, in the case of 2FA, will usually be an OTP URI you can use in Buttercup.
