### ISSUE TITLE
upgraded to vers. 2.20.0 -> error opening vaults on format B

### ISSUE THREAD

**Issue by dimforensics** [buttercup/buttercup-desktop#1215]
After I upgraded to version 2.20.0, I cannot open the vaults with format B, 
getting the following error

![image](https://github.com/buttercup/buttercup-desktop/assets/29274096/1613584a-bf9e-4a15-8431-d85dd653259c)

**Comment by perry-mitchell** [comment]
Confirmed.. I'll check this now.

**Comment by perry-mitchell** [comment]
Fixed, releasing..

**Comment by perry-mitchell** [comment]
Released: https://github.com/buttercup/buttercup-desktop/releases/tag/v2.20.1
