### ISSUE TITLE
upgraded to vers. 2.20.1 -> error to delete/save a record

### ISSUE THREAD

**Issue by dimforensics** [buttercup/buttercup-desktop#1216]
After upgrade to vers. 2.20.1, getting error when trying to delete/save a record

![image](https://github.com/buttercup/buttercup-desktop/assets/29274096/ff08e309-02bd-4704-ae0f-c9f1c1a94760)

**Comment by perry-mitchell** [comment]
I can't reproduce this. Can you please confirm you're running 2.20.1? And what storage are you using?

**Comment by dimforensics** [comment]
Using it on Windows 10 vers. 22H2, Buttercup vers. 2.20.1.

So, I tried the same vault on "Google Drive" and locally, 
and also I tried with a vault that had been saved as backup locally -> all with same error.

see below print screens:

![image](https://github.com/buttercup/buttercup-desktop/assets/29274096/30667bcd-443a-400f-a8f2-5eac5295097b)


![image](https://github.com/buttercup/buttercup-desktop/assets/29274096/6bb5d916-05ea-4b0b-8a85-aee5203c4a7a)

**Comment by Cristi-007** [comment]
same issue

**Comment by Cristi-007** [comment]
I've created a test vault with 2.19.1 and at opening with newest one get the error. Pass: 1111
![test bcup](https://github.com/buttercup/buttercup-desktop/assets/85635855/74b073ae-1f70-4378-8168-08a6b2e04d49)

**Comment by Cristi-007** [comment]
I've created a test vault with 2.19.1 and at opening with newest one get the error. Pass: 1111

[https://drive.google.com/file/d/1Jsqm4oG7rxdPz_Do4sA4U0ek1rppxFP8/view?usp=share_link](url)

**Comment by perry-mitchell** [comment]
Ok, I reproduced with your vault, thanks:

![image](https://github.com/buttercup/buttercup-desktop/assets/3869469/43c39079-1054-4ad6-96e8-24e71031b496)

I'll check this shortly..

**Comment by dimforensics** [comment]
The steps below I did with vers. 2.20.1, and works fine:
1. I've exported the data from my old.bcup in "Buttercup CSV" format> export.csv;
2. I've created a new new.bcup and imported the export.csv file;
3. Did some test with create/delete records;
4. Closed/Removed the new.bcup from App and then added back to the App
 --> I've checked and everyting is ok!

**Comment by perry-mitchell** [comment]
Ok, that's good news! So it seems like there's some issue not _migrated_ from historical vaults, causing the bug. Thanks to your example I can open it and see what's missing, and patch that accordingly.

**Comment by perry-mitchell** [comment]
Found the issue.. Patching and releasing ASAP. Thanks @dimforensics for the persisted testing and help here.. Would have been super tricky without it.

**Comment by perry-mitchell** [comment]
Published 2.20.2 - https://github.com/buttercup/buttercup-desktop/releases/tag/v2.20.2

@dimforensics Would you kindly mind checking again?

**Comment by dimforensics** [comment]
I've checked with old a new vault, and everything is perfect.
Well done!!!
