### ISSUE TITLE
Unable to save custom fields

### ISSUE THREAD

**Issue by geraldapeoples** [buttercup/buttercup-desktop#1222]
On macos with version 2.20.2

If I add a custom field the Save button grays out, and I cannot save the item. Changing the type of custom field makes no difference.

This is a local file vault.

**Comment by perry-mitchell** [comment]
Does it re-enable if you enter data into the name? All custom fields require keys before saving is permitted.

**Comment by geraldapeoples** [comment]
Yes it does .... I thought the 'Click to edit' was a bit of help text to tell you to edit the value ... my bad ... thanks for the quick response!

**Comment by perry-mitchell** [comment]
Ah, I see.. yeah I think UX could be clearer here. Cheers!
