### ISSUE TITLE
saving changed password 

### ISSUE THREAD

**Issue by ziltsh** [buttercup/buttercup-desktop#1227]
I updated a password on one of my favorite stores and noticed buttercup saved the old password in stead of the new one.  Also in an ideal world it would be nice if buttercup proposed to update existing records while keeping a password history (as fail-safe / backup).

Kind regards, Niels

--
<form id="account_password_editing" name="change_info" action="[/en/account/update/password](view-source:https://www.varusteleka.com/en/account/update/password)" method="POST">
  Password:<br />
  <input type="hidden" name="_token" value="DXfsexamplevalue">
  <input type="hidden" name="contact_id" value="10054" />
  <input type="password" name="contact_password_old" value="" placeholder="Old password"  required title="Old password" /> <br />
  <input type="password" id="contact_password" name="contact_password" value="" placeholder="New password"  pattern=".{4,}" required title="4 characters minimum"/> <br />
  <input type="password" id="contact_password_2" name="contact_password_2" value="" placeholder="New password again"  pattern=".{4,}" required title="4 characters minimum"/> <br />
  <script>
    $('#contact_password, #contact_password_2').keyup(function(event) {
      var pass1 = $('#contact_password').val();
      var pass2 = $('#contact_password_2').val();
 if ( pass1 == pass2 && pass1.length >= 4 && pass2.length >= 4) {
  $('#account_password_editing input[type="submit"]').removeAttr('disabled');
} else {
  $('#account_password_editing input[type="submit"]').attr('disabled','disabled');  
}
});

  </script>
  <input type="submit" value="Update password" disabled="disabled" onclick="window.dataLayer.push({'event':'legacy_event', 'event_data': { 'category':'Account', 'action':'Submit new account password' }});" />
  <br />
  <span class="account_login_editing_button" style="cursor: pointer;">Cancel</span><br /><br />
</form>

**Comment by perry-mitchell** [comment]
Hi!

Was this meant for the browser extension?

Buttercup keeps a password history already. Sounds like we just need to improve detection in forms, as well as improved prompting to update entries.

**Comment by perry-mitchell** [comment]
Closing due to no response.
