### ISSUE TITLE
[Bug] Cannot Launch Buttercup under Xubuntu 22.04 anymore

### ISSUE THREAD

**Issue by KometFox** [buttercup/buttercup-desktop#1232]
Buttercup used to run fine on my system for several weeks which I used it frequently because that program is quite handy to me but now recently I cannot launch this program anymore which forces me to use the Windows version instead via Lutris Wine and under Lutris Wine it's quite buggy but that's another bug issue.

Anyway here is the terminal output when I am trying to launch this program: 

```
[INF] 01:38:28: Application starting
[INF] 01:38:28: Application ready
[INF] 01:38:28: Application session started: 2023-08-11T01:38:28.445Z
[INF] 01:38:28: Logs location: /home/-/.local/state/Buttercup-nodejs/buttercup-desktop.log
[INF] 01:38:28: Config location: /home/-/.config/Buttercup-nodejs/desktop.config.json
[INF] 01:38:28: Vault config storage location: /home/-/.local/share/Buttercup-nodejs/vaults.json
[INF] 01:38:28: System locale detected: de-DE
[INF] 01:38:28: Starting with language: de-DE
[ERR] 01:38:28: SyntaxError: Unexpected end of JSON input
at undefined                                                                                                                                                  
at parse                                                                                                                                                      
at <anonymous>  …mount_ButtereoPozm/resources/app.asar/build/main/index.js:2  (()=>{var e,t={2067:function(e,t,r){"use strict";var n=this&&this.__awaiter||fu…
at next                                                                                                                                                       
at a            …mount_ButtereoPozm/resources/app.asar/build/main/index.js:2  (()=>{var e,t={2067:function(e,t,r){"use strict";var n=this&&this.__awaiter||fu…
```

I don't know what got changed on my system at all that caused this bug since I am running the AppImage version of Buttercup. Else I would put the new system changes here too.

**Comment by stanschus** [comment]
> Buttercup used to run fine on my system for several weeks which I used it frequently because that program is quite handy to me but now recently I cannot launch this program anymore which forces me to use the Windows version instead via Lutris Wine and under Lutris Wine it's quite buggy but that's another bug issue.
> 
> Anyway here is the terminal output when I am trying to launch this program:
> 
> ```
> [INF] 01:38:28: Application starting
> [INF] 01:38:28: Application ready
> [INF] 01:38:28: Application session started: 2023-08-11T01:38:28.445Z
> [INF] 01:38:28: Logs location: /home/-/.local/state/Buttercup-nodejs/buttercup-desktop.log
> [INF] 01:38:28: Config location: /home/-/.config/Buttercup-nodejs/desktop.config.json
> [INF] 01:38:28: Vault config storage location: /home/-/.local/share/Buttercup-nodejs/vaults.json
> [INF] 01:38:28: System locale detected: de-DE
> [INF] 01:38:28: Starting with language: de-DE
> [ERR] 01:38:28: SyntaxError: Unexpected end of JSON input
> at undefined                                                                                                                                                  
> at parse                                                                                                                                                      
> at <anonymous>  …mount_ButtereoPozm/resources/app.asar/build/main/index.js:2  (()=>{var e,t={2067:function(e,t,r){"use strict";var n=this&&this.__awaiter||fu…
> at next                                                                                                                                                       
> at a            …mount_ButtereoPozm/resources/app.asar/build/main/index.js:2  (()=>{var e,t={2067:function(e,t,r){"use strict";var n=this&&this.__awaiter||fu…
> ```
> 
> I don't know what got changed on my system at all that caused this bug since I am running the AppImage version of Buttercup. Else I would put the new system changes here too.

had a similar error message and buttercup wouldn't start.
some how the `desktop.config.json` was empty, I used content  of `~/.config/Buttercup/config.json` and copy&pasted it into the file.
content of `~/.config/Buttercup/config.json`:
```
{
	"window": {
		"position": [
			329,
			537
		],
		"size": [
			1265,
			733
		]
	}
}
```
that solved the issue for me. hope that helps!

**Comment by JohnSmith25** [comment]
Hmm that's interesting, somehow my config.json there was empty but deleting the file ~/.local/share/Buttercup-nodejs/vaults.json fixed my issue with Buttercup not launching. I just had to reload the vault file again and now everything seems to be working fine again. Thanks for the help.

**Comment by perry-mitchell** [comment]
Sorry I didn't see this earlier. Sounds like a corrupted config file :thinking: 

I've seen similar before but am not sure what causes it. Thanks for sharing this however.
