### ISSUE TITLE
Feature request: fingerprint unlock

### ISSUE THREAD

**Issue by TMSdot** [buttercup/buttercup-desktop#1239]
I've just installed Buttercup Desktop on my MacBook, I've using it on My Windows PC and my phone maybe a year ago.  
It would be lovely if I could use my fingerprint sensor to unlock my vault.

**Comment by TMSdot** [comment]
.

**Comment by TMSdot** [comment]
This issue I closable.

**Comment by perry-mitchell** [comment]
It's already supported when you enable biometric unlocking. It uses whatever your macbook is configured to use - fingerprint, face etc..
