### ISSUE TITLE
PIN code to unlock the vault 

### ISSUE THREAD

**Issue by sidielnikov** [buttercup/buttercup-desktop#1240]
hello, I really like buttercup, I want to ask you to make a function for unlocking the storage with a pin code like in bitwarden, this is a very convenient function and it is sorely missed

**Comment by perry-mitchell** [comment]
Glad you like it!

I'm not sure a PIN code is suitable for the desktop application.. As we have biometric unlock as well as password. We eventually want to support key files and hardware keys, but I don't think PIN is necessary for this app, sorry.
