### ISSUE TITLE
Buttercup Mac desktop no longer opens

### ISSUE THREAD

**Issue by sacred-eye** [buttercup/buttercup-desktop#1245]
Hi,

I had to force quit Buttercup and now the application no longer opens. All I get are a couple of bounces of the icon in the dock and a self-quit. I restarted the computer and the problem persisted. I redownloaded, reinstalled, and replaced the application to no avail but did not touch any original support files associated with the app.

I am using a late 2015 iMac with OS 10.14.6. If any log files are needed to diagnose the problem, please direct me to where I can find them.

Thanks!

**Comment by perry-mitchell** [comment]
You can find the logs [here](https://github.com/buttercup/buttercup-desktop#logs). Perhaps they show what's going wrong?

You might also check the contents of your config file. The location is mentioned a couple of sections prior.

**Comment by perry-mitchell** [comment]
>2015 iMac with OS 10.14.6

This is quite old, which is the only thing I can think of being an issue. Newer versions of electron and Chrome/V8 may be wholly incompatible. I'm not sure.

I'll close this for now - if there's something actionable here I'll happily reopen.
