### ISSUE TITLE
[feature request] Allow to start Buttercup at session launch (AppImage)

### ISSUE THREAD

**Issue by Oxalin** [buttercup/buttercup-desktop#1253]
Hey @perry-mitchell 

While I was working on adding a feature to start Buttercup in the background (done, see https://github.com/buttercup/buttercup-desktop/issues/1229), I tought about adding an option to have Buttercup started when the user logs in. So... also done.

The solution is based on Node auto-launch and should support all major OSes. However, I'm not used to code in typescript, so the code may have to be tweaked.

The code is available under my master branch. The series from https://github.com/Oxalin/buttercup-desktop/commit/2ef187bde74843fd37e2e724768fb81085ad3aa2 to https://github.com/Oxalin/buttercup-desktop/commit/a992e7b792da694d0f4a1aa190a2f18a432b6d61.

To be sure, I tested the packages I had created for Windows: installer (perMachine and perUser), portable, 7z. I'll test it under Linux later this evening.

**Comment by Oxalin** [comment]
Tested under Linux:
- when installed by a native package, it works without any problem. Tested on ArchLinux.
- when installed by an AppImage, the needed file is properly created, but the path is "wrong", i.e. that since it is an AppImage, it runs in a folder located under /tmp. This folder disappears when logging off or rebooting. However, the logic behind auto-launch is to find the path of the executable and to use it as the path written in the .desktop file it creates.
-- As stated under AppLauncher's repository: "AppImages use the term "desktop integration", as they're not "installed" in the traditional sense. They remain single, self-contained executable files. AppImageLauncher and other tools extract and patch the desktop entry as well as the related icons into the relevant locations." So there is no easy way to fix it but to let the user modify the file and point it to the .AppImg file wanted (and more than one .AppImg of an app can exist at the same time).
-- Otherwise, I could see if I can disable the option at build time for AppImg target.

**Comment by perry-mitchell** [comment]
Thanks for the detailed summary! This is excellent.

I'm currently fixing some other things for an upcoming desktop release so I'll get to this one after that. Definitely during this week.

Regarding the AppImage issue - I'm surprised that it wouldn't work as I've seen other applications autostart just fine using appimagelauncher, such as with Nextcloud desktop. I wonder if there's something we could glean from another project.

Perhaps in the near future we'll support deb/rpm builds again, which would hopefully support auto starting.

**Comment by perry-mitchell** [comment]
Thanks @Oxalin! After the MR is reviewed I'll release this as it is now, as it's sorely needed. Hopefully we can find improvements for the Appimage build going forward.

**Comment by Oxalin** [comment]
I'm almost done. The feature was not properly implemented in node-auto-launch, but I'm almost there. The .desktop file is now using the AppImage file path instead of its mount path. It also escapes reserved characters (like spaces) for the Exec key. There is still a small tweak I'm looking at, but things look good. I'll update the dependency in Buttercup Desktop afterward.

**Comment by perry-mitchell** [comment]
Addressed in:
 * #1251
 * #1262
 * #1263
