### ISSUE TITLE
Fail to enable biometric unlock

### ISSUE THREAD

**Issue by macno** [buttercup/buttercup-desktop#1256]
I tried to enable biometric unlock after upgrading to v2.22.0, but when confirming the vault password, an error message is shown:

```
Error invoking remote method 'register-biometric-unlock': Layerr: Failed storing source biometric details: Invalid password provided for source: 44361eb2-88c1-4260-b705-8c95ed9b7063
```

Environment:
* Vault is stored on WebDAV
* OS: macos Sonoma 14.1.1
* uname -a: `Darwin cayenne 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64`

**Comment by perry-mitchell** [comment]
I'm not running the latest MacOS so I'm not able to test this I'm afraid. I wonder if there's something in that which would cause an incompatibility with our dependencies. I don't think we've updated anything in that area though.

Would you mind kindly trying to create a new vault, and enabling biometrics there? Just to see if it's possible at all for you?

**Comment by macno** [comment]
Just tried to create a new vault (local file) and enabling biometric unlock: same failure.

I'll try to wipe out bc and reinstalling it from scratch

**Comment by perry-mitchell** [comment]
@macno Any luck? Is this still occurring?

**Comment by alvin13** [comment]
Was running into the same issue. Didn't matter if it was loading an existing vault or creating a new one, same error.
However as a workaround, I removed and installed Jun 2 v2.20.3
Using this version I was able to enable the biometric unlock and then upgrade to latest and the unlock still works now. 
So it seems to me that the issue occurs only on the registration to the MacOs of biometric unlock on a vault, not the biometric identification part itself.

Apple M2 Sonoma 14.2 (23C64)

**Comment by LambertPhil** [comment]
I confirme that it comes after an update. I reactivated version 2.21 and enabled biometrics on all the vaults and everything worked fine. Since then, all biometrically-enabled vaults have accepted biometric unlocking, even with the latest version.

Apple M2 Somona 14.1.2

**Comment by Valiumm** [comment]
Same issue here with latest version of Buttercup : 2.24.4 and Mac Sonoma 14.1
Unable to use Biometric unlock method on current file or even on fresh new one

**Comment by perry-mitchell** [comment]
I'm not currently running Sonoma yet, and cant' reproduce this on earlier MacOS versions. I'd appreciate if someone might debug this on Sonoma and contribute a fix, if possible.

**Comment by macno** [comment]
I've just tried to debug the issue, but after cloning the repo and starting the app via `npm run start:main` I was not able to reproduce the issue: after typing the password the OS prompt for enabling touchId appears correctly.
Any suggestion on how to proceed?

**Comment by perry-mitchell** [comment]
I'm now on Sonoma and haven't been able to reproduce this. Until there's a repeatable process or consistent failures there's not much to do here. I'll close for now. Thanks.

**Comment by LambertPhil** [comment]
still the same error with Somona 14.2.1 and buttercup Desktop @ v2.25.0 Core @ v7.4.0

![Screenshot 2024-02-13 at 17 50 01](https://github.com/buttercup/buttercup-desktop/assets/75611724/4dde29cb-53e4-42a7-8ceb-bdf4ae45dbc2)
