### ISSUE TITLE
Double-click to make fullscreen

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#126]
In a lot of mac apps, double-clicking the title bar makes the app expand to cover the available screen area. This is different to the _fullscreen_ that the green button provides, but a very handy feature imo.

Is there a possibility we could add this without interrupting other functionality?

**Comment by perry-mitchell** [comment]
@sallar ?

**Comment by sallar** [comment]
@perry-mitchell Makes total sense. I can do that alongside another fix :)

**Comment by sallar** [comment]
@perry-mitchell there's a small issue... we don't have a specific Title bar section :D

**Comment by perry-mitchell** [comment]
> we don't have a specific Title bar section

Yes that is a problem.. What about clicking in the area beside the mac buttons? Left of the search box?

![image](https://cloud.githubusercontent.com/assets/3869469/21750984/35712c92-d5c8-11e6-8ae1-e64c8e61bede.png)

**Comment by perry-mitchell** [comment]
No longer relevant as we have a native title bar.
