### ISSUE TITLE
[Feature Request] Add a logoff OAuth2/change account button

### ISSUE THREAD

**Issue by Choco02** [buttercup/buttercup-desktop#1266]
I've logged in on my dropbox account to create a vault, but i have 2 dropbox account and i logged in on wrong one, now i can't logoff and change to another one. I miss a logoff OAuth2 or change account button

**Comment by perry-mitchell** [comment]
Dropbox sign-in occurs in your browser. You can just go to www.dropbox.com, log out, and then try again. Buttercup can't control your browser's sessions.

If Dropbox provides a way to _choose_ accounts before signing in, like Google does, then that'd be an option but I'm not sure that they do.
