### ISSUE TITLE
Error when trying to add Touch ID link to macOS app

### ISSUE THREAD

**Issue by gradygambrell** [buttercup/buttercup-desktop#1281]
After entering the correct password, a red box on the top right stated the following:

`Error invoking remote method 'register-biometric-unlock': Layerr: Failed storing source biometric details: Invalid password provided for source: debc9936-f870-4c49-b5d5-406783fe4ddd`

The password is correct. Tried doing an sample file (locally, not on Google Drive) with a simple password and the error still appears.

**Comment by ValoXya** [comment]
Same issue from my side. I also tried to create a new vault and that's the same thing

**Comment by spr2** [comment]
can confirm too, once you remove a vault or create a new one, you can't add Touch ID again with the error message above!

**Comment by devlanda** [comment]
https://github.com/buttercup/buttercup-desktop/blob/5c9a36db6a4e39020d50c8061c1c4880cc103f7a/source/main/ipc.ts#L289-L294

The password value is not available here. Inserted the code below before L292.

`logInfo("Password: " + password);`

**Comment by spr2** [comment]
working again! Thank you both for fixing this!
