### ISSUE TITLE
Real-time synchronization

### ISSUE THREAD

**Issue by lagethomas** [buttercup/buttercup-desktop#1288]
I just discovered the app and missed real-time synchronization like Safeincloud, for example.

Would this be possible?
To synchronize a change I need to leave the app and log in again, it would be interesting for this to be automatic as soon as the item is saved in the bank.

**Comment by perry-mitchell** [comment]
It is automatic and runs on a schedule, around 2 minutes.

**Comment by perry-mitchell** [comment]
It's not user configurable, as that'd make it easier to spam Google/Dropbox APIs. 2 minutes is fine for most use cases.

This feature might help when implemented: #1226
