### ISSUE TITLE
can't connect to a webdav folder

### ISSUE THREAD

**Issue by v0ltmn** [buttercup/buttercup-desktop#1290]
hi everyone!
noticed something strange:

i set up a webdav on my server, but I can’t connect to it via buttercup. I get a 401 error as if I'm logging in without credentials. but the credentials are correct.

obviously there is an error in the webdav configuration, but it is not obvious where exactly this error is: the browser and system utilities easily open the webdav folder, but buttercup doesn't.

try it yourself:

https://bcp.v0ltmn.xyz
user: demo
pass: pass

**Comment by perry-mitchell** [comment]
Created an issue in the relevant root repository for Webdav connectivity. There does indeed seem to be some issue. Would you mind leaving that demo account open for as long as possible while I debug it?

**Comment by perry-mitchell** [comment]
Works - release due this week :)

![Screenshot_20240318_223626](https://github.com/buttercup/buttercup-desktop/assets/3869469/e5a29fa4-4dbb-4cdd-a8e8-259afa1a0567)
![Screenshot_20240318_223748](https://github.com/buttercup/buttercup-desktop/assets/3869469/c1e74a9d-bfe6-4695-a827-b7cde3675bf7)

**Comment by perry-mitchell** [comment]
I'll release this later this week.

**Comment by v0ltmn** [comment]
***     ***
                          *   *   *   *
                         *     * *     *
                        *       *       *
                         *             *
                     >>>--------      *---->
                           *         *
                            *       *
                             *     *
                              *   *
                               * *
                                *

**Comment by perry-mitchell** [comment]
Released
