### ISSUE TITLE
Cannot unlock Vault from WebDAV [Jumpcloud]

### ISSUE THREAD

**Issue by adamturcsan** [buttercup/buttercup-desktop#1293]
Buttercup Desktop @ v2.26.2
Core @ v7.7.0

Ubuntu 20.04 - AppImage build

I added a new Vault with WebDAV from an ownCloud instance. Adding it went smooth, I was able to select the Vault .bcup file from the WebDAV. After that the app asks to unlock the Vault, and it fails with an 401 error. It seems that the app loses the authentication with the WebDAV.

The same Vault is working perfectly through this ownCloud WebDAV instance on and Android device and with a FireFox webbrowser (still standalone one)

Is there anything that I'm missing in order to setup the desktop app? I'm kinda getting worried that once I'll be not able to use the browser addon without the desktop app, I'll be screwed.

**Comment by perry-mitchell** [comment]
Hmm, I'm not sure, but let's see if we can figure out what the difference is. Do you know if you're still using standard basic auth on ownCloud, or digest?

If there's any chance you'd consider giving me a demo account, to help debug, that would help expedite the debugging. You might do so via Keybase. If you're not comfortable doing that it's fine, but my ability to help via github will be limited as ownCloud/Nextcloud are quite vanilla WebDAV wise.

**Comment by adamturcsan** [comment]
We use JumpCloud and I believe it's an LDAP under the hood

**Comment by perry-mitchell** [comment]
Ok. LDAP probably won't affect the auth mechanism for WebDAV, I don't think. But something must be up for some of the paths.

Not sure that there's much we can do without more info I'm afraid.

**Comment by perry-mitchell** [comment]
This needs triaging then, either here or in the [webdav client library](https://github.com/perry-mitchell/webdav-client). I don't have time currently.

**Comment by adamturcsan** [comment]
Since I switched to a NextCloud instance I don't have this issue. It could've been caused by ownCloud or the problem had since an unrelated solution. I don't know but I'm closing this.

**Comment by perry-mitchell** [comment]
Thanks for updating!
