### ISSUE TITLE
Freshly installed v3 Firefox Browser addon fails to use desktop app - unexpected application error

### ISSUE THREAD

**Issue by adamturcsan** [buttercup/buttercup-desktop#1295]
After connecting the desktop app with the addon and unlocking a vault in the app I see the following error in the addon menu:

Unexpected Application Error!
Invalid URI format

parse@moz-extension://deb8f94a-9e99-415d-a4d1-58261cdd505d/scripts/popup.js:747:29350
Ti/c<@moz-extension://deb8f94a-9e99-415d-a4d1-58261cdd505d/scripts/popup.js:832:1538
Dl@moz-extension://deb8f94a-9e99-415d-a4d1-58261cdd505d/scripts/popup.js:653:240947
7463/t.unstable_runWithPriority@moz-extension://deb8f94a-9e99-415d-a4d1-58261cdd505d/scripts/popup.js:653:303569
Ga@moz-extension://deb8f94a-9e99-415d-a4d1-58261cdd505d/scripts/popup.js:653:181800
Pl@moz-extension://deb8f94a-9e99-415d-a4d1-58261cdd505d/scripts/popup.js:653:240415
2551/Ml/<@moz-extension://deb8f94a-9e99-415d-a4d1-58261cdd505d/scripts/popup.js:653:240326
D@moz-extension://deb8f94a-9e99-415d-a4d1-58261cdd505d/scripts/popup.js:653:302630
7463/w.port1.onmessage@moz-extension://deb8f94a-9e99-415d-a4d1-58261cdd505d/scripts/popup.js:653:301353

It may be an addon issue, sorry if I put it into the wrong project but before unlocking the vault in the desktop app it seems to be working: showing the settings proeprly, managing the connection, detecting if a vault has been unlocked, etc.

**Comment by jyelland** [comment]
@adamturcsan see https://github.com/buttercup/buttercup-browser-extension/issues/466

**Comment by perry-mitchell** [comment]
Yep, closing in favour of #466
