### ISSUE TITLE
After upgrade to V3 brouwser plug can't communicate with desktop Buttercup Appimage

### ISSUE THREAD

**Issue by SD45T-2** [buttercup/buttercup-desktop#1296]
Today I was forced, it just happened the upgrade to V3.
Installed tha Appimage from github and could login into my fault (pfff).
However the buttercap plugin refuses to communicate with the desktop buttercup appimage application.
Where can I find a  solution, I hop this is not a bug/added feature because I'm lost at the moment, buttercup does not work any more in the browser (chrome and Brave)

Kind Regards,
Maarten

**Comment by perry-mitchell** [comment]
Hi @SD45T-2 - What error are you getting? We need more information if we're to help you. Please attach a screenshot and logs if possible.

**Comment by perry-mitchell** [comment]
Also, have you enabled browser access in the desktop app's Connection menu?

**Comment by SD45T-2** [comment]
I copied th error:
14:04:51.283 › Buttercup starting up...
14:04:51.446 › Restoring state... {
  settingsByArchiveId: {},
  archives: [
    {
      name: '1Ut5rNdMIvRIDNv6u7OfyQ53pqlyWg_Ec',
      id: 'aeb9e04c-7b80-42a0-acf1-ab955066fb4c',
      type: 'googledrive',
      status: 'locked',
      colour: '#000000',
      order: 0
    }
  ],
  settings: {
    columnSizes: { tree: 230, entries: 230 },
    isButtercupFocused: true,
    condencedSidebar: true,
    menubarAutoHide: false,
    archivesLoading: false,
    isTrayIconEnabled: true,
    secondsUntilClearClipboard: 15,
    autolockSeconds: 0,
    lockArchiveOnFocusout: false,
    lockArchiveOnMinimize: false,
    isBrowserAccessEnabled: true,
    updateOnStartDisabled: false,
    locale: 'en',
    globalShortcuts: {
      'preferences.minimize-and-maximize': 'CommandOrControl+Shift+X',
      'app-menu.app.preferences': 'CmdOrCtrl+,',
      'app-menu.archive.new': 'CmdOrCtrl+Shift+N',
      'app-menu.archive.open': 'CmdOrCtrl+O',
      'app-menu.archive.connect-cloud-sources': 'CmdOrCtrl+Shift+C',
      'entry.add-entry': 'CmdOrCtrl+N',
      'group.new-group': 'CmdOrCtrl+G',
      'app-menu.archive.search': 'CmdOrCtrl+F',
      'app-menu.view.condensed-sidebar': 'CmdOrCtrl+Shift+B',
      'entry-menu.username': 'CmdOrCtrl+B',
      'entry-menu.password': 'CmdOrCtrl+C',
      'archive-menu.lock': 'CmdOrCtrl+L'
    }
  }
}
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
Error: listen EADDRINUSE: address already in use :::12821
    at Server.setupListenHandle [as _listen2] (net.js:1228:14)
    at listenInCluster (net.js:1276:12)
    at Server.listen (net.js:1364:7)
    at Function.x.listen (/opt/Buttercup/resources/app.asar/dist/app.js:308:4557)
    at createHost (/opt/Buttercup/resources/app.asar/dist/app.js:226:270949)
    at startFileHost (/opt/Buttercup/resources/app.asar/dist/app.js:187:26391)
    at ka (/opt/Buttercup/resources/app.asar/dist/app.js:381:129702)
    at /opt/Buttercup/resources/app.asar/dist/app.js:381:137175
    at Va (/opt/Buttercup/resources/app.asar/dist/app.js:381:137180)
    at App.<anonymous> (/opt/Buttercup/resources/app.asar/dist/app.js:381:144699) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 12821
}

**Comment by SD45T-2** [comment]
![image](https://github.com/buttercup/buttercup-desktop/assets/40334141/6b5a90eb-9d52-48d4-9ccf-ff747b1ffb2b)

**Comment by SD45T-2** [comment]
I also have the enable browser access on.

**Comment by perry-mitchell** [comment]
Ah, your desktop application is too old. Looks like you're on V1 still. Please upgrade to the newest desktop version to use the browser API.

I'll close this as I believe we've found the problem.

**Comment by SD45T-2** [comment]
Hi Perry,

Thanks to pointing out. I upgrades my desktop app, I never used before and also installed AppImagelancher.
Ik all works now besides a error during startup but I could make the connection with the browser and that par also works.

Thanks,
Maarten
