### ISSUE TITLE
Unable to open .bcup file from Google Drive

### ISSUE THREAD

**Issue by golobolus** [buttercup/buttercup-desktop#1298]
I have 2 .bcup files over my Google Drive account and was able to use them both on the previous Browser app.

After the update, I am only able to use 1 file, and the Desktop App [AppImage version] is unable to recognize the other one, and is not showing on the list of files that can be selected. 

I have tried moving the other .bcup file to an alternate Google Drive Account but still no avail.

I also have the mobile app which has both bcup files loading fine and is able to sync with the cloud sources. 

Is there a way or workaround to have both files working and syncing through the Desktop App or is this a bug that's already being worked-on in the pipeline?

I'm using 
Ubuntu 22.04.4 LTS
GNOME 42.9

**Comment by perry-mitchell** [comment]
Perhaps one was not added using Buttercup, and uploaded manually? We recently had to drop our restricted Google Drive permission, "drive", as Google didn't want us to use it. They instead suggested us to just use `drive.file`. The difference here is that the latter requires that the file was edited/added by Buttercup.

**Comment by morojgovany** [comment]
I can confirm that, I had the same problem with my windows computer and I found a workaround :
- download the "old" file and open it in local with bcup by creating a new vault.
- export it in csv buttercup file
- create a new empty vault on drive
- import the local csv file
The new bcup file is now visible in the list when adding a new one.

But on linux (Ubuntu 20.04.6 LTS) I am stuck after google authentication, the magnet link is not opening & the desktop app still asking for login. (tried 3 browsers)
The only error in terminal after init is : `Failed registering protocol: buttercup`
Should I create a new issue ?

Thx

**Comment by perry-mitchell** [comment]
>Failed registering protocol: buttercup

This is usually due to missing/misconfigured components on the host system regarding custom protocols. 

> Should I create a new issue ?

Sure, you should feel free to - but it would probably only help if there was some easy way to reproduce it.

> Edit2: After researches it exports OTP but into a field otpauth://totp/xxxxxx (no longer visible as a code)

Exporting to CSV doesn't preserve field types. It would be better for us to work on a Buttercup specific import/export format (we plan to do this, but have no issue yet) so that these are preserved.

**Comment by perry-mitchell** [comment]
Getting back to the parent issue then - I think this comes down to adapting to the new way of working with Google Drive, without the open permissions option. I think we need an upload button in the file view, so we can upload local vaults to GDrive _using_ Buttercup so they're accessible. That, or implement Google's own JS based file picker.

Sigh.. Google wastes so much of my time with this stuff.
