### ISSUE TITLE
Cannot Connect or use Google Drive File

### ISSUE THREAD

**Issue by Pandasdontfly** [buttercup/buttercup-desktop#1299]
Admittedly i have had the buttercup app installed but never used it in a long while but upon getting the update my old connection will not work I'm first told to re-authenticate which i do by logging in again. Then it says I'm authenticated but when re-entering the password I'm giving the error in the first screenshot.

I thought that maybe it was because it was an old connection and to make a new one but upon trying to get a new connection to it going i realized i cannot add as my only option from google drive is to make a new one (which is seemingly does successfully and it does create the file in the google drive) thus i cant access my old passwords at all even though my old file is still sitting on my drive.

![Screenshot_80](https://github.com/buttercup/buttercup-desktop/assets/87935732/8bc6ca18-bad3-459e-97c7-325080afd3a8)

![Screenshot_81](https://github.com/buttercup/buttercup-desktop/assets/87935732/69aaff2d-49aa-49a0-8697-c71ea41fe7ef)

**Comment by perry-mitchell** [comment]
I'd need some logs to say why the 401 occurred. It'd be great if you could run the app from the command line, perform the same task and see what logs are output.

**Comment by Pandasdontfly** [comment]
> I'd need some logs to say why the 401 occurred. It'd be great if you could run the app from the command line, perform the same task and see what logs are output.

I'm sorry i don't know how to do that?

**Comment by perry-mitchell** [comment]
Closing in favour of #1309. They're duplicates but the other has more information.
