### ISSUE TITLE
Latest Buttercup-linux-x86_64.AppImage is out of date

### ISSUE THREAD

**Issue by jyelland** [buttercup/buttercup-desktop#1302]
I am trying to update Buttercup to the latest desktop version, 2.26, on Ubuntu 22.04.4 LTS. I'm trying to solve a (possibly related) issue with the V3 browser extension. But when I download the [latest release](https://github.com/buttercup/buttercup-desktop/releases/download/v2.26.2/Buttercup-linux-x86_64.AppImage), make it executable and run it, the program is still version 2.24.3.

![image](https://github.com/buttercup/buttercup-desktop/assets/45605554/752184fa-2da7-4eb6-ab3f-90a6f4f1dcf7)

**Comment by jyelland** [comment]
I was able to update through a release notification within the app. But does the link still point to an out-of-date release?

**Comment by perry-mitchell** [comment]
![image](https://github.com/buttercup/buttercup-desktop/assets/3869469/4189e9fd-ae5f-4bae-800e-0fbee1b48b90)

I think it's correct. I downloaded and got the right version. It's most likely an AppImage config issue on your system, as we release from the CI which is cleaned every time it runs.

**Comment by jyelland** [comment]
Got it, thanks. I'm a bit confused, because I thought everything was self-contained within the downloaded AppImage executable, but I'll do some homework.
