### ISSUE TITLE
Browser extension requiring desktop app

### ISSUE THREAD

**Issue by klizadesign** [buttercup/buttercup-desktop#1306]
Today, my Buttercup Chrome extension was updated to require a desktop app to run. It looks like all of my vaults are gone, the extension won't connect to the desktop app, and I had to make a Github account to even talk with you. Very upset, this came without any warning and it looks like all of my passwords are gone. Please advise, I'm done with this if this is how you're going to roll out changes. No access to any passwords today, so mad right now.

**Comment by perry-mitchell** [comment]
https://github.com/buttercup/buttercup-browser-extension/discussions/451
