### ISSUE TITLE
Unable to release - notarization broken

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#1307]
Mac notarization is broken, so we can't release new builds: https://github.com/samuelmeuli/action-electron-builder/issues/101

We might have to move to Electron Forge and start again, with the publishing process, as there doesn't seem to be any simple way to force the current configuration to use the new `notarytool` that would be required. Don't particularly want to waste time writing custom notarization scripts either honestly.

**Comment by quintushr** [comment]
Hi @perry-mitchell, I can assist you; I've already worked on notarizing an app.

Why are you using a fork of Electron Builder action instead of the official Electron Builder?

https://github.com/electron-userland/electron-builder.git

**Comment by perry-mitchell** [comment]
Thanks @quintushr - I think I already got it fixed, pending a release later. At least it said it notarized successfully.

As far as I'm aware there is no official GitHub action for electron builder. We are using the official electron builder library as well though. The action invokes the builder.

Appreciate the help! If it fails I'll definitely ask more from you if you have the time 🙏

**Comment by johannesjo** [comment]
@perry-mitchell may I ask how you were able to fix the issue?

**Comment by johannesjo** [comment]
That worked! Thank you very much! I really appreciate it. Some of these electron builder issues are my personal hell xD

I added you on LinkedIn, since we seem to share a passion or two, I hope that is alright :)

**Comment by perry-mitchell** [comment]
Hey that's great to hear! Happy to have helped someone else out of that mess. Agree it's hell. That's why I hate touching it.

Yeah of course! Happy to be connected mate.
