### ISSUE TITLE
Can not run Buttercup desktop on my MacOS (M1)

### ISSUE THREAD

**Issue by mdemri** [buttercup/buttercup-desktop#1308]
When i click on the link, it starts then fails (no ui shown)
Tried to delete the contents from /Library ...

That's what i found in the logs
2024-03-28 14:13:42.657676+0200 0xdbbc7    Error       0x0                  90707  0    Buttercup: (CoreVideo) [com.apple.corevideo:] CurrentVBLDelta returned 199999 for display 1 -- ignoring unreasonable value
2024-03-28 14:13:42.657679+0200 0xdbbc7    Error       0x0                  90707  0    Buttercup: (CoreVideo) [com.apple.corevideo:] [0x7fc0ef021220] Bad CurrentVBLDelta for display 1 is zero. defaulting to 60Hz.

Dont know if relevant.

I have this issue for months.. but now it became crucial, since the browser extension requires a working desktop app

**Comment by mdemri** [comment]
How can i run the application in debug mode.. so i'll see the relevant logs?

Otherwise, how could i extract the vault file to csv via command line?

**Comment by perry-mitchell** [comment]
By debug I mean run the application using NodeJS etc. to see if changing some flags or upgrading certain packages might help. Narrow down the issue. I suppose the error you've shown is already as verbose as we're going to see by just executing it.

**Comment by perry-mitchell** [comment]
There seems to be quite little docs for such an error: https://developer.apple.com/forums/thread/701855

Can you try the following?

> Try adding OS_ACTIVITY_MODE to the envirable variables (within the run settings) and set that env variable to disable

**Comment by mdemri** [comment]
Still doesn't work, with OS_ACTIVITY_MODE = disable / disable_all

**Comment by mdemri** [comment]
BTW, Its working when i'm running the code via "npm run start"

**Comment by perry-mitchell** [comment]
I think we just need to be able to release the arm equivalents of the Mac release like we do on Linux. Not sure if our version of electron-* supports that, hopefully it does.

**Comment by perry-mitchell** [comment]
@mdemri Would you be willing to test an experimental build for Mac? I've got a config update in #1316 but don't currently have Apple Silicon to test it on.

**Comment by mdemri** [comment]
Np. How do i publish a mac app via npm command?On Mar 31, 2024, at 20:00, Perry Mitchell ***@***.***> wrote:﻿
@mdemri Would you be willing to test an experimental build for Mac? I've got a config update in #1316 but don't currently have Apple Silicon to test it on.

**Comment by perry-mitchell** [comment]
@mdemri No need, but thanks for being so keen to help!

I'm going to add support for a pre-release channel today/tomorrow, so you can safely update to it and try it out. I'll keep you posted.
