### ISSUE TITLE
Cant Update to Newest vVrsion

### ISSUE THREAD

**Issue by Pandasdontfly** [buttercup/buttercup-desktop#1315]
On Windows 11 for the past couple days i've not been able to update and keep getting a massive error message. Pc and App Restarts dont fix it.

![image](https://github.com/buttercup/buttercup-desktop/assets/87935732/7c4034c5-8787-4243-801b-8e95ad5d4b9b)

**Comment by perry-mitchell** [comment]
Confirmed, massive oversight on my part. Releasing a patch asap.

**Comment by perry-mitchell** [comment]
@Pandasdontfly are you able to confirm whether or not the latest release (2.26.5) fixes this issue?

**Comment by Pandasdontfly** [comment]
> @Pandasdontfly are you able to confirm whether or not the latest release (2.26.5) fixes this issue?

Sorry i had not even tried since then. But no it no longer produced the error just finished the installation bar then nothing... Uninstalling and reinstalling fixed it for me though

**Comment by perry-mitchell** [comment]
Interesting. It shouldn't have corrupted anything if the signing failed, but seems like it might have had some lock-up effect. Good it worked afterwards.
