### ISSUE TITLE
Unable to update from v2.26.3

### ISSUE THREAD

**Issue by mas268ga** [buttercup/buttercup-desktop#1324]
The last 2 or 3 updates result in a large red box with code. I'm stuck at v2.26.3.

![2024-04-02](https://github.com/buttercup/buttercup-desktop/assets/69015144/e6b2ce36-5b31-4932-85bb-bea710ce9437)

**Comment by perry-mitchell** [comment]
This should have fixed in [2.26.5](https://github.com/buttercup/buttercup-desktop/releases/tag/v2.26.5).. The latest versions, when downloaded, should be correctly signed.

@mas268ga can you please attach the full error?

**Comment by mas268ga** [comment]
I think copy/paste caught it all


Vault Locked
LastPass

Update failed: New version 2.27.0 is not signed by the application owner: publisherNames: Vault Garden, raw info: { "SignerCertificate": { "FriendlyName": "", "IssuerName": { "Name": "CN=Sectigo Public Code Signing CA R36, O=Sectigo Limited, C=GB", "Oid": "System.Security.Cryptography.Oid" }, "NotAfter": "/Date(1717718399000)/", "NotBefore": "/Date(1654560000000)/", "PrivateKey": null, "PublicKey": { "Key": "System.Security.Cryptography.RSACryptoServiceProvider", "Oid": "System.Security.Cryptography.Oid", "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData", "EncodedParameters": "System.Security.Cryptography.AsnEncodedData" }, "SerialNumber": "51308BBDCB43A3B863439D11A735C4FB", "SignatureAlgorithm": { "Value": "1.2.840.113549.1.1.12", "FriendlyName": "sha384RSA" }, "Thumbprint": "DBBB825FB465D7153D58BEAC559195A16B4BF07C", "Version": 3, "Issuer": "CN=Sectigo Public Code Signing CA R36, O=Sectigo Limited, C=GB", "Subject": "CN=MadDev Oy, O=MadDev Oy, S=Uusimaa, C=FI" }, "TimeStamperCertificate": { "Archived": false, "Extensions": [ "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension", "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension", "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension", "System.Security.Cryptography.X509Certificates.X509Extension", "System.Security.Cryptography.X509Certificates.X509Extension", "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension", "System.Security.Cryptography.X509Certificates.X509Extension", "System.Security.Cryptography.X509Certificates.X509Extension" ], "FriendlyName": "", "IssuerName": { "Name": "CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O=\"DigiCert, Inc.\", C=US", "Oid": "System.Security.Cryptography.Oid" }, "NotAfter": "/Date(2044396799000)/", "NotBefore": "/Date(1689292800000)/", "HasPrivateKey": false, "PrivateKey": null, "PublicKey": { "Key": "System.Security.Cryptography.RSACryptoServiceProvider", "Oid": "System.Security.Cryptography.Oid", "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData", "EncodedParameters": "System.Security.Cryptography.AsnEncodedData" }, "SerialNumber": "0544AFF3949D0839A6BFDB3F5FE56116", "SubjectName": { "Name": "CN=DigiCert Timestamp 2023, O=\"DigiCert, Inc.\", C=US", "Oid": "System.Security.Cryptography.Oid" }, "SignatureAlgorithm": { "Value": "1.2.840.113549.1.1.11", "FriendlyName": "sha256RSA" }, "Thumbprint": "66F02B32C2C2C90F825DCEAA8AC9C64F199CCF40", "Version": 3, "Handle": 2860182820912, "Issuer": "CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O=\"DigiCert, Inc.\", C=US", "Subject": "CN=DigiCert Timestamp 2023, O=\"DigiCert, Inc.\", C=US" }, "Status": 0, "StatusMessage": "Signature verified." }

**Comment by perry-mitchell** [comment]
Not sure why the publisher name is "Vault Garden", as it's been corrected in the build config: https://github.com/buttercup/buttercup-desktop/blob/master/package.json#L161

**Comment by perry-mitchell** [comment]
@mas268ga It's probably broken because you're _on_ a broken version (wrong publisher name). 2.26.3 is bad. Can you try installing 2.26.2 (https://github.com/buttercup/buttercup-desktop/releases/tag/v2.26.2) and then see if it'll update?
