### ISSUE TITLE
2.6.2 on ipad -  Since update can’t access Password file on Google Drive  

### ISSUE THREAD

**Issue by tshaper** [buttercup/buttercup-desktop#1331]
Get the following error in safari

Access blocked: authorisation error
Missing required parameter: client_id
Error 400: invalid_request

**Comment by brianloekkeborg** [comment]
Same issue

**Comment by Traimb0t** [comment]
Same issue in the Android app. Confirmed on two different devices.

**Comment by iouston** [comment]
Same issue in the Android app, with vault stocked on gdrive

**Comment by Pemichka** [comment]
Gleiches Problem in der Android-App. Bestätigt auf zwei verschiedenen Geräten. Ich verwende jetzt WEBDAV.

**Comment by tshaper** [comment]
Checked today. Has started working again in Safari on Android.

**Comment by tshaper** [comment]
I note that  app has been updated to 2.6.3. Thanks devs.

**Comment by tshaper** [comment]
Sorry previous comment should have said “now working in Safari on ipad” .  I’ll leave this thread open in case people having problems on Android wish to  confirm that problem is fixed..

**Comment by Pemichka** [comment]
Hallo,
  

  

  
seit heute früh ist alles wieder i.O..😀
  

  

  
  
Mit freundlichem Gruß
  

  
Peter Kaps
  

  

      
  
  
>

**Comment by perry-mitchell** [comment]
How're you all running Buttercup in Safari? 😅 

Good if the issues have passed at least.

**Comment by tshaper** [comment]
Sorry not actually in Safari just with safari. Cutting and pasting passwords. Buttercup did once work with the ipad password system. Ipad provides a dropdown list of password programs you can choose from  when you click in a password field, but the buttercup option stopped working a long time ago. Sent from my iPadOn 6 May 2024, at 17:51, Perry Mitchell ***@***.***> wrote:﻿
How're you all running Buttercup in Safari? 😅
Good if the issues have passed at least.

**Comment by iouston** [comment]
Today on android app with a vault on gdrive, all is good.
Thank's a lot for fix this issue !

**Comment by brianloekkeborg** [comment]
2.6.3 has resolved My issue thanks devs

**Comment by tshaper** [comment]
Issue seems to be resolved for android and ipad.  Thanks again devs.
