### ISSUE TITLE
Clipboard clear display/clock

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#134]
Some sort of indicator that shows when the clipboard will clear would be very useful.

Depends on #2

**Comment by perry-mitchell** [comment]
What about a simple bar like the following? https://github.com/react-component/progress

It could be only a slight contrast difference to the bg colour of Buttercup and could simply count down with the time left before clipboard clearing..

What do you think @sallar ?

**Comment by sallar** [comment]
@perry-mitchell definitely mate.

**Comment by perry-mitchell** [comment]
Maybe not required, we can decide later if it's needed.
