### ISSUE TITLE
[request] A Cryptomator plugin to use Buttercup vaults as the database for storing and retrieving passwords

### ISSUE THREAD

**Issue by aderchox** [buttercup/buttercup-desktop#1354]
I know this is probably not the best place to request it, but since I'm interested in Buttercup as my main vault software, I'd like to request the folks here to also make a plugin for Cryptomator so that its passwords may be stored in the Buttercup.
See here for more information: [Replacement for "Windows Data Protection" used in Cryptomator](https://community.cryptomator.org/t/preferences-safe-password-with-windows-data-safty/10678/2)
![image](https://github.com/user-attachments/assets/c82f1592-b850-436b-909d-4ae908a06cd0)
Thanks.

**Comment by perry-mitchell** [comment]
Hi @aderchox - Thanks for the interest!

I'm not exactly sure what you're asking, but if it's a direct integration you're after I'd probably say it's a no, sorry. Buttercup can interact with datasources to **store** vaults, and it can have other formats imported to bcup format and then have its data exported to other formats. If Cryptomator's use case doesn't fit into one of these 3 cases then it's probably out of scope for what Buttercup is trying to provide.

That being said - this is open source, so you're always welcome to try integrating yourself. If I misunderstood something here I apologise. I'll close this for now however.
