### ISSUE TITLE
background color issue

### ISSUE THREAD

**Issue by Kortex76** [buttercup/buttercup-desktop#1356]
Hello, i have detected an issue, i think it appears on the latest version 2.28.0 : it's impossible to read the text (application list) in the right frame, as the text is the same color as the background.
If Windows is in dark mode, you don't see the bug, because by default the theme of buttercup will be on dark mode also. The problem is visible in light mode.

In the dev mode, it appears that the background color is not updating automatically as it should

![Capture d’écran 2024-07-19 181455](https://github.com/user-attachments/assets/152dfb31-36bf-437d-9ab0-e231ead0c166)

thank you

**Comment by perry-mitchell** [comment]
Can you attach a picture of what you mean? I only see the screenshot of the dev pane.

**Comment by Kortex76** [comment]
here you are :
![Capture d’écran 2024-07-19 181114](https://github.com/user-attachments/assets/78060db6-6192-4a34-b479-920cbcb13e99)

**Comment by fvpv** [comment]
Hi!
Same thing for me, fresh windows install with the light theme has the same effect, defining the light theme on buttercup and then restarting the software dosen't change anything

**Comment by ilpirata81** [comment]
I encountered the same problem on mac osx Sonoma 14.5 (23F79) - M1

**Comment by perry-mitchell** [comment]
Apologies for the delay here - confirmed. I'll try to fix it today.

Dark mode works however, and might be a suitable fix until a patch is pushed out. I develop in dark mode primarily and neglected to test in light for this release.. Sorry for that.
