### ISSUE TITLE
Use fuzzy/deep searching from core

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#136]
Depends on buttercup-pw/buttercup-core#135

**Comment by sallar** [comment]
@perry-mitchell any updates on this from core?

**Comment by perry-mitchell** [comment]
@sallar Not yet, hopefully soon :)

**Comment by sallar** [comment]
@perry-mitchell Hey man, does the search exist on core now?

**Comment by perry-mitchell** [comment]
Yep! It's used in the browser extension..
