### ISSUE TITLE
Password entry modes (new entry)

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#139]
When creating entries, only entering the password in full-visible form is possible. Some other managers allow for this form as well as 2 hidden password entries (password & repeat password), which seems to work very well.

For security reasons the hidden format would best be set as the default. Some sort of toggle between the two would be required.

EDIT: Not on my mac so I can't check, but I guess there were the binoculars there at some stage (not on linux/windows). I guess this functionality would extend from that..

**Comment by sallar** [comment]
@perry-mitchell could you please include a screenshot or some kind of visual clue? not sure I completely understand it. thanks mate

**Comment by perry-mitchell** [comment]
I don't think this is necessary right now.. We can reopen if necessary.
