### ISSUE TITLE
Setting for configuring auto-lock time

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#141]
A per-archive setting of auto-lock time after x seconds/minutes of inactivity for locking the GUI would be very handy to have.

After the default time of say, 10 minutes, the archive is locked. This can be overridden by the archive's settings.

This depends on:

- #140 
- ~~buttercup-pw/buttercup-core#137~~

**Comment by ws141** [comment]
Any opinions on implementing this without the configuration ability and just having a hard coded time limit to start with? That should limit the effort needed to implement the feature since not leaving your archive open for an indefinite amount of time would be of higher priority then just medium?

**Comment by perry-mitchell** [comment]
@ws141 I personally agree with that point - it'd be better than leaving it open permanently. This is how our platform currently behaves:

 * Mobile app autolocks after 10? minutes
 * Browser extension locks on closing of all tabs
 * **Desktop doesn't currently autolock**

So it would be very beneficial to have this feature. It would, in my opinion, have to:

 * Lock all currently unlocked archives
 * Listen for user-cues in terms of _activity_
   * Reset lock timer on mouse move
   * Reset lock timer on focus change
   * Reset lock timer on tray icon menu open
 * **Disable** the timer while **any item is being edited**

Does that sound fair? What's your opinion @sallar?

**Comment by perry-mitchell** [comment]
Available in V2.
