### ISSUE TITLE
Confirm master password

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#261]
The master password, when being entered for the first time or changed, should have at least another input to confirm that the typed password is correct. This will help prevent corruption.

**Comment by perry-mitchell** [comment]
This is related to #78, and could be coupled together in the same release.

**Comment by hd719** [comment]
Hello! 

I am new to open source can I work on this? 

-Thank you.

**Comment by sallar** [comment]
@hd719 Any help is appreciated.

**Comment by hd719** [comment]
@perry-mitchell I am going to do issue #78 and this issue together.
