### ISSUE TITLE
Export/import from Firefox Sync

### ISSUE THREAD

**Issue by donty** [buttercup/buttercup-desktop#271]
Looks good but not been able to use it in anger until I find a suitable import solution.

As a suggestion for Firefox users, an import option from Firefox sync would be great. I can export the password list to CSV using a Password Exporter plugin https://github.com/fligtar/password-exporter/wiki but we would need a filter similar to the Lastpass one but for Firefox sync fields to pull it in. 

Though maybe something cleaner with the new Firefox security access controls would be smoother? However, when you have lots stored already elsewhere anything to make it easier to push in would ease adoption.

**Comment by perry-mitchell** [comment]
Thanks @donty! If you discover anymore on FF sync we'd appreciate it. Having more of an idea of how hard it might be may make it easier for someone to contribute.

**Comment by perry-mitchell** [comment]
Closing as we have an issue in importer to track. No need for this one.
