### ISSUE TITLE
Export archives on standard formats

### ISSUE THREAD

**Issue by nd4pa** [buttercup/buttercup-desktop#278]
Hi, i'm realy excited about what you've done with this project, we've realy missed this kind of tools before and i think it's gonna help a lots of people. 

A nice feature would be to be able to export the database in a standard formats like csv or json, cause' one of the aspect to use free software is it's ability to be interoperable with other tools and standard formats is a great way to do it, you could use a gpg based encryption to protect, that way it could be easy for anyone ( like me ) to create a backup tool ( yeah, sounds pretty paranoid though, but we're never too paranoid about our passwords isn't it ? )

see you around,

Antoine Blondeau

**Comment by perry-mitchell** [comment]
> Hi, i'm realy excited about what you've done with this project, we've realy missed this kind of tools before and i think it's gonna help a lots of people.

Thanks!

> A nice feature would be to be able to export the database in a standard formats like csv or json, cause' one of the aspect to use free software is it's ability to be interoperable with other tools and standard formats

Agreed.

> you could use a gpg based encryption to protect, that way it could be easy for anyone

Many platforms export to unencrypted formats for easy interop support.. which would probably be our first port of call. Having encrypted exports is nice for backup purposes, but backups as a whole is another task. Backup features need to support all of our remote sync systems (webdav/dropbox etc.) and it needs to be well integrated into the platform. I'd advise anyone reading this to keep export and backup separate for simplicity's sake :smile:

**Comment by fmommeja** [comment]
Hi, I totally agree with the express need to be able to export Buttercup datas and to reimport them.
For instance I wanted to make my password stronger without having to recreate my whole archive… And I found out there was no way to achieve that!
I'd really appreciate to see this feature Priority evolve to high  ;)

Thanks for the great job already done anyway.  :)

**Comment by nd4pa** [comment]
I'm working on csv export with a friend right now, we will send a PR asap

**Comment by benseitz** [comment]
@nd4pa  any news on that PR?

@fmommeja I agree! Alternatively: #78 is a `Priority:High` Issue for making the master password changeable. Unfortunately with no news

**Comment by perry-mitchell** [comment]
> Issue for making the master password changeable. Unfortunately with no news

Apologies regarding the lateness there - We're now working to complete the password-change feature. It's already been added in core.

**Comment by sallar** [comment]
@benseitz Thats WIP. Coming soon in next release :)

**Comment by fmommeja** [comment]
@perry-mitchell @sallar Great news!!!  Thanks! 👍

**Comment by rebootit** [comment]
Next release is here and I don't see the option, how can I export ?

**Comment by perry-mitchell** [comment]
I think you misunderstood- my colleague was referring to changing the master password, not exporting archives..

**Comment by perry-mitchell** [comment]
An update on this: Exporting will soon be available to CSV. No other export formats are planned at this stage.
