### ISSUE TITLE
Buttercup in Spanish?

### ISSUE THREAD

**Issue by llkiriell** [buttercup/buttercup-desktop#284]
I want to have the application in Spanish language. I found these files:

![shot_170608_214656](https://user-images.githubusercontent.com/12781734/26959160-4282874e-4c94-11e7-9d6a-f567529a79f2.png)

Exists? How can I change the language?

**Comment by perry-mitchell** [comment]
Thanks @llkiriell - This is blocked by #285. Although those files exist, we do not currently have any translations available. We're looking at adding a translation system so people can contribute and add localisations based upon demand. We should have this soon enough :)

**Comment by sallar** [comment]
Thanks @llkiriell - Those translation files that you mentioned belong to the embedded chrome/electron runtime and not us. But like @perry-mitchell mentioned, we are looking into adding localization.

**Comment by sallar** [comment]
This is done and will be released today. Closing this 🎉
