### ISSUE TITLE
Open last group on archive unlock

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#293]
Currently the last group open in an archive seems to be the last created(?).. It would be best if each group selection stored the following in localstorage (as a suggestion): `lastGroup:(archiveID)/(groupID)`. When an archive is opened this value could be checked and, if it's valid, could be selected (only of the group exists).

**Comment by sallar** [comment]
This is a great idea. Although we don't need to store it in localStorage since we have "per archive" state in our redux tree. expanded keys, column sizes, etc are all persisted to disk and restored, so this `lastGroup` thing can be also one of those. right?

**Comment by sallar** [comment]
and I agree it's very annoying when you open the archive again, it doesn't remember the last selected group and it always goes to `General`

**Comment by perry-mitchell** [comment]
> it doesn't remember the last selected group and it always goes to General

This doesn't happen now however.. It would be better than the current _last created group_ which it seems to do.

This is extremely minor of course.. just a nice to have :)
