### ISSUE TITLE
Consider renaming repo to "buttercup-desktop"

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#295]
Due to the high amount of issues that are missing their mark (should be on this repo or on another and are misplaced), it may be wise to consider renaming this repo. "Buttercup" is very broad and although simplicity is grand, it may be causing more harm than good at this stage.

Providing external linking still works on `buttercup/buttercup`, this should be quite painless imo.

**Comment by sallar** [comment]
@perry-mitchell I agree, Let's do this change today then? If you're ok, I can do the renaming.

**Comment by perry-mitchell** [comment]
Let's do it.. No harm in it. Let's do a sanity check afterwards to make sure our gear works as expected:

 * Website & download links
 * Twitter links (profiles)
 * Travis

Also @sallar make sure to update the git url in the package.json ;)
