### ISSUE TITLE
[Lastpass] Import parsing error

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#297]
Originally posted by @doodlemania2:

> When performing a LastPass import (CSV) it appears as though the importer is not properly escaping out the commas that appear in different fields/entries. End up with a variety of misplaced/incorrect entries.

_Posted [here](https://github.com/buttercup/buttercup-browser-extension/issues/79)_

**Comment by perry-mitchell** [comment]
As we don't always have access to Lastpass archives, we would need someone to submit a small test export from Lastpass in CSV format with the following:

 * Some multi-line values
 * Values with commas (including password)
 * Regular username/password

This could be submitted here or in the buttercup-importer project.

**Comment by perry-mitchell** [comment]
This is related to [this issue on the importer](https://github.com/buttercup/buttercup-importer/issues/14).

**Comment by woohooatb** [comment]
Is this issue fixed?

**Comment by sallar** [comment]
@woohooatb yes it should be.

**Comment by bzin** [comment]
Was this fixed? I keep having it when I have an entry that  has multilines.
