### ISSUE TITLE
Got this error message at first run

### ISSUE THREAD

**Issue by rezamarandi** [buttercup/buttercup-desktop#310]
Hey guys ...
first of all , thanks for your great work
but when i open buttercup for first time , i got this message , can you explain what is going on ?
![screen shot 2017-07-06 at 7 52 20 pm](https://user-images.githubusercontent.com/1782425/27918639-d09b24d6-6284-11e7-9d6a-81e22436a95e.png)

**Comment by sallar** [comment]
Thanks @rezamarandi. This will be fixed in the next release. Does this happen every time you open buttercup?

**Comment by rezamarandi** [comment]
@sallar , actually no , i just got this message @ first run
