### ISSUE TITLE
Windows build issue: Unhandled Promise Rejection

### ISSUE THREAD

**Issue by 4A616D6573** [buttercup/buttercup-desktop#311]
Hi,

I get this error each time I try open Buttercup:

![2017-07-07 16_26_43-](https://user-images.githubusercontent.com/26444435/27945618-22a9db26-6331-11e7-9747-bab033de2455.png)

Have tried with both V17.2 and V18.

**Comment by sallar** [comment]
@4A616D6573 Thanks. Does the app work normally after you close this?

**Comment by 4A616D6573** [comment]
@sallar 
Hey, No I can't use the app, it is still running in the background though.

I have tried uninstalling and re-installing and receive the same issue.

Let me know if you need anymore information.

**Comment by metamorphosis-org-mk** [comment]
I got the same error after a update of the app today. I tried to install the previous version but there was the same error. Using Windows 10.

**Comment by 4A616D6573** [comment]
I'm also using Windows 10, still haven't been able to fix the issue. I will try install V18.1 tomorrow and see what happens.

**Comment by perry-mitchell** [comment]
Thanks everyone - We currently don't have direct access to a windows machine, so any help would be greatly appreciated!

**Comment by metamorphosis-org-mk** [comment]
Ok, I'll be detaled as I can:
I used the app this morning, and there was a little message in the bottom of the screen that there is a update, I guess there is some automatic way of updating, the install process started and nothing happened. When I tried to open the app again I got this

![buttercup-error](https://user-images.githubusercontent.com/19167472/28365661-b697816a-6c89-11e7-9b6c-ef36c1d0c863.png)

there were three processes in the background which i ended. I uninstalled the app, restarted the PC, then tried to install a older version 18.0 cause I thought there is some problem with the new update. Same error occurred with the older version as well. I tried to install the new version 18.1, but after the install there was the same error.

**Comment by perry-mitchell** [comment]
@4A616D6573 @metamorphosis-org-mk Hey guys, could you please show us the contents of your state? It's located here: `~/AppData/Roaming/Buttercup/storage/state.json` - There may be some kind of corruption. If we can figure out what it is we can address it immediately..

**Comment by sallar** [comment]
@4A616D6573 @metamorphosis-org-mk @perry-mitchell Providing that files before updating your Buttercup will help us prevent this from happening again! Thanks.

**Comment by 4A616D6573** [comment]
@sallar Here is the contents of my state.json file:

![2017-07-20 07_59_24-c__users_pembertonj_appdata_roaming_buttercup_storage_state json - notepad](https://user-images.githubusercontent.com/26444435/28391428-65b4b392-6d21-11e7-9a5f-4a9b7162d04a.png)

**Comment by sallar** [comment]
@4A616D6573 yeah, what I suspected... although I have no idea how this has happened...

**Comment by 4A616D6573** [comment]
@sallar v18.2 works for me, thanks so much!

**Comment by metamorphosis-org-mk** [comment]
Can confirm that hotfix works on my machine as well. Thank you so much for the quick reaction!

**Comment by perry-mitchell** [comment]
Thanks guys! Sorry again for the outage. We're working to try and prevent this.
