### ISSUE TITLE
Integration test case

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#312]
I think we need to have at least one high-coverage integration test for the UI. This could test something basic like adding and unlocking a file-based archive. Once working, this would be great to run on all platforms so that we could ensure some level of automated stability checking.

**Comment by sallar** [comment]
@perry-mitchell this is definitely possible, however a bit difficult. But I agree that we need to add this quite soon.

**Comment by perry-mitchell** [comment]
@sallar Agreed it is certainly difficult. Once it's going however, it'll be a massive help for PRs and gradual updates. Let's discuss this next meeting.

**Comment by perry-mitchell** [comment]
I have an idea for this one, which I might try to make today. The requirements of such a test:

 * Be executable, which exits with success (0) or failure (1+) exit codes.
 * Works on windows, linux and mac
 * Has tests for each platform
 * Tests the bare minimum, to begin with:
   * Boot of application without error

Should be started by executing the program with a flag, such as the following: `./buttercup --test=integration`. It could then wait until the app boots and finishes, and then could execute some minor tests (to begin with). After which it could force close with exit code 0.. if an error occurs obviously the test should fail.
