### ISSUE TITLE
[ Feature Request ] Add default label 'Notes' when add custom field

### ISSUE THREAD

**Issue by esutton** [buttercup/buttercup-desktop#320]
I think common use is to add a single custom field.  
Default label to 'Notes',

Thank you for sharing your work! Nice job.

I am looking forward to trying out https://github.com/buttercup/buttercup-mobile

**Comment by sallar** [comment]
Thanks @esutton. We are working on a new feature that will allow this. We'll keep this updated.

**Comment by perry-mitchell** [comment]
This depends on #540

**Comment by perry-mitchell** [comment]
Having another look at this issue, I don't think we want to set default labels.
