### ISSUE TITLE
[Feature] Locked/Unlocked state for archives

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#325]
Currently it's not possible to tell if an archive is locked or unlocked, just by looking at it.. I wonder if there's some way we could easily visualise the state of each archive in the sidebar..

**Comment by sallar** [comment]
@perry-mitchell the state is only visible if the sidebar is expanded (cmd+B) but not if its condensed. We should add that in condensed mode too.
