### ISSUE TITLE
Archives list could be moved up a little?

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#327]
![image](https://user-images.githubusercontent.com/3869469/29765358-889d8114-8be3-11e7-8d4e-a12cca868d8f.png)

On Linux (and presumably windows), because the mac closing button isn't present, the archives list looks to be quite far down the bar. What are your thoughts @sallar? If you like it we can leave it as is.

The mac ones sit quite close to the buttons:

![image](https://user-images.githubusercontent.com/3869469/29765415-c2ebcf92-8be3-11e7-8ea1-58ba6ee24899.png)

**Comment by sallar** [comment]
Thanks @perry-mitchell Thats definitely something that I should have done before.
