### ISSUE TITLE
Open archive after update

### ISSUE THREAD

**Issue by jprdev-paderick** [buttercup/buttercup-desktop#328]
After a update yesterday i cant't open my .bcup archive. I got this message: "Failed adding source: Authentification failed while decrypting content".
I'm sure that i used the right master password. And i don't had change anything at my computer.

**Comment by perry-mitchell** [comment]
Hi! That is unfortunate.. Do you have any other copies or history of the archive? If you use Dropbox or owncloud, for instance, you could restore older copies to try.

If none work or you have no older copies, could you download an older release and run that? If you disconnect from the internet to test to prevent auto updates, it should work fine.

Please let us know if it works..

**Comment by jprdev-paderick** [comment]
Hi, thanks for your fast answer. 
The archive is stored local and i havn't any backups. 
I had try the 0.18.0 release but it doen't work.

**Comment by perry-mitchell** [comment]
Ok.. well I guess I don't have to explain the likelihood to restoring a corrupt archive.. so I'm sorry if it turns out to be that way. Nevertheless.. can you open the archive with a text editor? Does it contain "buttercup" near the start?

You could paste some of the contents here if it's in string/hex form.. just not all of it of course.. first 50/100 chars should do.


Sent from my iPhone

**Comment by jprdev-paderick** [comment]
Here you can see a the beginning of the .bcup file:
`b~>buttercup/a3KjPbEbb510Cc2P0iejFGtNTUWbMkjRhGkfTIRiKGELrHaQMCQATJb5hzBOjeQE5x8s2PXyrbYY+sB`

how shoud the end of the file look like?

**Comment by perry-mitchell** [comment]
Well that actually looks normal and not corrupt. Things are looking better already.

I would suggest that you may have entered your password incorrectly at one critical juncture, but I'm not sure how that might be possible. Could you try with Caps etc? Do you have any alternate keyboard layouts?

Could you have overwritten your file when creating a new one?

**Comment by jprdev-paderick** [comment]
So i already had opened the archive by going to Admin Mode and enter the same password i had tried at least. 
I don't know why that works. 

Now I can open the archive, but its empty.

**Comment by perry-mitchell** [comment]
If you'd created a new archive with the same file name by any chance, it would've overridden it with an empty one. Impossible to tell if that's what happened here..

**Comment by sallar** [comment]
@jprdev-paderick Did you figure out the issue or is it still damaged / unavailable?

**Comment by jprdev-paderick** [comment]
it's still damage but i think it exist no way to get the lost entries back to the archive

**Comment by perry-mitchell** [comment]
Sorry to hear that @jprdev-paderick. We're looking in to ways to prevent corruption and accidental overwrites. We may add a built-in backup system soon. Hopefully you didn't lose anything too vital.
