### ISSUE TITLE
Incorrectly formatted error

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#330]
When logging in to a corrupted archive, for example, the error contains a `m:` at the beginning:

![image](https://user-images.githubusercontent.com/3869469/29940212-3125fe96-8e97-11e7-8810-61b023d88364.png)

**Comment by hd719** [comment]
Hey @perry-mitchell  can I work on this?

**Comment by sallar** [comment]
@hd719 you can :)

**Comment by hd719** [comment]
Hey @perry-mitchell so I got the application working locally and I created an archive how would I get the message above`m:Failed to unlock . . .`? 

-Thank you.

**Comment by perry-mitchell** [comment]
Hi. The error could be reproduced by simply typing the wrong password and trying to log in.

**Comment by hd719** [comment]
Hey @perry-mitchell so I am typed in the wrong password and instead I got this error not the one displayed above. 

<img width="1440" alt="screen shot 2017-09-23 at 10 22 38 am" src="https://user-images.githubusercontent.com/20329318/30773958-42d3298e-a049-11e7-9878-1bef58dea42a.png">

-Thank you.

**Comment by perry-mitchell** [comment]
Yep, but still looks like the same case. The error formatting is still a bit ugly. Thanks!

**Comment by snhasani** [comment]
@perry-mitchell You can assign it to me. Anyway I fixed already.
