### ISSUE TITLE
Broken UI on macOS High Sierra

### ISSUE THREAD

**Issue by 5k9m** [buttercup/buttercup-desktop#339]
Hey!

I just upgraded to macOS High Sierra (10.13) on my MacBook Pro Retina 13" Late 2013 and saw some issues concerning the design. See for yourself (black boxes were added to hide content):
![macos-high-sierra](https://user-images.githubusercontent.com/13706131/30834458-7d6c4830-a253-11e7-94b4-16e6ef35eba4.png)

**Comment by sallar** [comment]
@5k9m Thank you. this seems very odd. Maybe it's related to Electron itself? I'll investigate. But I have to first upgrade to High Sierra myself.

**Comment by perry-mitchell** [comment]
Thanks @5k9m. @sallar mentioned that this is related to electron/electron#10521. We're blocked until that gets resolved.

**Comment by perry-mitchell** [comment]
Recent tests on High Sierra have shown that there isn't an issue any longer.
