### ISSUE TITLE
Analytics version shows electron version on occasion

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#346]
The versions returned to the analytics have electron versions included on occasion, which is perhaps not necessary (and should be in a different variable if it is). [This issue](https://github.com/electron/electron/issues/7085) seems to be related to `app.getVersion()`.

**Comment by sallar** [comment]
@perry-mitchell It only happens when developing Buttercup in development. Before "building" Buttercup, the app is shown as "Electron". This can be fixed by checking if `process.env.NODE_ENV === 'development'` and not sending the event altogether.
