### ISSUE TITLE
'Condenced Sidebar' should be 'Condensed Sidebar'

### ISSUE THREAD

**Issue by ncguk** [buttercup/buttercup-desktop#347]
Hi. I've just discovered this project and one of the first things I noticed was that on the Mac version (and, I assume, other platforms), under the View menu, 'Condenced' should be spelled 'Condensed'. As I don't understand the code structure I don't want to submit a pull request for fear of missing something or messing something up.

**Comment by perry-mitchell** [comment]
Thanks for submitting. We’ll get this fixed shortly :)

**Comment by sallar** [comment]
@ncguc @perry-mitchell this is actually fixed and will come out in next release :) thanks!
https://github.com/buttercup/buttercup-desktop/commit/1863bd60f203897133255a7355aee3ba996ccd63
