### ISSUE TITLE
Share-able archives using QR code

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#349]
Add the ability to share archives by showing a QR code. The code modal/page could be presented by right-clicking on an **unlocked** archive.

Once requested, the QR code could be generated by using the following string:

`bcup-archive:1:credentialsHash`

Where **credentialsHash** is the output of securing a credentials instance using the master password. When scanned by the mobile app (or another application), the master password must be used to decrypt it and add it to the app.

**Comment by sallar** [comment]
@perry-mitchell isn't this a duplicate of #306?

**Comment by perry-mitchell** [comment]
Yes 😎
