### ISSUE TITLE
Analytics need sessions

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#350]
The analytics for desktop & mobile don't store any cookies/sessions, so every visit is "unique". Add storage or cookies to allow for smarter session tracking.

Related to buttercup/buttercup-mobile#44

**Comment by perry-mitchell** [comment]
Seems there are some extra parameters we can add from the documentation to help with tracking. One such item is `_id`, which is the unique visitor ID. Let's use the npm package [uuid](https://www.npmjs.com/package/uuid) to generate a random ID, store it locally, and use that in the analytics tracking.

We should also specify `rand` as a random number (cachebuster). Check out the [docs here](https://developer.piwik.org/api-reference/tracking-api#recommended-parameters).

**Comment by sallar** [comment]
Due to #362, this is not needed anymore. Closing.
