### ISSUE TITLE
Connected cloud source gets removed

### ISSUE THREAD

**Issue by ElPsyCongro** [buttercup/buttercup-desktop#354]
Hi, I'm using the 0.21.2 version on Windows and when I connect a cloud source and then relaunch Buttercup the cloud source gets removed and I have to add it again, I think this worked well in an earlier version but I do not remember. 
The same version on Mac works well. The cloud that I'm using is DropBox.

**Comment by danyfu** [comment]
Hi, same problem using 0.21.2 version on Windows, and using connect cloud source to Dropbox.

**Comment by perry-mitchell** [comment]
Hmm.. that’s interesting. Do you see any errors throughout the connection or usage of Dropbox?

**Comment by danyfu** [comment]
There is no error, when I use the connection using Dropbox I can work fine and everything is good, but if I close the windows app and reopen it, it opens like there is no connection before and then I need to set the connection to Dropbox again with the credentials.

**Comment by perry-mitchell** [comment]
That’s weird.. Dropbox should save using the same method as the others. Have you by any chance tested a local file or another cloud source?

**Comment by perry-mitchell** [comment]
Yeah it definitely seems to be reproducible. Before:

![image](https://user-images.githubusercontent.com/3869469/31649313-f120a9f6-b31a-11e7-9521-e81c08d08460.png)

After reloading:

![image](https://user-images.githubusercontent.com/3869469/31649360-258cf1ea-b31b-11e7-9b38-bf2742efaa48.png)

**Comment by sallar** [comment]
@ElPsyCongro @danyfu @perry-mitchell I'm working on an update, it will come through tonight hopefully. Could you guys please install that and let us know if it's fixed or not? If not, please re-open this issue (this will auto close by the PR). The version will be `0.21.3`

**Comment by danyfu** [comment]
Thanks @sallar, now its working fine. The Cloud Source persists when close and open the windows app.

👍

**Comment by ElPsyCongro** [comment]
I confirm that this issue was solved. Thanks to the team for the fast attention.
