### ISSUE TITLE
suppress analytics

### ISSUE THREAD

**Issue by krominet** [buttercup/buttercup-desktop#362]
hello,
please explain "Analytics - Anonymous launch statistics for counting active users over time." 
I don't want ANY communication between  my buttercup database and analytics server !

In my mind this is a potentially insecure funtion! and not conform with a passwords database !
Anonymity is not a sufficient condition for that.

**Comment by perry-mitchell** [comment]
Hi @krominet - I'm sorry you feel that way. Please understand that we do indeed only collect anonymous statistics, and at no point is there identifiable or secure data sent via analytics. We believe that we have an important use case for these analytics, so let me try to explain:

Buttercup, as a platform, is something that we want to expand - global usage (people in every country) would be great, and for this we need to know what the uptake is. These launch statistics tell us how many people are launching our applications so we can determine a few things in the near future:

 * Is this area showing significant growth - should we add additional localisation information?
 * Is this greater area in need of more server infrastructure?
 * Is there something wrong with this release/design and causing adoption to drop off?

In our eyes, that's a very good reason to have analytics (of the anonymous kind). You can also see in the [code](https://github.com/buttercup/buttercup-desktop/blob/2a907a6ecd01cdd2fa1723513a41e91217552460/src/main/actions.js#L63) that we don't send anything besides the anonymous statistics, and we do the sending in the NodeJS side away from the archives and other sensitive information.

**Comment by perry-mitchell** [comment]
Would having the analytics in the app be enough to stop you from using it? Would this be resolvable if the analytics had an opt-out feature? What about opt-in?

**Comment by krominet** [comment]
Hello,
Yes to be compliant with GDPR (European data protection law) :
- You need OPT-IN to manage consent and opposition right (art 21)
- You need OPT-OUT option to manage the "right to erasure" (art 17)

**Comment by perry-mitchell** [comment]
The GDPR is for personally identifiable data (and data collected about users), primarily, and is still very-much in its infancy. I do agree that user consent is necessary, and my colleagues and I have been working with this area for quite some time.

That being said, your issue did spark some good conversations today. We may indeed be dropping the analytics for now, and may revisit the topic at a later date if required. Rest assured that we won't be adding analytics packages in the future that do not have an opt-in procedure (clarification: analytics off by default).

Thanks for posting and we'll update you with how this goes shortly.

**Comment by krominet** [comment]
Thank's a lot !
I am happy by your positive attitude and i think your can be proud to manage the ButterCup project like that !

**Comment by sallar** [comment]
@krominet New version without analytics is out :)

**Comment by Rafi993** [comment]
Hi there how do I install version of butter cups without analytics ?

**Comment by perry-mitchell** [comment]
Buttercup does not use any analytics. Providers of the software might measure some metrics related to downloading and installing the software from their platform..
