### ISSUE TITLE
Error when saving a new entry with multiple empty fields and then close the application

### ISSUE THREAD

**Issue by pelonchasva** [buttercup/buttercup-desktop#363]
Hello again guys,

Today I faced two bugs in a row, let me explain how I found them:

First of all, I was adding a new entry, after entering a custom field I started adding more but these ones where empty because I thought I was going to need them, but I wasn't, so I just hited the save button just expecting that if the fields were empty, they weren't going to be saved, but just ignored. turns out, when I did that, this error popped up:

![buttercup-save-entry-empy-fields](https://user-images.githubusercontent.com/4713147/31789591-9cc13bf6-b4e0-11e7-9f9a-aedbe23df9ac.png)

So I just hitted the Ok button, the dialog closed, then I deleted all the blank fields and just leave those I had information, and then saved normally.

Finally, I closed the app because I wasn't going to use it anymore, and then this error popped up:

![buttercup-close-error](https://user-images.githubusercontent.com/4713147/31789660-d8450b44-b4e0-11e7-9075-96f8070b4975.png)

That's all I did in order to found this errors, if it is helpful, here is my PC specs and buttercup version:

**Buttercup Version**: 0.21.4
**OS**: Windows 10 64-Bit
**CPU**: Intel Core i3-3220 3.30GHz
**RAM**: 16GB
**SSD**: 240 GB

**Comment by perry-mitchell** [comment]
Hi @pelonchasva - Sorry for the inconvenience. This looks to be an issue with race conditions during saving. I can't think of anything else that might cause this. Saving slowly and waiting in between saves might help.

That noted, I've created some tasks to address this in a proper way, which may take a couple of days:

 * buttercup/buttercup-core#182 - Save debouncing

**Comment by sallar** [comment]
Closed by #400
