### ISSUE TITLE
Show menu bar once auto hide

### ISSUE THREAD

**Issue by lalitsom** [buttercup/buttercup-desktop#369]
Hey I am using this on windows 7 32 bit. I don't know if this is an actual issue or not.
How to show the menu bar again, once you hide it from menu bar->view->auto hide menubar?

**Comment by sallar** [comment]
@lalitsom I just tested it. You are right... it's "supposed" to come back when you hold the `alt` key (like normal windows apps) but it didnt happen for me. Does it come back when you hold alt?

**Comment by perry-mitchell** [comment]
> when you hold the alt key (like normal windows apps)

I'm not sure if holding is how it is normally.. At least I've always pressed it once to show the menu 😅

**Comment by lalitsom** [comment]
No it does not come back when I hold alt.
