### ISSUE TITLE
Cloud Source support for Citrix Sharefile?

### ISSUE THREAD

**Issue by ElPsyCongro** [buttercup/buttercup-desktop#370]
Hi, is there a possibility that you guys add support for this cloud source in the future?
https://www.citrix.com/products/sharefile/

**Comment by sallar** [comment]
@ElPsyCongro Hi! Like my colleague mentioned [here](https://github.com/buttercup/buttercup-desktop/issues/280#issuecomment-307188621), this depends on community interest. if someone is willing to put in the effort for the research etc, we'd appreciate it.

**Comment by perry-mitchell** [comment]
At this stage I think that we won't implement support for Sharefile - [They support WebDAV](https://support.citrix.com/article/CTX207863), so theoretically their services can already be used with Buttercup already. We'll be recording planned/pending/blocked cloud storage providers in the [roadmap](https://github.com/buttercup/roadmap/blob/master/roadmap/CLOUD_SERVICES.md).

We may reopen this issue at a later stage when we have more bandwidth, or if there are substantially more requests for Sharefile. Thanks!
