### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by regoremor** [buttercup/buttercup-desktop#372]
The links of the installer for Linux are broken on https://buttercup.pw/ and the link to receive a donation is broken too https://opencollective.com/buttercup-desktop/donate

**Comment by perry-mitchell** [comment]
Closing as this should be in the website repo. Thanks for letting us know @regoremor!

**Comment by perry-mitchell** [comment]
Where did you see that donate link @regoremor? Can't seem to find it.

**Comment by regoremor** [comment]
![screenshot from 2017-10-23 11-19-45](https://user-images.githubusercontent.com/9708927/31897384-38c539d4-b7e4-11e7-8981-5fa15c2819e2.png)
