### ISSUE TITLE
Grammar (extra text) on welcome screen.

### ISSUE THREAD

**Issue by the-wazz** [buttercup/buttercup-desktop#376]
buttercup-desktop/src/renderer/components/empty-view.js

the text: "You haven't added **have** any archives yet. Why not add one?"

possible updates:
"You haven't added any archives yet. Why not add one?"
or
"You don't have any archives yet. Why not add one?

**Comment by perry-mitchell** [comment]
Ah.. good catch.

I would personally prefer “You haven't added any archives yet. Why not add one?”, as you recommended.
