### ISSUE TITLE
new group directory disappear after focusout

### ISSUE THREAD

**Issue by snhasani** [buttercup/buttercup-desktop#379]
In MacOS app when you want to create a new group if after enter group name you focus out from input to somewhere else, group is not creating and group be disappear.

I think this is a UX issue and user should be able submit a group with focus out by tab, click or whatever it could.

**Comment by perry-mitchell** [comment]
Hi @snhasani - Thanks for posting. You're right, especially in OSX - focus-out does in fact complete the group/folder creation. I would agree that this would be desired behaviour.

**Comment by snhasani** [comment]
Hey @perry-mitchell , where I can find labels definition? Like `Status: Available`.

and I can fix this issue and you can assign me.

**Comment by perry-mitchell** [comment]
Hi @snhasani - I've assigned this to you. You can find the label definitions for Buttercup [here](https://github.com/buttercup/roadmap/blob/master/admin/LABEL_DEFINITIONS.md) (thanks for asking, I just added them).
