### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by sallar** [buttercup/buttercup-desktop#384]
I had Buttercup idle and closed my laptop lid. When I opened it back up a day after I saw this error:

![image](https://user-images.githubusercontent.com/768052/32242198-d4e5dff2-be7a-11e7-96de-b10ba1314ab6.png)

I'm guessing the update checker failed at some point and threw an error.

**Comment by perry-mitchell** [comment]
I guess it should fail silently?

**Comment by sallar** [comment]
Yes. We should just add a Noop handler
