### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by saderi** [buttercup/buttercup-desktop#389]
In Debian 9.0 getting the following error when launching buttercup-desktop 0.22.2 :
`Unhandled Promise Rejection
TypeError: Cannot read property 'catch' of undefined
    at checkForUpdates (/opt/Buttercup/resources/app.asar/dist/app.js:9013:82)
    at startAutoUpdate (/opt/Buttercup/resources/app.asar/dist/app.js:9004:3)
    at setupActions (/opt/Buttercup/resources/app.asar/dist/app.js:34106:97)
    at App.<anonymous> (/opt/Buttercup/resources/app.asar/dist/app.js:33940:89)
    at Generator.next (<anonymous>)
    at step (/opt/Buttercup/resources/app.asar/dist/app.js:33821:191)
    at /opt/Buttercup/resources/app.asar/dist/app.js:33821:361
    at <anonymous>`

**Comment by scharepmc2hr** [comment]
I'm also getting the similar error on Manjaro after this:
> ava && npm run lint

**Comment by aproposnix** [comment]
Same thing in Ubuntu 17.04

> Unhandled Promise Rejection
> TypeError: Cannot read property 'catch' of undefined
>     at checkForUpdates (/opt/Buttercup/resources/app.asar/dist/app.js:9013:82)
>     at startAutoUpdate (/opt/Buttercup/resources/app.asar/dist/app.js:9004:3)
>     at setupActions (/opt/Buttercup/resources/app.asar/dist/app.js:34106:97)
>     at App.<anonymous> (/opt/Buttercup/resources/app.asar/dist/app.js:33940:89)
>     at Generator.next (<anonymous>)
>     at step (/opt/Buttercup/resources/app.asar/dist/app.js:33821:191)
>     at /opt/Buttercup/resources/app.asar/dist/app.js:33821:361
>     at <anonymous>

**Comment by gellenburg** [comment]
Same for Windows 10.0.16299 (Fall Creator's Update):

![untitled](https://user-images.githubusercontent.com/7026750/32664834-6debd5da-c600-11e7-97fc-32d5aae3ffe9.png)

**Comment by sallar** [comment]
@gellenburg Are you sure this is the same error? Does Buttercup work normally regardless of this?

**Comment by pomeroythomas** [comment]
![image](https://user-images.githubusercontent.com/16737111/66003387-34c91780-e463-11e9-86cb-26399ee74dc2.png)
I'm still getting this now on the latest Windows update.

**Comment by perry-mitchell** [comment]
Happy to take PRs on these.. we can’t seem to reproduce this, at least not reliably.
