### ISSUE TITLE
Can't connect to Nextcloud instance

### ISSUE THREAD

**Issue by moulip** [buttercup/buttercup-desktop#395]
Hi,

I have installed both buttercup-desktop and Android App, and i can't connect to my Nextcloud instance from both of them.
I get "Network request failed on Android" and "Connection to https://xxxxxx/remote.php/webdav failed. Please check your credentials and try again."

In the server logs no attempt to connect is visible.

**Comment by perry-mitchell** [comment]
Are you using the Nextcloud archive type? If so, you need only put `https://xxxxxx`, without the `remote.php/webdav` section. If you use **webdav**, however, you would keep that suffix.

Also, while I'm asking, are you by any chance using a self-signed SSL cert?

**Comment by moulip** [comment]
Hi 
I have tried using the url with or without the suffix. Nothing changes. I'm using a cacert certificate but I don't have the ca in the system but I have it in the browser. 


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Perry Mitchell <notifications@github.com> Date : 11/11/2017  21:35  (GMT+01:00) À : buttercup/buttercup-desktop <buttercup-desktop@noreply.github.com> Cc : moulip <julien@technoaddict.fr>, Author <author@noreply.github.com> Objet : Re: [buttercup/buttercup-desktop] Can't connect to Nextcloud instance (#395) 
Are you using the Nextcloud archive type? If so, you need only put https://xxxxxx, without the remote.php/webdav section. If you use webdav, however, you would keep that suffix.
Also, while I'm asking, are you by any chance using a self-signed SSL cert?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buttercup/buttercup-desktop","title":"buttercup/buttercup-desktop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buttercup/buttercup-desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@perry-mitchell in #395: Are you using the Nextcloud archive type? If so, you need only put `https://xxxxxx`, without the `remote.php/webdav` section. If you use **webdav**, however, you would keep that suffix.\r\n\r\nAlso, while I'm asking, are you by any chance using a self-signed SSL cert?"}],"action":{"name":"View Issue","url":"https://github.com/buttercup/buttercup-desktop/issues/395#issuecomment-343692411"}}}

**Comment by perry-mitchell** [comment]
Ok, so you're using a recognised SSL certificate vendor, like Verisign or Geotrust, for example?

**Comment by moulip** [comment]
No it's a cacert.org.



Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Perry Mitchell <notifications@github.com> Date : 11/11/2017  22:14  (GMT+01:00) À : buttercup/buttercup-desktop <buttercup-desktop@noreply.github.com> Cc : moulip <julien@technoaddict.fr>, Author <author@noreply.github.com> Objet : Re: [buttercup/buttercup-desktop] Can't connect to Nextcloud instance (#395) 
Ok, so you're using a recognised SSL certificate vendor, like Verisign or Geotrust, for example?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buttercup/buttercup-desktop","title":"buttercup/buttercup-desktop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buttercup/buttercup-desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@perry-mitchell in #395: Ok, so you're using a recognised SSL certificate vendor, like Verisign or Geotrust, for example?"}],"action":{"name":"View Issue","url":"https://github.com/buttercup/buttercup-desktop/issues/395#issuecomment-343694637"}}}

**Comment by perry-mitchell** [comment]
Ok, well this is an interesting problem. Could you perhaps try a demo account at [https://demo.nextcloud.com](https://demo.nextcloud.com)? We'll be doing the same to check if there are any issues that have cropped up in say a recent update..

**Comment by moulip** [comment]
Yes that's what I wanted to do. I'll keep you posted. 


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Perry Mitchell <notifications@github.com> Date : 12/11/2017  10:45  (GMT+01:00) À : buttercup/buttercup-desktop <buttercup-desktop@noreply.github.com> Cc : moulip <julien@technoaddict.fr>, Author <author@noreply.github.com> Objet : Re: [buttercup/buttercup-desktop] Can't connect to Nextcloud instance (#395) 
Ok, well this is an interesting problem. Could you perhaps try a demo account at https://demo.nextcloud.com? We'll be doing the same to check if there are any issues that have cropped up in say a recent update..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buttercup/buttercup-desktop","title":"buttercup/buttercup-desktop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buttercup/buttercup-desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@perry-mitchell in #395: Ok, well this is an interesting problem. Could you perhaps try a demo account at [https://demo.nextcloud.com](https://demo.nextcloud.com)? We'll be doing the same to check if there are any issues that have cropped up in say a recent update.."}],"action":{"name":"View Issue","url":"https://github.com/buttercup/buttercup-desktop/issues/395#issuecomment-343724923"}}}

**Comment by moulip** [comment]
So it appears that it's working with demo.owncloud.com. I don't get what possibly could be wrong with me setup. I have checked the webdav url and it's the same. I can connect to my nextcloud instance using a davs client.

**Comment by perry-mitchell** [comment]
Interesting.. Have you considered my other proposals? 🙂

**Comment by moulip** [comment]
What other proposals? The ones regarding the url? 


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Perry Mitchell <notifications@github.com> Date : 12/11/2017  19:50  (GMT+01:00) À : buttercup/buttercup-desktop <buttercup-desktop@noreply.github.com> Cc : moulip <julien@technoaddict.fr>, Author <author@noreply.github.com> Objet : Re: [buttercup/buttercup-desktop] Can't connect to Nextcloud instance (#395) 
Interesting.. Have you considered my other proposals? 🙂




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buttercup/buttercup-desktop","title":"buttercup/buttercup-desktop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buttercup/buttercup-desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@perry-mitchell in #395: Interesting.. Have you considered my other proposals? 🙂\r\n"}],"action":{"name":"View Issue","url":"https://github.com/buttercup/buttercup-desktop/issues/395#issuecomment-343758229"}}}

**Comment by perry-mitchell** [comment]
> What other proposals? 

> If we still can't get it to work, then we have a couple of options. One, you can try to debug a bit further by digging into the code (running the project in dev) as it's trying to connect. Two, you could open up a temporary account on your server that I could debug with (You could share it to me using Keybase, for instance).

😊

**Comment by moulip** [comment]
Do you use GPG ? I could send you the credentials by encrypted mail.

**Comment by perry-mitchell** [comment]
Ok, so using just the webdav component I get the following error, even after you changed the certificates:

```
{ FetchError: request to https://address/remote.php/webdav/ failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/Users/perry/git/webdav-client/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:385:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://address/remote.php/webdav/ failed, reason: unable to verify the first certificate',
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

So for some reason it seems like the certificates aren't accepted by our client. Will keep looking into this.

**Comment by moulip** [comment]
Ok. Problem fixed. I have changed my SSL provider for LetsEncrypt, and then I have replaced the first certificates by the full chain with the intermediate embedded.
Thank you for the time you have spent on my issue.

**Comment by perry-mitchell** [comment]
Thanks for following up @moulip, and as well for the opportunity to debug using your live server. Hopefully this remains a working solution for you, and it's help highlight the fact that we need some kind of SSL bypass in Buttercup (#398).

All the best!
