### ISSUE TITLE
Hubic archive access

### ISSUE THREAD

**Issue by Xavier73** [buttercup/buttercup-desktop#396]
Hi the Buttercup community,

I did not find any information about Hubic support for archive access in the roadmap.

Such as Dropbox archive access feature #40, it's seem the same procedure to connect at Hubic cloud (OVH) services. Hubic have a [API](https://api.hubic.com/) based on OAuth2 like Dropbox API.

I can implement this feature and his tests if you want ?

I already started looking around the [Buttercup-Core](https://github.com/buttercup/buttercup-core/) code which manage credentials and tokens necessary for OAuth2 authentication, do you confirm ?

**Comment by perry-mitchell** [comment]
Hi @Xavier73 - Thanks for taking an interest in adding support for new features. Often times we'll jump at the chance to have functionality added to Buttercup, but the cloud services are a bit different. They're integrations and as such contribute to the overall image of Buttercup as a brand. In my opinion, Hubic is not as mature as I would have hoped, and the reviews I've read are mixed at best.

At this stage I would say that we don't currently want to integrate with Hubic. To clarify this process for future queries, I've created a [roadmap document for our cloud services](https://github.com/buttercup/roadmap/blob/master/roadmap/CLOUD_SERVICES.md).

If Hubic supports a protocol that Buttercup already uses, like WebDAV, I would suggest using that to connect your archives. I'm sorry for any inconvenience this might cause, but I hope that you can understand our caution around these integrations. We have to stand by them and maintain each and every one throughout the life of Buttercup as a platform - and this raises the entry bar to quite a strict level.

**Comment by Xavier73** [comment]
I did not read this roadmap, shame on me... I understand, and as you say Hubic is not mature enough. The paradox is that Hubic no longer supports WebDAV, that's why I wanted to add Hubic brick to ButterCup, no worry.

So this issue can be closed, thank you :)

**Comment by perry-mitchell** [comment]
Thanks for understanding. I've been discussing with my colleague that there may be a future possibility here using a plugin-like infrastructure, but we don't have bandwidth to dig into that right at this moment.

All the best!
