### ISSUE TITLE
Add possibility to lock the archive in desktop app

### ISSUE THREAD

**Issue by moulip** [buttercup/buttercup-desktop#399]
The mobile app and Firefox extension, allow to lock the archive, whereas in the desktop one, once you have entered the master password, you can't lock the archive without completely closing the app.
Is there something I'm missing ?

**Comment by perry-mitchell** [comment]
Nope! We definitely need this functionality. There is actually already an issue for this: #375..

Thanks @moulip :smile:

**Comment by moulip** [comment]
Great !
