### ISSUE TITLE
"About" Buttercup not available when menu not present

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#408]
On Ubuntu, for instance, there's no menu that provides the "About" screen.

**Comment by perry-mitchell** [comment]
Raising the prio due to the fact that there's no way to "Check for updates".

**Comment by sallar** [comment]
@perry-mitchell check for update is there actually

![image](https://user-images.githubusercontent.com/768052/36904737-34bb051e-1e3a-11e8-8fa7-401d3334570a.png)

But "about" is not. Adding that + adding more items to tray in an upcoming PR
