### ISSUE TITLE
Can't type more than one caracter at a time in Version 0.24.0 (0.24.0)

### ISSUE THREAD

**Issue by fmommeja** [buttercup/buttercup-desktop#410]
Hi, after you merged my translation contribution, I updated to Version 0.24.0 (0.24.0) and since then every time I want to type something in any input field, I can't type more than one caracter at a time.
I have to clik on the field again to be able to type a second one and so on…

Buttercup Version 0.24.0 (0.24.0) on MacOSX 10.9.5 Build 13F1911 - Intel Core i7 RAM 16 Go

Thanks
Frederic

**Comment by perry-mitchell** [comment]
Yes, just saw this:

> When typing info into a new entry, focus is lost immediately:

![entry_bcup_broken](https://user-images.githubusercontent.com/3869469/32898943-4033dd30-caf2-11e7-9a5b-df068c7b5499.gif)

**Comment by perry-mitchell** [comment]
I did notice this on 0.23.0 as well, so I'm not sure when it was introduced..

**Comment by perry-mitchell** [comment]
It *might* be to do with the react-intl package and the redux forms. There's a couple of [issues](https://github.com/erikras/redux-form/issues/3591) hinting towards that.

**Comment by ph1p** [comment]
Fast fix: Comment out uglifyJs and build it again.

**Comment by perry-mitchell** [comment]
@ph1p That's what we did. Thanks guys!!

**Comment by perry-mitchell** [comment]
Fixed in 0.24.1
