### ISSUE TITLE
Update fails on some connections

### ISSUE THREAD

**Issue by sallar** [buttercup/buttercup-desktop#416]
When the app is trying to auto-update, sometimes an error is thrown and the update is cancelled.

**v0.22.3** 
I don't know if this happens on higher versions or not.

Restarting the app several times seems to fix the issue. We need to attach an error handler to the download event.

<img width="1083" alt="screen shot 2017-11-17 at 11 33 54" src="https://user-images.githubusercontent.com/768052/32940467-618e0480-cb8b-11e7-880c-813ff43a4584.png">
<img width="583" alt="screen shot 2017-11-17 at 11 31 43" src="https://user-images.githubusercontent.com/768052/32940468-61a61a8e-cb8b-11e7-9514-10e0bc01851e.png">

**Comment by ph1p** [comment]
I got this error a while ago.
Can't reproduce it. 
![zipfailure](https://user-images.githubusercontent.com/15351728/32982017-ed4e345c-cc7d-11e7-9b31-db3fd3983e30.png)

**Comment by sallar** [comment]
@ph1p Yeah.. I have seen it also.

**Comment by perry-mitchell** [comment]
I think this should be solved by adding a couple of features:

 * Timeout on the fetch/network request (something sane, like 15 seconds)
 * Logged error when it fails
 * No error shown to the user
