### ISSUE TITLE
Detect system language

### ISSUE THREAD

**Issue by sallar** [buttercup/buttercup-desktop#417]
It would be nice if Buttercup could detect the user's OS language and set the language based on that automatically (if available) or fall back to English.

This package can be used: https://github.com/sindresorhus/os-locale

**Comment by brajabi** [comment]
Happy to give it a hand tonight! 😃

**Comment by yasharAyari** [comment]
why don't you use 'i18next' instead of 'os-locale' ? we implement it on [lisk-nano](https://github.com/LiskHQ/lisk-nano/) and it works very well. I can implement the same structure in your app , if you want.

**Comment by perry-mitchell** [comment]
@yasharAyari i18next looks a bit bloated when compared to os-locale. We already have the translation functionality working, all we need is the detection of the _current_ locale on the user's machine.

**Comment by yasharAyari** [comment]
i18next has no dependency you can use it on the your electron app and on your react app. it has a react [addon](https://github.com/i18next/react-i18next). So you use same library on electron and react for translation.

**Comment by sallar** [comment]
@yasharayari we are already using `react-intl`. This issue is just about “detecting” user’s language instead of setting it to English by default.
