### ISSUE TITLE
"Move to Root" of a folder already in root possible and error on following ctrl+z / undo

### ISSUE THREAD

**Issue by violoncelloch** [buttercup/buttercup-desktop#421]
Hi, I just downloaded Buttercup and importet a keepass file and then I accidentally stumbled upon the follwing situation:

If I right klick on a folder already in root and chose "Move to Root" the Folder is gone to nowhere. On a ctrl+z / undo then, the following error appears:

`Unhandled Error
TypeError: Cannot read property 'style' of null
    at hide (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:62006:7)
    at Function.sweetAlert.resetValidationError (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:62955:7)
    at HTMLInputElement.input.oninput (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:61841:16)`

Luckily after a restart of Buttercup, the folder appears again on root level.
I think the option "Move to Root" shouldn't even be selectable on a folder already in root directory...?
I hope I can help tracking down the issue. I hope I'm at the right place here on buttercup-desktop repo.

Win 10
Buttercup v0.24.1

**Comment by perry-mitchell** [comment]
Confirmed.. Seems there's a UI glitch here. You're right in that the menu option should not be available. The archive data should always be fine though - At most it should throw an error and no changes be made.
