### ISSUE TITLE
<localisations> Untranslated password tips&hints

### ISSUE THREAD

**Issue by RakotStargazer** [buttercup/buttercup-desktop#433]
There's some untranslated parts in tips&hints, at least when editing an entry all password-related hints are in english regardless of the selected language, pls see screenshots.
Unfortunately I couldn't find these sentences in the code, so I've no idea how to fix it.

![2017-11-19_21-14-21](https://user-images.githubusercontent.com/33731754/33036406-54d8fe32-ce3f-11e7-8b5f-9303bf7ab1c2.png)
![2017-11-20_22-15-16](https://user-images.githubusercontent.com/33731754/33036717-5430b79e-ce40-11e7-8e5e-65e37574057c.png)

**Comment by perry-mitchell** [comment]
Thanks @RakotStargazer - Good observation.

This has been mentioned in the original [localisation PR comments](https://github.com/buttercup/buttercup-desktop/pull/397#issuecomment-344228351): Basically the password generator and some other components, are external and need separate localisation support. For instance, I've added a task on the generator [here](https://github.com/buttercup/buttercup-generator/issues/8). I'll close this issue as it has to do with the other components.

**Comment by RakotStargazer** [comment]
@perry-mitchell don't think these parts related to password generator. PG have it's own pop-up window, and it's untranslated, yes, but the password field tips isn't part of the generator. btw I couldn't find these sentences in ALL the Buttercup's github code (you can try to find the word "Uncommon" for example). It have to be related to some external code that checks if password secure enough. All that I've found today that this is most likely the result from result.feedback.suggestions from buttercup-ui/src/components/meter.js
 
![2017-11-20_23-42-25](https://user-images.githubusercontent.com/33731754/33040582-8765e8a8-ce4c-11e7-9d31-fae6eff96162.png)

**Comment by RakotStargazer** [comment]
aaaaaand finally after some investigation - these tips are from zxcvbn function (https://www.npmjs.com/package/zxcvbn)
