### ISSUE TITLE
Support tray-icon/background mode in Windows/Linux

### ISSUE THREAD

**Issue by Akimace** [buttercup/buttercup-desktop#444]
Hello,
There is possibility to minimise in windows toolbar ? Like internet access icon

**Comment by perry-mitchell** [comment]
Hello again @Akimace - Do you mean like a tray icon? Like this:

![image](https://user-images.githubusercontent.com/3869469/33381309-53c42e98-d526-11e7-953d-41c62f28807c.png)

**Comment by Akimace** [comment]
@perry-mitchell Yes, like this

**Comment by perry-mitchell** [comment]
Not currently no.. But it's something we may want to explore for Windows/Linux users.

**Comment by sallar** [comment]
@Akimace Out of curiosity, what is the behavior for the apps that do this? What do you need to do to an app so it ends up there? And what happens when you click on it?

**Comment by perry-mitchell** [comment]
@sallar I guess it would have to operate very similarly to the mac one. Mac runs as a daemon when closed unless it's forced to close. That allows for quick start up and I presume continual execution in the background even when no windows are shown.

On windows you could have the same, plus a context menu that could potentially look like:

 * **Show Buttercup**
 * Lock all archives
 * Quit

**Comment by sallar** [comment]
@perry-mitchell so it's similar to running in macOS dock then?

**Comment by n8v8R** [comment]
Looking forward of this being implement. There is no need for BC to occupy space on the taskbar, a tray icon would be neat indeed, option to tray on minimize and/or close.

![tray option](https://user-images.githubusercontent.com/13611490/35914076-32fd6ea0-0c02-11e8-9bde-c19667886303.PNG)

And to auto-start upon OS boot
