### ISSUE TITLE
Can't hide menu bar in Ubuntu

### ISSUE THREAD

**Issue by Hedronmx** [buttercup/buttercup-desktop#447]
Could it be possible to add the option to hide the menu bar?
Thanks!

**Comment by sallar** [comment]
@Hedronmx There is an option already in Buttercup: `View -> Auto-Hide Menubar`
does that work for you?

**Comment by Hedronmx** [comment]
I see no Auto-Hide Menu bar option anywhere.
Any ideas?
![image](https://user-images.githubusercontent.com/26935602/33616826-e87c3f74-d992-11e7-8a66-06411f1f5137.png)

**Comment by sallar** [comment]
@Hedronmx true! I will fix this in next release :)
