### ISSUE TITLE
Initially hide password when editing entry

### ISSUE THREAD

**Issue by reddo** [buttercup/buttercup-desktop#456]
Hi,

Love the app! I have a suggestion though: when clicking to edit an entry, the password is shown unobfuscated; I would prefer it to be hidden (just as a password field is) and having to click a button or icon to reveal, maybe even having to enter the master password again (as chrome does). I think it would be more secure this way, we don't always want to edit or see the password, just the title or some other field and having the password visible is insecure.

**Comment by perry-mitchell** [comment]
It could even be on hover, for instance.. there are a variety of options for this.

**Comment by reddo** [comment]
Asking for master password when trying to unhide would be preferred though 🤓

**Comment by perry-mitchell** [comment]
> Asking for master password when trying to unhide would be preferred though 🤓

I think that this would be overkill.. You've already unlocked the archive.. no point in _unlocking_ something else a second time.

**Comment by reddo** [comment]
You got a point here. :)
