### ISSUE TITLE
Unable to Import

### ISSUE THREAD

**Issue by michaelcurry** [buttercup/buttercup-desktop#458]
For some reason, I am unable to import password archives.  No open window pops up, and I don't see any other way to do this.  I can not simply "open archive" my 1Password file either.

Is this something on my end? OR is this a real problem with the current build? (v0.25.1)

![image](https://user-images.githubusercontent.com/2658933/34011754-fac39940-e0c5-11e7-9d6f-be720b940cb2.png)

**Comment by perry-mitchell** [comment]
Hi @michaelcurry - This is interesting. I can currently open the dialog just fine:

![image](https://user-images.githubusercontent.com/3869469/34013127-f49b90be-e11e-11e7-867e-fe7be6bfb9d4.png)

(After selecting 1password:)

![image](https://user-images.githubusercontent.com/3869469/34013165-10944626-e11f-11e7-90ae-c92fe5ea3e81.png)

Do you have an archive unlocked while trying this?

**Comment by michaelcurry** [comment]
Thanks for the quick reply @perry-mitchell 

I understand the issue now! You must have an archive created before you can import!

I was unaware that you would be importing TO an archive.  I thought you could Import and it would Create a new archive.

I think a great action item would be to add "create new archive" from the import list OR at least have  info there saying you have to import into an existing archive

**Comment by sallar** [comment]
@michaelcurry having the menu "say something" maybe in grayed out text would be nice to guide the user. I agree this is a bit confusing. Thanks!

**Comment by perry-mitchell** [comment]
What about even changing the "Import" label to "Import into existing archive"?

**Comment by michaelcurry** [comment]
Yeah, I think that would work great!

Thanks for the quick replies, and great product! I am glad someone is finally making a production quality Cross-Platform password manager.  🥇
