### ISSUE TITLE
Portuguese-BR translation

### ISSUE THREAD

**Issue by GabrielCoelho** [buttercup/buttercup-desktop#463]
Hey, I'm an enthusiast of electron but never put my hands in any electron project. So the Buttercup came up in my discover feed and I like it so much. As i cannot help so much with new features, my first show up here is for an pt-br Translation. 

## What I've already did

 - Created a new folder named "pt-br" with a file inside (base.json) with all translations.
 - Added the "pt-br" in the locales/config.json with the name of the language (as known world wide)

## What should I do know?

After those steps above, I've runned the cli command: "npm install" and "npm run start" to test the translation. The "pt-br" language is there but, when I click to change the language, nothing happens (even if I reload or Force Reload the app). 

It seems that I'm missing some instruction or some step to do.

* * *
hope you all can help me in this little issue. And I'm sorry, _in advance_, if there's any grammatical mistake. I'm still learning English (I can understand more than I can talk or write).

**Comment by perry-mitchell** [comment]
Hi @GabrielCoelho! Thanks for creating an issue for this. We'd be keen to help you get this addition into the application.

I think the best way from here would be to actually create a PR with your changes which we could review and test. This way we can find what the issue may be a lot faster, and you can see first hand what's needed to get it into the desktop application.

How does that sound?
