### ISSUE TITLE
Lock open archive with keyboard shorcut

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [buttercup/buttercup-desktop#470]
Hello!

Is it possible to add a keyboard shortcut as `ctrl+l` to lock an open archive?

**Comment by sallar** [comment]
Thanks @FlorentinDUBOIS this is a great idea.

**Comment by brooksbecton** [comment]
Hello! I would like to try this. 

I know I can listen for the key press with this code and then probably set off an action to lock the program, but I wasn't sure where the best spot for the event to start listening at would be 

```js
 window.addEventListener("keydown", function (e) {
   if(e.keyCode === 76 && (e.ctrlKey || e.metaKey)){
     // Lock
   }
 })
```

Thanks

**Comment by sallar** [comment]
Hi there!
We have a file for that: https://github.com/buttercup/buttercup-desktop/blob/master/src/renderer/system/shortcuts.js

You can add a shortcut here and use redux and  `getArchiveManager()` to find the active archive and lock it. 

Thanks!

**Comment by brooksbecton** [comment]
Working on it in #493
