### ISSUE TITLE
Delete old Buttercup update files periodically

### ISSUE THREAD

**Issue by umutkacar** [buttercup/buttercup-desktop#475]
Whenever my hard drive runs out of space, I check what's consuming space with WinDirStat.

I encountered severaltimes that Buttercup setup files indeed, fills up the disk.

On **C:\Users\<username>\AppData\Local\Temp** , there are lots of folders with prefix **up-** and under them, there are several files like **buttercup-desktop-setup-0.25.1.exe**  (78 folders with 78 files, totaling 4,88GB)

I clean them once in a while but they keep re-appearing.

What can we do about this?

**Comment by sallar** [comment]
Hi @umutkacar That is very unusual. I will look that up. Thank you.

**Comment by perry-mitchell** [comment]
@sallar @umutkacar I've updated the details of this issue to make it a feature.
