### ISSUE TITLE
'Sort by Title' is sorting lowercase apart from uppercase

### ISSUE THREAD

**Issue by carlmrichter** [buttercup/buttercup-desktop#476]
When sorting the entries in a group the sorting **algorithm differentiates between lowercase and uppercase** entries. Maybe it is just me, or the german habit of capital letters, but that is pretty annoying.
If you want a alphabettically sorted list, you **have to (re)name the entries** either just lowercase letters or just uppercase letters.

Maybe just give the user the option to choose between ignoring capital letters or not?

In my opinion, this could easily be fixed by transforming all strings to lowercase before sorting.

**Comment by sallar** [comment]
Thanks @carlmrichter, I should have ignored casing before sorting. I will fix that.

**Comment by alireza-ahmadi** [comment]
@sallar I like to send a Pull Request for this, does this issue been resolved?

**Comment by sallar** [comment]
@alireza-ahmadi it's available. Feel free to take it :)

**Comment by alireza-ahmadi** [comment]
@sallar Great, should lowercasing items only get applied to entries or it should get applied to the groups as well?

**Comment by sallar** [comment]
@alireza-ahmadi there is a generic sort function on buttercup, it can be done there so its applied everywhere
