### ISSUE TITLE
Check for updates menu does not do anything

### ISSUE THREAD

**Issue by moulip** [buttercup/buttercup-desktop#478]
Hi,

In the desktop app, the Help menu has a "Check for Updates" function. When I click on it, nothing is happening, even if there are some updates available.

**Comment by sallar** [comment]
Hi @moulip 
Could you please paste some parts of Buttercup log here so we can debug?

+ on Linux: ~/.config/Buttercup/log.log
+ on OS X: ~/Library/Logs/Buttercup/log.log
+ on Windows: %USERPROFILE%\AppData\Roaming\Buttercup\log.log

**Comment by moulip** [comment]
Hi Sallar,

Please find the logs below. Also please note I'm using Debian Buster
and I have of course the latest Buttercup version.

[2018-01-05 18:48:35:0581] [info] Checking for update
[2018-01-05 18:48:35:0591] [error] Error: Error: ENOENT: no such file
or directory, open '/opt/Buttercup/resources/app-update.yml'
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace]
(/opt/Buttercup/resources/app.asar/dist/app.js:71319:19)
    at new PromiseSpawn
(/opt/Buttercup/resources/app.asar/dist/app.js:73289:17)
    at /opt/Buttercup/resources/app.asar/dist/app.js:73443:21
    at AppImageUpdater._checkForUpdates
(/opt/Buttercup/resources/app.asar/dist/app.js:8884:11)
    at AppImageUpdater.checkForUpdates
(/opt/Buttercup/resources/app.asar/dist/app.js:8830:39)
    at checkForUpdates
(/opt/Buttercup/resources/app.asar/dist/app.js:31842:67)
    at startAutoUpdate
(/opt/Buttercup/resources/app.asar/dist/app.js:31832:3)
    at setupActions
(/opt/Buttercup/resources/app.asar/dist/app.js:95764:82)
    at App.<anonymous>
(/opt/Buttercup/resources/app.asar/dist/app.js:37014:74)
    at Generator.next (<anonymous>)
    at step (/opt/Buttercup/resources/app.asar/dist/app.js:36895:191)
    at /opt/Buttercup/resources/app.asar/dist/app.js:36895:361
    at <anonymous>

**Comment by sallar** [comment]
@moulip Thanks. Your issue looks like this:
https://github.com/electron-userland/electron-builder/issues/2364
I'll investigate.

**Comment by sallar** [comment]
Hi @moulip, can you try updating to v1.0.1 manually to see if this issue is still there?

**Comment by moulip** [comment]
Hi Sallar,
Sure will do. I'll keep you posted.


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Sallar Kaboli <notifications@github.com> Date : 11/02/2018  11:51  (GMT+01:00) À : buttercup/buttercup-desktop <buttercup-desktop@noreply.github.com> Cc : moulip <julien@technoaddict.fr>, Mention <mention@noreply.github.com> Objet : Re: [buttercup/buttercup-desktop] Check for updates menu does not do anything (#478) 
Hi @moulip, can you try updating to v1.0.1 manually to see if this issue is still there?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buttercup/buttercup-desktop","title":"buttercup/buttercup-desktop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buttercup/buttercup-desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sallar in #478: Hi @moulip, can you try updating to v1.0.1 manually to see if this issue is still there?"}],"action":{"name":"View Issue","url":"https://github.com/buttercup/buttercup-desktop/issues/478#issuecomment-364742135"}}}

**Comment by moulip** [comment]
Hi Sallar,

Yes still there.

**Comment by sallar** [comment]
@moulip By the way, are you using Linux?

**Comment by moulip** [comment]
Of course what else ?;-)


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Sallar Kaboli <notifications@github.com> Date : 20/02/2018  22:43  (GMT+01:00) À : buttercup/buttercup-desktop <buttercup-desktop@noreply.github.com> Cc : moulip <julien@technoaddict.fr>, Mention <mention@noreply.github.com> Objet : Re: [buttercup/buttercup-desktop] Check for updates menu does not do anything (#478) 
@moulip By the way, are you using Linux?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buttercup/buttercup-desktop","title":"buttercup/buttercup-desktop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buttercup/buttercup-desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sallar in #478: @moulip By the way, are you using Linux?"}],"action":{"name":"View Issue","url":"https://github.com/buttercup/buttercup-desktop/issues/478#issuecomment-367130345"}}}

**Comment by sallar** [comment]
Which file did you use to install Buttercup? Currently only the AppImage provides auto-updating

**Comment by moulip** [comment]
I used the *.deb available on your website.

**Comment by sallar** [comment]
@moulip That makes sense. I think our auto-update only supports AppImage on Linux. Can you give that a try?

**Comment by moulip** [comment]
Yeah sure but can you explain what AppImage is please ?

**Comment by sallar** [comment]
@moulip It's this one: https://github.com/buttercup/buttercup-desktop/releases/download/v1.2.2/buttercup-desktop-1.2.2-x86_64.AppImage 
It's usually found from the releases page. I think we need to do a better job at clarifying this.

**Comment by perry-mitchell** [comment]
@moulip There are several linux install methods available:

 * deb/rpm: Packages which are executed by the OS' package manager
 * AppImage: Executable installer compatible with most Linux flavours (sometimes needs to be run from CLI)
 * [Snap](https://www.ubuntu.com/desktop/snappy): Self-proclaimed universal linux packages

**Comment by moulip** [comment]
Thx Perry.

**Comment by moulip** [comment]
So I have just installed the AppImage (and remove the previous *.deb
setup). And as per the following logs, it seems to work now:

[2018-02-21 18:04:16:0777] [info] Checking for update
[2018-02-21 18:04:17:0640] [info] Update for version 1.2.2 is not
available (latest version: 1.2.2, downgrade is disallowed.

Thank you

**Comment by GGShinobi** [comment]
I am using Ubuntu 18.04 and I am trying to install Buttercup. At first, I installed it via the .deb file from the homepage. That gave me  same error message about app-update,yml not being found. Also, I couldn't create any new archives with that version (it only created the directories). So I searched for the error on the internet and found this page.
I therefore uninstalled the .deb version and downloaded the latest AppImage (Buttercup-1.19.0-i386.AppImage).
I made it executable by typing
chmod a+x Buttercup-1.19.0-i386.AppImage

But when I try to run it via
./Buttercup-1.19.0-i386.AppImage
I 
bash: ./Buttercup-1.19.0-i386.AppImage: No such file or directory

Note that this is my first time using AppImages. I have the feeling I'm plain stupid and miss something obvious here. Can you help me?

**Comment by mmirabetti** [comment]
Same here... Also Ubuntu 18.04

**Comment by rayj-pgi** [comment]
same
