### ISSUE TITLE
Attachments support

### ISSUE THREAD

**Issue by AndreyIvanovSetronica** [buttercup/buttercup-desktop#484]
What about to have the ability to attach some files like archives, secret keys etc? In my opinion it is necessary for such application.

**Comment by perry-mitchell** [comment]
Please watch your tone @tiaga.. No need for that kind of attitude here.

We don't have attachment support because it hasn't been developed yet. I think it's definitely a must-have feature but we haven't yet landed on a way to implement it in a way that is:
 1. Future proof (so we don't support an undesirable system)
 2. Well performing (doesn't decrease archive decryption speed)
 3. Secure

When we have such an implementation, it must first be developed in the core library before being supported here.

**Comment by tgoncuoglu** [comment]
tiaga's tone not withstanding, I too believe this is a must-have feature. I when I checked it I liked buttercup, but, I've been using keepass for a very long time and having the ability to attach files to an entry is an absolute must-have for me. I keep private key files there, scanned personal identification documents, as well as PDF files that hold sensitive content. many other examples. I understand your performance argument but if used with care, ie, dont attach a 2GB movie, that doesn't become a problem (or didn't, I never felt any problem performance-wise with keepass with all those attached files - tho I've been careful not to attach anything big). Simply limit file size for each entry to something like a couple of megabytes and you'll be fine.

In the interface this can be achieved by giving more control over "new field" function: give user the ability to specify type for the new field such as: text, password, textarea, file, perhaps checkbox etc. Just a suggestion.

**Comment by perry-mitchell** [comment]
This is dependent on https://github.com/buttercup/buttercup-core/issues/254 and the relevant implementation discussion will occur there. This issue can remain open to track the integration in the desktop app after the core support is added.

@tgoncuoglu I hear you, and that option crossed our minds, but adding any amount of binary data to our text-based vaults is simply a deal killer imo. Having the binary files stored separately (not in a single binary file either) has several aspects to it I like:

* Improved decryption performance (single binary file)
* No impact on current vault performance
* Network usage is lower as only necessary files are requested
