### ISSUE TITLE
Use non-minified buttercup core library (speed issue)

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#486]
The core currently has an issue with minification, in that the `buttercup-web.min.js` asset is much slower than the non-minified copy when it comes to crypto (locking/unlocking archives via `ArchiveManager`).

Issue: buttercup/buttercup-core#199

Use the non-minified copy for now.

**Comment by perry-mitchell** [comment]
I don't actually feel that there's a speed issue at all currently. It seems that there was in the browser extension, but the desktop app I feel handles the crypto stuff quite quickly. Thoughts @sallar?

**Comment by sallar** [comment]
@perry-mitchell crypto stuff are quick yes... There is a lag in the desktop application which is quite general. but MAYBE thats the redux store syncing or something... maybe we should rename this issue or close it for now?
