### ISSUE TITLE
1Password Import Fails - Nothing appears?

### ISSUE THREAD

**Issue by mannp** [buttercup/buttercup-desktop#499]
**Congrats on the v1.x release :) looks great.**

Trying to transfer my 1password details and I export the 1pif from 1P and import into Buttercup for 'Imported 1password archive' to be added as a new group in my buttercup archive, but that entry is empty?

Fails on a mac and on arch linux.

Not entirely sure where to find the logs, but will try and give you some specifics shortly. 

If it matters its an archive stored on nextcloud, but it also fails to import 1P data into a local archive too..

**Edit: Mmm Is it that buttercup only supports logins and won't import individual passwords from 1password? Perhaps that is it...**

**Comment by perry-mitchell** [comment]
I don't recall where the logs were stored - @sallar? Maybe we could add it to the readme too after this 😊

**Comment by sallar** [comment]
@perry-mitchell done: https://github.com/buttercup/buttercup-desktop/pull/527

**Comment by perry-mitchell** [comment]
@mannp Are you able to check the logs regarding this issue?

**Comment by sallar** [comment]
@mannp this will be fixed in next release
