### ISSUE TITLE
Linux icon has reverted to Electron

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#500]
The icon on linux no longer appears:

![image](https://user-images.githubusercontent.com/3869469/35901878-a3644090-0be1-11e8-8fa6-7a2cadcaf393.png)

![image](https://user-images.githubusercontent.com/3869469/35901898-bf031bdc-0be1-11e8-94de-a197d3fa9035.png)

Running Ubuntu 16.04. Buttercup 1.0.1.

**Comment by gschoenberger** [comment]
I can confirm the issue with the electron icon!

I am also not able to change the icon for a specific entry:
![image](https://user-images.githubusercontent.com/1648307/35903304-da5a539e-0bde-11e8-80f2-d394ebfd1a86.png)

Can you tell how to change an icon for an entry, or is this feature not available under Linux?

**Comment by sallar** [comment]
@gschoenberger Changing of the entry icon is not possible yet. But if you add a custom field called "URL" and put a URL in there, it will load an icon for that url.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/768052/35937323-8db31fa6-0c4e-11e8-8925-c907256aad8b.png">
