### ISSUE TITLE
The app is taking 100% CPU and freezed

### ISSUE THREAD

**Issue by moulip** [buttercup/buttercup-desktop#505]
I have upgraded to the latest version, and it has an annoying behavior. When I open the app, let's say I create a new entry, the app is freezing and the laptop's fan is spinning loudly. I can't do anything inside the app for 2 minutes and then it calms down and I can continue what i was doing. It seems it has something to do with the icons fetching.

**Comment by sallar** [comment]
Thanks @moulip, I've done a fix for that. We'll try to get it in soon. 
https://github.com/buttercup/buttercup-desktop/pull/506
