### ISSUE TITLE
Retrieving an icon from some urls freezes the app

### ISSUE THREAD

**Issue by darsain** [buttercup/buttercup-desktop#520]
OS: Windows 10
Version: 1.1.0

The whole app will spike CPU usage, freeze, and I have to kill it a few seconds after I start navigating my imported database. The freeze is not attached to any specific action, the only requirement is to start navigating the imported database, and within a few seconds the app will freeze 100% of the time.

I suspected it being related to favicon retrieval and that some of the items has a url with a weird favicon that is freezing your app when it's trying to process it. After a lot of trial and error I've managed to isolate the app freezing to an item with this url:

[`https://ello.co`](https://ello.co)

Here is a test database that will always freeze the app a few seconds after clicking on `Freezing item` folder:

[test.zip](https://github.com/buttercup/buttercup-desktop/files/1731061/test.zip)

Master password: `a`

Please, make the icon retrieval so robust that this won't happen again no matter how unconventional the content behind the url.

**Comment by sallar** [comment]
@darsain yup it froze:

![image](https://user-images.githubusercontent.com/768052/36307378-95c4c29e-1324-11e8-9b62-2bd7ea4eb7c3.png)

I'll investigate.

**Comment by perry-mitchell** [comment]
Thanks @darsain - Nice effort getting this together!

I can also confirm that it freezes, but it seems that it's just the renderer/UI part that dies. All of the menus are still responsive. I'll test in our icon downloader.

**Comment by perry-mitchell** [comment]
Turns out that the icon from ello.co is only 3 bytes in length:

```
AQID
```

Using the library that we currently have to detect image types, I wonder if it's dying on such an item?

**Comment by perry-mitchell** [comment]
I can confirm that this works for me in master, after updating iconographer:

![image](https://user-images.githubusercontent.com/3869469/36353948-f50d3fda-14d5-11e8-88eb-0ffa7765a8a0.png)

**Comment by sallar** [comment]
@darsain @perry-mitchell released: https://github.com/buttercup/buttercup-desktop/releases/tag/v1.2.2

**Comment by perry-mitchell** [comment]
Thanks @sallar !

I can confirm that this is fixed:

![image](https://user-images.githubusercontent.com/3869469/36355021-57c94628-14e5-11e8-8f4f-5ec1a4efe240.png)
