### ISSUE TITLE
Icons dont update, just stay as green hue document icon? (1.1 to 1.2.1)

### ISSUE THREAD

**Issue by mannp** [buttercup/buttercup-desktop#524]
Running buttercup 1.2.1 on a mac and 1.1 on arch linux and none of the icons get updated with favicons?

Icons are all the same document icons with a green hue or border.

**Comment by sallar** [comment]
@mannp Can you press Cmd/Ctrl+Alt+I and open developer tools to see if there's any errors in the console?

**Comment by mannp** [comment]
@sallar no there are no erros at all in the console. Usually they are obvious but all seems well?

**Comment by mannp** [comment]
@sallar I have just noticed that importing all of my logins from 1password has not imported any urls from the original source 1pif file, so it seems all the logins have no urls associated with them?

Which could explain why none of the logins have icons?

**Comment by sallar** [comment]
@mannp Thanks! I will look into it soon :)

**Comment by nickbe** [comment]
Wouldn't it be nice to simply be able and change the icons manually?

**Comment by perry-mitchell** [comment]
@nickbe Absolutely! I would say that the automatic icons should be the base functionality and custom icons be a feature. It's just that storing data in vault files is a tricky concept and we're not sure how that should be done right now.
