### ISSUE TITLE
[BUG] Click jamming issue on bcup 1.2.1

### ISSUE THREAD

**Issue by jgtoriginal** [buttercup/buttercup-desktop#525]
Whenever I launch the app if I click on different items of the Group tree, the app freezes out and I need to force close it for it to work back again.

The problem is that as I have many groups and I don't have a general search bar, I need to navigate through all of them manually in order to find the credential I need.

**Comment by sallar** [comment]
This is a dupe of #520. Thanks for reporting it though. Seeing that it's a critical issue, we'll fix it soon.

**Comment by jgtoriginal** [comment]
my bad bad I didn't check if that was the case before posting. sorry about that!
I'm glad you're working on it, please keep me in the loop if you need a hand testing it. Thx!
