### ISSUE TITLE
Password strength meter for new archive password

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#531]
When changing an archive's password (or when creating it for the first time), show a strength meter.

**Comment by brooksbecton** [comment]
I would like to look into this issue!

Is there a particular package ya'll would want to check passwords with?

I found this [zxcvbn](https://github.com/dropbox/zxcvbn#usage) that can give a strength score based on the number of guesses it would take a computer to brute force it. I think this lines up with what **darsain**  said in #449 

`The best warning would be to give people an estimated time it'd take the current fastest supercomputer to bruteforce the password.`
