### ISSUE TITLE
Remember window position and size

### ISSUE THREAD

**Issue by darsain** [buttercup/buttercup-desktop#535]
I have 3 monitors. I'd love for buttercup to launch on a specific one with previous size and position, just like every other app does :)

Here is a simple to implement library for this:

https://github.com/mawie81/electron-window-state

**Comment by perry-mitchell** [comment]
Only screen position is not implemented currently.

**Comment by ph1p** [comment]
I've sent a PR

**Comment by darsain** [comment]
@perry-mitchell dunno what you mean by currently, but 1.2.2 on win 10 definitely doesn't remember window size.

**Comment by sallar** [comment]
@darsain So size is not remembered? It's currently implemented and *should* remember it... If it doesn't then it's a separate bug

**Comment by darsain** [comment]
@sallar I've been playing with it, looked at the code, and the issue is that the `resize` event is [debounced to a whooping 2 seconds](https://github.com/buttercup/buttercup-desktop/blob/45736ff066b82e36f542575b85ad8a32f7c88d41/src/main/windows.js#L80) :) Turn it down to at least `500` like the other `move` event is.

**Comment by sallar** [comment]
@darsain you’re right. I’ll do the change

**Comment by sallar** [comment]
@darsain next release will reduce it to 500 :)
