### ISSUE TITLE
Entry types display formatting

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#540]
Implement entry types (available in core) so that new types of entries can be created. For example:

 * SSH keys
 * **Notes**
 * Credit cards

**Comment by darsain** [comment]
Don't forget for **password** entry type. I'd use it for PINs, CVC, and such.

Also, I assume **note** field type will support properly entering and displaying new line characters. Well I'd also love an alternative field **code**, which would work the same as **note**, but entering and displaying in monospaced font.

Use case: PGP keys, license keys such as for Sublime text, etc... example:

```
----- BEGIN LICENSE -----
Username
Single User License
EA0E-000000
00F0000D CF000D00 0000CEDC F0C00DD0
000D00EF 00FE00B0 00CCFCA0 00FBD0F0
00AAEB0B 000B00AD 0BAC0B00 00000DD0
00A00000 0000E0C0 00F0E0BB BE00C0E0
C00C000E C0AC0000 0F0C00C0 0000CA0F
A00DE00F 000BB0E0 0D00000E 0000000F
EDF0D0A0 0A00DCCB 00000CB0 00ABEC00
00E0F0A0 FB00CC00 D0E000C0 C00A0AE0
------ END LICENSE ------
```

**Comment by perry-mitchell** [comment]
Great idea @darsain - I completely agree with the idea of having a more monospace-friendly Note type. A password type also sounds good - to compliment the default username/password login type.

**Comment by perry-mitchell** [comment]
Closing in favour of #807 as it references the new featureset which needs integration.
