### ISSUE TITLE
Launching added .bcup file causes database duplication

### ISSUE THREAD

**Issue by darsain** [buttercup/buttercup-desktop#543]
If I have a database `foo.bcup` already added in Buttercup, and than I double-click on the file, the same database is added into Buttercup again, creating a duplicate.

Ideal behavior: Already added database is opened or activated/focused when it was opened already.

**Comment by jenstornell** [comment]
I think I have the same problem. I just noticed today that I have multiple items in the left sidebar and in "Window".

Is there a simple way to clear them out? I always double click the password file that I have in my local dropbox folder on Windows 10.

![image](https://user-images.githubusercontent.com/927011/49359688-2e4d0080-f6d7-11e8-9ef1-2d093b6d94d7.png)

**Comment by sallar** [comment]
@jenstornell unfortunately for now you can just right click on the items in sidebar and remove them from your buttercup. But this shouldn't be happening.

I'll look into this ASAP.
