### ISSUE TITLE
Enforce single instance mode

### ISSUE THREAD

**Issue by darsain** [buttercup/buttercup-desktop#544]
Buttercup doesn't have a single instance mode enabled. This allows multiple buttercup instances to run, possibly fighting over database access and creating conflicts in settings storage.

Practical case when this might happen: you have buttercup open, and you want to add another .bcup database. You double click on it and instead of it being added to the current instance (or activated when it's already in the list, related issue #543) you get a new buttercup window. And since both instances share the same settings storage, there will definitely be conflicts and confusion.

**Comment by sallar** [comment]
@darsain Can I send you a windows executable of my change, so you can test this?

**Comment by sallar** [comment]
@darsain here's the installer: https://www.amazon.com/clouddrive/share/DHG2JSFHGDkZA3JFvy1z172HBuQpY9ewn8X5AtgynXY

**Comment by darsain** [comment]
@sallar Yes, there is no 2nd window being launched, instead the 1st one gets focused, which is correct, but ... nothing happens. If I double-click a .bcup file to open it, something *should* happen. When nothing does it feels like a bug.

The database should get added to the list, and when it already is in the list it should just get activated.

**Comment by sallar** [comment]
> and when it already is in the list it should just get activated.

@darsain well this one is a separate issue that you mentioned before. so that's for another time. but right now the archive *should* get added to the list like a normal double-click. I'll check what's wrong.

**Comment by sallar** [comment]
@darsain updated the code: https://www.amazon.com/clouddrive/share/3qq9gRSxjAlNOFs1gggPc9oA3OgMPdxibTIl00jCnR4 this time it should open the file

**Comment by darsain** [comment]
Yeah it opens the file now.
