### ISSUE TITLE
Hide entries search box

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#556]
The search box now does nothing and could now be considered bad for UX. Removing it in favour of the few global search dialog would be best.

**Comment by mustii82** [comment]
Not a good Idea in my Opinion not everybody know the shortcut for the Global Search, at least the searchbox should provide a filter function or provide simple Acess to the Global Search. So please bring it back.

**Comment by perry-mitchell** [comment]
Why would you require a filter box for entries when there’s a global search? I can’t see why you’d need to filter only the currently displayed entries..

**Comment by mustii82** [comment]
Even then a Button for the Global Search is always a good thing like on Mac OSX you can acess spotlight via button and shortcut. fore People to use a shortcut is never a good thing.

**Comment by perry-mitchell** [comment]
@mustii82 I agree that _only_ a shortcut would be bad, but we also have a menu item:

![image](https://user-images.githubusercontent.com/3869469/36809127-b4e3caa8-1ccf-11e8-8cbc-e1bac9a62faa.png)

I can't see any reason to have a filter box for entries unfortunately. The fact that we support nested groups mean that Buttercup archives can have more depth in terms of sorting and organising. Users don't have to force their 10s or 100s of entries into one large folder. Having them spread out like this means that global search is definitely the more effective mode of searching, if compared to filtering items in the current folder only.

Due to our application design and what I just mentioned, I don't think we'll be bringing back the entries filter box, sorry.

**Comment by mustii82** [comment]
@perry-mitchell But something useful like a search needs a Button for qucik acess especially for a Password Manager with Multiple Accounts. We are not talking about a rare condition like Settings editing, We must provide a Button like every modern App.

**Comment by perry-mitchell** [comment]
@mustii82 I think some things are more widely known.. For instance, I would expect the **average** user to know:

 * Shortcuts for Copying things
 * Shortcuts for Pasting things
 * Shortcuts for Cutting things
 * Shortcuts for Finding things

And so finding things using a hotkey should be second-nature to most. On top of that, we have a button in the menu. I hear that you're pushing the quick-access angle here, but I would argue that we don't need several ways to "quick" access (assuming a single action equates to "quick") the same functionality. You go once into the menu to search, discover that you can use the hotkey which is **standard**, and then you use the hotkey from then on out. 

If you choose to avoid using the hotkey, for whatever reason, I don't feel that a shortcut button would really help the situation... At least not right now in this current design.

Who knows, we may bring back some kind of search button in a future design, but we don't currently see a need for one now.

**Comment by mustii82** [comment]
Even on my College People dont know the Finding Shortcut. Every GUI Builder know that something important like this could never be replaced by a shortcut. not in Windows, Max OSX or any other Programm that breaks the entire User Interface Guide Line
