### ISSUE TITLE
[feature request] option to (auto)start (minimized) with OS

### ISSUE THREAD

**Issue by n8v8R** [buttercup/buttercup-desktop#565]
Such options would be handy/welcome now that the tray icon been implemented.

![tray option](https://user-images.githubusercontent.com/13611490/35914076-32fd6ea0-0c02-11e8-9bde-c19667886303.PNG)

**Comment by perry-mitchell** [comment]
Good idea.. Those options sound good, but this should be handled by a proper settings interface, not just writing everything to storage like we're doing now. So for that, I'm going to block this by #140.

**Comment by jookk** [comment]
windows auto start missing a lot, because firefox cant open valut without desktop app launched.  Now its needed to manually start bc
