### ISSUE TITLE
Tray icon menu shows no contents

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#567]
On ubuntu, the tray icon menu is empty:

![bcup_tray](https://user-images.githubusercontent.com/3869469/36841733-f524c9be-1d51-11e8-8f7e-f6d603a8c6f0.JPG)

(apologies for the poor qual photo, ubuntu didn't want to print-screen the menu when it was open)

EDIT: The icon is also incorrect it seems.. It should be the rounded-corners square type icon.

**Comment by ph1p** [comment]
I noticed this too. With `appIcon.setContextMenu(contextMenu);` electron handles the context menu automatically. Maybe we can use this method.
The .ico files are corrupt.

![screen shot 2018-03-01 at 17 05 56](https://user-images.githubusercontent.com/15351728/36855095-fefc86d6-1d72-11e8-9529-078d40abef61.png)
![screen shot 2018-03-01 at 17 06 45](https://user-images.githubusercontent.com/15351728/36855096-ff2f0f16-1d72-11e8-8255-bfbc4e62cba6.png)

**Comment by Zjemm** [comment]
I see no tray icon at all on my Budgie-desktop where as enpass does show up. and there is no settings page to enable or disable this..... is it set in some config file?

**Comment by perry-mitchell** [comment]
@Zjemm There should be a context menu in the application window to show the tray icon, if I remember correctly. I don’t configure this myself usually.

**Comment by Zjemm** [comment]
There is an option called "diplay in menu bar" but thats on by default and doesnt do anything
how can i troubleshoot that?
i also downloaded the appimage but no difference there

**Comment by perry-mitchell** [comment]
What do you mean by “budgie” desktop? Maybe you could debug it in the dev environment. You’d need to install Nodejs 8 or 10, clone the repo and open 2 terminals. In one run “npm run start:renderer” and in the other “npm run start:main”. You’d have to do some tweaking with the code to see why it doesn’t show..

**Comment by perry-mitchell** [comment]
Understandable if the dev environment doesn’t sound comfortable. Let us know some more details about your system to see what the problem may be..

**Comment by Zjemm** [comment]
I'll see what is can do

Budgie desktop is a DE from solusos. It's based on gnome

I'm running budgie on arch linux

**Comment by Zjemm** [comment]
Hmm running dev is not working for me at the moment, can't seem to get that going.
Can we do something else to troubleshoot this?

i'm running:
arch linux
Budgie-desktop
and the buttercup appimage (latest version at this moment)

**Comment by perry-mitchell** [comment]
I'm wondering if it's something to do with the `AppImage` build. AppImage is an executable, and not perfectly designed for installing applications. Some features like **updating** are not available with this installation method - Perhaps the persistence of the app, along with the tray icon, simply doesn't function properly.

@sallar do you know where the app is extracted to? It could be tmp or something I guess. Somewhere incompatible with this feature..

**Comment by Zjemm** [comment]
well i had the same problem with the installer version, i installed it via the arch AUR. then after that i tried the appimage

**Comment by sallar** [comment]
@perry-mitchell @Zjemm based on my knowledge AppImage actually doesnt extract anywhere and just runs like an executable... I have to investigate further.

**Comment by Zjemm** [comment]
@perry-mitchell @sallar anything i could collect to help troubleshooting?

**Comment by Zjemm** [comment]
@perry-mitchell @sallar
ive tried the following:

appimage on:
solus-budgie and solus-mate, no tray icon
ubuntu-budgie, ubuntu vanilla no tray icon

then i installed the full client:
ubuntu-budgie, ubuntu vanilla YES tray icon

then i tried on arch (which i'm using)
arch with budgie NO tray icon
installed via the AUR because there is no official package. and i think the problem might just be in that aur package because ive seen the tray icon working on budgie, so that should not be an issue

but why, im not sure
