### ISSUE TITLE
Mobile Version dosent support OS Specific Password APis

### ISSUE THREAD

**Issue by mustii82** [buttercup/buttercup-desktop#570]
A Password Manager which runs on iOS and Android must work with the OS APis to get easier acess to our Passwords. We must provide this compatibility.

**Comment by perry-mitchell** [comment]
Hi @mustii82 - Please make sure to open issues in the correct repository. This repo is only for the desktop application - The mobile app is in [this repo](https://github.com/buttercup/buttercup-mobile). Thanks.
