### ISSUE TITLE
About menu doesn't work

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#574]
The about menu item does not open the about box.

**Comment by dotamir** [comment]
Hi, I used Buttercup on Linux and I tried to figure it out why it does not open. And I reviewed the code and I couldn't find anything. I just found this line:
```{ role: 'about', label: label('app.about') },```
BTW, can you lemme know how you guys handle this? Maybe I could help.
(I haven't tested it on another OS like macOS to know how is working).

**Comment by perry-mitchell** [comment]
This is still the case on version 1.10

**Comment by perry-mitchell** [comment]
This is also present on Windows..

**Comment by sallar** [comment]
@perry-mitchell I'll take a look at this. I just need to reinstall my VM

**Comment by perry-mitchell** [comment]
Fixed in v2.
