### ISSUE TITLE
Tray error on every load

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#581]
On ubuntu 16.04, I get this error every time I open buttercup:

![image](https://user-images.githubusercontent.com/3869469/37643410-1beeb704-2c29-11e8-8148-b9434a868b26.png)

I have the tray icon enabled.

**Comment by perry-mitchell** [comment]
It looks like it's running stuff from the temp folder.. and may have something to do with the update on Linux. The AppImage way might still be a bit broken.. not sure.

**Comment by Megilla** [comment]
I have the same issue with Ubuntu 17.10.

![buttercup1](https://user-images.githubusercontent.com/4919450/37758789-c2371bcc-2db1-11e8-8bc9-9fc537c18c01.png)

I noticed on my machine that the message only appear, when Buttercup already running. 

1. Not all processes will stop when I close buttercup.

![buttercup2](https://user-images.githubusercontent.com/4919450/37758880-1a2a2f72-2db2-11e8-89a4-f3fb75348943.png)

2. And there are two menu buttons when buttercup starts. (the left one with the buttercup icon and the last one on the right)

![buttercup3](https://user-images.githubusercontent.com/4919450/37758980-7c19401a-2db2-11e8-901d-508e1a30194b.png)

If I click on the buttercup button now, the error will appear.

**Comment by perry-mitchell** [comment]
The error does not occur for me when opening buttercup **from** the tray icon. It's only regular launches that show it.

**Comment by sallar** [comment]
Hi @perry-mitchell @Megilla, I'm trying to fix the Tray issues. However before releasing, could you please confirm that it works? I have uploaded the patched version here. Let me know if they work... Thanks!

deb: https://send.firefox.com/download/a63dd8caf9/#SAa0pYNWdu_CLf4fdNZjRw
rpm: https://send.firefox.com/download/1af462534c/#3Iz94sLMhczKbRFRCYuL1w
