### ISSUE TITLE
Drag&Drop error message

### ISSUE THREAD

**Issue by Megilla** [buttercup/buttercup-desktop#582]
If I want to drag and drop an entry into another directory, I get this error message.

Ubuntu 17.10 & Buttercup-Desktop v1.6.0

![buttercup4](https://user-images.githubusercontent.com/4919450/37759435-e8ab1374-2db3-11e8-9dcf-87ffc848622c.png)

**Comment by sallar** [comment]
@perry-mitchell @Megilla This is actually not a bug... Dragging and dropping entries into groups is not currently supported. So adding it would fix this issue too.

**Comment by perry-mitchell** [comment]
Stale.
