### ISSUE TITLE
Bitwarden CSV

### ISSUE THREAD

**Issue by ArtexJay** [buttercup/buttercup-desktop#583]
Issue when importing Bitwarden's CSV. The titles are imported nothing else, not the passwords, username, links ,etc

**Comment by perry-mitchell** [comment]
Hi @ArtexJay - Unfortunately Bitwarden [isn't yet supported](https://github.com/buttercup/buttercup-importer#supported-password-archive-formats). This should be added to the importer project first. Thanks.

**Comment by perry-mitchell** [comment]
I've added an issue for this: buttercup/buttercup-importer#30

**Comment by ArtexJay** [comment]
Great thanks! Hope it gets supported soon
