### ISSUE TITLE
App displaying error after updating Linux

### ISSUE THREAD

**Issue by Hedronmx** [buttercup/buttercup-desktop#584]
![Error](https://i.imgur.com/yFWI89H.png)
This is the error that shows inside the buttercup window after updating to 1.6.0.

I had to revert to 1.4.0... that version does work. I tried with 1.5.2 and the same error happens.
Running Elementary Os 0.4.0 Loki based on ubuntu. Installed using the Deb file.

**Comment by perry-mitchell** [comment]
Updating shouldn’t be possible on the deb file installation, due to issues.. 🤔

**Comment by sallar** [comment]
@Hedronmx By updating do you mean installing it yourself manually? As @perry-mitchell mentioned auto-updating is not possible with deb files

**Comment by Hedronmx** [comment]
I installed it with the new deb... So should I switch to appimage or what should I do?
Thanks and sorry for the inconvenience

**Comment by perry-mitchell** [comment]
No problem! We do need to fix that somehow. You can uninstall the deb version and use the `.AppImage` version, which supports updating.

Closing in favour of #586
