### ISSUE TITLE
Auto lock unlocked archives after time

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#587]
Based on #141 - Auto lock the archive after **x** minutes of inactivity. The following points should be covered:

 * Lock all currently unlocked archives
 * Listen for user-cues in terms of activity
   * Reset lock timer on mouse move
   * Reset lock timer on focus change
   * Reset lock timer on tray icon menu open
 * Disable the timer while any item is being edited

**Comment by exside** [comment]
This is one critically missing feature, I'd say high priority =)

**Comment by alper** [comment]
I had happily started Buttercup until I noticed that this feature is missing. I'd say this is critical for a lot of the more serious users of a password manager.

**Comment by ph1p** [comment]
@alper I'm currently working on a PR https://github.com/buttercup/buttercup-desktop/pull/699 ... I hope I finish it this week.

**Comment by alper** [comment]
Excellent. I have confidence (and a bit of patience and laziness as well).

**Comment by eandersons** [comment]
It also would be really useful if unlocked vaults were locked when a screen gets locked (for example, when pressing keys `Windows` + `L` on Windows and Linux machines).
