### ISSUE TITLE
Add more cloud services

### ISSUE THREAD

**Issue by AwesomeTech10** [buttercup/buttercup-desktop#589]
I think Buttercup is a great program, but I use LastPass. Maybe add in support for LastPass, 1Password, etc?

**Comment by perry-mitchell** [comment]
Hi @AwesomeTech10 - As Lastpass and 1Password are our competitors, we won't be offering integrations for _working_ with them. We'd like to offer a platform superior to theirs.

We do provide import support for them, however, so you can easily switch from their platform to ours.

Thanks!

**Comment by AwesomeTech10** [comment]
Well, maybe create a tool that would integrate them better, such as a option for importing, which would ask you to log in, and it would import. Also, consider making an extention for Brave (brave.com), because that is my browser-of-choice
