### ISSUE TITLE
Store passwords with Sync.com cloud storage

### ISSUE THREAD

**Issue by ArtexJay** [buttercup/buttercup-desktop#596]
I have recently seen many users on alternativeto talk about sync.com. It's a cloud storage service, and it differs greatly from Dropbox or Gdrive as it boasts that it encrypts all files uploaded.

So I was wondering it Buttercup could implement a store/sync feature to work with this cloud storage like the ones already existing for Dropbox.

The cloud storage is: https://www.sync.com

**Comment by perry-mitchell** [comment]
Looks good! This should first be added to [buttercup/datasources](https://github.com/buttercup/datasources).

**Comment by perry-mitchell** [comment]
Added to our [roadmap](https://github.com/buttercup/roadmap/blob/master/roadmap/CLOUD_SERVICES.md#blockedpending-solutions). It should be added to the core library after an issue and discussion takes place there (or in the datasources repo).
