### ISSUE TITLE
Mac icon invisible when light theme used

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#598]
As per title:

![image](https://user-images.githubusercontent.com/3869469/39098853-cb2f5344-4679-11e8-9ec4-4057bb0de32c.png)

**Comment by sallar** [comment]
Hey mate, this is one of the fixes in the latest PR. It will be gone with the next release :)

**Comment by sallar** [comment]
Fixed by #592 592
