### ISSUE TITLE
Pb in managing https requests for webdav connection

### ISSUE THREAD

**Issue by eldy** [buttercup/buttercup-desktop#599]
Buttercup desktop (same on android) return a network error during the ssl handshake when try to create a webdav source. Certificate is fro letsencrypt and is valid.
Without https, buttercup client make a PROPFIND. With the https, the PROPFIND is never sent and a message is return saying "network error".
The webdav url can by accessed with any other webdav client like cadaver

This is a screenshot of networks stream.
The first halh is when using cadaver. No problem.
The second half is using buttercup. The connection is reset during handshake just after receiving the message TLS 1.2 Alert 21.

![image](https://user-images.githubusercontent.com/883887/39200875-a8213dac-47ed-11e8-9da3-6129efb7fb2a.png)

Is there any setup i can do on my https server on in buttercup to have buttercup working with my https server like any other webdav clients ?

**Comment by perry-mitchell** [comment]
Hi @eldy - Thanks for the detailed report. Unfortunately we need more information - we use Buttercup daily on several different webdav connections which all work, some of which are secured using letsencrypt.

Could you perhaps check that your SSL cert is valid? Tools like [this](https://www.sslshopper.com/ssl-checker.html) should work just fine. Usually these issues are to do with some kind of custom configuration or setup with the server or certificate.

**Comment by perry-mitchell** [comment]
I'm going to close this issue for now, as we're not able to deal with all the connection issues that arise with so many different platforms & SSL configurations. I've created a [contribution and issues guide](https://github.com/buttercup/roadmap/blob/master/agreements/issues.md) which details some basic pointers when creating issues, and we'll start to enforce these from now on.

If a bug is confirmed we can of course re-open the issue, and would be happy to patch it in such a case. Thank you!
