### ISSUE TITLE
not found fse-v1.0.17-node-v64-darwin-x64.tar.gz

### ISSUE THREAD

**Issue by robbinhan** [buttercup/buttercup-desktop#607]
download  fse fail. that was 404 status

![image](https://user-images.githubusercontent.com/241873/39955553-4e39df32-5603-11e8-9d7a-c28f78858a03.png)

**Comment by sallar** [comment]
@robbinhan this looks like an issue with npm... can you try again?

**Comment by robbinhan** [comment]
@sallar yes,I have been retried，and same the error

**Comment by sallar** [comment]
@robbinhan I tested master a few times and it works. Can you check one more time and if it doesn't work, would you be able to tell us the OS you're using?

Also, it seems like when you npm install there are a few errors related to what you have shown in the logs, but those are harmless.

**Comment by sallar** [comment]
I'm closing this issue since we havent heard from you and the master works in different systems. Please let us know if it's still broken so we can re-open.
