### ISSUE TITLE
Feature request - Upload pictures

### ISSUE THREAD

**Issue by Sblop** [buttercup/buttercup-desktop#608]
Thanks for a great app... This is bringing keepass like password management into a more modern package.

As a future feature I suggest the availability to upload pictures to the database. My bank uses a key-card with hundreds of one-time codes. It would be usefull to be able to upload these directly to the DB, compared to copying it to the db by hand. :-)

**Comment by sallar** [comment]
Hi @Sblop, this is something we are thinking about right now. We will update this issue with more information once we have more info :)

**Comment by exside** [comment]
I'd like to see file attachments in general, not only images, but the problem with this is always database bloat...

**Comment by perry-mitchell** [comment]
@exside File attachments will most likely _not_ be included in the archive file, because of bloat like you said. They'll most likely be encrypted separately and stored in a relative location to the archive file (hidden subfolder most likely).

**Comment by ldexterldesign** [comment]
+1

Use case: passports

Regards

**Comment by perry-mitchell** [comment]
Closing in favour of #484
