### ISSUE TITLE
Hope to add onedrive synchronization

### ISSUE THREAD

**Issue by dornenkrone** [buttercup/buttercup-desktop#611]
just as it's write ,when i write my password file on my pc without dropbox ,i can't sync it to my chrome 
it would be much convience if it can sync files with onedrive

**Comment by perry-mitchell** [comment]
Hi @dornenkrone - OneDrive is mentioned in our [roadmap](https://github.com/buttercup/roadmap/blob/master/roadmap/CLOUD_SERVICES.md#greenlit-solutions). It should be added to the core library before being implemented here, so I'll close this request for now.
