### ISSUE TITLE
Copied password remains in clipboard after clearing-time

### ISSUE THREAD

**Issue by toniobido** [buttercup/buttercup-desktop#626]
Hi,
I noticed that the copied passwords remain in the clipboard.
Also in the version windows 10 17704 (insider) there is a history of the clipboard, and we find the password in clear. 

do you think that it will be possible to correct this ?

![image](https://user-images.githubusercontent.com/14336821/42001229-ab4199ac-7a63-11e8-81a6-725d208abf19.png)

**Comment by perry-mitchell** [comment]
The clipboard should automatically be cleared after some time.. 10-15 seconds or something like that. If it doesn’t automatically clear then it’s definitely a bug with that function..

**Comment by toniobido** [comment]
Yes I know, 
It's why I notify it.

Even in Windows 10 1803 (stable) after 3 minutes clipboard remains copied password

**Comment by sallar** [comment]
I’m guessing that Windows ignores attempts at copying an empty string to clipboard, which is how we clear the clipboard. We should definitely improve this. Wondering if Electron provides any APIs to clear the clipboard. 

But also we can’t really clear their entire history. Can we?

**Comment by deadcoder0904** [comment]
No its not only for Windows, its for my Mac as well. I used some other software before ButterCup & as soon as you closed the app, it used to clear the password. So what you can do is after 15 seconds, clear password but if someone quits the app then before quitting copy empty string to their clipboard
