### ISSUE TITLE
can't unlock my archive

### ISSUE THREAD

**Issue by leongrdic** [buttercup/buttercup-desktop#631]
I tried opening my local archive on my laptop today and I keep getting this message:
```
failed mapping credentials to a source: invalid property name for entry: pin
```
I tried creating a new archive and opening it and it works regularly. Also, when I type a wrong password I get a different error message so that isn't the problem. How am I supposed to access my passwords now?
Thanks!

**Comment by perry-mitchell** [comment]
Hi. Could you please confirm your desktop app version? This should be solved in the latest release.

**Comment by leongrdic** [comment]
the version is 1.8.0 windows

**Comment by perry-mitchell** [comment]
Ok, well the issue might be elsewhere. Are you able to attach a stacktrace at all? This could be done by opening the I inspector (in the menu). This would help us narrow down the bug.

**Comment by leongrdic** [comment]
The console doesn't throw any errors, and I'm not really able to do anything in the dev tools as the js bundle is so big the dev tools become unresponsive when trying to do any debugging.

**Comment by perry-mitchell** [comment]
It’s hopefully not necessary in this case.. the stack trace should be printed hopefully. It may be on the nodejs side so perhaps it could be possible to see if you run the app from the command line?

**Comment by leongrdic** [comment]
just tried it and there's no trace in node console.. i only get the 'restoring state' and 'checking for update' messages. is there perhaps a debug flag i could enable?

**Comment by sallar** [comment]
Hi @leongrdic, could you please update Buttercup and see if the new version works for you? The latest version is 1.9.0

**Comment by leongrdic** [comment]
problem solved! it unlocks properly now. thank you :)

**Comment by sallar** [comment]
@leongrdic cheers! closing this now.
