### ISSUE TITLE
prevent loss of unsaved new entry

### ISSUE THREAD

**Issue by leongrdic** [buttercup/buttercup-desktop#634]
when adding a new entry, I often find myself forgetting to actually save it, and later switching to another (already existing) entry to copy a different password. this way i lose the new, unsaved entry.
a possible solution to avoid this problem would be a dialog that appears when trying to open another entry while the current one isn't saved, saying "you didn't save your entry, you will lose the data if you don't save it now" or something similar.
same thing goes for editing existing entries!

**Comment by perry-mitchell** [comment]
I like this idea. Editing could almost grey-out/disable the other items to prevent this, or a dialog like you suggested.

What do you think @sallar ?

**Comment by sallar** [comment]
@perry-mitchell fortunately we are using redux-form so we *can* persist the data and show it again later, but IMO showing a dialog to confirm navigating away is a better option. Because the goal here would be to prevent the user from "forgetting" right?

**Comment by sallar** [comment]
This issue isn't fixed in master. So won't be included in release notes.

**Comment by leongrdic** [comment]
okay, i opened the new issue.
i just noticed that closing the buttercup window (app) while adding a new entry doesnt show any warning or a chance to prevent the user from losing the new unsaved entry. should i also open a new issue for this?

**Comment by ldexterldesign** [comment]
> I just noticed that closing the buttercup window (app) while adding a new entry doesn't show any warning or a chance to prevent the user from losing the new unsaved entry. should i also open a new issue for this?

Yes, I also noticed this today

IMO *any* entry change that's unsaved should trigger a save prompt if the user events outside the entry column/pane:

<img width="554" alt="screenshot 2019-01-21 at 16 13 04" src="https://user-images.githubusercontent.com/1715809/51482733-87601900-1d97-11e9-88dc-b1c1a0b0baba.png">

One new issue should suffice

Cheers
