### ISSUE TITLE
Fields order is wrong and password is not showing for some entries

### ISSUE THREAD

**Issue by pelonchasva** [buttercup/buttercup-desktop#636]
Hello devs,

I just updated to version 1.9.0, and I just noticed a weird behavior in the application for some entries, I tried to get my password for one of my accounts but it is not showing, and the order of the fields got mixed up, now the Password field is at the top, the username is below that, and my custom fields are in the wrong order too. If I click on edit, there are multiple custom fields separators, not just one like before.

I need a fix on this because I am at work right now and I cannot retrieve the password for one of my Production servers 😢.

Should I downgrade the version and see if it works?

Additional Info:
OS: Windows 10 v1709
Log: There are no error on the log as of today

Cheers

**Comment by perry-mitchell** [comment]
Hi,

Sorry to hear! Yes I would suggest downgrading until further notice. We’ll try to check this out asap. Any chance you could provide a screenshot without showing secure data? Not sure how we could reproduce this issue.

**Comment by pelonchasva** [comment]
Hi,

No problem about that, I just downgraded to version 1.8.0 and it is working fine now, attached you can see how the data was changed.

**Wrong Fields Order**
![wrong fields order](https://user-images.githubusercontent.com/4713147/43414062-acefd8ee-93ff-11e8-9293-2eb86b2da9c2.png)
---
**Correct Fields Order**
![correct fields order](https://user-images.githubusercontent.com/4713147/43414063-ad090620-93ff-11e8-8abf-bf7e0d56403e.png)

I wish the log could have some error entry so you can see for yourself, but unfortunately there is none when upgrading to 1.9.0 😞.

Thanks

**Comment by perry-mitchell** [comment]
Thanks for the screenshots.. that’s actually very helpful. I think I know the cause. 

Regarding your password however - you said you weren’t able to retrieve it? Not sure if we’re actually looking at 2 different issues here - the field order and your password not being retrievable.

**Comment by pelonchasva** [comment]
Yeah, if you see, on the first screenshot the password field doesn't show the dots for the password, and the icons to show/hide and copy the password were missing too, I think this should be on the same issue since everything is related somehow, but I'm not quite sure.

Although, on the previous version, everything works normal, thankfully, the entry values were not deleted from my file, so this must only be a bug on version 1.9.0

**Comment by sallar** [comment]
@pelonchasva so in the new version the password shows up as raw text?

**Comment by pelonchasva** [comment]
HI Sallar,

On the new version, the password doesn't even show at all, it shows up as a blank field and the show/hide and copy buttons doesn't show on hover too.

**Comment by sallar** [comment]
@pelonchasva We fixed the issue and will release 1.10.0 soon! Watch out for new updates :)
