### ISSUE TITLE
search entry not open sub-folders location

### ISSUE THREAD

**Issue by conovor** [buttercup/buttercup-desktop#638]
Hello,

I love Buttercup but we have a big trouble with the search function in my team : 

1. I search something and I have several results. I click on one result
2. the looking result is on a sub-folder, the sub-folder not open automaticly, so I cannot find where is the looking result in the folder tree (because I have several sub-folder)

Bug : the folder and sub-folder should be open and change in green to know where looking for
Improvment : It will be nice to headline all the folder entry in relation with the looking result (like in Keepass who gives all searching result (and location).

Best regards,
Alain

**Comment by sallar** [comment]
Hi @conovor. Thanks a lot. Yes this is an issue. We will update this task with more information once we start working on it :)
