### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by phineas0fog** [buttercup/buttercup-desktop#643]
Hello :)
Since I've updated buttercup, I get a segfault when I try to launch it :/ This is a VERY big problem cause because of this problem, I can't access to my servers (because of the pass etc. And yes, no other solution). I use `strace` to see if I can correct the problem myself, but I don't think.

`buttercup` try to access to the file `/etc/gnutls/default-priorities` that don't exist on my system. Yes, gnutls is installed and up-to-date.

# Strace output extract
```
getrandom("\x9f", 1, GRND_NONBLOCK)     = 1
stat("/etc/gnutls/default-priorities", 0x7ffe64945b30) = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0xb87650} ---
+++ killed by SIGSEGV (core dumped) +++
[1]    8480 segmentation fault (core dumped)  strace buttercup
```

# My system
- Archlinux (antergos) with 4.17.12 kernel
- gnutls: version 3.5.19-1
- lib-gnutls: version 3.5.18-1 (apparently up-to-date)

Thanks a lot :heart:

**Comment by sallar** [comment]
Hi @phineas0fog thanks for letting us know. I will look into this, since I havent used Archlinux before and we haven't this error in other systems, I have to research a bit.

Thanks
Sallar

**Comment by phineas0fog** [comment]
Hello,
I just test with an old version of buttercup (on archlinux too, I haven't updated anything in a few days) and the `strace` command don't show any things related to the missing file from my previous post.

I hope this can help ;)

**Comment by perry-mitchell** [comment]
Arch is unfortunately not part of our testing suite, so getting anything done here will be difficult without contributed effort. We'd appreciate any help you might provide @phineas0fog - debugging this on your machine would most likely be really helpful. If there's some dependency missing on arch (due to the fact that arch runs more lean than other linux distros) perhaps we can find out what it is and document that for other arch users.

**Comment by perry-mitchell** [comment]
@phineas0fog before we continue, please try the solution posted [here](https://www.reddit.com/r/archlinux/comments/957v3k/segfaults_at_startup_on_a_bunch_of_apps_after/) to see if that helps.

**Comment by Zjemm** [comment]
same issue here on arch
is there anything i can check to help out?

**Comment by perry-mitchell** [comment]
@Zjemm You could try out that solution I linked in the previous post, or you could perhaps open a dev environment and try to debug it there. Any information would help..

**Comment by Zjemm** [comment]
glibc 2.28-4 is released, and now it starts normal with that new version :)

**Comment by perry-mitchell** [comment]
Hi @Zjemm - Great news! I'll close this and will make a note on our readme.

With regards to the ENOENT error, we have a bug for that: #641.

If you could create a new issue for the group-dragging issue, that'd be really helpful!
