### ISSUE TITLE
UI glitch: Rendering issues on some machines

### ISSUE THREAD

**Issue by Jaimefs** [buttercup/buttercup-desktop#644]
Hello:

I open a vault and the password window no desapear, it goes to background. I have this problem from last update.

![Error screenshot ](https://user-images.githubusercontent.com/36184710/44307335-d8ab4d00-a3a0-11e8-9ecb-266a2155d21e.png)

I use MacOS version 10.13.6.

I love your program. Thanks a lot.

**Comment by sallar** [comment]
Hi @Jaimefs. So if you download a previous release the problem goes away?

**Comment by Jaimefs** [comment]
Hello:

I download and install a previous release. This release works fine before update. But now i have de same problem.

![captura de pantalla 2018-08-21 a las 7 34 56](https://user-images.githubusercontent.com/36184710/44382424-1af59b00-a515-11e8-8728-e342785f38e0.png)

Thank a lot.

**Comment by perry-mitchell** [comment]
Renamed for clarity.

**Comment by perry-mitchell** [comment]
@Jaimefs We've been able to reproduce this issue on one of our macbooks, and it looks like some kind of rendering issue from the browser/electron side. Updating the electron version didn't seem to help at all.

**Comment by perry-mitchell** [comment]
Wondering if it might be some rendering issue to do with lower-spec/older GPUs on Mac:

 * electron/electron#13303
 * atom/atom#17694

Someone also mentioned that not having a background on the `<body>` caused weird UI issues when scrolling.. Might be worth to try setting it to something as well if it isn't already.

**Comment by perry-mitchell** [comment]
Solution was to roll back Electron to the previous major version. Seems that something with v2 has broken rendering on some macs.
