### ISSUE TITLE
[ Feature Request ] Default size for labels is too small

### ISSUE THREAD

**Issue by bogdansuditu** [buttercup/buttercup-desktop#646]
First of all, thanks for this wonderful applications. I had no issues with it so far. 

However there's one thing that for me is a deal breaker. I have a lot of data imported from keepass and almost all records are containing one field called Notes (shouldn't matter the name). 

In buttercup (all variants, mobile or desktop) the default display for such field is one small text field. I store in that Notes field various data, such as configuration settings, etc, small data, text only. Right now, to see that data I need to copy the field and paste in another application. It would be great to be able to see such fields when opening the entry in a larger (scrollable) text box. 

Many thanks!

**Comment by sallar** [comment]
Hey @bogdansuditu thanks :)

I understand. This is something that we're working on. We're changing the way we display the fields and this issue will be fixed once that's implemented :) We'll update this issue.

**Comment by perry-mitchell** [comment]
The new UI supports note multi-line fields.
