### ISSUE TITLE
Can't open buttercup after changing to higher resolution monitor

### ISSUE THREAD

**Issue by reedpro** [buttercup/buttercup-desktop#650]
After switching out to a higher resolution desktop, buttercup shows as open on my taskbar, but I can't get it to actually show. I have tried changing to a lower resolution, disconnecting the new monitor, restarting windows, and selecting the app and using windows+arrows to try and move it around

**Comment by reedpro** [comment]
I've also tried uninstalling and reinstalling, downgrading and upgrading again, and opening a new desktop and moving buttercup there.

**Comment by reedpro** [comment]
I eventually got it to work by hovering over the icon on the taskbar, which opened the preview, right clicking on the preview, and hitting maximize.

Sorry if I seem like a spaz for this issue, I've been struggling with it for a few days, and at the very least, if this happens to someone else they might see this and figure it out

**Comment by perry-mitchell** [comment]
Hi @reedpro - Thanks for posting the issue.. glad you got it sorted! Off-monitor windows can be tricky sometimes. [Here's a link on how to get them back](https://www.howtogeek.com/howto/windows/bring-misplaced-off-screen-windows-back-to-your-desktop-keyboard-trick/) if you happen to lose any windows.

I'll close this as it's not related to Buttercup in particular.

**Comment by reedpro** [comment]
I'm ok with the ticket being closed, but i feel it must be related to
buttercup, since none of the steps listed here worked and even uninstalling
reinstalling didnt fix the issue
