### ISSUE TITLE
[Linux] Tray icon should be coloured

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#652]
Perhaps having a coloured icon in the tray would look better on linux?

![image](https://user-images.githubusercontent.com/3869469/45279540-20be1b00-b4da-11e8-81ff-6ae589172641.png)

Or, having the option to change. ownCloud supports this:

![image](https://user-images.githubusercontent.com/3869469/45279566-33385480-b4da-11e8-9a32-f8e1dfd69a2c.png)

**Comment by sallar** [comment]
@perry-mitchell great idea we can add the option when we have the settings panel too.
