### ISSUE TITLE
Web APP - some bugs with WebDav and Nextcloud vault

### ISSUE THREAD

**Issue by warnerbryce** [buttercup/buttercup-desktop#656]
Hello to the ButterCup Team, 

I'm facing issues since a month now with the WebApp version of ButterCup.
I'm using firefox and having BC V1.11.1 and the bug was present with older version. 

I can't connect to my servers using WebDav or Nextcloud choice. 
I have a 401 error answer from the Console of Firefox, but i have nothing on the log of my Nextcloud. 
Even if i type a good or bad password i have the same error : 
[info] Creating WebDAV connection to: https://cloud.tdu69.com/remote.php/webdav setup-index.js:1:85071
[info] Testing WebDAV connection... setup-index.js:1:85071
[error] WebDAV failed to connect: Invalid response: 401 Unauthorized setup-index.js:1:85071
[error] Failed establishing WebDAV connection: https://cloud.XXXXX.com/remote.php/webdav setup-index.js:1:85071
Error: "Connection failed to WebDAV service: https://cloud.XXXXX.com/remote.php/webdav"
connectWebDAVmoz-extension://9cf68431-8b6c-486e-b4b3-4ab641f01b02/setup-index.js:1:14433

On the Desktop client i have no problem to use WebDav or Nextcloud choice, it works like a charm. 

Anybody have the same problem ? 
Someone can help me to troubleshoot ? 
I have another nextcloud instance and i have the same bug.

Thanks

**Comment by perry-mitchell** [comment]
Hi @warnerbryce - Unfortunately this is the desktop application, and not the right place to post issues regarding the [browser extension](https://github.com/buttercup/buttercup-browser-extension). I'll close this issue.

If you still have issues you can open an issue there. But please remember that we cannot possibly reproduce every connection issue, and usually except only demonstrable bugs. Test with the Nextcloud demo instances first.
