### ISSUE TITLE
Error: Connection failed with Android app and NextCloud with .ovh extension

### ISSUE THREAD

**Issue by skriwell** [buttercup/buttercup-desktop#658]
Hello,
(My English is not good, so it's a translation of Google)
With the Android app, I can not connect to my NexCloud. I have the following message: "Error: Connection failed"
By cons with the desktop app, it works.
My Nexcloud uses the .ovh extension
The problem can come from there?

Thanks

**Comment by perry-mitchell** [comment]
Hi, unfortunately this is not the right place for mobile issues. That would be on our [mobile repo](https://github.com/buttercup/buttercup-mobile).
