### ISSUE TITLE
Connect cloud dropbox

### ISSUE THREAD

**Issue by waguirre** [buttercup/buttercup-desktop#661]
Problem connect cloud dropbox

![image](https://user-images.githubusercontent.com/2904511/46831938-67699400-cd6a-11e8-891d-1f997057e958.png)

**Comment by perry-mitchell** [comment]
@waguirre Please include more information, like what version of Windows, exact steps to reproduce the issue, which version of Buttercup. Have you tried more than once?

Consider that the information you provide should be enough to reproduce the issue. I've not been able to see Dropbox fail like this.

**Comment by evileumas** [comment]
I have the same issue. 
SO: Windows 10 version 1803 OS Build 17124.345
buttercup: v1.10.2

**Steps to reproduce:** 
1. Connect cloud sources
2. Select Dropbox
3. Click on AUTHENTICATE WITH DROPBOX
4. Enter Credentials and Sign in
![butter_cup](https://user-images.githubusercontent.com/7860597/46894527-ad396180-ce29-11e8-97db-07dca9dc53c1.PNG)

If you close the pop up you get 
![butter_cup_2](https://user-images.githubusercontent.com/7860597/46894541-b6c2c980-ce29-11e8-95dd-3996988b9e57.PNG)

**Comment by evileumas** [comment]
@perry-mitchell This error only happens on v1.10.2, I just tried on v1.10.1 and Dropbox works fine.

**Comment by Darkblader24** [comment]
I have the same issue on v1.10.2.
I tried to connect to Dropbox but after I authorized Butterfly to use Dropbox it just redirects to the homepage of Buttercup and nothing happens. If I close the window I get the error message that the conntection to Dropbox failed.

**Comment by perry-mitchell** [comment]
Hi everyone - I can confirm this bug. There's been regression in the 1.10.2 release. We'll be looking into it immediately.

**Comment by perry-mitchell** [comment]
@waguirre @evileumas @Darkblader24 Thanks for taking the time to comment on the issue. We've managed to find the issue (API change in Electron) and patch it, release pending.

**Comment by perry-mitchell** [comment]
This has been fixed and is available in 1.10.3.

**Comment by waguirre** [comment]
Working thanks to all for your comments...
