### ISSUE TITLE
[question] mobile, ui, ux, stack

### ISSUE THREAD

**Issue by Thomazella** [buttercup/buttercup-desktop#664]
Hi guys :)

The password manager is great! Really like it. I'm considering contributing to the project and I have a few questions

- It uses react and electron right? With redux-thunk.
- Do you think a react native version/mobile version is feasible? Does it exist already?
- Would you be open to discussing the UI design and UX? I think there's room to improve it.

Cheers :)

**Comment by sallar** [comment]
Hi @Thomazella!
A mobile version is available for Android and iOS. You can find it from here: https://github.com/buttercup/buttercup-mobile

We are working on a redesign of our UIs starting with the browser extensions. But we welcome any UX related discussions and ideas :)

**Comment by Thomazella** [comment]
Awesome! I'll use the mobile version right away.

**Comment by perry-mitchell** [comment]
> Is there any mockups of the new UI for the browser?

Not yet, but you're welcome to [follow the progress](https://github.com/buttercup/buttercup-browser-extension/pull/177).

**Comment by perry-mitchell** [comment]
I believe the question(s) have been answered, so I'll close this issue. We can reopen if necessary.
