### ISSUE TITLE
Exception when adding a password

### ISSUE THREAD

**Issue by gabo01** [buttercup/buttercup-desktop#673]
Unhandled Promise Rejection
ReferenceError: Inigo is not defined
    at r (file:///opt/Buttercup/resources/app.asar/dist/main.bundle.js:230:280951)
    at file:///opt/Buttercup/resources/app.asar/dist/main.bundle.js:230:282122

**Comment by perry-mitchell** [comment]
Could you please confirm that the error occurs when saving a new entry item?

What version are you using?

**Comment by julian7** [comment]
I can confirm this error exists when creating a new entry. I'm using `Version 1.10.3 (1.10.3)`, downloaded from releases page, to MacOS Mojave 10.14.1. My app is at a different location, it gives the following error: 

```text
Unhandled Promise Rejection

ReferenceError: Inigo is not defined
    at r (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:230:280951)
    at file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:230:282122
```
