### ISSUE TITLE
[Linux] Error in warning.js file

### ISSUE THREAD

**Issue by zoheirkhonyagar** [buttercup/buttercup-desktop#675]
when I open buttercup desktop on ubuntu 18.04 i got this error :
`(node:4429) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`
![screenshot from 2018-11-03 11-52-46](https://user-images.githubusercontent.com/21988949/47949927-f3cd3800-df5f-11e8-802e-c0f2ec10a232.png)

**Comment by perry-mitchell** [comment]
This is just a deprecation.. not really an issue. I’m sure many libraries that use buffers suffer from such warnings.

I guess you opened the dev tools yourself?

**Comment by zoheirkhonyagar** [comment]
> This is just a deprecation.. not really an issue. I’m sure many libraries that use buffers suffer from such warnings.
> 
> I guess you opened the dev tools yourself?

yes man I opened it
