### ISSUE TITLE
Cannot connect to WebDAV

### ISSUE THREAD

**Issue by Extarys** [buttercup/buttercup-desktop#676]
I keep getting credentials error with buttercup. The strange thing is that the error message have an extra character to the URL.

Version: 1.10.3

URL:
`https://192.168.1.146:5006` or `192.168.1.146:5006` or `https://192.168.1.146:5006/home/`

The IP address have a valid certificate trusted by my computer.

Username and password are valid since I just tested them with another password manager's WebDAV functionality.

Same issue applies to Firefox extension - so I cannot use ButterCup at the moment :cry: 

![flameshot-2018-11-04-01 05 25](https://user-images.githubusercontent.com/11581433/47960779-fb2b2a80-dfcd-11e8-8bf4-7e64f3b49f28.png)

**Comment by perry-mitchell** [comment]
Hi @Extarys - What version of the browser extension are you using? It should be v2.

What WebDAV server are you using? It's possible that we don't have support for it.

**Comment by perry-mitchell** [comment]
Ah, I missed the fact that that you’re using self signed certificates. Buttercup only supports certificates signed against public authorities- ie SSL certificate services.

This is due to the fact that it uses Chrome under the hood, which has this requirement.

**Comment by perry-mitchell** [comment]
I've made mention of the [self-signed cert limitation](https://github.com/buttercup/buttercup-desktop#webdav) in the readme. Unfortunately this is not currently on our roadmap.

**Comment by Extarys** [comment]
I should have mention that I also tried with a Let's encrypt certificate later. It's synology WebDav server.

Using enpass I can enter https://mydomain.com:5006/home/ and it works and create the database file there.

Port 5006 is the WebDav SSL port on a synology server.

```
Version
    2.0.0
Browser
    name: Firefox
    version: 63
    fullVersion: 63.0
    os: Linux
```
