### ISSUE TITLE
[Feature Request] Undo edit to login

### ISSUE THREAD

**Issue by willisplummer** [buttercup/buttercup-desktop#679]
accidentally almost lost my non-recoverable password for an account while trying to update it to a new one because i generated the new password, clicked use this and then save before realizing i needed to enter the old one into a form.

I ended up having to revert my password list on dropbox to recover the older password but it was pretty touch and go for a second there 😅 -- would be really nice if there was the ability to undo a single change (cmd+z) for situations like this one

**Comment by perry-mitchell** [comment]
Great point! I can appreciate the fear of doing exactly what you did.. I've had to do the same.

Buttercup actually keeps the history of **all changes to every entry**, but currently doesn't provide a way to access this information. I've created #680 for this (I'd thought that we already had such an issue, but I couldn't find one).

I'll close in favour of that issue. Upon its completion you'll be able to view the previous value and restore it if needed.
