### ISSUE TITLE
Cannot scroll at the column of entry

### ISSUE THREAD

**Issue by wyudong** [buttercup/buttercup-desktop#684]
OS: macOS 10.14
BC: 1.10.3

When the number of entries is greater than the one can be displayed in a window, mouse cannot scroll up/down the entries. But using trackpad is OK.

![2](https://user-images.githubusercontent.com/5687273/48061050-b0d9c180-e1f8-11e8-99f8-4abf6cf3cd98.jpg)

**Comment by wyudong** [comment]
The mouse scrolling cannot be reproduced after restarting my Mac. The mouse is Logi M585 bluetooth.

**Comment by wyudong** [comment]
Closing.

**Comment by sallar** [comment]
Thanks for the update @wyudong please let us know so we can reopen if it happens again :)

**Comment by julianpoemp** [comment]
I'm facing the same issue. Scrolling using the Magic Mouse 2 or the trackpad works, but not with mouses that use a scrolling wheel. This bug is not fixed.

Mouse: Logitech MX Anywhere 2S, Bluetooth
Client: 1.16.2
macOS: 10.14.6 (18G87)
