### ISSUE TITLE
Auto-refresh vault contents after time

### ISSUE THREAD

**Issue by tourtools** [buttercup/buttercup-desktop#686]
Hello,

when you add a new item from browser, in the desktop application it doesn't show, to show it you need to do a view>reload, but it bumps you out and you need to re-authenticate.

Is it possible to add a Refresh action which doesn't need a new login?

**Comment by sallar** [comment]
Hi @tourtools we have already added this to the browser extension (since it's a new feature in core), but we are working on adding it to the desktop app too :) Stay tuned!

**Comment by perry-mitchell** [comment]
@sallar We should jump on this soon! Let's chat about how we can make this happen. I suspect that we can load in the background without preventing user mouse selection etc., but perhaps disabling the _edit_ functionality while updating/merging would be best. If the user is editing we can delay the update until they're finished.

**Comment by perry-mitchell** [comment]
Fixed in v2.
