### ISSUE TITLE
Global hotkey

### ISSUE THREAD

**Issue by mokhosh** [buttercup/buttercup-desktop#702]
Hi, thanks for this awesome app.

Can we add a global hotkey for maximizing/minimizing buttercup?
It would be also nice to have a preferences dialog where we can customize these things.

**Comment by ph1p** [comment]
Hi! I'm currently working on a preferences window https://github.com/buttercup/buttercup-desktop/pull/699 and added the max and minimizing feature you've mentioned. Feel free to pull and test it :) The shortcut is: **CommandOrControl+Shift+B**

**Comment by mokhosh** [comment]
Thanks, awesome job. Can we customize hotkeys btw?

**Comment by ph1p** [comment]
Definitely! I'll create a solution inside the preferences window later. Currently it's hard coded.

Maybe a restart of buttercup is required, we will see (:

**Comment by ph1p** [comment]
@mokhosh I have pushed a solution to my branch. Please take a look at it.  (:

![screenshot 2019-01-22 at 21 50 34](https://user-images.githubusercontent.com/15351728/51564612-0c2e5e00-1e90-11e9-934f-d573cca2dbc8.png)

**Comment by ph1p** [comment]
Jep. Just clone it, run `npm i` and `npm start` or `build`.

**Comment by mokhosh** [comment]
Good job.

I don't think the minimize/maximize shortcut is global. It does minimize the window when it's focused but doesn't bring it back when it's not.
Also, the preferences window looks weird in Windows (tabs are way too big).
And I think preferences usually belongs in Edit menu, doesn't it?

**Comment by ph1p** [comment]
Thank you for your feedback! 👍 I'm developing this feature on Mac. I will test everything under windows again. The design is only functional.  I will redesign it and test it again everywhere.

> I don't think the minimize/maximize shortcut is global. It does minimize the window when it's focused but doesn't bring it back when it's not.

Okay. Good to know! Maybe that's a problem with Windows. 
I take a look at it.

> And I think preferences usually belongs in Edit menu, doesn't it?

I think on windows, this makes sense. 
The preferences window on mac is always included in the first tab.
![screenshot 2019-01-24 at 23 14 17](https://user-images.githubusercontent.com/15351728/51712024-dc1cc180-202d-11e9-921b-d8e07ff7aa30.png)
![screenshot 2019-01-24 at 23 14 08](https://user-images.githubusercontent.com/15351728/51712025-dcb55800-202d-11e9-9fac-3d1e4f93b442.png)
![screenshot 2019-01-24 at 23 13 55](https://user-images.githubusercontent.com/15351728/51712027-dcb55800-202d-11e9-9009-3e6619900f82.png)

Thank you again for your feedback ;)

**Comment by ph1p** [comment]
@mokhosh Fixed global hotkey and disable the menubar in preferences window

**Comment by ph1p** [comment]
Fixed it (: The setting of the tray icon is now taken into account. The `redux-subscriber` package is now added to the `package-lock.json`.

**Comment by ph1p** [comment]
Good to hear! (: I've already created an issue. https://github.com/buttercup/buttercup-desktop/issues/740 But yeah, this shouldn't be a problem at the end. 

Next steps for me: Testing if all settings work correctly, writing tests and creating a final design.

**Comment by mokhosh** [comment]
any updates on this?
