### ISSUE TITLE
FF WX access to local vault not working

### ISSUE THREAD

**Issue by n8v8R** [buttercup/buttercup-desktop#703]
W10 Pro x_64 v1809 b17763.134
BC desktop v1.12.0
FF 65.0a1 (2018-11-27) (64-bit)
BC WX v2.1.1

Having inserted the Authorization Code generated by the desktop app into the FF WX and then clicked Authenticate this always produces

![bc wx](https://user-images.githubusercontent.com/13611490/49104633-591dfb80-f276-11e8-9e4d-bb422751ee59.png)

FF console putput

>  [error] Failed fetching localfile contents of '/': Failed reading remote file: / setup-index.js:69:6821 
> Navigation error
>       tabId: 109
>       url: about:blank
>       error: Error code 2152398850
> utils.js:188:7
> Navigation error
>       tabId: 109
>       url: view-source:moz-extension://fd885cb3-eecb-4a79-a774-f9dcbec1e680/setup-index.js
>       error: Error code 2152398850 utils.js:188:7
> Security Error: Content at moz-nullprincipal:{3a77d067-5df3-41c8-8f4c-6f5eb8fff965} may not load data from moz-extension://fd885cb3-eecb-4a79-a774-f9dcbec1e680/setup-index.js.
> NS_ERROR_DOM_BAD_URI: Component returned failure code: 0x805303f4 [nsIWebNavigation.loadURI] viewSource-content.js:284
> SecurityError: The operation is insecure. instrument.js:35

**Comment by perry-mitchell** [comment]
Also reproducible in Chrome :(

**Comment by perry-mitchell** [comment]
Error is something we saw during development:

```
{ [Error: EPERM: operation not permitted, stat 'C:\Config.Msi']
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'C:\\Config.Msi' }
```

This is actually fixed in a newer dependency version, but something has gone wrong in packaging.

**Comment by n8v8R** [comment]
> Error: EPERM: operation not permitted

seems related to user rights for package installation, also indicated by *mis and thus I am doubtful of bearing a correlation to the actual browser error (security violation)

> Security Error: Content at moz-nullprincipal:{3a77d067-5df3-41c8-8f4c-6f5eb8fff965} may not load data from moz-extension://fd885cb3-eecb-4a79-a774-f9dcbec1e680/setup-index.js.
> NS_ERROR_DOM_BAD_URI: Component returned failure code: 0x805303f4 [nsIWebNavigation.loadURI] viewSource-content.js:284
> **SecurityError: The operation is insecure**. instrument.js:35

Maybe you could check the console output in Chrome and see whether it is something similar.

**Comment by perry-mitchell** [comment]
Ah, good point. I immediately attempted to reproduce, saw the same popup error again and thought it was related - it is not.

Your error looks more like CORS, which can be fixed just as easily (if it is so). I'll fix the obvious bug that I was referencing and will then try to reproduce your exact error.

Apologies for the inconveniece!

**Comment by perry-mitchell** [comment]
Quite bad documentation on the **NS_ERROR_DOM_BAD_URI** error. I only really found this one SO post: https://stackoverflow.com/questions/15229330/attempt-to-add-a-rule-to-a-css-stylesheet-gives-the-operation-is-insecure-in-f - It's for CSS but presents a good case for it being CORS related.

**Comment by sallar** [comment]
@perry-mitchell it also looks like that Firefox is expecting https requests?

**Comment by n8v8R** [comment]
> Quite bad documentation

Suppose you had a look at https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIProtocolHandler#Constants ?

`ALLOWS_PROXY` `ALLOWS_PROXY_HTTP` `URI_IS_LOCAL_FILE` `URI_INHERITS_SECURITY_CONTEXT`

**Comment by perry-mitchell** [comment]
@n8v8R Nope! That's new to me. Thanks for that - I'll keep it in mind if a simpler solution is not possible :)

**Comment by perry-mitchell** [comment]
@sallar I still suspect CORS, as we never added CORS headers on the secure-file-host. We should be setting them [here](https://github.com/buttercup/secure-file-host/blob/master/source/host.js#L52). We could also use the [cors package](https://www.npmjs.com/package/cors).

**Comment by perry-mitchell** [comment]
I'm not able to reproduce your issue @n8v8R. The only error I see is the permission one, which I can easily fix by running a newer version of the dependency I mentioned (to be released in a couple of hours).

I suspect that there could be something else going on here, such as a more restrictive security configuration in your Firefox install. My firefox is running with defaults - have you modified something which may affect this feature?

**Comment by n8v8R** [comment]
@perry-mitchell 
I just tested with maiden profiles each on FF 63.0.3 and FF Nightly and both producing the same issue.

I would not imagine this being an issue with any OS settings considering the error reported in the log, this one now from 63.0.3

> [error] Failed fetching localfile contents of '/': Failed reading remote file: / setup-index.js:69:6821
> Security Error: Content at moz-nullprincipal:{f2771ac4-9652-4a2b-9999-aabdaa61d1c8} may not load data from moz-extension://a4954087-9f0a-49dd-bbd6-97cf847b785e/setup-index.js.
> NS_ERROR_DOM_BAD_URI: Component returned failure code: 0x805303f4 [nsIWebNavigation.loadURI] viewSource-content.js:284 

`view-source:chrome://global/content/viewSource-content.js`
    `webNav.loadURI(URL, loadFlags, null, null, null);`

**Comment by n8v8R** [comment]
Tried it now with Vilvaldi 2.1.1337.51 (Stable channel) (64-bit) which is based on Chrome 70.0.3538 and it produces the same error but different log output

> [info] Checking local endpoint
> setup-index.js:69 [info] Received status from local endpoint: ok (ready: true)
> setup-index.js:69 [info] Beginning handshake
> setup-index.js:69 [info] Initial connection phase completed
> setup-index.js:69 [info] Completing handshake using code
> setup-index.js:69 [info] Received key: Handshake complete
> setup-index.js:69 [info] Fetching remote contents for path: /
> localhost:12821/get/directory:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> setup-index.js:69 [error] Failed fetching localfile contents of '/': Failed reading remote file: /

**Comment by n8v8R** [comment]
1.12.1 solved the issue for both browsers, i.e. it is working now with FF as well as Vivaldi

**Comment by perry-mitchell** [comment]
Thanks for the help @n8v8R! Glad it was solved.
