### ISSUE TITLE
Windows binary code signing

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#704]
We should be codesigning our build on Windows before releasing.

**Comment by perry-mitchell** [comment]
Links:
 * [Electron builder code signing](https://www.electron.build/code-signing)
 * [Comodo certs](https://www.comodo.com/landing/ssl-certificate/authenticode-signature/)

**Comment by n8v8R** [comment]
The code signing with Electron been taken up already earlier, not?

https://github.com/electron-userland/electron-builder/issues/3188

**Comment by jenstornell** [comment]
Maybe this comment https://github.com/buttercup/buttercup-desktop/issues/690#issuecomment-442603899 belongs here:

![](https://user-images.githubusercontent.com/13611490/49182063-1ed55c80-f351-11e8-8f48-5752100e9739.png)

**Comment by perry-mitchell** [comment]
Certificate purchase is underway.. Just waiting for the validation to be completed.

**Comment by perry-mitchell** [comment]
Validation complete - Now we just need to add the signing process to the desktop build procedure.

**Comment by n8v8R** [comment]
Looks like it does not make a difference with Defender's SmartScreen

![defender smart screen](https://user-images.githubusercontent.com/13611490/50606449-ae74aa80-0ebd-11e9-901f-1587a9e0bf9b.PNG)

**Comment by sallar** [comment]
@n8v8R this warning will go away once more users start to install it. It shows our company name now. But because it’s not a EV (expensive) cert it will take a while to be fully trusted :)
