### ISSUE TITLE
[Linux] StartupWMClass missing from .desktop file

### ISSUE THREAD

**Issue by AmazingBeu** [buttercup/buttercup-desktop#705]
When you pin buttercup in Gnome 3 and launch the application, the window created by the application is not associated with the shortcut used to start the application.

![screenshot](https://user-images.githubusercontent.com/26152831/49161250-c2f6dd80-f328-11e8-954f-430e6f0cc14a.png)

To fix it, you can add this in the **build/buttercup-desktop.desktop** file : 

```
StartupWMClass=Buttercup
```

**Comment by perry-mitchell** [comment]
Thankyou @AmazingBeu! Great advice :)
