### ISSUE TITLE
WX local access displaying a non-existent folder

### ISSUE THREAD

**Issue by n8v8R** [buttercup/buttercup-desktop#709]
W10 Pro x_64 v1809 b17763.134
BC desktop v1.12.1
FF 65.0a1 (2018-11-27) (64-bit)
Vilvaldi 2.1.1337.51 (Stable channel) (64-bit)
BC WX v2.1.1

This folder is non-existent (neither hidden) on the drive and yet it is showing?

![non-existent folder](https://user-images.githubusercontent.com/13611490/49182967-92786900-f353-11e8-8f17-0df54b78d137.png)

**Comment by perry-mitchell** [comment]
The results are returned by regular filesystem queries using Node's `fs` module.. I would expect that it would be there in some form (mount/link etc.).

Do you have access to Git Bash? Maybe running an `ls -la` in that dir would show the directory..

**Comment by n8v8R** [comment]
Looks like link indeed, showing up as

> lrwxrwxrwx    1 SYSTEM   42949672        15 Oct  3 16:36 Documents and Settings -> /drives/c/Users

**Comment by perry-mitchell** [comment]
Ok.. Interesting. I think this feature will need fine tuning of course. Those `$..` prefixed could also be hidden.
