### ISSUE TITLE
[Linux] Enable Browser Access not available

### ISSUE THREAD

**Issue by skion** [buttercup/buttercup-desktop#711]
On the Add vault page, the following is mentioned:

> To connect a local vault on your computer you must first gain access by connecting to the Buttercup Desktop Application. Make sure that it's running and that that Browser access is enabled via the menu: System ❭ Enable Browser Access.

Yet, when running on Linux (Ubuntu 18.10, GNOME), there seems to be no way to `Enable Browser Access` for the desktop client?

**Comment by perry-mitchell** [comment]
Is the `System` menu not available for you? Can you screenshot your menu bar?

**Comment by skion** [comment]
Here you go...

![buttercup](https://user-images.githubusercontent.com/532192/49314004-fe3c0c80-f4e0-11e8-940b-d20d81d2be70.png)

**Comment by sallar** [comment]
That's interesting @skion, so none of Buttercup's menu items are visible? Is that a custom skin on your Ubuntu or is it something that comes by default?

**Comment by skion** [comment]
@sallar No, just standard Ubuntu with GNOME, which is (I believe) the default again in 18.10.

Related to this, was wondering if it makes sense to expose the option as a command line parameter as well.

**Comment by zedgoat** [comment]
Everyone - menu is there but the text is blended in with the background - if you click in the strip between the titlebar and the vault display you can still trigger the menus. They also become visible when the window loses focus.

Same observation under Gnome on Ubuntu 18.10.

**Comment by skion** [comment]
I can confirm: Menu is indeed there, just not visible...

**Comment by sallar** [comment]
Seems like this is an issue with Electron. I'll investigate updating the electron dependency to see if it fixes the issue.

https://github.com/electron/electron/pull/15878

For this I'll need to also install Ubuntu 18

**Comment by perry-mitchell** [comment]
Any updates on this? Anyone still experiencing this issue? Works for me on Ubuntu 18.04.

**Comment by sallar** [comment]
This should have been fixed in the latest version since electron has fixed their issue. Can anyone confirm?

**Comment by perry-mitchell** [comment]
App menu is working on Ubuntu as of v2, closing this.
