### ISSUE TITLE
As a user, when I hover buttons, I want (title?) tooltips on everything so I know what buttons do #Enhancement

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-desktop#713]
Hi all,

Hope you're well

Thanks for software

As a user, when I hover buttons (notably in edit state), I want (title?) tooltips on everything so I know what they do

Screen shot/cast:

![foo mov](https://user-images.githubusercontent.com/1715809/49250794-17c94f80-f420-11e8-9650-589e961b9cb3.gif)

If you're reading this and:

a) agree, then please up-vote and/or reply +1, or;
b) disagree, then I'd love to know why?

Unless you specify a time frame, I'll follow up again in the near future and base my decision to keep using buttercup on whether this is fixed

If you have any issues (e.g. questions/queries) happy to help

Hope this helps!

Keep up great work!

Cheers

**Comment by perry-mitchell** [comment]
I think tooltips are very important - good idea!
