### ISSUE TITLE
As a user, when I generate passwords inside the tooltip, what's the meaning of the cursor and the intended functionality (if any)? #Help #Question

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-desktop#714]
Hi all,

Hope you're well

Thanks for software

As title

Screen shot/cast:

<img width="1440" alt="screenshot 2018-11-29 at 21 07 25" src="https://user-images.githubusercontent.com/1715809/49251285-6b886880-f421-11e8-867f-cbf77e9d1dda.png">

NB If the intended functionality is to copy the password string on click, which is what the cursor suggests and I'd expect/wish, then this isn't working for me

If documentation exists then feel free to link me or else can something on this topic be added to the documentation?

If you have any issues (e.g. questions/queries) happy to help

Hope to hear back

Keep up great work!

Yours faithfully

**Comment by ldexterldesign** [comment]
BUMP

**Comment by perry-mitchell** [comment]
@ldexterldesign Stepping in for @sallar on this one - I'm not sure if it has any specific meaning... but it should somehow indicate that clicking the password in the generator selects and copies the whole text. This needs some tweaking as I'm not sure it works on every environment right now, but it should select the whole password and copy it - there may be a bug here if it's not working like that.

The generator is stored in the [ui project](https://github.com/buttercup/ui).

**Comment by ldexterldesign** [comment]
Thanks for reply

No, doesn't work for me in macOS

New label(s) or should I create an issue in the other repo[r]?

Cheers

r: https://github.com/buttercup/ui

**Comment by perry-mitchell** [comment]
@ldexterldesign It would be advantageous to have the issue in other repos where it's present, if you have time :)

**Comment by ldexterldesign** [comment]
Transferred[t]

Cheers

t: https://github.com/buttercup/ui/issues/19
