### ISSUE TITLE
Show a warning when saving two custom fields with the same label

### ISSUE THREAD

**Issue by uwqwxing886** [buttercup/buttercup-desktop#717]
If you save an entry after adding two custom fields with the same label (like "URL") only the last one will be saved.

**Comment by uwqwxing886** [comment]
I'm new to the code but it seems like the underlying structure is a key-value store that doesn't allow multiple fields with the same key (label), therefore that is why a warning message was suggested.

**Comment by perry-mitchell** [comment]
Good idea! I would also prevent saving for such situations.

**Comment by ldexterldesign** [comment]
I lost some crucial banking/finance data today because of this issue. It's not the first time it's happened (usually duplicate data which I tolerate) but it is the first time it's been important data.

Please consider higher priority or even bug status

Yours hopefully

**Comment by perry-mitchell** [comment]
@ldexterldesign Agreed it could be higher prio. We don't currently have bandwidth for it, and would hope that someone could contribute it. Sorry that you lost some data.

**Comment by keywordnew** [comment]
I hit this bug today. Saved 10 custom fields (as a workaround for not being able to create a note-like item instead of a login entry/item) and it only kept the last one.
