### ISSUE TITLE
Error unlocking source

### ISSUE THREAD

**Issue by Cecios0** [buttercup/buttercup-desktop#718]
Hi,
I show this error when try to unlock with master password:

Error: Failed unlocking source: "" : Failed mapping credentials to a source: Invalid response: 401
I have reinstalled buttercup-desktop-setup-1.12.2 but the error show again.
Thanks

**Comment by perry-mitchell** [comment]
401 is a http error - “unauthorised”. Either your password is wrong or the connection is failing due to invalid data.

Please include details regarding what you’re connecting too, how it’s hosted etc.

**Comment by Cecios0** [comment]
Hello,
problem solved. I reset my connection to my cloud and now the problem is solved.
Thanks for your help
