### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by yiftizur** [buttercup/buttercup-desktop#724]
Cannot connect to Dropbox behind a proxy
===================================
We have a corporate proxy, and trying to authenticate with Dropbox, i get an `Error: read ECONNRESET` in internal/process/next_tick.js.

I could find no place to define a proxy, and starting the process with a --proxy-server argument did nothing to help...

**Comment by Schroeffu** [comment]
I think I have a similar issue in the windows app: Cannot connect to external NextCloud (url and standard port 443) behind a company proxy, unfortunately there is no option to say use "windows-defined-proxy" or similar.
