### ISSUE TITLE
Exception when starting Windows App

### ISSUE THREAD

**Issue by ajfoster85** [buttercup/buttercup-desktop#734]
When starting the Windows app, an error screen appears with the following exception details:

> Unhandled Error
Error: listen EADDRINUSE :::12821
    at Function.y.listen (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:321:4541)
    at createHost (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:199:240237)
    at startFileHost (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:171:26943)
    at fc (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:406:123939)
    at C:/Program Files/Buttercup/resources/app.asar/dist/app.js:406:130490
    at Nc (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:406:130495)
    at App.i.app.on (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:406:134595)

Version is 1.14.0 and it's a fresh install (I've only just started using it). I am also using the Firefox extension on the same computer (v2.3.0).

**Comment by perry-mitchell** [comment]
It seems that something's listening on that port already, which is weird. It's not reserved in the IANA port registrations, so I can't imagine that another process would be randomly using it.

Would it be possible for you to [check what process is using that port](https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows)?

**Comment by AndreasFurster** [comment]
I'm not sure if the referenced commit solved the whole problem. I am experiencing the same issue and have some more info. 

I think the issue occurs when Buttercup is initially started by the browser extension and then opened in Windows. 

After opening a couple of instances via the browser or Windows I have a lot of instances of Buttercup. Even after closing all windows the processes stay active. At the moment I have 7 processes of Buttercup without a opened window. There is however only one system-tray icon.

I have not looked into the internals of Buttercup, but I suspect there is a http listener started multiple times. This causes to have the port used multiple times by Buttercup.

**Comment by perry-mitchell** [comment]
Thanks for checking on this! It could be that the listener/server is not closed properly on shutdown, or something to that effect.

**Comment by perry-mitchell** [comment]
Closing as the issue relates to a port in use. Either close the other app using the port, or disable Buttercup's browser connection feature.
