### ISSUE TITLE
update message while typing archive password

### ISSUE THREAD

**Issue by leongrdic** [buttercup/buttercup-desktop#736]
every time (when theres an update available) i open buttercup and start typing the password the update window appears right in the middle of typing the password so its kinda annoying to have to close the window to enter the password again.
i think maybe the best solution would be not to use the update window at all, because people usually open buttercup only when they need to copy a password so they dont want to update right away (and interrupt what they were previously doing), and if they close the window might forget to update later. so i suggest you add a little badge somewhere inside the app, kinda like Atom does, that says "update available, click to update".
that way the update notification wouldnt interrup the user in doing whatever they wanted but it would still make it obvious an update is available.

**Comment by perry-mitchell** [comment]
Good idea! I know the feeling of frustration with popup windows.. Telegram does the same thing for me.

I would think something like an in-window update notification, in say the bottom-right corner, could make this issue less of a problem? We want users to update - it's very important - so I don't think we'd want to hide it like with VSCode or something.

It could sit in the corner so users aren't disturbed by it:

![image](https://user-images.githubusercontent.com/3869469/51518287-16b40d80-1e26-11e9-9138-87c0d9ef3e6c.png)

This would allow it to be enough of a nag to get the user to click it, while not interrupting typing or stealing focus.

Thoughts?

**Comment by leongrdic** [comment]
this seems like a decent solution. the only problem could be the notification covering some buttons in the corner, but i guess you could adjust the notifications position accordingly.

**Comment by perry-mitchell** [comment]
> the only problem could be the notification covering some buttons in the corner

Of course the overlay could have a closing button just like the Cancel button in the update dialog now.. so functionally it'd still be as usable.

**Comment by perry-mitchell** [comment]
Closing in favour of #847
