### ISSUE TITLE
Cannot start dev server

### ISSUE THREAD

**Issue by ph1p** [buttercup/buttercup-desktop#740]
Hi

I have two problems with the buttercup dev server.
It cannot install this package:
```
"kdbxweb": {
"version": "1.2.4",
"resolved": "https://registry.npmjs.org/kdbxweb/-/kdbxweb-1.2.4.tgz",
"integrity": "sha512-n5ls0UtwcN+N2lalDP/ULDX9AhV37cNAnxKGjpnqOZL3OmTMnbVW01wGwWxZpdxRBOxUIQZ4w7dNlQFbngrtbA==",
"dev": true,
"requires": {
-------------> "pako": "github:keeweb/pako#653c0b00d8941c89d09ed4546d2179001ec44efc",
"text-encoding": "github:keeweb/text-encoding#4dfb7cb0954c222852092f8b06ae4f6b4f60bfbb",
"xmldom": "github:keeweb/xmldom#ec8f61f723e2f403adaf7a1bbf55ced4ff1ea0c6"
},
```

**Error:**
```
Could not install from "node_modules/kdbxweb/pako@github:keeweb/pako#653c0b00d8941c89d09ed4546d2179001ec44efc" as it does not contain a package.json file.
```
To fix it, I removed the package-lock.json. After I run `npm i` again, buttercup starts and shows an error on this line:
https://github.com/buttercup/buttercup-desktop/blob/master/src/renderer/index.js#L37

This is, because `npm i` updates the `buttercup` package from `2.7.0` to `2.10.0`.
My question is: "What is this line for?" As I can see, it now uses axios. 
Couldn't we remove this line and update the `buttercup` package?

**Comment by perry-mitchell** [comment]
@ph1p Can you try `npm install kdbxweb`? It works for me, albeit with a few errors:

![image](https://user-images.githubusercontent.com/3869469/51937561-a273fe00-2413-11e9-9f9f-f3862205703d.png)

It could be just some caching that broke on your machine.. Good if it goes away after removing package-lock.json.

**Comment by perry-mitchell** [comment]
With regards to that error, yes, we can remove that line now that we're using axios.

**Comment by ph1p** [comment]
I pulled it again and it works ... strange 🙄 Maybe it was really a cache problem.

> With regards to that error, yes, we can remove that line now that we're using axios.
Ok cool (:
