### ISSUE TITLE
Use facades to render specific entry types (note, OTP, password etc.)

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#742]
Use the core facades functionality to render specific types like **Credit cards** and **Notes**.

All fields in an entry should be rendered dynamically from the facade type matching the entry. Custom fields should then be able to be added.

**Comment by loxK** [comment]
Can't wait for OTP and credit cards support in desktop version to switch from Enpass ...

**Comment by perry-mitchell** [comment]
Closing in favour of #807
