### ISSUE TITLE
Buttercup dropbox function not working in Tor Browser

### ISSUE THREAD

**Issue by gerkmao** [buttercup/buttercup-desktop#743]
Tried using the password manager in the Tor browser with Tor network disabled, but it doesn't work. Other password managers work, but not buttercup.  When i click on "grant dropbox access" it redirects to buttercup.pw, but no vault is created.

Version and info

Version
    2.3.1
Browser
    name: Firefox
    version: 60
    fullVersion: 60.0
    os: Windows

**Comment by perry-mitchell** [comment]
Hi @gerkmao - this is the wrong repository. You want https://github.com/buttercup/buttercup-browser-extension

I'll close this.
