### ISSUE TITLE
Support for notes

### ISSUE THREAD

**Issue by vkuznet** [buttercup/buttercup-desktop#751]
Hi, I recently found buttercup and considering it as alternative of 1password. One thing I found that is missing is an import notes and basically general support for notes. I can create a new entry field, but text entry field is just one line. My question/request is the following:
- do you plan to support importing 1password secure notes
- can you make some changes to UI to make entrance of notes more comfortable, e.g. larger textfield where user can place text in some formatted form (paragraphs).

**Comment by perry-mitchell** [comment]
Hi @vkuznet! We will be supporting notes, that'll be handled by #742. Due to that I'll close this issue as a duplicate.

> do you plan to support importing 1password secure notes

Yes, once #742 is implemented we can add import support for notes from other managers.

> can you make some changes to UI to make entrance of notes more comfortable, e.g. larger textfield where user can place text in some formatted form (paragraphs).

Absolutely! This is currently underway.

Thanks for dropping by!
