### ISSUE TITLE
When to support Chinese language?

### ISSUE THREAD

**Issue by jearton** [buttercup/buttercup-desktop#752]

**Comment by ph1p** [comment]
Feel free to create an PR. All translations were done voluntarily.

**Steps:**
- Fork this Repo 
- Create a new branch
- Add **./locales/cn/base.json** to locales
- Update **./locales/config.json**
- Create a PR (https://github.com/buttercup/buttercup-desktop/compare)

**Comment by perry-mitchell** [comment]
Thanks for the write up @ph1p! Will close this now.
