### ISSUE TITLE
Can't unlock archive

### ISSUE THREAD

**Issue by Bangio19** [buttercup/buttercup-desktop#755]
Hello!
 I recently tried to open Buttercup and access to my passwords but when I entered my master password, it said : Archive source was not found.
I know the password is not wrong because I tried writing something else and it said : Authentification failed.
I also updated Buttercup but it didn't change anything.
Could you tell me what this means and if it is possible to have access again to my archive?
Thank you

**Comment by jqhercules** [comment]
I'm also experiencing the exact same issue.  It happened right after upgrading currently on v1.15.0

**Comment by Bangio19** [comment]
I forgot to close this topic but I actually managed to get to the archive. 
You shoud check if your archive is stored locally on your desktop or on the cloud, in your dropbox or in another app compatible with Buttercup. 
I hadn't any of those so I downloaded the chrome extension and then I could have access. I don't really know how that worked but there you go. I hope it helped you.
Cheers

**Comment by jqhercules** [comment]
I installed the extension after clicking "unlock vault" new tab appeared with the following 

Unlock archives
Noting shows

2019-03-13

Bugfix:

([#244](https://github.com/buttercup/buttercup-browser-extension/issues/244)) 
Google Drive fetching fails on large directories 

I have never used gdrive to store anything suggested to the link

**Comment by sallar** [comment]
Hi there! Can you remove the archive from Buttercup Desktop (right click on it and click remove) and add it again to see if it helps?

**Comment by jqhercules** [comment]
I removed the archive  as suggested but forgot to locate where its stored on my mac to restore it, so its all gone. You can close this thread.
