### ISSUE TITLE
Failed connecting to 'nextcloud' resource

### ISSUE THREAD

**Issue by IsidoreIsou** [buttercup/buttercup-desktop#758]
Hello, I get this error when I try to connect to my Nextcloud server, on Firefox or macOS app:
```
Failed connecting to 'nextcloud' resource
A connection attempt to 'my.server' has failed: Connection failed to WebDAV service: my.server/remote.php/webdav
```
I have a Let's Encrypt certificate.
Should I paste you a log?

Thanks for your help.

**Comment by boris779** [comment]
same here

**Comment by perry-mitchell** [comment]
@IsidoreIsou Hmm.. that's quite cryptic. A log may help! Please scan it first before sending, for any sensitive data.

**Comment by perry-mitchell** [comment]
Closing due to our deprecation of first-hand support of Nextcloud/ownCloud: https://github.com/buttercup/roadmap/blob/master/roadmap/CLOUD_SERVICES.md#unofficial-supportrecognition
