### ISSUE TITLE
Searchbar always visible

### ISSUE THREAD

**Issue by CSparn** [buttercup/buttercup-desktop#765]
Hi,
first I have to say that I really like this application.. nice work!
But one thing is a bit annoying. If you want to search the archive you have to use a button in the menu bar. It would be very nice if there is a search bar that is visible all the time. For example instead of the label that shows the amount of the entries.

Greetings

**Comment by perry-mitchell** [comment]
Thanks @CSparn - we can consider this but I don't personally see the hotkey approach to searching being a particularly difficult option. Having a search bar always visible takes up a lot of visual real estate, and it's maybe not a super common feature for all users to require. We'll definitely take this in to consideration as we actually have a new design on the horizon. -cc @sallar 

And thanks for the kind words!!

**Comment by jdeudy** [comment]
While I can certainly understand having a search bar takes up visual real estate, I agree with CSparn that instead of showing "Displaying # entries" at the top of the password list, this could be replaced with a search bar. Hope this is a feature that can be considered.

**Comment by sallar** [comment]
The new UI we are working on has the search box as well. You can see a preview of that in action in Buttercup Browser Extensions :)

**Comment by perry-mitchell** [comment]
Closing this as we've decided to stick with a hidden search input (until triggered). This is commonplace in many desktop applications nowadays.
