### ISSUE TITLE
Existing Vaults not listed in WebDAV View

### ISSUE THREAD

**Issue by kopfsalat** [buttercup/buttercup-desktop#767]
Hi,

I already set up the buttercup android app and browser extension. When I connect to my WebDAV (nginx + dav_ext module) I get a list of existing vaults. This fails in the desktop application. It obviously connects to the webdav and I can create new vaults but existing vaults are not listed. It is also possible to overwrite existing vaults without further ado if you create a new one with the same name.

I used v1.15.0 (.deb and AppImage) on Debian 9 / gnome 3.2.22

No related messages in debug log. Just an error about missing Buttercup/resources/app-update.yml

Dev Tools in the App has just one warning: fileManager.bundle.js:349 Wrapper div has no height or width, try overriding style with `containerStyle` option

Thanks for your help,
Jeldrik

**Comment by perry-mitchell** [comment]
Thanks @kopfsalat - Are you able to see what's returned in the network requests? Do you see any bcup vaults there? What about if you create a new one and then connect again, does that one show up?

What about if you access your webdav using another webdav client, can you see the .bcup files?

**Comment by kopfsalat** [comment]
Oh sorry, I missed your answer. I will hook an anylizer to it tomorrow and post you some data.

**Comment by kopfsalat** [comment]
Hi @perry-mitchell - I didn't manage to get the Application to log TLS Keys (therefor no usefull wireshark data) and the debug tools didn't really log something within the network tab. Maybe I did something wrong or maybe that is already part of the problem.

So, I took the other approach and logged the reponse on the webservers site: https://gist.github.com/kopfsalat/ec6890b3a63662458a8e745ddffab07d
Wireshark at least showed me tls traffic from my server that indicates the response arrived - but that's of course just an educated guess. 
Additionally I installed the firefox plugin on the same client. It works perfectly fine and as expected. I configured url, user and pw and got a list of existing vaults. I can select, add and edit them. 

If you give me some advice on debugging the app I would gladly provide more data.

**Comment by kopfsalat** [comment]
Did another quick test: created a new vault within the desktop app and added it. Used the browser addon and added it there (as mentioned browser app works fine). Quitted desktop app and started it again. The already added test vault was still there. I was able to edit and save data and I saw the changes in the browser app. Than I deleted the vault from the desktop app and tried to re-add it but it doesn't show up in the list of existing bcups on the server. The list is completly empty.

**Comment by joel-wright** [comment]
I can confirm the described behaviour on Ubuntu 19.04 as well.

**Comment by perry-mitchell** [comment]
This doesn’t make sense. It should not at all be related to the operating system of the client as it’s a network request - if the vault isn’t visible it’s either a server fault (less likely) or a request client error (not related to operating system)..

**Comment by joel-wright** [comment]
While I agree with what you're saying, I can only report the behaviour I'm seeing. I successfully added webdav vaults using the v1.15.0 desktop client on Ubuntu 18.04, but on Ubuntu 19.04 the webdav file listing is never populated. Using the Firefox extension worked fine, and the exact same credentials work fine to browse through nautilus on either version.

**Comment by Igneous** [comment]
Also seeing a similar thing using the 1.16.2 deb on a debian -testing desktop. Using lighttpd + mod-webdav as the webdav server. Cadaver connects and sees the .bcup file just fine, but the webdav listing in buttercup is empty.

I notice buttercup-desktop requests to PROPFIND the "/dav" collection instead of "/dav/", which causes a 301 redirect to the proper collection (and it's then served the proper data). I guess it's probably pretty unlikely this is the problem since it's following the redirect, but still worth mentioning.

e.g.:
```
2001:ee0:<snip> stor.<snip> username_here [31/Jul/2019:12:51:03 +0800] "PROPFIND /dav HTTP/1.1" 301 0 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
2001:ee0:<snip> stor.<snip> username_here [31/Jul/2019:12:51:03 +0800] "PROPFIND /dav/ HTTP/1.1" 207 1598 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
```

**Comment by perry-mitchell** [comment]
Stale, closing this. Please create a new issue if it's still occurring. We've had major upgrades on both the WebDAV client and the desktop app since.
