### ISSUE TITLE
Installed Buttercup and now I am lost .... (a bit)

### ISSUE THREAD

**Issue by bartve66** [buttercup/buttercup-desktop#769]
I looked for a manual or at least a getting started  / howto, but nothing there on the website, in the app, or here on github? Am I not looking hard enough?

Thanks!

[Update] Still trying to figure out some things that are not self explanatory (at least not to me ...).
Found out that the free version of Dropbox has a limit of 3 devices that can connect to Dropbox. Dropbox is my only option to keep the Buttercup archive in the cloud, and 3 devices is not enough for me, so I will divert my attention form Buttercup to KeepassXC ... see how that works out.
Just to share my considerations.

**Comment by perry-mitchell** [comment]
Hi @bartve66 - Sorry for this! We don't have all our ducks in a row yet with our documentation. The plan is to add it to the website, here: https://github.com/buttercup/buttercup-website/issues/49

With regards to Dropbox - unfortunately we can't control the sync limit of these external services. We're trying to get the Google Drive integration complete on the desktop and mobile apps, but trying to do everything we want at the same time is quite tricky! 

We appreciate the message and your experience.. Hope to see you around! :)
