### ISSUE TITLE
Always show password option

### ISSUE THREAD

**Issue by tmanaud** [buttercup/buttercup-desktop#770]
**Rationale:**
I handle login/password all the day along, and as I'm alone in my office, I dont mind always having the password in plain view.    

**Whish:**
- Have an option to always show password (without having to click on reveal every time).    

**Pro:**
- Time saving
- Password in plain test: easier to check if this password is weak and has to be upgraded or is - compromised.   

**Cons:** 
None, as it's a option to be enabled, default off

**Comment by perry-mitchell** [comment]
Sounds fine to me as an option, but it'd need to be set per-archive and not per Bcup app. This makes it more difficult as we don't have any UI to edit options per archive as of yet. Otherwise this is a good issue and I'll flag it as such.

**Comment by tmanaud** [comment]
@perry-mitchell why having a per-archive option? I don't see any issue with having it system/app wide from a security point of view. 
And it would be easier to implement too.

**Comment by perry-mitchell** [comment]
Well we have to consider the majority of people and use-cases, and having a system level option for what ultimately is reduced security is not a good idea in my opinion.. sorry.

**Comment by tmanaud** [comment]
> Well we have to consider the majority of people and use-cases, and having a system level option for what ultimately is reduced security is not a good idea in my opinion.. sorry.

I'm sorry but really see the issue with displaying the password. I mean you can place it in the system clipboard, it's actually a way bigger security risk than actually displaying it on the screen.

That's said, could we at least have larger "copy to clipboard" button? 
Like clicking anywhere on this field could place it in the clipboard would be nice.

Thanks for considering.
