### ISSUE TITLE
Import custom fields from 1Password

### ISSUE THREAD

**Issue by DavidJameson** [buttercup/buttercup-desktop#772]
I can't tell if #742 has been implemented but I just discovered Buttercup, tried to import my 1Password data and none of my note fields nor attachments came in --- it's not practical to move those manually --- any sense when it will become possible to import note fields and attachments? I would love to switch from 1Password now that it has become a subscription-based system and I really love that you are supporting NextCloud

**Comment by perry-mitchell** [comment]
I believe note fields should work, but my colleague probably has more experience here - @sallar?

Also, we don't _yet_ support attachments.

**Comment by sallar** [comment]
It should be included, but I can double check from the code. Will report back soon

**Comment by DavidJameson** [comment]
I think I mischaracteriszed the bug. It’s not note fields but in fact all extra fields that I added to the entry. I’ve attached a PDF with screen images showing what’s in 1Password and what shows up in Buttercup  (obviously, I’ve blurred most of the content, it’s sensitive but you can still see what’s going on).

Also, I looked at the exported data from 1Password and the data is there — below is the beginning of the section, again with sensitive fields replaced with 000 or xxx etc


"sections":[{"fields":[{"k":"concealed","v":"000-00-0000","n":"number","a":{"generate":"off"},"t":"xxx"},{"k":"string","n":"(long hex string here)","v":"000-00-0000","t":"xxx"},

**Comment by DavidJameson** [comment]
Well, that's annoying -- attachments sent via email replies don't show up (sigh). Here's the PDF showing the comparison
[Images.pdf](https://github.com/buttercup/buttercup-desktop/files/3350301/Images.pdf)

**Comment by DavidJameson** [comment]
I changed the title of this report to more accurately reflect what's actually going on.

**Comment by perry-mitchell** [comment]
Depends on buttercup/buttercup-importer#43

**Comment by perry-mitchell** [comment]
Removed attachments from title as that's a much larger task, and will be rolled out to all parts of the platform once we support it. It shouldn't block this issue.

**Comment by perry-mitchell** [comment]
Closing in favour of https://github.com/buttercup/buttercup-importer/issues/43 - Once that's done it'll be merged and released here.
