### ISSUE TITLE
Run as background helper rather than active application

### ISSUE THREAD

**Issue by daeh** [buttercup/buttercup-desktop#775]
UX feature suggestion: fo me (MacOS) it'd be great if the desktop application could be reduced to a background helper task rather than an open application. At present, I have to cycle past it in the application switcher and it takes up room in the dock, which seems very unnecessary since my only frequent interface with the application is through the browser extension.

This is a very promising project! Thanks for all the great work

**Comment by sallar** [comment]
@daeh This is already implemented in Buttercup:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/768052/60759681-e9ed5e80-a031-11e9-9d62-dadbc57a961c.png">

Make sure "Display in Menu bar" is active in "View" menu of Buttercup!

Thanks
