### ISSUE TITLE
Nextcloud Password Wallet seems not to work

### ISSUE THREAD

**Issue by Justinizer** [buttercup/buttercup-desktop#783]
> Unhandled Promise Rejection
Error: Request failed with status code 503
    at e.exports (file:///opt/buttercup-desktop/resources/app.asar/dist/main.bundle.js:356:254552)
    at e.exports (file:///opt/buttercup-desktop/resources/app.asar/dist/main.bundle.js:369:1318)
    at XMLHttpRequest.h.(anonymous function) (file:///opt/buttercup-desktop/resources/app.asar/dist/main.bundle.js:356:253550)

I updated buttercup to new version (1.16.0). Now I can't update, import or save passwords with nextcloud anymore. Maybe do you can go look over?

**Comment by perry-mitchell** [comment]
Webdav connections work fine for me in 1.16 - Such as Yandex. Unfortunately we can't help with connection issues to Nextcloud/ownCloud unless there's a demonstrable/reproducible issue with WebDAV in general. Nextcloud and ownCloud connections have been deprecated for some months/weeks I'm afraid :( - https://github.com/buttercup/roadmap/blob/master/roadmap/CLOUD_SERVICES.md#unofficial-supportrecognition

**Comment by Justinizer** [comment]
I have done a webdav Repository with nginx by mself now.
But I get following error: Failed unlocking source: 0b50a...: Failed mapping credentials to a source: Request failed with status code 500.
