### ISSUE TITLE
Browser extension does not reliably access unlocked archives 

### ISSUE THREAD

**Issue by daeh** [buttercup/buttercup-desktop#789]
Within the last week, the communication between the browser extension and the desktop app seems to have become unreliable. More often than not, the archive will be unlocked but the browser extension will not find an unlocked archive to access. I'm using the Chrome extension (2.7.0) and version 1.16.1 of the desktop app with Brave browser (0.66.100, chromium version 75.0.3770.142) on a Mac (10.14.5).

![Screen Shot 2019-07-17 at 4 23 20 PM](https://user-images.githubusercontent.com/12652166/61409161-a3102c00-a8af-11e9-8c01-959e142e1374.png)

**Comment by daeh** [comment]
I removed the browser extension and readded the vault and it seems to be working ok for now. Will reopen if symptoms reemerge.

**Comment by perry-mitchell** [comment]
Hi @daeh - I may have misunderstood, so apologies if I have, but it sounds as though you expect that the archive is unlocked in the browser when the desktop app unlocks the same item? If so, this is not the case.. There is no synchronisation between desktop + browser in terms of unlocked archives.

You can provide access to archive **files** (encrypted) via the "Enable Browser Access" option, but this only allows the extension to read the encrypted files to unlock them itself later in the browser. Unlocking a vault in my app will not unlock it in another.
