### ISSUE TITLE
Multiple users/passwords in a single entry

### ISSUE THREAD

**Issue by ovkhasch** [buttercup/buttercup-desktop#793]
Sometimes it is convenient to keep information for a multiple accounts in single service in one entry, i.e. have many username/password pairs. Please, consider implementing this.

**Comment by ovkhasch** [comment]
You can check padlock (padlock.io) manager for a similar feature. I am trying to migrate from it and badly missing this.

**Comment by perry-mitchell** [comment]
This will be handled by #85. I don't see any other requirements that this might have. Currently we only support a single logical login item per entry, and this is the way it'll stay, for simplicity. When logging in to a website etc., you can of course copy the values you'd like, but if executed automatically the original username and password would always be used. I don't think going more granular than entries is a good idea.

**Comment by nitish771** [comment]
> This will be handled by #85. I don't see any other requirements that this might have. Currently we only support a single logical login item per entry, and this is the way it'll stay, for simplicity. When logging in to a website etc., you can of course copy the values you'd like, but if executed automatically the original username and password would always be used. I don't think going more granular than entries is a good idea.

I am here because because i wanted a password manager to store multiple accounts for same websites. And i couldn't find any one till yet. I don't think adding features like this will make it any difficult to use. If you don't want to do it let other contributors do it for you.
