### ISSUE TITLE
open archive from connected cloud service

### ISSUE THREAD

**Issue by janbols** [buttercup/buttercup-desktop#794]
Hi,
I have a bcup file stored on an owncloud/webdav server. 
When I startup the application I get an empty file manager window.
I want to open it inside the Buttercup desktop application (1.16.2) running on Ubuntu 18.04.
To do this I click on "Connect cloud service" and fill in the settings for my ownCloud (or webdav = same behaviour).
After clicking the connect button the file manager window is shown again and remains empty. I would expect it to show the stored *.bcup file instead.
I can't find any errors or log files.

Perhaps I'm completely mistaken in how the UI works.

Any ideas how to get this working?
Jan

**Comment by perry-mitchell** [comment]
This is most likely an issue with OC configuration - sorry that yours was overlooked.

I'll close this due to the age of the issue, but if it's still occurring and there's something _we_ can do to help, I'll happily reopen.
