### ISSUE TITLE
Support new Keepass export format: Argon2

### ISSUE THREAD

**Issue by erodriguezh** [buttercup/buttercup-desktop#796]
Hi Everyone,

I am trying to import my database from a .kdbx file, but I keep getting the following error: 

> Importing from KeePass archive failed: Error NotImplemented: Argon2 not implemented

I am using version 1.16.2 (1.16.2)

I also tried writing a small javascript snippet using the @buttercup/importer package and I also got the same error message.

![Screen Shot 2019-07-31 at 21 30 10](https://user-images.githubusercontent.com/710174/62242281-18fdb280-b3db-11e9-87ae-02bac4f0bfca.png)

Thanks

**Comment by perry-mitchell** [comment]
Renamed as this doesn’t seem to be a bug: I expect that the keepass export format has changed as this was working originally.

**Comment by Aephir** [comment]
I can confirm that using the current format (KDBX 4.0), this is the error I get. If I try with an old format test database (KDBX 3.1), then I can import.

**Comment by perry-mitchell** [comment]
If someone could share a KDBX 4.0 export here (using sample data) that'd help a lot :)

**Comment by Aephir** [comment]
Sure, only a few entries, let me know if you'd like more. I've uploaded both the *.kdbx and the csv export.

https://www.dropbox.com/s/xzec9dytnt395pp/KDBX4.kdbx?dl=0
https://www.dropbox.com/s/wgosthnxz0fwq3b/test_export.csv?dl=0

**Comment by sallar** [comment]
Due to build issues, reverting and re-opening this. cc @perry-mitchell

**Comment by semihcanturk** [comment]
I'm having the same issue - what's the status for this at the moment?

**Comment by perry-mitchell** [comment]
As my colleague said, we had to revert. Argon2 seems to not be so cross-platform friendly. We’ll try again soon.

**Comment by perry-mitchell** [comment]
We've decided that it's not advantageous for Buttercup to try and _decrypt_ other vault types. This is out of scope for importing. Instead, we expect that all incoming vaults are already in exported formats (CSV, JSON, XML etc.).

This is in line with the fact that no other password manager would be expected to import from a Buttercup vault file (BCUP), but instead might support doing so from a generic CSV.
