### ISSUE TITLE
Error "Unhandled Promise Rejection"

### ISSUE THREAD

**Issue by theoricher** [buttercup/buttercup-desktop#798]
Hello,

I regularly encounter the error below when I move elements or create some in my buttercup archive. The archive is synchronized with NextCloud.

I use Buttercup `v1.16.2` on Windows 10

![image](https://user-images.githubusercontent.com/12476264/62356937-66c90680-b512-11e9-97f5-4799d309fb7c.png)

**Comment by perry-mitchell** [comment]
It means that your service is rejecting your authentication, or it having CORS issues. This is a known problem with Nextcloud and is not usually a problem with Buttercup. I’ll close this for that reason.

If we trace an issue with the WebDAV component we can reopen this issue. Sorry for the inconvenience..
