### ISSUE TITLE
change password

### ISSUE THREAD

**Issue by juanbosh** [buttercup/buttercup-desktop#803]
I take a pass weak and i can see how to change the pass of the file of keys. thanks

**Comment by perry-mitchell** [comment]
@juanbosh I'm not sure I understand, sorry. Are you describing an issue you're having?

**Comment by julianpoemp** [comment]
@perry-mitchell I think he had set a weak password for a vault and wanted to change it. Probably he didn't see the option to change the password (right click on the vault's icon > change password)
