### ISSUE TITLE
Terminal integration request

### ISSUE THREAD

**Issue by JuliusHerrmann** [buttercup/buttercup-desktop#804]
### Feature Request
I would like to somehow access my password and user name via the terminal, making for example git easier and more pleasant to use.

**Comment by perry-mitchell** [comment]
Hi @JuliusHerrmann - You're probably looking for our [CLI app](https://github.com/buttercup/buttercup-cli), but unfortunately it's currently out of service. We haven't had the bandwidth to rebuild it just yet. It is on the roadmap however!

I'll close this for now :)

**Comment by JuliusHerrmann** [comment]
Alright, thank you very much @perry-mitchell. I'm looking forward to the rebuild.
