### ISSUE TITLE
Entry types: note, SSH key, etc

### ISSUE THREAD

**Issue by jokeyrhyme** [buttercup/buttercup-desktop#807]
Howdie,

Thanks so much for this project, love it!

I noticed today that the in-browser vault editor has a New Entry button, with a dot-dot-dot button beside it offering other Entry types: 

![image](https://user-images.githubusercontent.com/479816/64688885-a94a0f80-d4d0-11e9-8f06-f635550c0b40.png)

There's an Add Entry button in the Windows / macOS desktop app, but there's no dot-dot-dot-button

Is there a different way to access alternative Entry types in the desktop app?

I'm using Windows 10 with the Buttercup desktop app v1.16.2

**Comment by perry-mitchell** [comment]
Hello! Not yet unfortunately.. this will come with the new desktop version that is underway. @sallar is tackling this at the moment :)

**Comment by keywordnew** [comment]
Super. So looking forward to this one!

I ran into issue #717 using custom fields as a workaround, but notes will solve the need.

Thank you very much for your time working on this project @perry-mitchell @sallar 🎉

**Comment by perry-mitchell** [comment]
Thanks @keywordnew! Nice to see you on here 😁. Yep this stuff is dropping very soon with the new UI. First party support for custom structures and UI.. notes will look like notes and so on. This will probably arrive some time after we finish OTP/2FA codes support for the mobile app (almost complete).

**Comment by sidahmed-malaoui** [comment]
Any news about this feature ?

**Comment by andradei** [comment]
I'm using the browser plugin for that reason, but would love to see that on mobile and desktop too.
This is a great tool.

**Comment by perry-mitchell** [comment]
Released in v2.
