### ISSUE TITLE
Google Drive not shown in desktop vers, not working in mobile vers, ok in browser vers

### ISSUE THREAD

**Issue by ToMMy86** [buttercup/buttercup-desktop#808]
Hello, in the desktop version ( i'm using the RPM release in Fedora 30 ) the Google Drive cloud option is not shown..
In the mobile version seems ok .. but it doesn't authenticate... ( i have a stock version of latest android, dropbox worked like a charm but GDrive doesn't ) 
I was only able to use Google Drive as cloud storage for the vault in the browser app.

It is crucial that a cloud provider if supported, must be present in all the version of the apps or deleted because the purpose of having a cloud storage is portability of the vault in different envs ...

Also i report that in the mobile version of the app, it's impossible to delete a locked vault from the app IF it's not anymore available in the cloud ..  for example if you had DropBox .. if you delete the vault from there and then you try to delete che vault from the mobile app, it doesn't work because you must unlock first che vault...  
One should be able to delete the vault from the app/list without the need to unlock the same vault...

Thank You.

**Comment by perry-mitchell** [comment]
@ToMMy86 Google drive isn't yet supported in the desktop app, but it's coming! #756

I haven't also noticed any issue with removing vaults while they're locked:

![ezgif-2-6ce70cb2edc1](https://user-images.githubusercontent.com/3869469/65273506-f3af3a00-db29-11e9-9356-b57bd8cfbb23.gif)

If this is an ongoing issue for you, I'd suggest creating an issue for it on the mobile repo.

**Comment by perry-mitchell** [comment]
Closing in favour of #164
