### ISSUE TITLE
"Recent buttercups" shows deleted archives

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup/buttercup-desktop#81]
1. Create an archive
2. Delete the file
3. It still shows in the "Recent buttercups" list

**Comment by perry-mitchell** [comment]
This one isn't so much a bug as it would be an improvement. Deleting or moving the file is a bit weird, especially if it's on a storage (webdav/dropbox) that's not easily/possibly checked.

This could be achieved for file-type archives only, by looping over them on startup and checking if they exist using an async call. Call could be cancelled if it takes longer than x milliseconds.
