### ISSUE TITLE
UX suggestions: show vault's title on password modal and highlight selected vault

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#812]
When I start the desktop client with two vaults, the first vault is selected when I do the shortcut ⌘ + 1. Every time I forgot that I don't want to unlock the first vault and typed in the password for the second one. That's because, I don't see which vault was selected.

1. It would be nice if there was any title  of the vault next to the "Master password" string. On that way the user would see at first glance which password he has to type in.
![Bildschirmfoto 2019-10-03 um 12 27 04](https://user-images.githubusercontent.com/25926588/66120061-48e35500-e5da-11e9-99bc-9f28a04fbb40.png)

2. After I did ⌘ + 1 after buttercup started the first vault is not visually selected in the sidebar. I think it would be more user friendly if the vault's icon was highlighted or something like that.
![Bildschirmfoto 2019-10-03 um 12 38 35](https://user-images.githubusercontent.com/25926588/66120252-c018e900-e5da-11e9-9855-cb25f12a30a5.png)

**Comment by antoine-amara** [comment]
I have some time for contributions, can I take a look at this improvement @perry-mitchell? I already look at the code and I think I know how to add this.
