### ISSUE TITLE
AUR version doesn't have an icon

### ISSUE THREAD

**Issue by hrqmonteiro** [buttercup/buttercup-desktop#818]
![13-10-2019-17:56:38](https://user-images.githubusercontent.com/17055027/66722358-d6952080-ede2-11e9-9084-14d6091415ce.png)
![13-10-2019-17:56:42](https://user-images.githubusercontent.com/17055027/66722359-d72db700-ede2-11e9-8bff-cee74ebcb584.png)

It only shows a blank icon and this is VERY buggy and ugly

**Comment by perry-mitchell** [comment]
@hrqmonteiro That's a bummer - we don't actively maintain the AUR version, as it was submitted by a contributor. We don't have the expertise nor the bandwidth to take this on right now, unfortunately.
