### ISSUE TITLE
installer for windows can't be downloaded from the homepage: wrong naming?

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#821]
When you click on the download button for Windows on your homepage (www.buttercup.pw), the file can't be found:
https://github.com/buttercup/buttercup-desktop/releases/download/v1.17.0/buttercup-desktop-setup-1.17.0.exe

The windows release is named ``Buttercup-Setup-1.17.0.exe`` instead of ``buttercup-desktop-setup-1.17.0.exe``. That's why it can't be downloaded from the homepage and via the updater on windows.

**Comment by sallar** [comment]
@julianpoemp can you check if it's fixed now? thank you!

**Comment by julianpoemp** [comment]
@sallar fixed 👍

**Comment by sallar** [comment]
Thanks @julianpoemp
