### ISSUE TITLE
Name archive on Google Drive incorrect in Desktop software

### ISSUE THREAD

**Issue by Peppeo** [buttercup/buttercup-desktop#822]
Hi there,
When I add an archive located on Google Drive it gets a 'crazy' name in the Desktop application. In the browser extension the correct names are shown.
Here are the two archives on my Drive:
<img width="616" alt="Screen Shot 2019-10-15 at 11 06 02" src="https://user-images.githubusercontent.com/53419266/66801200-72896e00-ef42-11e9-97e8-47ef3f48f9ff.png">
Here I am adding the test archive to the desktop application:
<img width="664" alt="Screen Shot 2019-10-15 at 11 08 00" src="https://user-images.githubusercontent.com/53419266/66801239-9f3d8580-ef42-11e9-93be-d0eeaff505d1.png">
This is how it shows up in Buttercup (see also the entry above for peppe.bcup, also a different name)
<img width="664" alt="Screen Shot 2019-10-15 at 11 08 35" src="https://user-images.githubusercontent.com/53419266/66802331-47088280-ef46-11e9-8e55-7a11e13d5224.png">
If I add it in the browser extension all looks normal:
<img width="664" alt="Screen Shot 2019-10-15 at 11 18 29" src="https://user-images.githubusercontent.com/53419266/66802365-669fab00-ef46-11e9-8d9f-7dc35b851f1c.png">
And that continues to be so after addition:
<img width="667" alt="Screen Shot 2019-10-15 at 11 19 05" src="https://user-images.githubusercontent.com/53419266/66802395-78814e00-ef46-11e9-92af-fa0ab87169d0.png">
So the same files in the Desktop software have a strange naming convention.

**Comment by perry-mitchell** [comment]
I think it's because it's somehow reading the google drive identifier rather than the filename - @sallar?

**Comment by quidiello** [comment]
It is an old problem and it is difficult to work with Google Drive. Is there a date to fix it?

**Comment by perry-mitchell** [comment]
Haven't had time to address this. Would accept a PR for it.

**Comment by perry-mitchell** [comment]
Will be fixed in next release:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/3869469/114616016-0a3e5880-9caf-11eb-9984-e30d0a36f95b.png">
