### ISSUE TITLE
add more options for linux

### ISSUE THREAD

**Issue by mrwanashraf** [buttercup/buttercup-desktop#823]
is there a possibility to provide buttercup as an [appimage](https://appimage.org/)

would be also nice to see buttercup on [snap](https://snapcraft.io/)

**Comment by Peppeo** [comment]
<img width="825" alt="Screen Shot 2019-10-24 at 11 54 46" src="https://user-images.githubusercontent.com/53419266/67454643-2a123480-f655-11e9-8634-d651ad5ab8d3.png">
Hi, as you can see it is already available as an Appimage. Also as RPM, deb and yml file. Hope that helps.

**Comment by mrwanashraf** [comment]
ah my bad, I just didn't see it on the website download options, okay but how about the possibility of seeing it published as a snap?

**Comment by Peppeo** [comment]
Well, that we have to ask the developers. But in general a Snap is more related to the Ubuntu Snap Store, whereas an Appimage is more distro-agnostic. I think that might be a reason? And of course they probably want to focus their efforts on the application and less on the 'packaging'. But I assume this and you know how it is with assumptions ;-)

**Comment by mrwanashraf** [comment]
I do understand your point of view but buttercup would benefit a lot from the auto update feature that snapcraft provides plus snapcraft works on many distros not just ubuntu, for an example you can publish the appimage as a snap on snapstore, so it's not really much 'packaging' work, I think it would benefit buttercup and increase its popularity, that would solve also the inconsistency of the buttercup icon across distros.

**Comment by Peppeo** [comment]
Yes, when i read your comment I agree with that. The 'snapping' I read about after my previous message (how easy it is, too quick to the keyboard I was ;-) and w/r to popularity and 'branding' I agree also. The inconsistency for at least AUR (also mentioned here in the issue list) I will doublecheck tonight. If i am correct it does show on my Manjaro so. But that could all also be related to the DE that is used perhaps. I never got around to installing Buttercup on XFCE or KDE, just on Mint and Manjaro, both Cinnamon.

**Comment by sallar** [comment]
We had `snap` format as an option a while ago, but it started breaking the build process so I had to remove it. I check to see if it now works with newer versions of `electron-builder` that we're using, if it does, I'll put it back up.

**Comment by sallar** [comment]
Related: #647

**Comment by mrwanashraf** [comment]
@sallar I believe that you can submit appimages on snap, maybe consider this option if the build process kept breaking?

**Comment by sallar** [comment]
@mrwanashraf working on this.
