### ISSUE TITLE
Issue connecting to Google Drive from Buttercup desktop

### ISSUE THREAD

**Issue by Peppeo** [buttercup/buttercup-desktop#835]
<img width="1132" alt="Screen Shot 2019-10-29 at 10 49 06" src="https://user-images.githubusercontent.com/53419266/67736485-66b9a380-fa3a-11e9-8f60-7751f5ca54c2.png">

As of this morning I have an issue connecting to Google Drive with the Desktop version of Buttercup? Not for an already existing archive, situated on Drive. That works okay. This happens when i want to add another archive. After clicking on 'Authenticate with Google' and going through the motions I get the error above. And of course the password etc. is correct. First I thought it was Manjaro related (since there is no official support for the AUR version), but it happens right now in Desktop on Mac also. Any ideas? thanks

**Comment by PaoloneM** [comment]
Same problem for me. Fresh install (brew cask) yesterday, macOS 10.13.6 High Sierra, after successful authentication in Google, got the reported error. No previous archives, I'm a brand new user.

**Comment by macno** [comment]
Same here on macOs 10.14.6. Google authentication succeeded, but then the error showed up.
First installation.

**Comment by christianschneider89** [comment]
Same here on Windows 10 1903

**Comment by perry-mitchell** [comment]
![image](https://user-images.githubusercontent.com/3869469/67978615-36812900-fc23-11e9-8511-7c9168f4adbf.png)

Can confirm.. Seems there's something up with the GDrive client.

**Comment by riyadhalnur** [comment]
I opened an issue [here](https://github.com/buttercup/buttercup-desktop/issues/835). This should fix the problem with Google Drive.

**Comment by Peppeo** [comment]
Great! Can confirm working with Brave 0.68.141 and Firefox 70.0.1 with Manjaro 18.1. Thanks!

**Comment by riyadhalnur** [comment]
@perry-mitchell @sallar I think the windows builds didn't update properly. The version still shows 1.17.2 in the menus and drive errors while trying to connect. Linux builds are fine on my side.
