### ISSUE TITLE
Wrong version in help menu

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#837]
Installed 1.17.2, have 1.17.1 in the help menu: 
![image](https://user-images.githubusercontent.com/3869469/67980430-1489a580-fc27-11e9-8b95-051d20f0b97b.png)

**Comment by theoricher** [comment]
Installed 1.17.3, have 1.17.2 in the help menu: :)

![image](https://user-images.githubusercontent.com/12476264/68467594-c708cc00-0216-11ea-9dfb-c3b57d466a74.png)

**Comment by theoricher** [comment]
Issue fix on pull request #845

**Comment by perry-mitchell** [comment]
Fixed in v2.
