### ISSUE TITLE
About menu doesn't work, could be moved

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#838]
Clicking "About" under windows does nothing.

Perhaps "About" should also appear in the help menu?
![image](https://user-images.githubusercontent.com/3869469/67980513-413dbd00-fc27-11e9-88b1-e1ee7951b922.png)

**Comment by julianpoemp** [comment]
I see this issue, too. Additionally I don't see any version string after "Show changelog for v"
![Bildschirmfoto 2019-12-06 um 17 17 45](https://user-images.githubusercontent.com/25926588/70338048-75228880-184c-11ea-891a-ec471c304870.png)

Version 1.18.1

**Comment by perry-mitchell** [comment]
> I don't see any version string after "Show changelog for v"
#866 😁

**Comment by perry-mitchell** [comment]
Fixed in v2.
