### ISSUE TITLE
Identical field name overwrite data 

### ISSUE THREAD

**Issue by tmanaud** [buttercup/buttercup-desktop#840]
Issue: when adding custom field name with identical name:
![image](https://user-images.githubusercontent.com/265371/68108449-12a23980-fee8-11e9-95e8-bbb50dc38640.png)

Then when saved, only the last one is stored:
![image](https://user-images.githubusercontent.com/265371/68108455-1cc43800-fee8-11e9-86b1-09477d3449c7.png)

I know it doesn't make sense from a developer point of view to save multiple field with identical name, but from a user point, it does: they are free custom field names.
Edit: the problem is the the same with a custom field name "password"
![image](https://user-images.githubusercontent.com/265371/68108657-a83dc900-fee8-11e9-926b-0c0e9ee1ea16.png)

Solution: either add a hidden ID to allow identical custom field or prevent the user of adding identical name.

Buttercup-desktop V1.15.0 on Ubuntu 19.10

**Comment by montrueque** [comment]
I have tried this behaviour in v1.20.5 and if there are several fields with identical name is throwing an error:
![image](https://user-images.githubusercontent.com/20231801/95379872-3cc55e00-08e6-11eb-8625-99915f5aceb6.png)
However, I noted that if the fields have identical name but cased differently both are saved:
![image](https://user-images.githubusercontent.com/20231801/95380003-667e8500-08e6-11eb-900b-beb33e44882f.png)
![image](https://user-images.githubusercontent.com/20231801/95380013-6c746600-08e6-11eb-8844-fb8d6f60386e.png)
I wonder if is needed to review that

**Comment by perry-mitchell** [comment]
This will be solved with the new UI. We'd accept a PR for it, on v1, but it's not a priority unfortunatelly as we'll be completely removing the case where this can happen.

**Comment by perry-mitchell** [comment]
Now, in v2, it simply overwrites if it has the same name. This is intended behaviour.
