### ISSUE TITLE
Unhandled Error Error: listen EADDRINUSE :::12821

### ISSUE THREAD

**Issue by rugabunda** [buttercup/buttercup-desktop#842]
> Unhandled Error
> Error: listen EADDRINUSE :::12821
>     at Function.x.listen (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:290:4544)
>     at createHost (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:208:246875)
>     at startFileHost (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:178:27322)
>     at zs (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:363:134800)
>     at C:/Program Files/Buttercup/resources/app.asar/dist/app.js:363:141348
>     at oc (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:363:141353)
>     at App.r.app.on (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:363:145719)

then it loads fine

**Comment by perry-mitchell** [comment]
This will be because an instance is already running when you try to open a second copy. This should ultimately detect an existing instance and not run a new one, but open a window in the original app. @sallar we looked into this a while back didn't we?

**Comment by perry-mitchell** [comment]
Closing in favour of #849
