### ISSUE TITLE
ROOT display recursive. Sort date.

### ISSUE THREAD

**Issue by bigalgeorge** [buttercup/buttercup-desktop#843]
1.16.2
Seems unlikely the browser extension is going to supersede the desktop app so here is an issue.
When vault is open, Ive said it before, and will repeat - when ROOT is selected, this and only this should display all directory contents within eg child directories of ROOT.
Reason; allows user much easier access for finding entries to edit. EG I have shoecaps.com in a subdir [sales]. Currently shoecaps.com could not be found unless I went to [sales] however if ROOT displayed all child, and the sort option on top worked properly, the finding of shoecaps.com would be much easier.
2..Sort options only work for name/ascend/descend second option date/ascend/descend inoperative.

**Comment by perry-mitchell** [comment]
Root here is just another name for a meta group that shows all items, right? It wouldn't necessarily need to be the root of the tree. Having a root element would needlessly push all items out one extra level of indent and seems superfluous. The tree list for groups could simply have an "All" element or something similar.

**Comment by bigalgeorge** [comment]
[All] or [Top] same as [ROOT]

**Comment by perry-mitchell** [comment]
I think we're going to move away from this for the time being. Having an "all" type group would just be confusing in my opinion. Inheritance is a bit magical too and it's good, for now, to keep the tree of directories as naive as possible. We'll most likely revisit this as we see the UI envolve.

For now, search should suffice for finding entries quickly.
