### ISSUE TITLE
download URL for windows leads to 404 Not found error

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#846]
I tried to download the new release 1.17.3 for windows from the website, but it failed.

The URL from the website is:
https://github.com/buttercup/buttercup-desktop/releases/download/v1.17.3/buttercup-desktop-setup-1.17.3.exe

The URL from the realeases page is:
https://github.com/buttercup/buttercup-desktop/releases/download/v1.17.3/Buttercup-Setup-1.17.3.exe

related to #821

**Comment by theoricher** [comment]
Hello,

Issue already reported here : https://github.com/buttercup/buttercup-website/issues/50
And fix here : https://github.com/buttercup/buttercup-website/pull/51

She is currently waiting for merge ;)

**Comment by julianpoemp** [comment]
> I have solve this issue on pull request #51 :)

The last time I reported this it was about an invalid naming of the windows release. It's the same again and could be fixed if the name of the build is correct, too...

**Comment by theoricher** [comment]
@julianpoemp You can't rename the windows release with you access right ?

**Comment by julianpoemp** [comment]
> @julianpoemp You can't rename the windows release with you access right ?

No, I can't...

**Comment by theoricher** [comment]
> > @julianpoemp You can't rename the windows release with you access right ?
> 
> No, I can't...

Who is in charge of releases ?

**Comment by julianpoemp** [comment]
> > > @julianpoemp You can't rename the windows release with you access right ?
> > 
> > 
> > No, I can't...
> 
> Who is in charge of releases ?

I assume @sallar

**Comment by julianpoemp** [comment]
this is fixed by https://github.com/buttercup/buttercup-website/pull/51
