### ISSUE TITLE
Subtle update notification (no window / focus steal)

### ISSUE THREAD

**Issue by 8520456963** [buttercup/buttercup-desktop#847]
Hi, 
I still have the problem when unlocking the archive, when I am typing my password the update window appears and I have to start typing my password again from the beginning. How to avoid problems: 
1) Disable update (not good idea) 
2) Wait until the archive is unlocked to request the update 
3) Put the update window in the background 
4) Add a button to view your password

**Comment by perry-mitchell** [comment]
I like how Telegram desktop does this, with the little update notification in the left hand corner. It can appear and be somewhat unobtrusive - I agree that stealing focus isn't very nice.

**Comment by perry-mitchell** [comment]
An example, taken from a prior issue:
![image](https://user-images.githubusercontent.com/3869469/72223986-a5f98a00-357d-11ea-8da8-2410cda5ba64.png)

**Comment by perry-mitchell** [comment]
Implemented in v2.
