### ISSUE TITLE
File host: Can't unlock archives/vault

### ISSUE THREAD

**Issue by sinameraji** [buttercup/buttercup-desktop#848]
Hi guys, I'm absolutely loving Buttercup but noticed an issue with the chrome extension.

I basically can't generate a password in-browser as I'm signing up for something, because I can't unlock an archive. 

<img width="1306" alt="Screenshot 2019-11-05 at 10 59 03 AM" src="https://user-images.githubusercontent.com/6380359/68192697-af4dff80-ffec-11e9-9ad2-5861d24ceca2.png">
<img width="642" alt="Screenshot 2019-11-05 at 10 58 55 AM" src="https://user-images.githubusercontent.com/6380359/68192692-aeb56900-ffec-11e9-8422-c76773eb1fd1.png">

using Chrome 78.0.3904.70 on a Mac 

Thanks

**Comment by tmotyl** [comment]
@perry-mitchell is there anything I can provide to help finding the issue?
I would love to migrate to buttercup from other tool but unfortunatelly this block me

**Comment by perry-mitchell** [comment]
@tmotyl Any chance of getting a look at your bcup desktop logs? https://github.com/buttercup/buttercup-desktop#debugging

Besides seeing something potentially helpful in there, I'd say the only way could be to debug the networking side of things yourself. Run bcup desktop in development and try connecting from the extension. When it fails, check out the logs in the browser (foreground and background), as well as those in the CLI when running the desktop app.

All of this having failed, would you ever consider a remote desktop session so I could see the issue? I'd be completely fine being an observer only, and happy if you demonstrate with a **test** vault.

**Comment by tmotyl** [comment]
Hi
I've run the dev version of the buttercup, and the only errors in the logs were:
log.log
```
[2019-12-20 13:55:52.702] [info] Checking for update
[2019-12-20 13:55:52.702] [error] Error: Error: ENOENT: no such file or directory, open '/opt/Buttercup/resources/app-update.yml'

```
and in the application console (shown when e.g. right clicking)
```
[1] [9992:1220/135524.185481:ERROR:CONSOLE(24)] "Empty response arrived for script 'devtools://devtools/remote/serve_file/@595db07ff0ba77637a9e5d016388cdac2d34701e/product_registry_impl/product_registry_impl_module.js'", source: devtools://devtools/bundled/shell.js (24)
[1] [9992:1220/135524.200999:ERROR:CONSOLE(109)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: devtools://devtools/bundled/shell.js (109)
[1] [10030:1220/135612.392162:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

```

None of these errors occured when trying to connect from the browser.
There were no errors in the browser console.
I'm open for doing the remote desktop session.

**Comment by mcglk** [comment]
I've always had this problem with Buttercup. Not once have I been able to get the browser extension working.

Yes, I have the Buttercup desktop application running.
Yes, I have **System ► Enable Browser Access** checked.

Nothing has ever worked; I wind up copy/pasting my information every time, and at this point, I'm about ready to try something else. I'm sure not going back to LastPass, and I am loathe to use something that forces me to log into their service to use, and would prefer an open-source solution. (At this point, I'm looking at BitWarden, but I'm reluctant to make that leap.)

**Comment by perry-mitchell** [comment]
We really need someone actively developing and helping us with the local file datasource. It's complex, error prone and not a system that @sallar nor myself ever use. It's obscure because most of our users prefer a cloud service (Dropbox or Google Drive) or a WebDAV-enabled storage provider (either some provider or self-hosted). 

I acknowledge that we made the choice to support this method of connectivity, and when I've tested it it's worked - but it's most certainly suffering on the testing side because neither of us use it regularly. If someone were willing to jump in and help us maintain it, we'd appreciate it and everyone facing this issue would benefit.

**Comment by mcglk** [comment]
I _am_ using Dropbox.

**Comment by perry-mitchell** [comment]
> I am using Dropbox.

> Yes, I have the Buttercup desktop application running.
> Yes, I have System ► Enable Browser Access checked.

@mcglk  Not in Buttercup's eyes, if you're using the browser-based access - it's just a directory on your computer.

It would be best if you used the Dropbox connection directly:

![image](https://user-images.githubusercontent.com/3869469/103169318-283c9600-4843-11eb-89e9-f818acdc1f0c.png)

**Comment by dotamir** [comment]
I test it twice and I haven't had any problem with local files on macOS. But I'll do more investigation on this feature on other platforms as well and also the code.

**Comment by perry-mitchell** [comment]
Closing this as stale - And this thread is long-winded and off-track. Please open a new issue if you're experiencing this issue, with an apt description and guide to reproduce.
