### ISSUE TITLE
Allow masking non-password fields

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup/buttercup-desktop#85]
Please add the binocular feature to non-password custom fields as well :smile:

It would be good to hide them so people near the screen can't see them.

**Comment by sallar** [comment]
Thanks @Jameskmonger, @perry-mitchell is actually adding that in https://github.com/buttercup-pw/buttercup-cli and it'll come to the GUI soon :)

**Comment by perry-mitchell** [comment]
This is stateful in the archive, and will requite buttercup-pw/buttercup-core#136 to be completed.

**Comment by DiSino** [comment]
Any updates on the implementation. I had been a while.

**Comment by perry-mitchell** [comment]
@DiSino if there were, they'd be mentioned here I'm afraid. Checking buttercup/buttercup-core#136 would also show that it's not done yet. Sorry, but we're stretched for time right now and really appreciate community contributions where possible. Hope you understand.

**Comment by ovkhasch** [comment]
+1 for this feature

**Comment by perry-mitchell** [comment]
This is supported in the new UI, coming in V2.

**Comment by perry-mitchell** [comment]
Fixed in v2.
