### ISSUE TITLE
Fix sidebar background colour #Bug

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-desktop#856]
<img width="1440" alt="Screenshot 2019-11-29 at 22 42 17" src="https://user-images.githubusercontent.com/1715809/69891029-c3d69c80-12f9-11ea-83ca-255390d1e227.png">

**Comment by ldexterldesign** [comment]
First BC PR 😟

To reproduce this issue launch BC and then cmd + r to refresh. Because cmd + r, I assume it's some kind of dynamic props issue but I've attempted a fix by simplifying the CSS...

I don't see the need to use conditionals `isOSX()` in the CSS but if there is a need then I'd love to know why? Also, hsl(a) > rgb(a) > hex if one fancies giving global-styles.js some love.

NB please see my TODO in the PR as I'd hate this to break something I can't test

Hope this helps

Regards 😟

**Comment by sallar** [comment]
Thanks @ldexterldesign. We need the `isOSX()` calls, because the app looks different in macOS and there is vibrancy and translucency.

![image](https://user-images.githubusercontent.com/768052/69892422-f4c0cc80-130d-11ea-8c91-79e6a20ecd19.png)

**Comment by ldexterldesign** [comment]
Why's this platform (i.e. macOS) specific?

Cheers

**Comment by sallar** [comment]
@ldexterldesign Windows and Linux don't support vibrancy.

**Comment by ldexterldesign** [comment]
https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/translucency/

I see

If you can reproduce this issue then let me know and I'll take another look over the weekend

Cheers

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

> Can you reproduce this?

Cheers

**Comment by sallar** [comment]
The issue can be reproduced by opening and closing developer tools (`cmd+option+I`). I'm just not sure what can be done about it.

**Comment by ldexterldesign** [comment]
Will take another look at he PR ASAP

Regards

**Comment by perry-mitchell** [comment]
I wasn't seeing this issue in development on 1.18.1 / 1.18.2:

![image](https://user-images.githubusercontent.com/3869469/72187404-390cb580-3400-11ea-8a76-3f900fb71df7.png)

Anyone else seeing it?

**Comment by ldexterldesign** [comment]
I just experienced this issue in https://github.com/Sonarr/Sonarr/issues/3218 so I presume it's something in a core library, not buttercup-specific

Hope this helps

Sincerely
