### ISSUE TITLE
Add a field to save image or audio content

### ISSUE THREAD

**Issue by tmanaud** [buttercup/buttercup-desktop#858]
It could sound stupid but for few situation, one would need other credential than simple string.  
Just to name few: 
- One time key card: I simply take a picture of these one time password card from my bank and save it somewhere.  
- Audio login: devices need modulated signal for wifi sync: simply record it and you dont have to use the app anymore, just replay the audio.  
- Picture of a QRcode for Wifi credentials  

Would it be possible to save any data and embed a viewer/player?

**Comment by perry-mitchell** [comment]
Depends on #484

**Comment by perry-mitchell** [comment]
Will close for #484 as it's a bit neater to track this with only one issue.
