### ISSUE TITLE
Error-message on fresh install of 1.18.0 on Ubuntu 19.10 using deb-package

### ISSUE THREAD

**Issue by p4fg** [buttercup/buttercup-desktop#859]
Fresh install using the ubuntu-deb-package.
Starting up.
Getting error: 

```
Unhandled Promise Rejection
Error: ENOENT: no such file or directory, open '/opt/Buttercup/resources/app-update.yml'
```
![buttercup-bug](https://user-images.githubusercontent.com/2240012/70040921-9a00cc80-15bc-11ea-926b-68324d8cc9de.png)

**Comment by p4fg** [comment]
Creating the file (empty) gives the same results strangely enough

**Comment by perry-mitchell** [comment]
Hi @p4fg - Apologies for the delay. What's the permissions on that dir? If you start bcup as a more priviledged user does it help? Wondering if it's a permissions issue.

**Comment by ghostd** [comment]
Hi @perry-mitchell 

I have the same issue after an upgrade to 1.18.0

My 'resources' directory only contains a 'app.asar' file.

If i 'touch' the asked file, i get an other error (it seems the application attempts to read my empty file and does not find some required properties)

**Comment by Dashon1** [comment]
I'm also experiencing this problem on a fresh install of ubuntu 19.10 using buttercup-desktop version 1.18.1.

Here is the output of terminal when running as regular user and root:
buttercup-desktop
21:19:45.074 › Buttercup starting up...
21:19:45.146 › Restoring state... {
  settingsByArchiveId: {},
  archives: [],
  settings: {
    columnSizes: { tree: 230, entries: 230 },
    condencedSidebar: true,
    menubarAutoHide: false,
    archivesLoading: false,
    isTrayIconEnabled: true,
    isBrowserAccessEnabled: false,
    locale: 'en'
  }
}
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
21:19:50.619 › Checking for update
21:19:50.645 › Error: Error: ENOENT: no such file or directory, open '/opt/Buttercup/resources/app-update.yml'
[Error: ENOENT: no such file or directory, open '/opt/Buttercup/resources/app-update.yml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/Buttercup/resources/app-update.yml'
}
^C21:21:30.670 › Running before-quit operation.
d-air1@reki:~$ sudo buttercup-desktop
[29747:1221/212142.894449:FATAL:atom_main_delegate.cc(207)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap
d-air1@reki:~$ sudo buttercup-desktop --no-sandbox
21:22:01.441 › Buttercup starting up...
21:22:02.436 › Restoring state... {}
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
21:22:07.920 › Checking for update
21:22:07.930 › Error: Error: ENOENT: no such file or directory, open '/opt/Buttercup/resources/app-update.yml'
[Error: ENOENT: no such file or directory, open '/opt/Buttercup/resources/app-update.yml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/Buttercup/resources/app-update.yml'
}
Error creating proxy: Unknown or unsupported transport “disabled” for address “disabled:” (g-io-error-quark, 13)
Error creating proxy: Unknown or unsupported transport “disabled” for address “disabled:” (g-io-error-quark, 13)
Error creating proxy: Unknown or unsupported transport “disabled” for address “disabled:” (g-io-error-quark, 13)
Error creating proxy: Unknown or unsupported transport “disabled” for address “disabled:” (g-io-error-quark, 13)
Error creating proxy: Unknown or unsupported transport “disabled” for address “disabled:” (g-io-error-quark, 13)

(buttercup-desktop:29767): dconf-WARNING **: 21:22:15.851: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:15.889: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:15.900: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:15.918: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:15.951: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:15.968: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:15.984: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:16.001: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:16.019: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:16.036: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:16.052: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:16.068: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:16.082: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:19.977: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:19.987: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:20.005: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:20.022: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:20.047: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:20.080: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:20.095: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:20.123: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:20.140: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:20.156: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:20.173: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:20.189: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:22.899: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:22.933: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:22.950: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:22.971: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:22.985: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:22.996: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:23.013: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:23.030: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:23.046: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:23.063: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:23.080: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:23.101: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:23.125: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:24.080: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:24.107: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:24.125: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:24.490: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(buttercup-desktop:29767): dconf-WARNING **: 21:22:24.491: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

**Comment by Dashon1** [comment]
So it seems to be looking for a file that doesn't exist on startup and it seems it is having problems changing to dconf.

**Comment by Dashon1** [comment]
Unless I'm doing something wrong I can't create a new archive at all. I have tried this with version 1.18.1 using the deb package and the appimage. The appimage does not have the update check error however.

**Comment by Dashon1** [comment]
For now the 1.17.3 works.

**Comment by chasbro-1** [comment]
I still have this issue with 1.18.2.  Happens about 5 seconds after I open butter-desktop app.

![image](https://user-images.githubusercontent.com/55006395/71605584-7a16e700-2b2f-11ea-95b2-720ba0e08eb9.png)

**Comment by niniks** [comment]
> I still have this issue with 1.18.2. Happens about 5 seconds after I open butter-desktop app. I am using LinuxMint 19.3.
> 
> ![image](https://user-images.githubusercontent.com/55006395/71605584-7a16e700-2b2f-11ea-95b2-720ba0e08eb9.png)

Same problem here, fresh install on newest version ubuntu

**Comment by LuckyLukert** [comment]
Hi,

I have the same issue on Ubuntu 18-LTS. Is there anything we can do?
E.g. creating a file with some special content that is needed?

Also, is there a possibility to just disable automatic updates?
I would prefer my password manager to not open network connections.

Best, Philip

**Comment by perry-mitchell** [comment]
> I would prefer my password manager to not open network connections.

Security updates for something as vital as a password manager are super important. We wouldn't want to immediately provide the option for people to forgo updates and potentially forget to allow patching security vulnerabilities. Adding an option like this to Buttercup goes against our instincts here.

Perhaps a setting to allow specifying an update-check schedule? Not sure what would make this more appealing to you.

**Comment by ghostd** [comment]
Maybe this is related to https://github.com/electron-userland/electron-builder/issues/4233
This issue mentions a potential workaround: https://github.com/electron-userland/electron-builder/issues/2736#issuecomment-456380922... if someone knows how to check this

**Comment by heyvoon** [comment]
Samhe here on Linux Mint 18.3 Cinnamon
Buttercup 1.19.0

After installation, first time fire up;

![image](https://user-images.githubusercontent.com/3281265/75759325-a5879f00-5d35-11ea-913e-aa0683d8990d.png)

**Comment by EDavidF** [comment]
Continuing to get after update to 1.19.0. Between this and the android app to require Google services, I think my Buttercup experiment may be ending, which is too bad- these apps have a lot going for them.

**Comment by sallar** [comment]
Hi @EDavidF, we are working on this Linux issue. But would you mind elaborating on the Android issue? We had a problem with Google Services but it's now fixed.

**Comment by EDavidF** [comment]
@sallar see @perry-mitchell 's comment here: https://github.com/buttercup/buttercup-mobile/issues/75#issuecomment-585367962
I will add comment there.
Thanks.

**Comment by ziltsh** [comment]
![Screenshot_2020-03-26_10-33-42](https://user-images.githubusercontent.com/8758243/77632113-d41c2280-6f4d-11ea-8780-dcc0699f2548.png)

Also the system->about menu does not produce any window or information.

I am running:
$ date; lsb_release -d ; uname -srvmo
Thu 26 Mar 2020 10:47:25 AM CET
Description:	Debian GNU/Linux bullseye/sid
Linux 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux

**Comment by ndurbindhcs** [comment]
I have same issue on v1.18.2 & v1.19.0

Tue 07 Apr 2020 09:35:27 AM PDT
Description:	Fedora release 31 (Thirty One)
Linux 5.5.13-200.fc31.x86_64 #1 SMP Wed Mar 25 21:55:30 UTC 2020 x86_64 GNU/Linux

I wish I never upgraded from earlier v0.17.x This is such a PITA and has me regretting migrating to buttercup.  Why can't someone fix this after so many people asking for this to be patched for months?

**Comment by sidahmed-malaoui** [comment]
Apparently, in version `1.19.0`, disabling automatic updates at startup (`System -> Preferences -> Disable update on start`) will make this error disappear, and I could create or open archives.

PS : When you create an archive, you have to specify the extension (which is `.bcup`).

I hope this will help someone until the app is fixed.

**Comment by joubertredrat** [comment]
Same issue here. Installed in Linux Mint 19.3 using deb package

**Comment by perry-mitchell** [comment]
The issue is that only AppImage build types support auto-updates on linux, thanks to how electron-builder works. Because we currently can't detect how buttercup was installed, there's currently no way to know _if_ we should even attempt to check for updates (why this error is appearing). The solution would be to detect install type (probably at build time), and then disable auto-updates if on a platform that doesn't support them.

**Comment by franko108** [comment]
Same issue on my Ubuntu 19.10, installed instance from the link: https://github.com/buttercup/buttercup-desktop/releases/download/v1.19.0/buttercup-desktop_1.19.0_amd64.deb  

I can't create an empty archive. No errors on GUI, but archive isn't been created.

**Comment by rayj-pgi** [comment]
any idea what this file should contain so we can just populate it?

**Comment by rayj-pgi** [comment]
This did the trick, although I'm not sure if it will actually check for updates or not...

```➜ cat /opt/Buttercup/resources/app-update.yml 
---
provider: github
owner: buttercup
repo: buttercup-desktop
```

![image](https://user-images.githubusercontent.com/18078751/80321103-c7eae580-87d7-11ea-86bd-df8f8029d7f8.png)

**Comment by dreamstorpi** [comment]
I had the same issue. 
I got rid of the error message by disabling auto update on start up in the preferences.
But, of course, that doesn't solve the issue; just makes the annoyance go away.
V1.19.0 on Fedora 32

**Comment by jabbajac** [comment]
Still having the same issue on v1.19.0

![image](https://user-images.githubusercontent.com/5124266/83905394-73138680-a716-11ea-8835-c8521887e08f.png)

I'm on ubuntu 18.04 LTS

**Comment by Doctor-Who** [comment]
Same issue with RPM and openSUSE Leap 15.1

**Comment by SerhiiK** [comment]
Have the same issue on ubuntu 16.04 with  v1.19.0

**Comment by LeonardPeris** [comment]
This has already been referenced in Issue #917 .
As noted, this is Electron's Update Mechanism trying to update the app, which is not permitted on Linux system. This will be fixed in future releases.

**Comment by ldexterldesign** [comment]
FYI not just Linux

Wow, after months of tolerating this I'm glad it's not just me!

Be lovely to get this fixed 🙏

<img width="1792" alt="Screenshot 2020-07-09 at 14 25 17" src="https://user-images.githubusercontent.com/1715809/87098033-4f27f100-c23e-11ea-8aa3-fd1d6d7b2cfc.png">

Sincerely

software - operating system: Apple, macOS, 10.15.5 (19F101)
software - application: Buttercup, 1.19.0 (1.19.0)

**Comment by sallar** [comment]
Hey everyone, can you please check to see if this is still an issue?

**Comment by steve-goldberg** [comment]
I'm still having this issue. I'm pop os 20.04 on a dell xps 15.

**Comment by ldexterldesign** [comment]
Hi @sallar,

Apologies for delay

Not an issue for me any longer, haven't seen that error in a while

Hope this helps

Sincerely

**Comment by perry-mitchell** [comment]
Stale and no longer relevant as for now we're no longer supporting deb packages.
