### ISSUE TITLE
Force .bcup extension for new vaults

### ISSUE THREAD

**Issue by p4fg** [buttercup/buttercup-desktop#860]
1.18.0 on ubuntu 19.10 installed via .deb-package.

When creating a new (the first) archive, a name has to be selected.
I had a very hard time creating it, because it does not say anywhere that the file i enter has to have the extension `.bcup`.

I actually had to watch the 1.14 video to see what they were typing when creating a new archive.

Suggestion:
Allow any extension
or
Append .bcup automatically
or
Give errormessage explaining the situation

**Comment by perry-mitchell** [comment]
Renamed for brevity. Definitely agree this is the way to go! Sorry for the inconvenience.
