### ISSUE TITLE
Buttercup shows "Your archive is being saved" on startup

### ISSUE THREAD

**Issue by wodin** [buttercup/buttercup-desktop#861]
I have Buttercup v1.18.0 installed on Linux with the archive accessed via WebDAV.

I upgraded it recently, but it has been working fine (except for an unrelated auto-update error) so far.

Yesterday I added a new entry and soon after that I closed Buttercup. Nothing seemed out of place at this point.
I then opened Buttercup on my Mac and the new entry was there.

Later I tried opening Buttercup on my Linux machine again, but as soon as it opens it shows a spinner with the message "Your archive is being saved. Exiting automatically". This message stays there indefinitely and Buttercup does not automatically close. So it seems there's some state that causes Buttercup to think it is busy saving the archive when that has actually been done already.

If I close the Buttercup window then all of the `buttercup-desktop` processes die, so this problem does not appear to be caused by a processes that's still running from yesterday.

What do I need to clear/delete to get Buttercup to work again?

**Comment by FalloutXtreme** [comment]
Hello,

I have the same issue on macOS Catalina (10.15.1) after the 1.18.0 update (on adding a new element to my archive).

The temporary solution I found is to download the previous version again (v1.17.3) here : https://github.com/buttercup/buttercup-desktop/releases/tag/v1.17.3 and replace v1.18.0 with v.1.17.3 in the Applications folder.

Once the operation is done, restart the computer and open Buttercup again.
If the message "Your archive is being saved" appears again, wait about ten seconds and it should be disappear and you can use again Buttercup normally (don't reinstall update 1.18.0 before the developers release a fix).

**Comment by wodin** [comment]
Thanks, I'll give it a try.

**Comment by sallar** [comment]
This is because the `saving` state is being saved to disk by mistake. Will release a fix soon.

**Comment by FalloutXtreme** [comment]
> This is because the `saving` state is being saved to disk by mistake. Will release a fix soon.

Ok, thanks ;)

**Comment by crowell-snipes** [comment]
I've had this but for the last few days now.. can't get rid of it.

**Comment by willisplummer** [comment]
i'm running into this too now

**Comment by crowell-snipes** [comment]
@willisplummer I tried to force quit various tasks pertaining to Buttercup, but no avail. Interesting enough I was still able to access the information behind the error by navigating / copying via keyboard.
It ended up fixing itself after I rebooted my MBP.
