### ISSUE TITLE
MacOS Catalina security warning after manual installation

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#864]
Because I couldn't update Buttercup from 1.18.0 to 1.18.1 via "Search for updates"-feature, I downloaded the .dmg file from the releases page. After I moved the Buttercup app from the dmg container to the applications folder and tried to open it from there, I got a security warning window that states something like "Apple can not verify the contents of the app to validate if it contains malware. Please contact the developer. OK, Open in Finder" (I translated it from German to English). After that the Buttercup application did not open.

**Workaround**:
If this happens, the problem can be solved with these steps:

1. Go to MacOS Preferences > Security & Privacy.
2. Make sure that under "Allow apps downloaded from" "App Store and identified developers" is activated.
3. On the right side there should be a button that is labeled with "Open anyway" or something like that. Click on this Button and make sure it's about Buttercup. If not, try to open Buttercup again from the applications folder and try this step again.
4. Buttercup opens.

**System Information**:
MacOS 10.15.1
Buttercup 1.18.1

**Comment by Peppeo** [comment]
Hi there. TBH this is not a Buttercup issue, but a Catalina issue (so much for the great user-friendliness out of Cupertino). Even with previously (before Catalina) installed applications this happens when upgrading. I experienced this with Nextcloud, VLC and Joplin (next to Buttercup). I suggest to close this Buttercup issue. Your description on how to make it work is very useful anyway, thanks!

**Comment by julianpoemp** [comment]
@Peppeo ok, thanks. I close this issue.

**Comment by sallar** [comment]
Thank you @Peppeo. 
Yes @julianpoemp, I don't think this is a Buttercup issue because Buttercup **is** actually signed with a valid and verified Apple-issued certificate.

**Comment by sallar** [comment]
Ok seems like this is an actual issue.
https://github.com/electron-userland/electron-builder/issues/4179

**Comment by jmvallejo** [comment]
This is because catalina requires software to be notarized, I have done this recently using electron-notarize (using electron-builder) for another project but it requires access to an actual apple id.

**Comment by sallar** [comment]
Hi everyone. 
Can you please re-download the latest mac version to see if it works? I have notarized the application now.
Thank you
https://github.com/buttercup/buttercup-desktop/releases/download/v1.18.2/Buttercup-1.18.2-mac.zip

**Comment by julianpoemp** [comment]
@sallar I tested it. It works, but I didn't see any validation bei MacOS. Perhaps this happens only if an app is moved from a dmg container?

**Comment by sallar** [comment]
@julianpoemp if it doesn't show validation, then it has worked. If the app is notarized, then no warning is shown, and the app should just work.
Thank you! 
I'm going to close this. Please feel free to re-open if this happens again.
