### ISSUE TITLE
Can not connect to WebDAV, because of the bug in webdav-client

### ISSUE THREAD

**Issue by linw1995** [buttercup/buttercup-desktop#865]
https://github.com/buttercup/buttercup-desktop/blob/6d46dc60e0129dce05ab42b51e70655508456785/src/renderer/components/file-manager/sources/webdav.js#L88-L104

Can not connect to WebDAV, because the `getDirectoryContents` do not support `null` value as a parameter.

https://github.com/perry-mitchell/webdav-client/blob/1b70cef01ca40af1f2af508b7ce92b98104834d9/source/interface/directoryContents.js#L9-L32

`encodePath` function in `getDirectoryContents` only accepts value of str type.

https://github.com/perry-mitchell/webdav-client/blob/1b70cef01ca40af1f2af508b7ce92b98104834d9/source/request.js#L8-L21

**Comment by linw1995** [comment]
sorry for reporting the wrong issue, I find out buttercup wrapping webdav-client as  [WebDAVInterface](https://github.com/buttercup/file-interface/blob/master/source/interfaces/WebDAVInterface.js). it handles the `null` value as a parameter. And my error is caused by https://github.com/perry-mitchell/webdav-client/issues/185

**Comment by linw1995** [comment]
webdav-client fixed the bug and release in 2.10.1 https://github.com/perry-mitchell/webdav-client/issues/185

**Comment by perry-mitchell** [comment]
Apologies, shouldn’t have closed this: this requires an updated version of WebDAV client, from the core & datasources..
