### ISSUE TITLE
Error creating items in Trash (should be disabled)

### ISSUE THREAD

**Issue by mvallet-mxo** [buttercup/buttercup-desktop#871]
Hi,

I got a bug when i tried to click on 'add a group' on an element placed into trash.

![image](https://user-images.githubusercontent.com/14123084/71186827-2cbc8f00-227e-11ea-9709-e91fa38dbb9f.png)

The bug trace   : 

![image](https://user-images.githubusercontent.com/14123084/71186860-3cd46e80-227e-11ea-91f2-90efad7d1f3e.png)

And i need to completely close the program otherwise i have nothing more than a blank white application screen.

**Comment by perry-mitchell** [comment]
I think there should be no possibility to add groups or entries within Trash - as it's exactly that: deleted items. This is definitely a bug as there should be no context menu items to do this when in trash.
