### ISSUE TITLE
Update takes long time and eventually timeouts.

### ISSUE THREAD

**Issue by HristoKolev** [buttercup/buttercup-desktop#881]
This happens every time for as long as I have used the app.

This screen sits there and does nothing -> https://drive.google.com/file/d/1LXk0NS3azTpN-CjBdOLfr_C_9IwrGPMO/view?usp=drivesdk

**Comment by julianpoemp** [comment]
It would be nice if we see the progress of downloading (progress bar or spinner with percentage or something like that)👍

**Comment by HristoKolev** [comment]
I would settle for it to work eventually. Having a nice progress bar is secondary.

**Comment by sallar** [comment]
@HristoKolev would you be able to paste your logs here? 
https://github.com/buttercup/buttercup-desktop#debugging

**Comment by HristoKolev** [comment]
logs: https://pastebin.com/raw/Wvp156yN

**Comment by sallar** [comment]
That's weird because `https://github.com/buttercup/buttercup-desktop/releases/download/v1.18.2/Buttercup-Setup-1.18.2.exe.blockmap` exists and works. But in your logs it says the file is not found. Can you quit buttercup and try again one more time?

Thanks

**Comment by perry-mitchell** [comment]
Stale. Brand new updater and core system. Please open a new issue if this is still occurring for you.
