### ISSUE TITLE
suggestion: allow multi-line values for additional fields

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#890]
Currently the additional fields allow only one-line values. There are some situations where multi-line values were very helpful:

- Github 2-Factor authentication codes
- Discord backup codes
- Keybase paper key
- Backup phrases for crypto wallets
- certificates for ssh and GPG
- and more :)

Yes, you could add these values as one-line, too. But in some cases it would be more readable to see the new lines and tabs.

**Comment by perry-mitchell** [comment]
This refers to #807 and the work to support it therein, so I'll close this in favour of that issue. Completely agree, and it's in the works.
