### ISSUE TITLE
Segfault on AppImage/AUR on Manjaro Linux

### ISSUE THREAD

**Issue by prostomarkeloff** [buttercup/buttercup-desktop#891]
```sh
➜  Downloads ./Buttercup-1.18.2.AppImage
qt5ct: using qt5ct plugin
13:52:19.113 › Buttercup starting up...
Failed to get crash dump id.
Report Id: 
[1]    2678 segmentation fault (core dumped)  ./Buttercup-1.18.2.AppImage
```

I'm using latest Manjaro 19.
```
➜  ~ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	19.0
Codename:	Kyria
```

**Comment by vladimiry** [comment]
kernel and `glibc` package versions?

**Comment by prostomarkeloff** [comment]
> kernel and `glibc` package versions?

Kernel version is 5.4.18-1.
`glibc` version is 2.30-3

**Comment by vladimiry** [comment]
> Kernel version is 5.4.18-1.
glibc version is 2.30-3

I thought it could be similar to https://github.com/vladimiry/ElectronMail/issues/253 but it's something different since it's not the 5.5.x kernel case.

**Comment by prostomarkeloff** [comment]
Any progress?

**Comment by perry-mitchell** [comment]
@prostomarkeloff Neither @sallar nor myself use Manjaro, so we’d hope that someone might contribute a fix if they’re able to reproduce. Otherwise I suspect that there’ll be little activity here, sorry.

**Comment by Oxalin** [comment]
I think this can be closed since unable to reproduce (Manjaro is a derivative of Arch) and because AppImages are now dealt with by AppImageLauncher instead of Electron.
