### ISSUE TITLE
[Feature Request] Custom icons for sidebar

### ISSUE THREAD

**Issue by Haberkamp** [buttercup/buttercup-desktop#893]
Are there custom icons for the sidebar planned for the future? 🤔 

I would really like to upload custom icons to every single vault. 🙂 

Currenty the user is only able to change the color of the icon.

**Comment by perry-mitchell** [comment]
Design is completely changing, but we'll keep this in consideration.

**Comment by nickbe** [comment]
Now I'm afraid .... how will it be different from now?

**Comment by perry-mitchell** [comment]
We'll probably not include custom icons, for now.
