### ISSUE TITLE
WebDAV: Windows Desktop Client adds Backslash before file name

### ISSUE THREAD

**Issue by tuaris** [buttercup/buttercup-desktop#894]
Tested in version 1.19 (but also occurs in older versions) 

- I use the option "File" -> "Connect Cloud Service"
- Click on DAV WebDAV icon
- Enter in my webdav URL and creds (https://my.dav.server/remote.php/webdav)
- Hit connect

Server connects correctly as shown below:

```
192.168.0.x - myuser [13/Mar/2020:23:44:52 -0400] "PROPFIND /remote.php/webdav// HTTP/1.1" 207 22282
192.168.0.x - myuser [13/Mar/2020:23:44:53 -0400] "PROPFIND /remote.php/webdav// HTTP/1.1" 207 22282
```

- Click "New Archive"
- type in 'buttercup'
- Press ENTER
- UI Hangs with spinning circle on top left

Server logs show:

```
192.168.0.x - myuser [13/Mar/2020:23:46:30 -0400] "PUT /remote.php/webdav/%5Cbuttercup.bcup HTTP/1.1" 400 417
```

It's pre-appending a backslash (`%5C`)

Is this expected?  My WebDAV server doesn't like that.  For example, using CURL:

```
 curl --user myuser:xxxxx -T buttercup.bcup -XPUT http://my.dav.server/remote.php/webdav/%5Cbuttercup.bcup
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\InvalidPath</s:exception>
  <s:message>File name contains at least one invalid character</s:message>
  <o:retry xmlns:o="o:">false</o:retry>
  <o:reason xmlns:o="o:">File name contains at least one invalid character</o:reason>
</d:error>
```

**Comment by tuaris** [comment]
As a workaround, you cloud create the archive locally, upload it to your webdav server, then use the desktop client to open it instead of creating a new one.

**Comment by perry-mitchell** [comment]
This issue is stale. We can reopen if this is still occurring, but the app has undergone a complete rewrite since filing this issue, and uses an updated WebDAV client.
