### ISSUE TITLE
Buttercup desktop application window is not visible in Windows 10

### ISSUE THREAD

**Issue by godzillar** [buttercup/buttercup-desktop#895]
When I try to open the Buttercup app the window does not show up. I can see that buttercup has started (showing up in the taskbar and tray bar) however when clicking on the taskbar icon or tray icon it does not open the application window. The interesting issue is I can see the preview of the application window when hovering the taskbar icon though.

Currently using the latest version of buttercup: v1.19.0

**Comment by perry-mitchell** [comment]
Perhaps it's simply off-screen some home? Perhaps try something like [this](https://www.technipages.com/bring-off-screen-window-back-onto-screen)?

**Comment by godzillar** [comment]
Thank you for your reply. I was able to get the window to show again using one of the options as stated in the link, the windows key-d option did the trick.
