### ISSUE TITLE
TOTP not showing in application

### ISSUE THREAD

**Issue by tugdualenligne** [buttercup/buttercup-desktop#898]
Hi,
Great app!
I've got an issue: I configured one of my entries in Buttercup to show OTP. It worked well when I did, but now, a few weeks later, when I try to use it, the OTP stuff doesn't come up and therefore I can't access the site. I'm sure Buttercup saved correctly to the online vault as one of the additional fields I created in this entry when enabling OTP is still showing up...
Any idea?

**Comment by perry-mitchell** [comment]
Hi @tugdualenligne! Buttercup desktop doesn't yet support OTP - OTP fields will show as an OTP URI, but will not render OTP digits. This will be handled by #594
