### ISSUE TITLE
Fresh installation, AppImage won't create new archive

### ISSUE THREAD

**Issue by pilotferdi** [buttercup/buttercup-desktop#901]
The issue takes place using both buttercup-desktop (64-bit) and AppImage. The procedure to reproduce the issue is listed below:

1. Install buttercup-desktop-1.19.0. (Alternately, download the AppImage, and make it executable.)
2. Start a new Buttercup instance.
3. Attempt to create a new archive: Ctrl+Shift+N (or using "File" menu, or clicking on the "+ ADD ARCHIVE" button).
4. The archive is _not_ created after opening the "Create a New Buttercup Archive" dialog, inputting a name, and hitting "Enter" / clicking "Save".  "Add Entry" and "New Group" in the "File" menu are greyed out.
5. Disable SELinux in order to verify it doesn't conflict with Buttercup.
6. Re-attempt to create a new archive. No joy. Conclusion: it's not SELinux-related.

I have encountered a similar bug in another password manager (don't recall which one):

The program will not create the new database unless the filename _includes_ the extension. For example, if the user types in "newarchive" the file will not be created, however, if the user types in "newarchive.ext", then the new archive is created. Since a new user doesn't know which extension is used by Buttercup files, the user is unable to create an archive.

The issue takes place in Fedora Linux, 64-bit. It was reproduced on two different Fedora versions - 30 and 31. The output from stdout looks like this:

$ Buttercup-1.19.0.AppImage 
11:51:47.558 › Buttercup starting up...
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
11:51:47.727 › Restoring state... {
  settingsByArchiveId: {},
  archives: [],
  settings: {
    columnSizes: { tree: 230, entries: 230 },
    isButtercupFocused: true,
    condencedSidebar: true,
    menubarAutoHide: false,
    archivesLoading: false,
    isTrayIconEnabled: true,
    secondsUntilClearClipboard: 15,
    autolockSeconds: 0,
    lockArchiveOnFocusout: false,
    lockArchiveOnMinimize: false,
    isBrowserAccessEnabled: false,
    updateOnStartDisabled: false,
    locale: 'en',
    globalShortcuts: {
      'preferences.minimize-and-maximize': 'CommandOrControl+Shift+X',
      'app-menu.app.preferences': 'CmdOrCtrl+,',
      'app-menu.archive.new': 'CmdOrCtrl+Shift+N',
      'app-menu.archive.open': 'CmdOrCtrl+O',
      'app-menu.archive.connect-cloud-sources': 'CmdOrCtrl+Shift+C',
      'entry.add-entry': 'CmdOrCtrl+N',
      'group.new-group': 'CmdOrCtrl+G',
      'app-menu.archive.search': 'CmdOrCtrl+F',
      'app-menu.view.condensed-sidebar': 'CmdOrCtrl+Shift+B',
      'entry-menu.username': 'CmdOrCtrl+B',
      'entry-menu.password': 'CmdOrCtrl+C',
      'archive-menu.lock': 'CmdOrCtrl+L'
    }
  }
}
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
11:51:53.587 › Checking for update
11:51:55.169 › Update for version 1.19.0 is not available (latest version: 1.19.0, downgrade is disallowed).

**Comment by LeonardPeris** [comment]
The default extension for a Buttercup archive is `.bcup`

This issue has been documented in #860 and has been assigned as a milestone for v2.

**Comment by perry-mitchell** [comment]
The forced extension will probably make it in v1. Will close as it's a solved problem, pending release.
