### ISSUE TITLE
Failed unlocking Source - Checksum does not match

### ISSUE THREAD

**Issue by pedakas** [buttercup/buttercup-desktop#904]
Hello,
I have a problem, i've opened the buttercup vault in chrome through the extension, then i opened the desktop app i added some folders and entry's, then i closed the desktop app and when i try to reopen the vault in the desktop app i get after the login the error "Failed unlocking Source: xx - Checksum does not match" The file is connected through webdav, the only thing working at the moment is the chrome extension 
thanks!

**Comment by perry-mitchell** [comment]
We don't have any such error sorry: `Checksum does not match`. We do not use checksums. This error is likely propagating from some other software or service that is forming part of the hosting provider or client when connecting to said host.

I'd recommend confirming that you have the latest desktop app version. Lock all sources in all apps and try one by one to open the same vault in each, confirming that it's only the desktop that's failing.
