### ISSUE TITLE
Desktop on Ubuntu 19.10

### ISSUE THREAD

**Issue by franko108** [buttercup/buttercup-desktop#906]
Hi, 
I just installed buttercup-desktop on Ubuntu 19.10 from link: https://github.com/buttercup/buttercup-desktop/releases/download/v1.19.0/buttercup-desktop_1.19.0_amd64.deb

After running the app, first error is that can't find: _/opt/Buttercup/resources/app-update.yml_

Second, "Add Archive" is not working, new windows for creating file do appear, when I create a new file in my home directory, no error, but no archive is created.  
There is extremely big and non readable output in /var/log/syslog. I could try to copy it if you need to.

Running from cli:
```
$ buttercup-desktop 
10:14:46.879 › Buttercup starting up...
Failed to get crash dump id.
Report Id: 
Segmentation fault (core dumped)
```

**Comment by ghostd** [comment]
Hi,

Seems to be a duplicate of #859

**Comment by franko108** [comment]
Yes it is, we can close it.
