### ISSUE TITLE
Shared files in GoogleDrive are not shown

### ISSUE THREAD

**Issue by jkonze** [buttercup/buttercup-desktop#909]
When connecting GoogleDrive as a cloud source shared files (as in files shared with me) don't show up.

I think I found a fix for it in https://github.com/buttercup/file-interface/pull/2 but I need someone to review and test it on other platforms.

Any feedback would be much appreciated.

**Comment by perry-mitchell** [comment]
Sorry we didn't see this earlier! We'll get it merged.
