### ISSUE TITLE
Allow bulk selection of passwords 

### ISSUE THREAD

**Issue by NRiou** [buttercup/buttercup-desktop#910]
Hi guys,

Thanks for your hard work.

I'm wondering if it's possible to add a simple feature which will simplify the classification of passwords : bulk selection.

I've more than 500 passwords and for now I'm unable to use bulk selection in order to mass delete or mass move passwords to dedicated groups.

Thanks,

**Comment by NRiou** [comment]
Hi guys,

Is it something you plan to work on it ?

Thanks,

**Comment by perry-mitchell** [comment]
Do you mean build selection of _entries_? Sorry if our terminology is weird.

I'll close this in favour of buttercup/ui#25, as I believe it addresses what you're asking for. Work is needed there before it can be added here.

**Comment by NRiou** [comment]
Thanks @perry-mitchell, it's exactly what I've requested
