### ISSUE TITLE
Do not change case of property keys in non-edit mode

### ISSUE THREAD

**Issue by pft** [buttercup/buttercup-desktop#911]
All property keys are shown in uppercase, until editing, in which case the true characters are revealed.

This causes unnecessary confusion.

In my use case, I let users create and maintain a bcup file in the desktop app, and then use that file with a command line app. In my instructions I tell them to set the 'ip' (i.e. lowercase) property to the appropriate ip address for a server. Because in the GUI they see other servers listed with -- apparently -- a field called 'IP', i.e. uppercase, they create a new field called 'IP' for their new server. The command line app then tries to find entries with the property 'ip' set, and fails to find their new server.

**Comment by sallar** [comment]
You're right. I'll consider this for the next version

**Comment by perry-mitchell** [comment]
Stale, not an issue in new UI.
