### ISSUE TITLE
Can't add shared file from Google Drive

### ISSUE THREAD

**Issue by kimus** [buttercup/buttercup-desktop#913]
First, I cannot add shared files directly because "Shared With Me" folder it's not present in the Google Drive folder list.
Because of that, I'm using "Add Shortcut to Drive" option to create a shortcut that it's visible from ButterCup folder list.

When trying to add the 'shared' file, it prompts for the password, validates but after that I'm greeted with a error  "Failed mapping credentials to a source”

<img width="491" alt="image" src="https://user-images.githubusercontent.com/188404/82210224-8a750600-9906-11ea-950d-2f65e4c87057.png">

**Comment by apelly** [comment]
Same. I was looking for an open solution for sharing some creds amongst a team. This not a way to do it.

**Comment by sallar** [comment]
Sorry about this. Google Drive authentication is super complicated and we’ve had a lot of issues with it. I’ll mark this as a bug.

**Comment by Kryszak** [comment]
I have similiar issue: when trying to connect to GDrive, I'm redirected to browser, and then after granting buttercup access nothing happens in desktop app.
I can connect to GDrive archive that I added some time ago though.

**Comment by cruizba** [comment]
Hi guys! You guys rock :). Don't worry, I know gdrive is a bit tricky sometimes. We will wait for next release. Keep this great work!

**Comment by perry-mitchell** [comment]
Should be addressed in the new v2 pre-release.
