### ISSUE TITLE
Buttercup tasks remain active even after Buttercup window is closed.

### ISSUE THREAD

**Issue by dreamstorpi** [buttercup/buttercup-desktop#915]
Buttercup 1.19.0 on Linux Fedora 32. 

![Screenshot from 2020-05-19 14-34-23](https://user-images.githubusercontent.com/18091677/82327143-405f5380-99de-11ea-83ef-1bb21a3066ad.png)

Buttercup tasks remain active in task manager after Buttercup has been closed.
Opening buttercup again produces more tasks which are never closed. 
Here's the task manager showing the remaining tasks. Buttercup window was not active when this screenshot was taken.

**Comment by KingArthur3** [comment]
Check your Buttercup settings, there's an option which adds buttercup to your system tray and thus making it a background process. If you uncheck it the processes should dissappear. I haven't tested this but it seems to be the problem

**Comment by perry-mitchell** [comment]
It's possible that this is an issue with instance detection - The app should detect an existing instance and open that. It shouldn't be spawning new executables, even with the tray option enabled.

**Comment by dreamstorpi** [comment]
KingArthur3 - I disabled that option, called "Display in Menubar" in my version. It did the trick, I no longer have multiple processes.
But perry-mitchell is right, it shouldn't happen in the first place.
