### ISSUE TITLE
How far are we away from a v2 release?

### ISSUE THREAD

**Issue by nickbe** [buttercup/buttercup-desktop#918]
Since answers regarding the current version seems to be very sparse, I'd like to ask if we're still far away from a 2.0 release.

**Comment by perry-mitchell** [comment]
We're still a bit away, as we've been concentrating on our hosted service. Our plan is to still use the **buttercup-ui** interface so it shouldn't be too much work to:

 * Upgrade electron
 * Trash current UI code
 * Implement buttercup-ui integration
 * Reconnect all datasource browsers
 * Reconnect settings dialog

That being said, the electron side of things has given us issues. After the release of our hosted service (coming this week), we'll be back on to v2 for the desktop.
