### ISSUE TITLE
WebDav Service Returns 404 While Endpoint Tailed With Slashes

### ISSUE THREAD

**Issue by kenmjlee** [buttercup/buttercup-desktop#919]
Hi,

After upgrading to 1.19.0, I discovered that one of my webdav connections returned status 404 because WebDav Client was used instead of WebDev-FS while releasing 1.17.0. And this issue had been confirmed and fixed by Perry, the WebDav client's author, for the [Issue #185 of WebDav](https://github.com/perry-mitchell/webdav-client/issues/185), and I am using the same WebDav service as well as this issue's creator. 

Would you mind considering a plan to update this package in the next release? 

Thank you.

**Comment by perry-mitchell** [comment]
This app uses `webdav`, not `webdav-fs`, btw. I perform maintenance on WebDAV-fs more rarely than I do on the WebDAV client project. You're right that issues sounding similar to yours has been solved. 

We're about to release a new version, with a brand new Buttercup core build, that uses the latest build of webdav. Once this is out, let's revisit this to see if it's helped. Sorry for the inconvenience.

**Comment by kenmjlee** [comment]
Yep, I know that after the release v1.17.0 the buttercup have been using the webdav. So I mentioned this issue was occurred by webdev but not by buttercup. But anyway, it sounds good to hear there will be a brand new release. 

Thanks for your effort.

**Comment by sallar** [comment]
Fixed via #942
