### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by marafa** [buttercup/buttercup-desktop#920]
i am unable to login this is what i see
![Screenshot_20200625_173829](https://user-images.githubusercontent.com/1518315/85798085-de93b700-b70a-11ea-9fd8-77f1b57809b3.png)

**Comment by perry-mitchell** [comment]
Hi! This is the desktop repo, and that looks like an issue from the browser extension. Please make sure that you have added a vault as it appears like you've gotten to the unlock screen without any vaults having been added.

I'll close this issue - please open in the browser repo if this issue persists.
