### ISSUE TITLE
Browser access dialog may be displayed in wrong Windows account

### ISSUE THREAD

**Issue by eandersons** [buttercup/buttercup-desktop#924]
When on Windows 10 more than one user has been logged in, browser access confirmation is displayed in the account in which user logged in first.

For instance, I have two accounts - user and administrator. Most of the time I am using the user account and in rare cases I also log into the administrator account without logging out of the user account when I need to do something specific. If I try to add a local file vault to browser extension in administrator account, browser access dialog is not displayed even though the Buttercup desktop application is open. When I sign in back as an user, there is the browser access dialog.
I realise that this use case most probably is quite rare and there is a workaround for this issue (switching between accounts and memorizing access code), but it would be a lot nicer if browser access dialog would be displayed in the user account it was requested from.

**Comment by perry-mitchell** [comment]
This is probably resolved by v2. There's only a single window now, and the browser access dialog is not related to any one vault - it's just file-system access, _not_ vault access.
