### ISSUE TITLE
Unhandled Promise Rejection when editing record Buttercup on desktop client 1.19.0 macOS 10.13.6

### ISSUE THREAD

**Issue by houdini69** [buttercup/buttercup-desktop#930]
Unabled to edit a record in Buttercup desktop client 1.19.0. Database is on Webdav (Nextcloud) with this alert window each time I tried to save record:

Unhandled Promise Rejection
Error: Request failed with status code 503
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:362:269826)
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:385:2602)
    at XMLHttpRequest.d.onreadystatechange (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:362:268758)

It's ok in Buttercup browser extension.

Laurent

**Comment by houdini69** [comment]
Same behaviour in desktop client 1.20.3

**Comment by houdini69** [comment]
See #939 for save behavior

**Comment by perry-mitchell** [comment]
@houdini69 503 is a server error - meaning that the server failed to process the request. Nextcloud famously has many issues being requested via the browser using WebDAV. We've seen so many issues that we published a [deprecation notice](https://medium.com/@buttercup_pw/were-deprecating-owncloud-and-nextcloud-connections-but-it-s-still-possible-to-use-them-with-abeec4d30101) of our direct support for them.

As such I'll have to close this request, as webdav is working on other services. You can try configuring your Nextcloud service to provide correct CORS headers (common issue) but I'm not sure if this will help.

**Comment by houdini69** [comment]
I understand this issue. I use native webdav on my personal server with Buttercup without any problem. Is this Nextcloud app useful to solve this issue and how to configure it with Buttercup?
https://github.com/nextcloud/server/issues/3131#issuecomment-669023897
