### ISSUE TITLE
Unhandled Error when reload app in macOS Client 1.19.0 on macOS 12.4.6

### ISSUE THREAD

**Issue by houdini69** [buttercup/buttercup-desktop#933]
`
![par défaut 2020-07-22 à 19 01 18](https://user-images.githubusercontent.com/24533104/88206941-5d6b0980-cc4f-11ea-87f8-fe47332689cf.png)
`
in Display menu (command + R) or Force Reload (shift + command + R)

**Comment by perry-mitchell** [comment]
Closing as invalid - Will happily reopen if the content is fixed.
