### ISSUE TITLE
Can't open online Vault on iOS and Windows (but works on MacOS)

### ISSUE THREAD

**Issue by tugdualenligne** [buttercup/buttercup-desktop#935]
Can't understand what's the reason, except it happens since I upgraded to latest Buttercup version. 1.20.4
On Windows, it never opens the online vault and don't give access to offline version. 
On iOS it gives after some time access to offline version
My Vault is stored on Dropbox. Using that solution as is for 1,5 years without any change
Keep up that great app!

**Comment by zmnv** [comment]
https://github.com/buttercup/buttercup-desktop/issues/934

Guys!!!!!! It's very important where are you?

**Comment by zmnv** [comment]
@tugdualenligne which wersion of MacOS do you have?

**Comment by tugdualenligne** [comment]
Latest MacOsX version (10.15.6)
Windows 10 version 1709 (updates are Corp. driven)
iOS latest version 13.6 (on iPhone XR)

**Comment by tugdualenligne** [comment]
If I am not mistaken, this issue is closed by the new version 1.20.5 => it reduced the size of my vault to <1Mo and resolved the problem. Many thanks to the developers!
