### ISSUE TITLE
Archive increase dramatically in size

### ISSUE THREAD

**Issue by matiboux** [buttercup/buttercup-desktop#937]
I've noticed a dramatic increase in size of my archive when editing it, which I believe is not normal at all.
I use Buttercup with my archive hosted on my Dropbox.

In the image below you can see the increase in size, with the latest edit first in the list, even though I've only made small edits.

![image](https://user-images.githubusercontent.com/7428799/90583901-94dac080-e1d1-11ea-91de-00acfc558552.png)

Following the arrow for each step: I have..
- Added one entry
- Added another entry
- Added one folder
- Moved an entry

I've moved two more entries after that and it increased even more.

But that's not all! **The archive once got so large (over 100 MB) that not any Buttercup app could open the archive without crashing**:
- Blank screen on desktop (Windows)
- Crash (out of memory) on the browser extension (Chrome)

Here's another image showing the older and larger sizes for the archives:

![image](https://user-images.githubusercontent.com/7428799/90585008-29462280-e1d4-11ea-8e9c-93c0e687599c.png)

The archive over 100 MB could not be opened so I tried to open the 34.2 MB one: worked after some loading.
I've then tried to export the archive and import it back into a blank archive to see the "true" size of its content: 447.66 KB. I've used this "small" archive since then.

Initially I was using **Buttercup Desktop 1.18.2**, so I thought it might have been fixed.
But the first image shows the size as of now and I'm now using **Buttercup Desktop 1.20.4**.

So that's a serious bug and I can only thank Dropbox's file history for allowing me to get back a working version of the archive.

**Comment by perry-mitchell** [comment]
Hi @matiboux - Thanks a lot for taking the time to report your findings. It's very helpful. We still haven't found the cause of this, and are looking for help diagnosing the issue.

I suppose this is your personal vault - but if you could try to create a **sample vault** and are able to reproduce this behaviour, we'd **really** appreciate your sending it to us (using a test password too!). This would help us find the issue and release a patch asap.

**Comment by perry-mitchell** [comment]
This is actually a duplicate, so I'll close in favour of the original - buttercup/buttercup-core#287

Please continue discussing there.
