### ISSUE TITLE
Unhandled Error in macOS Client 1.20.5 on macOS 10.13.6

### ISSUE THREAD

**Issue by houdini69** [buttercup/buttercup-desktop#939]
I would like to change one field in a record but got error window after saving item

![snapshot1](https://user-images.githubusercontent.com/24533104/91024561-6c4f2e00-e5f8-11ea-9b6b-048d9b574f1f.png)

I was unable to open again my vault. Finally closing the app and reopening it get my vault back in the state before saving item

![snapshot2](https://user-images.githubusercontent.com/24533104/91024576-7113e200-e5f8-11ea-875d-6b42cb650298.png)

**Comment by perry-mitchell** [comment]
Closing in favour of #930
