### ISSUE TITLE
New archive dialog on Kubuntu 20.04 silently fails

### ISSUE THREAD

**Issue by jacobpennington821** [buttercup/buttercup-desktop#945]
### Issue
When creating a new archive, the create new archive dialog disappears without error or effect if the submitted filename does not explicitly end in ".bcup". The default Kubuntu file dialog does not provide this ".bcup" ending automatically, nor is it referenced before creation that this is required.
### Workaround
Name all new archive files with names ending in .bcup.

**Comment by hankster112** [comment]
Same issue on Kubuntu 18, when attempting to create a new archive, after giving a filename and location in the dialogue box it closes but does not create the file. Trying to externally create a dummy .bcup file does not work since it asks for a master password for the archive that does not exist.

**Comment by troe** [comment]
I confirm, both in Ubuntu and Kubuntu 18.04/20/04

**Comment by perry-mitchell** [comment]
Should be fixed by #954
