### ISSUE TITLE
Is it possible to add a rich text box ？

### ISSUE THREAD

**Issue by willre** [buttercup/buttercup-desktop#946]
Is it possible to add a rich text box at the bottom of the account password display page to add remarks?
The format is now lost when the added field value content is too long.

**Comment by perry-mitchell** [comment]
Rich text is mostly magic - There has to be some kind of decent formatting system underneath to store the data, like markdown or HTML. The richtext (RTF) format isn't something we'd consider integrating.

For now you can create notes (in the new UI, which will be available after #974 is complete).
