### ISSUE TITLE
import recovery keys in other file format

### ISSUE THREAD

**Issue by bumblebee2311** [buttercup/buttercup-desktop#948]
Hello, there
Can. buttercup support addition/ import of other file formats (txt/csv/...) so can we can store our recovery keys within the password manager 👍🏼 💯 
And the feature to add icon or automatically import website logo to buttercup-desktop.

**Comment by perry-mitchell** [comment]
Our browser extension supports attachments, and this is soon coming to desktop as well, with the next major version :)
