### ISSUE TITLE
Option: start minimized main window

### ISSUE THREAD

**Issue by ondrejnick** [buttercup/buttercup-desktop#951]
I am running buttercup-desktop on ubuntu 20.04 with firefox extension. There is missing option (or app parameter) in buttercup-desktop to start it with minimized main window (e.g. to start only in system tray, useful if buttercup is used as startup application).

**Comment by perry-mitchell** [comment]
Hi @ondrejnick, it doesn't have the option to _start_ minimised, but it can be left running:

![image](https://user-images.githubusercontent.com/3869469/95015291-bba36800-0654-11eb-9c8e-ff79a3e4cc48.png)

We need to add support for it to be started minimised.

**Comment by ChuVienTran** [comment]
- [ ]

**Comment by ChuVienTran** [comment]
> I am running buttercup-desktop on ubuntu 20.04 with firefox extension. There is missing option (or app parameter) in buttercup-desktop to start it with minimized main window (e.g. to start only in system tray, useful if buttercup is used as startup application).
> 
>

**Comment by ondrejnick** [comment]
Thank you very much for implementation this feature. IT works well! Thanks.
