### ISSUE TITLE
Cannot create local vault file on Linux using desktop client

### ISSUE THREAD

**Issue by wtsiamruk** [buttercup/buttercup-desktop#955]
The Local vault cannot be create on linux

OS: Ubuntu 20.04 (GNOME DE)
Latest releease of buttercup at the moment of writing.

Steps to Reproduce.

Install fresh buttercup
Open the app
Click on add vault, create new
Choose a folder to save the file, enter the filename, click save.

Expected result: file is saved and opened as a vault
Actual: Nothing happens.
The logs on ~/.config/../log.log are also clear.

**Comment by priyansh-anand** [comment]
Same issue
OS: Pop OS 20.04 (GNOME DE)

**Comment by priyansh-anand** [comment]
Solution: It is working if I add ".bcup" at the end of filename

**Comment by wtsiamruk** [comment]
> Solution: It is working if I add ".bcup" at the end of filename

Ok, so the fix would be to attach that ".bcup" when parsing filename :+1:

**Comment by ailtonbsj** [comment]
Same problem. I was trying with ".bcp" kkkk

♬ Electrify my heart-art-art-art-art-art-oh-ooh-ooh 🎶

**Comment by perry-mitchell** [comment]
This will be fixed in the upcoming major version (v2), but we'd still accept a PR for this on v1.

**Comment by perry-mitchell** [comment]
Closing this as stale.
