### ISSUE TITLE
Support standard Linux update channels

### ISSUE THREAD

**Issue by ISITWW** [buttercup/buttercup-desktop#957]
Hi , i am using buttercup daily , but the updates are not working in ubuntu linux , last time i had to download the latest .deb file and install it using "sudo dpkg -i" and it overwrited the previous version , is this normal or should it check for updates when i press the menu item from "System" > "Check For Updates" up at the right ? When i do this nothing appears. Thanks for support and help

**Comment by perry-mitchell** [comment]
Only AppImage can support automatic updates, as it alone is compatible with the auto-update system this application uses. Other formats, like deb and rpm, don't support the auto updater. We also don't manage any deb/rpm repositories so you can't update through those channels, yet.

We'd like buttercup to support those, so I'll leave this ticket open for that reason.

**Comment by ISITWW** [comment]
Thank you so much for support and help

**Comment by perry-mitchell** [comment]
We've decided that for now, we'll only support Appimage for linux. It works on all distros, and supports auto updating. None of the other options allow for this.
