### ISSUE TITLE
Dark Theme Request

### ISSUE THREAD

**Issue by ISITWW** [buttercup/buttercup-desktop#964]
Hi, thanks for all your efforts to make the beautiful buttercup password manager, i would appreciate if you add a dark theme to it , the right side of the archive, groups and entries are dark .... but the left side has a white background, i think a dark one would be amazing for eyes , thank you so much for support and help

**Comment by perry-mitchell** [comment]
Already underway.. Once the v2 MR is closed dark mode will be available.

**Comment by perry-mitchell** [comment]
Implemented in v2.
