### ISSUE TITLE
Attachment support

### ISSUE THREAD

**Issue by gcallari** [buttercup/buttercup-desktop#965]
Hello,

I have searched the issues list about this, but it seems the latest updates are more than a year old, and I frankly do not understand if this is going to ever be an actual feature or not. May I ask to clarify what the situation is? I am sorry if I am missing something, but this is an essential feature in my opinion and I would be really glad to see it implemented (encrypted and separated from the archive file to avoid bloating is absolutely ok).

Thanks

Gabriele

**Comment by perry-mitchell** [comment]
It would have been better to comment on #484 than creating a new issue. There's been no movement here, but this will be supported in the new version - #974.

People are free to contribute attachment support in the core - we don't have the time to implement everything :)
