### ISSUE TITLE
Not able to unlock local file vault

### ISSUE THREAD

**Issue by Logeshdas** [buttercup/buttercup-desktop#973]
Hi,
I have installed buttercup desktop on my windows machine and enabled **System -> Enable browser access**. I'm getting the below error message while creating and unlocking a new Local File vault.

Error:
Failed unlocking archive
Unable to unlock archive: Unlocking archive source (e3ac7176-4207-4524-aedd-b611d61c3e94) failed: Failed unlocking source: Failed reading remote file: /myvault.bcup

Please reply as soon as possible, we are facing this issue for long time.

![bcup](https://user-images.githubusercontent.com/51057319/107676111-c931c400-6cbe-11eb-8290-9de0a49a538f.png)

**Comment by perry-mitchell** [comment]
We're not able to reproduce this issue, sorry. As this is open-source software, we encourage our users to debug these issues themselves when it's not easily reproducible. Doing so may yield answers to what the core issue is. This will be addressed latest in #974.
