### ISSUE TITLE
Version 2 - megaissue - Major upgrade on its way

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#974]
The desktop application is getting a major revision, and we'll cover the how and why here.

## Why

Buttercup for Desktop has the most users out of the Buttercup application suite, but it's also been one of the more difficult platforms to maintain. A lot has changed for @sallar and I over the last couple of years, but we've recently taken a step back to assess how we can best help Buttercup get back on its feet in terms of stability and UX and releasing a new desktop rebuild seemed like the right decision. It's long overdue, and would go a long way to addressing the large number of issues we've been unable to keep up with.

We're hoping that a new, fresh desktop platform will result in more contributions, which we desperately need.

## How

Currently the new build is ongoing in a private repository while we get the bare-bones together. Progress is very good and we'd expect to have it merged into this main repository in Q1 2021. We may do another 1-2 releases of v1 before then, but it's safe to say that **v1 is deprecated**. This is unusual, we know, as we haven't yet released its successor, but we're unable to keep up with the flood of issues and need to concentrate on getting the platform in shape.

## Focus areas

There's a number of items that have already been addressed as a matter of priority, on the new release:

 * UI - The new desktop app is using the new vault user interface that's present in the browser extension. This unified editing/viewing UI means faster release times for us and less maintenance work.
 * Vault performance - The new core boasts better performance, with the new format right around the corner.
 * New foundation - We're releasing on the newest Electron version, with a brand new typescript codebase.

The following are some other key points we're focusing on before releasing this new version:

 * Optimised vault sessions - The new desktop app will yield a more useful daemon process that will, when configured, keep vaults open even when the vault window is closed. This means that you can easily open your vault by activitating the taskbar icon. Vaults will still autolock and all of these options will be configurable.
 * New importer - The new desktop app will use our new importer with improved vault format support.
 * New local-file (browser access) system
 * New auto-update functionality
 * Refined install types (AppImage for linux, DMG, MSI)

## Contributing to this thread

**Important**: Things you should not mention in this thread:

 * Positive/negative feedback/critique - keep the discussion constructive. 
 * Issues or complaints regarding v1
 * Suggestions for v2 features

Things that would be useful to mention here:

 * Questions regarding version 2 (nothing like "will v2 fix xyz?" please)
 * Suggestions for how to help, or offers to do so
 * Suggestions for improved release procedures, or technological advice relating to our platform's build/release pipeline

**Comment by perry-mitchell** [comment]
New temporary project is now public: https://github.com/buttercup/desktop-v2-beta

**Comment by andradei** [comment]
This is a very welcome change.

> New local-file (browser access) system

Does that mean the desktop app will be connected to the browser's plugin in some way?

**Comment by perry-mitchell** [comment]
> For example: locking/unlocking one will do the same to the other.

No, unfortunately not yet. Although we would definitely consider accepting a PR for such functionality, if implemented in a secure manner :)
