### ISSUE TITLE
Buttercup not start on the default screen on windows 

### ISSUE THREAD

**Issue by Rider128** [buttercup/buttercup-desktop#975]
Hello I found a problem when I connect my second screen and I close buttercup on this screen if I disconnect this and after relaunch without the second second screen buttercup start nowhere

**Comment by RaquelJusticia** [comment]
Same here, any news? I tried to uninstall and re-install back but no success

**Comment by ckuenz587** [comment]
I may have a similar issue? Buttercup opens, shows in my taskbar AND tray as running. But no GUI. If I try to access preferences via the tray icon, it crashes.

**Comment by Rider128** [comment]
The only solution I could find is to reconnect the screen and move the window to the main screen and relaunch

**Comment by perry-mitchell** [comment]
This is a bug in how Buttercup handles the window management. The window's last coordinates are saved to the local config file, so it remembers its last coordinates and size next time you open it, for convenience.

Obviously this behaviour when screen space is _lost_, effectively, is not convenient. I think buttercup should detect whether or not its saved coordinates are in visible screen space - and if not, reset to an area that is in the visible area.

We'd happily review a contribution for this feature, but won't have time to add it ourselves as a new desktop version is on its way.
