### ISSUE TITLE
Portable version for windows ?

### ISSUE THREAD

**Issue by OnionBoots** [buttercup/buttercup-desktop#977]
Hey there, I am fairly new to github , and I don't want to reveal my identity 
is there a portable version for windows so that I can store my Property credentials inside buttercup database inside my small sneaky  encrypted stick inside a vault 
I thought to get a separate PC for that purpose but , PC's are highly vulnerable and as per my situation my siblings can do serious harm to it leaving me nowhere
:)

**Comment by perry-mitchell** [comment]
#429
