### ISSUE TITLE
How to fix archive conflicts?

### ISSUE THREAD

**Issue by jeffwillette** [buttercup/buttercup-desktop#979]
I am using buttercup version 1.20.5 and I just noticed that I have three conflicting archives in my storage provider. I have hundreds of passwords in there and I some of the conflicts are from months ago so I have no way of knowing where the conflicts are. 

I don't see any way to resolve the conflicts and I also don't see any issues about how to do this. Is there a waay I can resolve these conflicts manually by diffing something? I have no idea about how to go about viewing the raw unencrypted files to do this...

Thanks

**Comment by perry-mitchell** [comment]
Unfortunately this can be an issue if multiple clients save at the same time - We've not had time to look at a solution for conflict resolving (automatically), but it's on our agenda.

In the mean time the only safe way is to open all conflicts separately and export to CSVs, and compare. It's UGLY, and I'm sorry for the inconvenience, but there's not yet another way.

**Comment by perry-mitchell** [comment]
Closing for now.. We will definitely address this in the future..

**Comment by jeffwillette** [comment]
I see. thanks. I was able to diff them and find all the changes. To anyone who finds this, it is probably better to keep all updates to one client if possible to avoid overwriting. I am not sure how often the storage provider updates happen.
