### ISSUE TITLE
Desktop client crashes on MacOS when moving entries between groups

### ISSUE THREAD

**Issue by Eskotus** [buttercup/buttercup-desktop#980]
The software crashes randomly (About every 5-10 time) when moving entries to different groups using the context menu "Move to group > _Group name_". The particular entry that was being moved when it crashed remains where it was and can be moved after restarting the software. The archive file seems to be fine. No log entries on the time of the crash in **~/Library/Logs/Buttercup/log.log**.

It didn't crash when I did something else like edited entries etc. Didn't test thoroughly or extensively though.

This was the first time I installed and used the software on mac.

**Software version:** 1.20.5 
**macOS version:** Big Sur 11.2.3

**Comment by perry-mitchell** [comment]
Hmm.. I suspect this might be a race condition, if it's something simple like that.. Right now the save handling in v1 isn't friendly to mass amounts of save-requests in a short amount of time.

Does it happen if you wait a few seconds between each move? Also, what datasource are you using?

**Comment by perry-mitchell** [comment]
This will be fixed by v2 most likely.

**Comment by perry-mitchell** [comment]
Please check in v2. Closing this for now.

**Comment by Eskotus** [comment]
With 5 minute testing I couldn't get it to crash if I waited 3 seconds between every move. Although I couldn't get it to crash every time I tried moving entries as quickly as I can. I'm using Google drive as datasource.

I'll test it again in v2.
