### ISSUE TITLE
Issue on Linux Desktop creating new file

### ISSUE THREAD

**Issue by arrdguez** [buttercup/buttercup-desktop#981]
Hi community!

I want to report an  issue, after install in my Debian PC do not create a new archive. I clicked to create archive ... wrote the file name but after push OK button but nothing happen. 
I play with other option and dont look bad.

Thank,
Alex

**Comment by perry-mitchell** [comment]
Hi @arrdguez, are you sure it's not this issue? #860

**Comment by arrdguez** [comment]
Absolutely is that issue! 
Sorry I did found! I suggest to write a Notice or Banner or I don't know to new users. 
I other hand, the app look so good  so simply and fresh and I like that simplicity. 
Thanks!

**Comment by arrdguez** [comment]
Solved !
