### ISSUE TITLE
 v2.0.0-r.4 on macOS High CPU usage.

### ISSUE THREAD

**Issue by zrzro** [buttercup/buttercup-desktop#983]
Buttercup Helper (Renderer) stays at about 90% CPU usage.
Buttercup stays at about 40% CPU usage.

I don't know how to bugfix.

**Comment by perry-mitchell** [comment]
Confirmed.. Thanks for the report! Looking into it now..

**Comment by perry-mitchell** [comment]
Found the issue. It's the new about dialog. It had an uncontained `useEffect` react hook that was causing infinite re-renders. It'll be patched shortly.

**Comment by perry-mitchell** [comment]
This will go out in 2.0.0-r.5

**Comment by zrzro** [comment]
Thanks. It's looking pretty good now that my fan isn't being loud. Good job.
