### ISSUE TITLE
translation does not work

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#991]
![Bildschirmfoto 2021-04-11 um 22 57 47](https://user-images.githubusercontent.com/25926588/114321237-07f6c580-9b1a-11eb-9d6c-d5a7928634b0.png)

If I try to add a new vault from webDAV I see missing translations. In the preferences I tried to set the language to English manually and restarted, but it still does not work. The translations are missing on other dialogues, too like Google Drive.

System:
- MacOS 11.2.3
- System Language: German
- Buttercup 2.0

**Comment by fmommeja** [comment]
Hi Julian,

this is because nobody provided the German translation yet.

But even in French for which I provided a full translation file, it is not working in many menu entries or main window's buttons like "Trash" "New Entry" and "Edit"…

macOS 10.14.6
Buttercup 2.0

**Comment by julianpoemp** [comment]
@fmommeja yes, as I stated before I tried to manually switch to English... same problem

**Comment by perry-mitchell** [comment]
This is a bug with the i18n translations, the keys are wrong. I'm fixing them now..

**Comment by perry-mitchell** [comment]
This will come out in the next release, some time today.

**Comment by julianpoemp** [comment]
@perry-mitchell thank you very much! 🎉

**Comment by perry-mitchell** [comment]
It's out! 2.1.0, thanks..
