### ISSUE TITLE
Translations: only a part of the GUI is translated

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#999]
When I try to select another language like German or French, only a part of the GUI is translated, but the translation for these languages exists. Parts of the GUI that I found correctly translated are: the menu bar, the unlock dialogue and the small sidebar with the three dots at the bottom. The other parts are all translated to English.

System:
MacOS 11.2.3
Buttercup 2.1.0

**Comment by julianpoemp** [comment]
I don't know why, but it works now for the settings window and other dialogues. Only in the main menu the "Groups", "New Entry", "Documents" and others are not translated. Perhaps these are translations coming from the `ui` repository?

**Comment by perry-mitchell** [comment]
>Perhaps these are translations coming from the ui repository?

Yes, that's correct. Anything in the vault editing "area" is from the UI repo.

**Comment by julianpoemp** [comment]
> Yes, that's correct. Anything in the vault editing "area" is from the UI repo.

I see 😄 . That means the translations from ui will be merged into this repository in the future?

**Comment by fmommeja** [comment]
Hi,
FYI, I made screenshots of the elements still not translated in the [#1032 issue](https://github.com/buttercup/buttercup-desktop/issues/1032)

**Comment by julianpoemp** [comment]
@fmommeja the missing translations exists in the [buttercup/ui](https://github.com/buttercup/ui) repository. I think that these translations should be imported somehow. I'm sure @perry-mitchell is working on it.

**Comment by quintushr** [comment]
I try to resolve these issues by adding a call to the `changeLanguage` function of [buttercup/ui](https://github.com/buttercup/ui), but there is an error in the build. Does anyone know how to resolve this error ?

![Capture d'écran 2023-11-20 140053](https://github.com/buttercup/buttercup-desktop/assets/67709967/4fd362e4-4366-465a-8313-47e695d30138)

**Comment by perry-mitchell** [comment]
Hmm, I thought this was fixed in `2.23.0` due to the full window reload I did 😅 

Though @quintushr your solution is far more elegant. I'll merge and test today, as it'd be better that the window doesn't close/reopen.
